#+TITLE: Bookmarks
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-01-15T14:26:11-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5 num:nil
#+HTML_DOCTYPE: html5
#+INCLUDE: org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ./index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
# Created Friday January 15, 2021 at  2:26PM

#+begin_quote
Where must we go... \\
we who wander this Wasteland \\
in search of our better selves? \\
--- /The First History of Man/
#+end_quote

* Blogs
:PROPERTIES:
:CUSTOM_ID: h-0643e128-8ed0-4882-a621-e5117128d5a8
:END:

- [[https://robwilson1.wordpress.com/][Robert A Wilson's blog]], the group theorist who wrote the book
  {{{book-title(The Finite Simple Groups)}}}.
- [[https://cameroncounts.wordpress.com/][Peter Cameron's blog]] on group theory
- [[https://fredrikj.net/blog/][Fredrik Johansson's blog]], interesting symbolic computation blog
- [[https://bernsteinbear.com/][Max Bernstein's blog]] for more on programming language theory
- [[https://www.easterbrook.ca/steve/][Steve Easterbrooks blog]] discusses climate models
- [[https://nhigham.com/blog/][Nick Higham's blog]] on numerical linear algebra, and related topics
- [[https://mathproblems123.wordpress.com/category/numerical-analysis/][Beni Bogosel's blog]] on numerical analysis
- [[https://lawrencecpaulson.github.io/][Lawrence Paulson's blog]] on theorem provers
- [[http://www.topology.org/tex/conc/dgstats.php][Alan U. Kennington]] book on differential geometry
- [[https://amelia.how/archive.html][Amelia's blog]] on type theory and Haskell and stuff

** Fun References
:PROPERTIES:
:CUSTOM_ID: h-4eb8d1d4-3e92-4d02-a65d-495f5f4d6ada
:END:

- [[https://dlmf.nist.gov/][NIST Digital Library of Mathematical Functions]]
- [[https://fungrim.org/][The Mathematical Functions Grimoire]]

* Programming and Computers
:PROPERTIES:
:CUSTOM_ID: h-2dd9593d-2bf8-4a41-8295-15b4c234c7cf
:END:

- Scott Walck,\\
  "Learn Physics by Programming in Haskell".\\
  [[https://arxiv.org/abs/1412.4880][arXiv:1412.4880]], 11 pages

** CS.LO Logic in Computer Science
:PROPERTIES:
:CUSTOM_ID: h-616db70f-0194-4a3e-adcb-1d56a7ee9cd7
:END:

- Danil Annenkov, Mikkel Milo, Jakob Botsch Nielsen, Bas Spitters,\\
  "Extracting functional programs from Coq, in Coq".\\
  {{{arXiv(2108.02995)}}}, 57 pages
- Gilles Barthe, Raphaëlle Crubillé, Ugo Dal Lago, Francesco Gavazzo,\\
  "On Feller Continuity and Full Abstraction (Long Version)".\\
  {{{arXiv(2207.10590)}}}, 41 pages
- Martin Berger, Dominic P. Mulligan,\\
  "A modest proposal: explicit support for foundational pluralism".\\
  {{{arXiv(2302.10137)}}}, 18 pages.
  - Intriguing discussion for explicitly marking proofs as "independent
    of axiom of choice", or "purely constructive proof".
- Joel D. Day, Vijay Ganesh, Nathan Grewal, Florin Manea,\\
  "Formal Languages via Theories over Strings".\\
  {{{arXiv(2205.00475)}}}
- Ciarán Dunne, J. B. Wells,\\
  "Isabelle/HOL/GST: A Formal Proof Environment for Generalized Set Theories".\\
  {{{arXiv(2207.12039)}}}, 20 pages.
- Marcelo Fiore,\\
  "Semantic Analysis of Normalisation by Evaluation for Typed Lambda Calculus".\\
  {{{arXiv(2207.08777)}}}, 41 pages.
- Herman Geuvers,\\
  "The Calculus of Constructions and Higher Order Logic".\\
  In /The Curry-Howard isomorphism/ (ed. Ph. de Groote)\\
  [[http://www.cs.ru.nl/~herman/PUBS/CC_CHiso.pdf][Preprint]], discusses inconsistency in extensions of HOL (e.g., HOL +
  (prop = type) is inconsistent).
  - Geuvers actually uses this as grounds for arguing ~prop != type~ in
    general (Automath experiment also shows if ~prop = type~, then the
    law of double negation acts like a Hilbert choice operator, due to
    proof irrelevance being "the same" as type non-emptiness --- another
    reason why ~prop != type~ is a good idea).
- Herman Geuvers, Rob Nederpelt,\\
  "Characteristics of de Bruijn's early proof checker Automath".\\
  {{{arXiv(2203.01173)}}}, 24 pages.
  - A surprisingly good review of Automath, in the context of modern
    type systems.
- Alexander V. Gheorghiu, David J. Pym,\\
  "Proof-theoretic Semantics and Tactical Proof".\\
  {{{arXiv(2301.02302)}}}, 22 pages.
- Robert Harper,\\
  "An Equational Logical Framework for Type Theories".\\
  [[https://arxiv.org/abs/2106.01484][arXiv:2106.01484]], 9 pages.
- Patricia Johann, Enrico Ghiorzi, Daniel Jeffries,\\
  "GADTs, Functoriality, Parametricity: Pick Two".\\
  [[https://arxiv.org/abs/2105.03389][arXiv:2105.03389]], 16 pages.
- András Kovács,\\
  "Type-Theoretic Signatures for Algebraic Theories and Inductive Types".\\
  {{{arXiv(2302.08837)}}}, PhD Thesis, 159 pages
- Leonardo de Moura, Jeremy Avigad, Soonho Kong, Cody Roux,\\
  "Elaboration in Dependent Type Theory".\\
  {{{arXiv(1505.04324)}}}, 28 pages.
- Tobias Nipkow, Simon Roßkopf,\\
  "Isabelle's Metalogic: Formalization and Proof Checker".\\
  {{{arXiv(2104.12224)}}}, 18 pages.
  - Formalizes Isabelle's Metalogic /in Isabelle!/
- Mary Southern,\\
  "A Framework for Reasoning About LF Specifications".\\
  PhD Thesis, University of Minnesota, [[https://arxiv.org/abs/2105.04110][arXiv:2105.04110]], 188 pages.
  Also presents a unique variant of Canonical LF in chapter 2.
- Bas Spitters, Eelis van der Weegen,\\
  "Type Classes for Mathematics in Type Theory".\\
  {{{arXiv(1102.1323)}}}, 30 pages.
- Christian Williams, Michael Stay,\\
  "Native Type Theory".\\
  {{{arXiv(2102.04672)}}}, 12 pages.
  + "We propose a unifying method of reasoning for programming
    languages: model a language as a theory, form the category of
    presheaves, and use the internal language of the topos."
  + "Virtually any language can be modelled as a structured category: the
    most comprehensive reference I’ve found is /Categorical Logic and Type Theory/ by Bart Jacobs."
- Bohua Zhan,\\
  "Formalization of the fundamental group in untyped set theory using auto2".\\
  {{{arXiv(1707.04757)}}}, 17 pages.
  + One of the few formalizations using *both* /untyped/ set theory *and* Isabelle
- Tesla Zhang,\\
  "Type theories in category theory".\\
  {{{arXiv(2107.13242)}}}, 39 pages.

*** Verification of ML-like languages
:PROPERTIES:
:CUSTOM_ID: h-1aab67dd-78f6-46ee-9913-8bd458f0708b
:END:

- Laila El-Beheiry, Giselle Reis, Ammar Karkour,\\
  "SMLtoCoq: Automated Generation of Coq Specifications and Proof Obligations from SML Programs with Contracts".\\
  {{{arXiv(2107.07664)}}}, 17 pages
- Mário Pereira, António Ravara,\\
  "Cameleer: a Deductive Verification Tool for OCaml (extended version)".\\
  {{{arXiv(2104.11050)}}}, 24 pages
- Don Syme,\\
  "Reasoning with the Formal Definition of Standard ML in HOL".\\
  In /HUG1993/ pp.43--60 {{{doi(10.1007/3-540-57826-9_124)}}}, [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.35.1838][citeseer]]

*** Algebraic Effects
:PROPERTIES:
:CUSTOM_ID: h-6bb6de2b-ffee-44e9-a5f0-5b97f9dd4dac
:END:

- Birthe van den Berg, Tom Schrijvers,\\
  "A Framework for Higher-Order Effects & Handlers".\\
  {{{arXiv(2302.01415)}}}, 48 pages
- Gordon Plotkin and Matija Pretnar,\\
  "Handling Algebraic Effects".\\
  {{{arXiv(1312.1399)}}}, 36 pages.
- Tiago Soares, Mário Pereira,\\
  "A Framework for the Automated Verification of Algebraic Effects and Handlers (extended version)".\\
  {{{arXiv(2302.01265)}}}, 13 pages

** CS.PL Programming Languages
:PROPERTIES:
:CUSTOM_ID: h-1700895e-0a22-4131-8528-cef6269bcae0
:END:

- Sandra Alves, Miguel Ramos,\\
  "An ML-style record calculus with extensible records".\\
  {{{arXiv(2108.06296)}}}, 35 pages.
- Andreas Abel,\\
  "Normalization by Evaluation".\\
  Habilitation thesis, 96 pages, [[https://www.cse.chalmers.se/~abela/habil.pdf][PDF]]. (2015?)
- Michael Borkowski, Niki Vazou, Ranjit Jhala,\\
  "Mechanizing Refinement Types (extended)".\\
  {{{arXiv(2207.05617)}}}, 32 pages.
- Chris Casinghino,\\
  "Strong Normalization for the Calculus of Constructions".\\
  {{{arXiv(2210.11240)}}}, 39 pages.
- Arjen Rouvoet,\\
  "Correct by Construction".
  PhD Thesis, [[https://ajrouvoet.github.io/files/thesis.pdf][pdf]], 244 pages
- KC Sivaramakrishnan, Stephen Dolan, Leo White, Tom Kelly, Sadiq Jaffer, Anil Madhavapeddy,\\
  "Retrofitting Effect Handlers onto OCaml".\\
  [[https://arxiv.org/abs/2104.00250][arXiv:2104.00250]], 16 pages
- Jonathan Sterling,\\
  "Reflections on existential types".\\
  {{{arXiv(2210.00758)}}}, 21 pages.
- Han Xu, Zhenjiang Hu,\\
  "Analytical Differential Calculus with Integration".\\
  [[https://arxiv.org/abs/2105.02632][arXiv:2105.02632]], 42 pages; discusses differential lambda calculus
  with integrals.

** Symbolic Computation
:PROPERTIES:
:CUSTOM_ID: h-5b88ae4b-23c9-4ba5-a3d2-b56f9105e02c
:END:

- Thomas Fischbacher,\\
  "A novel approach to symbolic algebra".\\
  [[https://arxiv.org/abs/cs/0406002][arXiv:cs/0406002]], 15 pages, discusses an approach using MzScheme.

* Math
:PROPERTIES:
:CUSTOM_ID: h-25791061-4fd7-4f31-9172-1c2505e13dc9
:END:

** Math.AG Algebraic Geometry
:PROPERTIES:
:CUSTOM_ID: h-420b41c1-0679-47b7-abe2-808d4ad68781
:END:

- Aravind Asok, Jean Fasel,\\
  "Vector bundles on algebraic varieties".\\
  {{{arXiv(2111.03107)}}}, 20 pages.
- Ravi Vakil's [[http://math.stanford.edu/~vakil/216blog/][Rising Sea]] lecture notes

** Math.AP Analysis of PDEs
:PROPERTIES:
:CUSTOM_ID: h-0c32530b-a377-482c-aa9c-6381085d035d
:END:

- Alexander V. Aksenov, Andrei D. Polyanin,\\
  "Construction of complex solutions to nonlinear partial differential equations using simpler solutions".\\
  [[https://arxiv.org/abs/2102.04815][arXiv:2102.04815]], 49 pages
- Thomas Doehrman, David Glickenstein,\\
  "Determinant of the finite volume Laplacian".\\
  {{{arXiv(2108.07308)}}}, 14 pages, discusses determinant of discrete Laplacian.
- Boris Khesin, Gerard Misiolek, Alexander Shnirelman,\\
  "Geometric Hydrodynamics in Open Problems".\\
  {{{arXiv(2205.01143)}}}, 37 pages.
- D. Maroncelli, E. Collins,\\
  "Weakly Nonlocal Boundary Value Problems with Application to Geology".\\
  [[https://arxiv.org/abs/2103.09095][arXiv:2103.09095]], 15 pages
- Peicheng Zhu, Lei Yu, Yang Xiang,\\
  "Weak solutions to an initial-boundary value problem for a continuum equation of motion of grain boundaries".\\
  {{{arXiv(2204.13325)}}}, 25 pages.

*** Euler Flow
:PROPERTIES:
:CUSTOM_ID: h-893ae18c-39ea-4aad-91b4-834832946cb4
:END:

- Tarek M Elgindi,\\
  "Finite-Time Singularity Formation for $C^{1,\alpha}$ Solutions to the
  Incompressible Euler Equations on R^3".\\
  [[https://arxiv.org/abs/1904.04795][arXiv:1904.04795]], 60 pages; see also follow up paper [[https://arxiv.org/abs/1910.14071][arXiv:1910.14071]].
- Evan Miller,\\
  "On the regularity of axisymmetric, swirl-free solutions of the Euler equation in four and higher dimensions".\\
  {{{arXiv(2204.13406)}}}, 52 pages
- Matthew Rosenzweig,\\
  "On the Rigorous Derivation of the Incompressible Euler Equation from Newton's Second Law".\\
  [[https://arxiv.org/abs/2104.11723][arXiv:2104.11723]], 20 pages.
- Luigi De Rosa, Marco Inversi, Giorgio Stefani,\\
  "Weak-strong uniqueness and vanishing viscosity for incompressible Euler equations in exponential spaces".\\
  {{{arXiv(2204.12779)}}}, 22 pages

*** Navier-Stokes Equations
:PROPERTIES:
:CUSTOM_ID: h-3998242d-365c-425f-98a3-d71d383c3e0b
:END:

- Dallas Albritton, Elia Brué, Maria Colombo,\\
  "Non-uniqueness of Leray solutions of the forced Navier-Stokes equations".\\
  {{{arXiv(2112.03116)}}}, 31 pages.
- Lorenzo Brandolese,\\
  "Hexagonal structures in 2D Navier-Stokes flows".\\
  [[https://arxiv.org/abs/2102.00728][arXiv:2102.00728]], 25 pages
- Yuxi Hu, Reinhard Racke,\\
  "Global existence versus blow-up for multi-d hyperbolized compressible Navier-Stokes equations".\\
  {{{arXiv(2204.13080)}}}, 26 pages.
- Jiaxu Li, Jing Li, Boqiang Lü,\\
  "Global Classical Solutions to the Full Compressible Navier-Stokes System in 3D Exterior Domains".\\
  {{{arXiv(2208.11925)}}}, 53 pages.
- Paolo Maremonti, Francesca Crispo, Carlo Romano Grisanti,\\
  "Navier-Stokes equations: a new estimate of a possible gap related to the energy equality of a suitable weak solution".\\
  {{{arXiv(2204.11359)}}}, 13 pages

** Math.CA Classical Analysis
:PROPERTIES:
:CUSTOM_ID: h-c09523ff-ba33-4ef9-ac67-9adddde406ce
:END:

- Felix Hummel, Peter Ashwin, Christian Kuehn,\\
  "Reduction Methods in Climate Dynamics -- A Brief Review".\\
  {{{arXiv(2209.12240)}}}, 48 pages.

** Math.CO Combinatorics
:PROPERTIES:
:CUSTOM_ID: h-e5b7653c-61c9-4ab3-bc0d-7fc41f162ea9
:END:

- Gerald Hoehn,\\
  "Self-dual Codes over the Kleinian Four Group".\\
  {{{arXiv(math/0005266)}}}, 26 pages.

** Math.CT Category Theory
:PROPERTIES:
:CUSTOM_ID: h-4f2e35f6-82de-4cb6-b32f-f6f39edd0b30
:END:

- Antoine Allioux, Eric Finster, Matthieu Sozeau,\\
  "Types are Internal ∞-Groupoids".\\
  [[https://arxiv.org/abs/2105.00024][arXiv:2105.00024]], 16 pages.
- Ingo Blechschmidt,\\
  "Exploring mathematical objects from custom-tailored mathematical
  universes".\\
  {{{arXiv(2204.00948)}}}, 32 pages.
- Carmen Constantin, Tobias Fritz, Paolo Perrone, Brandon Shapiro,\\
  "Weak cartesian properties of simplicial sets".\\
  [[https://arxiv.org/abs/2105.04775][arXiv:2105.04775]], 48 pages.
- Fabrizio Genovese, Fosco Loregian, \\
  "Differential 2-rigs". \\
  [[https://arxiv.org/abs/2103.00938][arXiv:2103.00938]], 32 pages.
- Matias del Hoyo, Giorgio Trentinaglia,\\
  "Simplicial vector bundles and representations up to homotopy".\\
  {{{arXiv(2109.01062)}}}, 66 pages.
- Giulio Lo Monaco,\\
  "Vopěnka's principle in ∞-categories".\\
  [[https://arxiv.org/abs/2105.04251][arXiv:2105.04251]], 22 pages.
- Ivan Contreras, Molly Keller, Rajan Amit Mehta,\\
  "Frobenius objects in the category of spans".\\
  [[https://arxiv.org/abs/2106.14743][arXiv:2106.14743]], 31 pages
  - Frobenius objects generalize Frobenius algebras, which describe
    TQFTs. Rajan Amit Mehta seems to have discussed them earlier in
    [[https://arxiv.org/abs/1907.00702][arXiv:1907.00702]] crediting their invention to:
    Joachim Kock, {{{book-title(Frobenius algebras and 2D topological quantum field theories)}}}, CUP, 2004.
  - The category *Rel* acts like a "toy symplectic category" without any
    of the difficulties.
- Ivo Dell'Ambrogio,\\
  "Green 2-functors".
  {{{arXiv(2107.09478)}}}, 41 pages.
  - Mackey 2-functors introduced in {{{arXiv(1808.04902)}}} (213 pages,
    "many beautiful figures").
- Yuri Shimizu,\\
  "∞-cosheafification".\\
  [[https://arxiv.org/abs/2106.14135][arXiv:2106.14135]], 11 pages.
- Yasuhiro Wakabayashi,\\
  "On the category of structure species".\\
  {{{arXiv(2201.11273)}}}, 21 pages
- Zhen Huan,\\
  "2-Representations of Lie 2-groups and 2-Vector Bundles".\\
  {{{arXiv(2208.10042)}}}, 62 pages.

** Math.DG Differential Geometry
:PROPERTIES:
:CUSTOM_ID: h-6db90c1a-f521-4efe-9c2a-fc00d37070b3
:END:

- Max Chemtov, Spiro Karigiannis,\\
  "Observations about the Lie algebra 𝔤2⊂𝔰𝔬(7), associative 3-planes, and 𝔰𝔬(4) subalgebras".\\
  {{{arXiv(2209.10613)}}}, 21 pages.
- Mathieu Desbrun, Anil N. Hirani, Melvin Leok, Jerrold E. Marsden,\\
  "Discrete Exterior Calculus".\\
  [[https://arxiv.org/abs/math/0508341][arXiv:math/0508341]], 53 pages
- Rui Loja Fernandes, Marius Crainic,\\
  "Lectures on Integrability of Lie Brackets".\\
  {{{arXiv(math/0611259)}}}, 95 pages; see especially \sect3.2 for a proof
  of Lie's third theorem using homotopic equivalence classes of paths.
- Olaf Müller,\\
  "Functors in Lorentzian geometry -- three variations on a theme".\\
  {{{arXiv(2205.01617)}}}, 12 pages.
- José Figueroa-O'Farrill,\\
  "Non-Lorentzian Spacetimes".\\
  {{{arXiv(2204.13609)}}}, 18 pages.
- Ichiro Yokota,\\
  "Exceptional Lie groups".\\
  {{{arXiv(0902.0431)}}}, 204 pages.

** Math.GR Group Theory
:PROPERTIES:
:CUSTOM_ID: h-5f6e5a83-f5db-4e97-8cde-16ac0f77d9d1
:END:

- [[https://kourovka-notebook.org/][Kourovka Notebook]] of unsolved problems in group theory

- Simon André, Vincent Guirardel,\\
  "Finitely generated simple sharply 2-transitive groups".\\
  {{{arXiv(2212.06020)}}}, 21 pages
- Martin van Beek,\\
  "Exotic Fusion Systems Related to Sporadic Simple Groups".\\
  {{{arXiv(2201.01790)}}}, 40 pages.
- Martin van Beek,\\
  "Saturated Fusion Systems on Sylow p-subgroups of Rank 2 Simple Groups of Lie Type".\\
  {{{arXiv(2302.02222)}}}, 44 pages.
- Christopher P. Bendel,\\
  "Cohomology of algebraic groups, Lie algebras, and finite groups of Lie type".\\
  {{{arXiv(2209.01140)}}}, 22 pages.
- Carl-Fredrik Nyberg Brodda,\\
  "The Adian-Rabin Theorem -- An English translation".\\
  {{{arXiv(2208.08560)}}}, 89 pages.
- Peter J. Cameron,\\
  "Graphs defined on groups".\\
  {{{arXiv(2102.11177)}}}, 81 pages, review paper.
- Jacques Darné, Martin Palmer, Arthur Soulié,\\
  "When the lower central series stops".\\
  {{{arXiv(2201.03542)}}}, 86 pages.
- Misha Gavrilovich,\\
  "Expressing the statement of the Feit-Thompson theorem with diagrams in the category of finite groups".\\
  {{{arXiv(1608.05927)}}}, 8 pages
- Oussama Hamza,\\
  "Isotypical study of Zassenhaus and lower central filtrations on pro-p groups".\\
  {{{arXiv(2207.12372)}}}, 25 pages.
- Kadeem Harrigan,\\
  "Aschbacher's Theorem for the General Linear Group".\\
  {{{arXiv(2112.02430)}}}, 49 pages; MSc thesis submitted at Imperial College London.
- Dimitri Leemans, Klara Stokes,\\
  "Incidence geometries with trialities coming from maps with Wilson trialities".\\
  {{{arXiv(2208.08215)}}}, 13 pages.
- Alastair J. Litterick, David I. Stewart, Adam R. Thomas,\\
  "Complete reducibility and subgroups of exceptional algebraic groups".\\
  {{{arXiv(2209.11310)}}}, 42 pages.
- Nicolas Magaud,\\
  "Spreads and Packings of PG(3,2), Formally!"\\
  {{{arXiv(2201.00541)}}}, 9 pages, discusses Coq formalization.
- Leo Margolis,\\
  "The Modular Isomorphism Problem: a survey".\\
  {{{arXiv(2202.11412)}}}, 31 pages.
- Alexander Moretó,\\
  "Methods and questions in character degrees of finite groups".\\
  {{{arXiv(2209.09221)}}}, 19 pages.
- Graham A. Niblo, Roger Plymen, Nick Wright,\\
  "Centralisers, complex reflection groups and actions in the Weyl group E6".\\
  {{{arXiv(2205.08230)}}}, 47 pages
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The BMS Group".\\
  {{{arXiv(2106.12513)}}}, 27 pages.
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The NU Group".\\
  {{{arXiv(2109.11476)}}}, 38 pages
- Robert A. Wilson,\\
  "Comparison of group-theoretical strategies for unification of 3+1 structures in physics".\\
  {{{arXiv(2108.04675)}}}, 8 pages.
- Robert A. Wilson,\\
  "Possible uses of the binary icosahedral group in grand unified theories".\\
  {{{arXiv(2109.06626)}}}, 28 pages.
- R. A. Wilson,\\
  "Integer versions of Yang-Mills theory".\\
  {{{arXiv(2202.08263)}}}, 13 pages.
- R. A. Wilson, T. Dray, C. A. Manogue,\\
  "An octonionic construction of E8 and the Lie algebra magic square".\\
  {{{arXiv(2204.04996)}}}, 19 pages.
- Yu Zeng, Dongfang Yang,\\
  "A characterization of finite groups by certain Galois conjugacy class of irreducible characters".\\
  {{{arXiv(2208.07782)}}}, 15 pages.

*** Algebraic Groups
:PROPERTIES:
:CUSTOM_ID: h-301b95cc-a6a0-42c2-a61e-3f4f274e03f8
:END:

- Benjamin Martin,\\
  "Algebraic groups and G-complete reducibility: a geometric approach".\\
  {{{arXiv(2207.12169)}}}, 28 pages.

*** Finite Groups
:PROPERTIES:
:CUSTOM_ID: h-519655a5-272d-441b-a718-06c3412d1064
:END:

- Sylvia Bayard, Justin Lynd,\\
  "Realizing Finite Groups as Automizers".\\
  {{{arXiv(2203.14413)}}}, 9 pages
- Yiming Bing, Bright Hu, Ronni Hu, Rhianna Li, Stefan Lu, Finn McDonald, Michael Sun, Nicholas Wolfe, Joshua Yao, Leon Zhou, Nathan Zhou,\\
  "The Mathieu group $M_{23}$ as additive functions on the finite field of size $2^{11}$".\\
  {{{arXiv(2201.00108)}}}, 15 pages.
- Eloisa Detomi, Andrea Lucchini,\\
  "Strongly generating elements in finite and profinite groups".\\
  {{{arXiv(2208.05761)}}}, 9 pages.
- Wenbin Guo, Danila O. Revin, Andrey V. Vasil'ev,\\
  "On embedding theorems for 𝔛-subgroups".\\
  {{{arXiv(2206.10267)}}}, 8 pages
- Neha Malik, Steven Spallone,\\
  "Stiefel-Whitney Classes of Representations of SL(2,q)".\\
  {{{arXiv(2208.05813)}}}, 24 pages.
- John McKay, Yang-Hui He,\\
  "Kashiwa Lectures on 'New Approaches to the Monster'".\\
  [[https://arxiv.org/abs/2106.01162][arXiv:2106.01162]], 42 pages.
- Peter M. Neumann,\\
  "Primitive permutation groups of degree 3p".\\
  {{{arXiv(2204.06926)}}}, 43 pages; unpublished manuscript from 1969.
- Parveen, Jitender Kumar, Siddharth Singh, Xuanlong Ma,\\
  "Certain properties of the enhanced power graph associated with a finite group".\\
  {{{arXiv(2207.05075)}}}, 8 pages.
- Martin Seysen,\\
  "A computer-friendly construction of the monster".\\
  {{{arXiv(2002.10921)}}}, 34 pages.
- Pablo Spiga,\\
  "An explicit upper bound on the number of subgroups of a finite group".\\
  {{{arXiv(2210.02972)}}}, 9 pages; claims the upper bound is $7.3722\cdot|G|^{1.5315+(\lg|G|)/4}$


**** ATLAS of Finite Groups
:PROPERTIES:
:CUSTOM_ID: h-39744a7a-ccec-4024-868e-d850ff724237
:END:

- Thomas Breuer,\\
  "Constructing the ordinary character tables of some Atlas groups using
  character theoretic methods".\\
  {{{arXiv(1604.00754)}}}, 90 pages.
- Thomas Breuer, Kay Magaard, Robert Wilson,\\
  "Verification of the ordinary character table of the Baby Monster".\\
  {{{arXiv(1902.07758)}}}, 17 pages. (The first draft had proved the
  Schur multiplier of the Monster is trivial, which was replaced by a
  citation in the second draft.)

**** Finite Groups of Lie Type
:PROPERTIES:
:CUSTOM_ID: h-0c8bd087-71d9-40dc-8b40-22f2b8ba8b46
:END:

- Hannah Knight,\\
  "The essential p-dimension of finite simple groups of Lie type".\\
  {{{arXiv(2109.02698)}}}, 65 pages
- Timothy C. Burness, Adam R. Thomas,\\
  "Normalisers of maximal tori and a conjecture of Vdovin".\\
  {{{arXiv(2207.09495)}}}, 33 pages.
- A. Pachera,\\
  "Embeddings of PSL2(q) in exceptional groups of Lie type over a field of characteristic ≠2,3".\\
  {{{arXiv(2212.08505)}}}, 88 pages.
  
**** Sylow p-Subgroups and Hall \pi-Subgroups
:PROPERTIES:
:CUSTOM_ID: h-fa155afc-5c2c-47cd-aeff-27b881b14a70
:END:

- Timothy C. Burness, Robert M. Guralnick,\\
  "On the generation of simple groups by Sylow subgroups".\\
  {{{arXiv(2204.04311)}}}, 17 pages.
- Wenbin Guo, Alexander N. Skiba,\\
  "On Hall subgroups of a finite group".\\
  {{{arXiv(1205.2496)}}}, 14 pages.
- N. N. Hung, A. Maróti, J. Martínez,\\
  "Classes of π-elements and nilpotent/abelian Hall π-subgroups".\\
  {{{arXiv(2207.04988)}}}, 18 pages.
- Gabriel Navarro, Benjamin Sambale,\\
  "Characters, Commutators and Centers of Sylow Subgroups".\\
  {{{arXiv(2204.04407)}}}, 18 pages
- Nomina Ch. Manzaeva, Danila O. Revin, Evgeny P. Vdovin,\\
  "The Hall property Dπ is inherited by overgroups of π-Hall subgroups".\\
  {{{arXiv(1808.03536)}}}, 27 pages
- D.O.Revin, E.P.Vdovin,\\
  "On the number of classes of conjugate Hall subgroups in finite simple groups".\\
  {{{arXiv(0912.1922)}}}, 54 pages.
- Ruslan Skuratovskii,\\
  "The commutator and centralizer description of Sylow 2-subgroups of alternating and symmetric groups".\\
  {{{arXiv(1712.01401)}}}, 19 pages.

** Math.HO History and Overview
:PROPERTIES:
:CUSTOM_ID: h-b63c6476-fd76-48f4-b419-4ecd2770303b
:END:

- Andy Eskenazi, Kevin You, Will Vauclain, Robin Murugadoss,\\
  "A Beginner's Guide to Homological Algebra: An Introduction for Intermediate and Advanced Mathematicians".\\
  {{{arXiv(2208.11199)}}}, 32 pages

** Math.LO Logic
:PROPERTIES:
:CUSTOM_ID: h-77765895-8b26-4057-b243-06f594378e59
:END:

- David Asperó, Ralf Schindler,\\
  "MM^{++} implies ~(*)~".\\
  {{{arXiv(1906.10213)}}}, 48 pages.
- Jeremy Avigad,\\
  "Foundations".\\
  {{{arXiv(2009.09541)}}}, 54 pages
- Vasco Brattka,\\
  "On the Complexity of Computing Gödel Numbers".\\
  {{{arXiv(2302.04213)}}}, 23 pages
- Walter Dean, Hidenori Kurokawa,\\
  "On the methodology of informal rigour: set theory, semantics, and intuitionism".\\
  [[https://arxiv.org/abs/2104.14887][arXiv:2104.14887]], 83 pages.
  - This is the second paper which references Georg Kreisel's paper on
    ZFC_{2} (ZFC formulated in second-order logic), specifically:\\
    G. Kreisel,\\
    "Informal Rigour and Completeness Proofs".\\
    In I. Lakatos, editor, {{{book-title(Problems in the philosophy of mathematics: Proceedings of the International Colloquium in the Philosophy of Science)}}},
    London, 1965, pages 138--186. North-Holland, Amsterdam, 1967.
- Gabriel Goldberg,\\
  "Reinhardt cardinals in inner models".\\
  {{{arXiv(2107.13119)}}}, 4 pages.
- Hunter Monroe,\\
  "Average-Case Hardness of Proving Tautologies and Theorems".\\
  {{{arXiv(2205.07803)}}}, 15 pages.
- Hoang Kim Nguyen, Taichi Uemura,\\
  "∞-type theories".\\
  {{{arXiv(2205.00798)}}}, 55 pages
- David Pym, Eike Ritter, Edmund Robinson,\\
  "Categorical Proof-Theoretic Semantics".\\
  {{{arXiv(2302.09031)}}}, 25 pages
  - Seems to describe proof-theoretic semantics using topoi via presheaves.
- Egbert Rijke,\\
  "Introduction to Homotopy Type Theory".\\
  {{{arXiv(2212.11082)}}}, 359 pages
- Saharon Shelah,\\
  "Logical Dreams".\\
  {{{arXiv(math/0211398)}}}, 34 pages
- S. Swierczkowski,\\
  "Finite sets and Gödel's incompleteness theorems".\\
  /Dissertationes Mathematicae/ *422* (2003), pp.1-58
  [[https://www.impan.pl/en/publishing-house/journals-and-series/dissertationes-mathematicae/all/422//88124/finite-sets-and-godel-s-incompleteness-theorems][Eprint]]
- Jouko Väänänen,\\
  "Sort logic and foundations of mathematics".\\
  {{{arXiv(2302.05947)}}}, 14 pages.

** Math.MG Metric Geometry
:PROPERTIES:
:CUSTOM_ID: h-61e9a3d9-2633-4f33-8a6a-a3aa1fdd365c
:END:

- Laith Rastanawi, Günter Rote,\\
  "Towards a Geometric Understanding of the 4-Dimensional Point Groups".\\
  {{{arXiv(2205.04965)}}}, 109 pages.
** Math.MP Mathematical Physics
:PROPERTIES:
:CUSTOM_ID: h-e1914301-bc40-4737-abbb-7eb782a529eb
:END:
- Luis J. Boya,\\
  "Introduction to Sporadic Groups".\\
  {{{arXiv(1101.3055)}}}, 18 pages
** Math.NA Numerical Analysis
:PROPERTIES:
:CUSTOM_ID: h-ac731c25-c32a-4b24-8f8e-fd09a0edb2d4
:END:
- M. Antoñana, E. Alberdi, J.Makazaga, A. Murua,\\
  "An implicit symplectic solver for high-precision long term integrations of the Solar System".\\
  {{{arXiv(2204.01539)}}}, 26 pages
- David Berghaus, Hartmut Monien, Danylo Radchenko,\\
  "On the computation of modular forms on noncongruence subgroups".\\
  {{{arXiv(2207.13365)}}}, 30 pages.
  - Nice use of mixed precision arithmetic in computational number theory, in this case using machine precision preconditioning to speed up arbitrary precision solving by orders of magnitude.
- Fedor Bukreev, Stephan Simonis, Adrian Kummerländer, Julius Jeßberger,
  Mathias J. Krause,\\
  "Consistent lattice Boltzmann methods for the volume averaged Navier-Stokes equations".\\
  {{{arXiv(2208.09267)}}}, 22 pages.
- Jérôme Droniou, Todd A. Oliynyk, Jia Jia Qian,\\
  "A polyhedral discrete de Rham numerical scheme for the Yang-Mills equations".\\
  {{{arXiv(2208.12009)}}}, 24 pages.
- Tomoya Kemmochi,\\
  "Lp-resolvent estimate for finite element approximation of the Stokes operator".\\
  {{{arXiv(2208.11892)}}}, 21 pages
- A. Melman,\\
  "Root finding techniques that work".\\
  {{{arXiv(2204.02326)}}}, 15 pages
** Math.NT Number Theory
:PROPERTIES:
:CUSTOM_ID: h-8b819207-58a1-476c-b108-cafb437af04b
:END:
- Samuel DeHority, Xavier Gonzalez, Neekon Vafa, Roger Van Peski,\\
  "Moonshine for All Finite Groups".\\
  {{{arXiv(1707.05249)}}}, 34 pages
** Math.QA Quantum Algebra
:PROPERTIES:
:CUSTOM_ID: h-fdf4a178-51f0-48ce-88aa-3c71749dbebf
:END:

- R. W. Gebert,\\
  "Introduction to Vertex Algebras, Borcherds Algebras, and the Monster Lie Algebra".\\
  {{{arXiv(hep-th/9308151)}}}, 55 pages.
- Yi-Zhi Huang,\\
  "Conformal-field-theoretic analogues of codes and lattices".\\
  {{{arXiv(math/0104150)}}}, 23 pages.
- Yi-Zhi Huang, James Lepowsky,\\
  "Vertex operator algebras and operads".\\
  {{{arXiv(hep-th/9301009)}}}, 16 pages.
- Chongying Dong,\\
  "Introduction to vertex operator algebras I".\\
  {{{arXiv(q-alg/9504017)}}}, 26 pages
- Haisheng Li,\\
  "Introduction to vertex operator algebras II".\\
  {{{arXiv(q-alg/9504018)}}}, 27 pages
- Yi-Zhi Huang,\\
  "Introduction to vertex operator algebras III".\\
  {{{arXiv(q-alg/9504019)}}}, 28 pages
- James Lepowsky,\\
  "Vertex operator algebras and the zeta function".\\
  {{{arXiv(math/9909178)}}}, 21 pages.
- Andrew Schopieray,\\
  "Categorification of integral group rings extended by one dimension".\\
  {{{arXiv(2208.07319)}}}, 25 pages.

** Math.RA Rings and Algebras
:PROPERTIES:
:CUSTOM_ID: h-fdda27db-b4c5-4f8d-89e1-aee0139e1c7e
:END:
- L. Caston, R. Fioresi,\\
  "Mathematical Foundations of Supersymmetry".\\
  {{{arXiv(0710.5742)}}}, 122 pages.
- Cristina Draper,\\
  "Notes on G2: The Lie algebra and the Lie group".\\
  {{{arXiv(1704.07819)}}}, 50 pages.
- Artem Lopatin, Alexandr N. Zubkov,\\
  "Separating G_2-invariants of several octonions".\\
  {{{arXiv(2209.12620)}}}, 21 pages.
  + In \sect2, there's a fascinating construction of the Octonions.
- Justin McInroy, Sergey Shpectorov,\\
  "Axial algebras of Jordan and Monster type".\\
  {{{arXiv(2209.08043)}}}, 39 pages.

** Math.RT Representation Theory
:PROPERTIES:
:CUSTOM_ID: h-b4106499-8cbd-44aa-87aa-940ff1bfb2e5
:END:

- Enrique Arrondo,\\
  "Representation theory of finite groups through (basic) algebraic geometry".\\
  {{{arXiv(2009.02774)}}}, 32 pages.
- John C. Baez,\\
  "Young Diagrams and Classical Groups".\\
  {{{arXiv(2302.07971)}}}, 19 pages.
- Anthony Britto,\\
  "A Mathematical Construction of an E6 Grand Unified Theory".\\
  [[https://arxiv.org/abs/2102.13465][arXiv:2102.13465]], 81 pages, master's thesis.
- Olivier Brunat, Frank Lübeck,\\
  "On defining characteristic representations of finite reductive groups".\\
  {{{arXiv(1211.3692)}}}, 22 pages
  + Gives parameterizations of the irreducible representations of finite
    groups of Lie type in their defining characteristic.
- Scott Carnahan,\\
  "Why do the symmetries of the monster vertex algebra form a finite simple group?".\\
  {{{arXiv(2206.15391)}}}, 22 pages.
- Alexandru Chirvasitu,\\
  "Lie-algebra centers via de-categorification".\\
  {{{arXiv(2207.11338)}}}, 20 pages
- Yi-Hao Ding, Chao-Ping Dong,\\
  "Dirac Series of $E_{7(-25)}$".\\
  {{{arXiv(2204.07902)}}}, 23 pages.
- Yihao Ding, Hongfeng Zhang,\\
  "Dirac series of GL(n,ℍ)".\\
  {{{arXiv(2208.09903)}}}, 31 pages.
- George Egorov,\\
  "How to superize 𝔤𝔩(∞)".\\
  {{{arXiv(2205.07046)}}}, 15 pages.
- Matthew Fayers, Lucia Morotti,\\
  "Irreducible spin representations of symmetric and alternating groups which remain irreducible in characteristic 3".\\
  {{{arXiv(2208.05207)}}}, 28 pages.
- Maria Gorelik, Vladimir Hinich, Vera Serganova,\\
  "Root groupoid and related Lie superalgebras".\\
  {{{arXiv(2209.06253)}}}, 58 pages
  + Suggests replacing Weyl group with "root groupoid" for Lie superalgebras.
- Jonas Hetz,\\
  "On the generalised Springer correspondence for groups of type E8".\\
  {{{arXiv(2207.06382)}}}, 28 pages.
- Christian Liedtke,\\
  "A McKay Correspondence in Positive Characteristic".\\
  {{{arXiv(2207.06286)}}}, 43 pages.
- Youssef Mousaaid,\\
  "Trivalent Categories for Adjoint Representations of Exceptional Lie Algebras".\\
  {{{arXiv(2204.13642)}}}, 25 pages.
- Anupam Singh,\\
  "Representation Theory of Finite Groups".\\
  {{{arXiv(1001.0462)}}}, 57 pages.
- Michel Rausch de Traubenberg, M J Slupinski,\\
  "Commutation relations of 𝔤_2 and the incidence geometry of the Fano plane".\\
  {{{arXiv(2207.13946)}}}, 38 pages.
- Steven V Sam, Andrew Snowden, Philip Tosteson,\\
  "Polynomial representations of the Witt Lie algebra".\\
  {{{arXiv(2210.00399)}}}, 25 pages.
- Benjamin Sambale,\\
  "Fusion systems in representation theory".\\
  {{{arXiv(2302.09016)}}}, 17 pages.
- Jack Saunders,\\
  "Cohomology and Ext for rank one finite groups of Lie type in cross characteristic".\\
  {{{arXiv(2208.11937)}}}, 19 pages.
- Jim Humphreys, [[https://mathoverflow.net/q/136880/22457][Definition of "finite group of Lie type"?]]

* Physics
:PROPERTIES:
:CUSTOM_ID: h-fa5b64f4-e7d5-4046-8fda-63f54dd93864
:END:

- Susan Fowler's [[https://www.susanjfowler.com/blog/2016/8/13/so-you-want-to-learn-physics][So You Want To Learn Physics...]], an annotated bibliography

** Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-d8af8a2e-ffde-4e10-a897-18a54a28bdb1
:END:

- Aymeric Spiga, Sandrine Guerlet, Ehouarn Millour, Mikel Indurain, Yann Meurdesoif, Simon Cabanes, Thomas Dubos, Jérémy Leconte, Alexandre Boissinot, Sébastien Lebonnois, Mélody Sylvestre, Thierry Fouchet,\\
  "Global climate modeling of Saturn's atmosphere. Part II: multi-annual
  high-resolution dynamical simulations".\\
  [[https://arxiv.org/abs/1811.01250][arXiv:1811.01250]], 68 pages.
- Sandrine Guerlet, Aymeric Spiga, Thierry Fouchet, Hugues Delattre,\\
  "Radiative-equilibrium model of Jupiter's atmosphere and application to estimating stratospheric circulations"\\
  [[https://arxiv.org/abs/1907.04556][arXiv:1907.04556]], 72 pages, for a 1-dimensional seasonal radiative model.

** Atmospheric and Oceanic Physics
:PROPERTIES:
:CUSTOM_ID: h-a055c4a4-e9b7-4ef0-9af8-accad7acdbc4
:END:

- V. Balaji, Fleur Couvreux, Julie Deshayes, Jacques Gautrais, Frédéric Hourdin, Catherine Rio,\\
  "Are GCMs Obsolete?".\\
  {{{arXiv(2204.06957)}}}, 9 pages + 93 citations
- Redouane Lguensat, Julie Deshayes, Homer Durand, V. Balaji,\\
  "Semi-automatic tuning of coupled climate models with multiple intrinsic timescales: lessons learned from the Lorenz96 model".\\
  {{{arXiv(2208.06243)}}}, 30 pages.
- Francois Louchet, Jerome Faillettaz,\\
  "Should we trust climate change predictions?"\\
  {{{arXiv(2204.11619)}}}, 5 pages
  + The authors seem confused and muddled, their argument self-defeating.

** Earth and Planetary Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-0694a5d9-fe8d-4af2-a571-9622720e3a21
:END:

- Tao Cai, Kwing L. Chan, Hans G. Mayr, \\
  "Deep, Closely-Packed, Long-Lived Cyclones on Jupiter's Poles".\\
  [[https://arxiv.org/abs/2103.08824][arXiv:2103.08824]], 33 pages
- Russell Deitrick, João M. Mendonça, Urs Schroffenegger, Simon L. Grimm, Shang-Min Tsai, Kevin Heng,\\
  "THOR 2.0: Major Improvements to the Open-Source General Circulation Model".\\
  [[https://arxiv.org/abs/1911.13158][arXiv:1911.13158]], 57 pages
- Soumya Sengupta,\\
  "Atmospheric Thermal Emission Effect on Chandrasekhar's Finite Atmosphere Problem".\\
  {{{arXiv(2208.06656)}}}, 12 pages.

** Fluids
:PROPERTIES:
:CUSTOM_ID: h-641b95a3-9114-4784-aca0-4e755aca9ca6
:END:

- Alexander T Bradley, C. Rosie Williams, Adrian Jenkins, Robert Arthern,\\
  "Asymptotic Analysis of Subglacial Plumes in Stratified Environments".\\
  [[https://arxiv.org/abs/2103.09003][arXiv:2103.09003]], 33 pages
- Gui-Qiang G. Chen, Yucong Huang, Shengguo Zhu,\\
  "Global Spherically Symmetric Solutions of the Multidimensional Full Compressible Navier-Stokes Equations with Large Data".\\
  {{{arXiv(2208.05094)}}}, 85 pages
- Eduard Feireisl, Young Sam Kwon,\\
  "Taylor-Couette flow with temperature fluctuations: Time periodic solutions".\\
  {{{arXiv(2208.04543)}}}, 24 pages.
- Mamdouh S. Mohamed, Anil N. Hirani, Ravi Samtaney,\\
  "Discrete exterior calculus discretization of incompressible
  Navier-Stokes equations over surface simplicial meshes".\\
  [[https://arxiv.org/abs/1508.01166][arXiv:1508.01166]], 35 pages
- F.S. Pereira, F.F. Grinstein, D.M. Israel, L. Eca, \\
  "Verification and Validation: the Path to Predictive Scale-Resolving Simulations of Turbulence".\\
  [[https://arxiv.org/abs/2103.09899][arXiv:2103.09899]], 30 pages.
- K.R. Sreenivasan, V. Yakhot,\\
  "Dynamics of three-dimensional turbulence from Navier-Stokes equations".\\
  {{{arXiv(2106.01293)}}}, 17 pages.

** High Energy Theory
:PROPERTIES:
:CUSTOM_ID: h-3b3061e0-e6b9-47a3-93fb-0bd0fbd86222
:END:

- Diego Buccio, Roberto Percacci,\\
  "Renormalization Group flows between Gaussian Fixed Points".\\
  {{{arXiv(2207.10596)}}}, 18 pages.
- Marc Gillioz,\\
  "Conformal field theory for particle physicists".\\
  {{{arXiv(2207.09474)}}}, 69 pages
- Kirill Krasnov, \\
  "SO(9) characterisation of the Standard Model gauge group". \\
  [[https://arxiv.org/abs/1912.11282][arXiv:1912.11282]], 19 pages
- Petr Kravchuk, Jiaxin Qiao, Slava Rychkov,\\
  "Distributions in CFT II. Minkowski Space".\\
  {{{arXiv(2104.02090)}}}, 88+18 pages.
- Aleksandar Mikovic, Marko Vojinovic, \\
  "Standard Model and 4-groups". \\
  [[https://arxiv.org/abs/2008.06354][arXiv:2008.06354]], 6 pages.
- José M. Figueroa-O'Farrill,\\
  "Higher-dimensional kinematical Lie algebras via deformation theory".\\
  {{{arXiv(1711.07363)}}}, 18 pages
- Álvaro Pastor-Gutiérrez, Jan M. Pawlowski, Manuel Reichert,\\
  "The Asymptotically Safe Standard Model: From quantum gravity to dynamical chiral symmetry breaking".\\
  {{{arXiv(2207.09817)}}}, 38 pages.
- Robert A. Wilson,\\
  "Chirality in an E8 model of elementary particles".\\
  {{{arXiv(2210.06029)}}}, 21 pages.
  + Sequel to "Octions: An E8 description of the Standard Model"
    {{{arXiv(2204.05310)}}}, 15 pages.

** HEP-PH High Energy Physics Phenomenology
:PROPERTIES:
:CUSTOM_ID: h-3e299f15-1852-449d-b5ea-d108990f3eb9
:END:

- John Collins,\\
  "A new approach to the LSZ reduction formula".\\
  {{{arXiv(1904.10923)}}}, 42 pages.
** QUANT-PH Quantum Physics
:PROPERTIES:
:CUSTOM_ID: h-8c0a726f-98b8-472e-84eb-39f444d68a5b
:END:

- Brian C. Hall,\\
  "Holomorphic Methods in Mathematical Physics".\\
  {{{arXiv(quant-ph/9912054)}}}, 59 pages.