#+TITLE: Bookmarks
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-01-15T14:26:11-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5 num:nil
#+HTML_DOCTYPE: html5
#+INCLUDE: org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ./index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
# Created Friday January 15, 2021 at  2:26PM

#+begin_quote
Where must we go... \\
we who wander this Wasteland \\
in search of our better selves? \\
--- /The First History of Man/
#+end_quote

* Blogs
:PROPERTIES:
:CUSTOM_ID: h-0643e128-8ed0-4882-a621-e5117128d5a8
:END:

- [[https://robwilson1.wordpress.com/][Robert A Wilson's blog]], the group theorist who wrote the book
  {{{book-title(The Finite Simple Groups)}}}.
- [[https://cameroncounts.wordpress.com/][Peter Cameron's blog]] on group theory
- [[https://fredrikj.net/blog/][Fredrik Johansson's blog]], interesting symbolic computation blog
- [[https://bernsteinbear.com/][Max Bernstein's blog]] for more on programming language theory
- [[https://www.easterbrook.ca/steve/][Steve Easterbrooks blog]] discusses climate models
- [[https://nhigham.com/blog/][Nick Higham's blog]] on numerical linear algebra, and related topics
- [[https://mathproblems123.wordpress.com/category/numerical-analysis/][Beni Bogosel's blog]] on numerical analysis
- [[https://lawrencecpaulson.github.io/][Lawrence Paulson's blog]] on theorem provers
- [[http://www.topology.org/tex/conc/dgstats.php][Alan U. Kennington]] book on differential geometry
- [[https://amelia.how/archive.html][Amelia's blog]] on type theory and Haskell and stuff

** Fun References
:PROPERTIES:
:CUSTOM_ID: h-4eb8d1d4-3e92-4d02-a65d-495f5f4d6ada
:END:

- [[https://dlmf.nist.gov/][NIST Digital Library of Mathematical Functions]]
- [[https://fungrim.org/][The Mathematical Functions Grimoire]]

* Programming and Computers
:PROPERTIES:
:CUSTOM_ID: h-2dd9593d-2bf8-4a41-8295-15b4c234c7cf
:END:

- Scott Walck,\\
  "Learn Physics by Programming in Haskell".\\
  [[https://arxiv.org/abs/1412.4880][arXiv:1412.4880]], 11 pages

** CS.LO Logic in Computer Science
:PROPERTIES:
:CUSTOM_ID: h-616db70f-0194-4a3e-adcb-1d56a7ee9cd7
:END:

- Danil Annenkov, Mikkel Milo, Jakob Botsch Nielsen, Bas Spitters,\\
  "Extracting functional programs from Coq, in Coq".\\
  {{{arXiv(2108.02995)}}}, 57 pages
- Gilles Barthe, Raphaëlle Crubillé, Ugo Dal Lago, Francesco Gavazzo,\\
  "On Feller Continuity and Full Abstraction (Long Version)".\\
  {{{arXiv(2207.10590)}}}, 41 pages
- Jonas Bayer, Aleksey. Gonus, Christoph Benzmüller, Dana S. Scott,\\
  "Category Theory in Isabelle/HOL as a Basis for Meta-logical Investigation".\\
  {{{arXiv(2306.09074)}}}, 15 pages.
- Martin Berger, Dominic P. Mulligan,\\
  "A modest proposal: explicit support for foundational pluralism".\\
  {{{arXiv(2302.10137)}}}, 18 pages.
  - Intriguing discussion for explicitly marking proofs as "independent
    of axiom of choice", or "purely constructive proof".
- Paolo Capriotti,\\
  "Models of Type Theory with Strict Equality".\\
  {{{arXiv(1702.04912)}}}, PhD thesis, 95 pages.
  - Proves that the collection of models for a given theory does not
    necessarily form a category.
- Mario Carneiro,\\
  "Reimplementing Mizar in Rust".\\
  {{{arXiv(2304.08391)}}}, 16 pages.
  - Code repo: https://github.com/digama0/mizar-rs/tree/main
- Mario Carneiro,\\
  "Lean4Lean: Towards a Verified Typechecker for Lean, in Lean".\\
  {{{arXiv(2403.14064)}}}, 17 pages
- Joel D. Day, Vijay Ganesh, Nathan Grewal, Florin Manea,\\
  "Formal Languages via Theories over Strings".\\
  {{{arXiv(2205.00475)}}}
- Gilles Dowek,\\
  "A theory independent Curry-De Bruijn-Howard correspondence".\\
  {{{arXiv(2304.08068)}}}, 3 pages
- Gilles Dowek,\\
  "Skolemization in Simple Type Theory: the Logical and the Theoretical Points of View".\\
  {{{arXiv(2305.03322)}}}, 11 pages.
- Gilles Dowek,\\
  "What do we know when we know that a theory is consistent?".\\
  {{{arXiv(2305.10012)}}}, 6 pages.
  - Observes that higher-order resolution can fail faster (in finite
    time) than first-order resolution (which requires infinite time),
    and this may lead to a way to determine if a theory is consistent.
- Gilles Dowek,\\
  "The Undecidability of Typability in the Lambda-Pi-Calculus".\\
  {{{arXiv(2306.07599)}}}, 7 pages.
  - Specifically discusses the topic with the Elf programming language
    in mind.
- Gilles Dowek, Alexandre Miquel,\\
  "Relative normalization".\\
  {{{arXiv(2310.20248)}}}, 11 pages.
- Gilles Dowek, Alexandre Miquel,\\
  "Cut elimination for Zermelo set theory".\\
  {{{arXiv(2310.20253)}}}, 32 pages.
- Gilles Dowek, Gérard Huet, Benjamin Werner,\\
  "On the Definition of the Eta-long Normal Form in Type Systems of the Cube".\\
  {{{arXiv(2307.00854)}}}, originally published in 1993; 25 pages.
- Ciarán Dunne, J. B. Wells,\\
  "Isabelle/HOL/GST: A Formal Proof Environment for Generalized Set Theories".\\
  {{{arXiv(2207.12039)}}}, 20 pages.
- Matthias Eberl,\\
  "A Reflection Principle for Potential Infinite Models of Type Theory".\\
  {{{arXiv(2407.00220)}}}, 20 pages
- Jie Fan,\\
  "Unknown Truths and Unknowable Truths".\\
  {{{arXiv(2310.05777)}}}, 13 pages.
- Marcelo Fiore,\\
  "Semantic Analysis of Normalisation by Evaluation for Typed Lambda Calculus".\\
  {{{arXiv(2207.08777)}}}, 41 pages.
- Herman Geuvers,\\
  "The Calculus of Constructions and Higher Order Logic".\\
  In /The Curry-Howard isomorphism/ (ed. Ph. de Groote)\\
  [[http://www.cs.ru.nl/~herman/PUBS/CC_CHiso.pdf][Preprint]], discusses inconsistency in extensions of HOL (e.g., HOL +
  (prop = type) is inconsistent).
  - Geuvers actually uses this as grounds for arguing ~prop != type~ in
    general (Automath experiment also shows if ~prop = type~, then the
    law of double negation acts like a Hilbert choice operator, due to
    proof irrelevance being "the same" as type non-emptiness --- another
    reason why ~prop != type~ is a good idea).
- Herman Geuvers, Rob Nederpelt,\\
  "Characteristics of de Bruijn's early proof checker Automath".\\
  {{{arXiv(2203.01173)}}}, 24 pages.
  - A surprisingly good review of Automath, in the context of modern
    type systems.
- Alexander V. Gheorghiu, David J. Pym,\\
  "Proof-theoretic Semantics and Tactical Proof".\\
  {{{arXiv(2301.02302)}}}, 22 pages.
- Robert Harper,\\
  "An Equational Logical Framework for Type Theories".\\
  [[https://arxiv.org/abs/2106.01484][arXiv:2106.01484]], 9 pages.
- Alex Hubers, J. Garrett Morris,\\
  "Generic Programming with Extensible Data Types; Or, Making Ad Hoc Extensible Data Types Less Ad Hoc".\\
  {{{arXiv(2307.08759)}}}, 29 pages.
- Patricia Johann, Enrico Ghiorzi, Daniel Jeffries,\\
  "GADTs, Functoriality, Parametricity: Pick Two".\\
  [[https://arxiv.org/abs/2105.03389][arXiv:2105.03389]], 16 pages.
- András Kovács,\\
  "Type-Theoretic Signatures for Algebraic Theories and Inductive Types".\\
  {{{arXiv(2302.08837)}}}, PhD Thesis, 159 pages
- Tim S. Lyon, Piotr Ostropolski-Nalewaja,\\
  "Foundations for an Abstract Proof Theory in the Context of Horn Rules".\\
  {{{arXiv(2304.05697)}}}, 19 pages
- Leonardo de Moura, Jeremy Avigad, Soonho Kong, Cody Roux,\\
  "Elaboration in Dependent Type Theory".\\
  {{{arXiv(1505.04324)}}}, 28 pages.
- Tobias Nipkow, Simon Roßkopf,\\
  "Isabelle's Metalogic: Formalization and Proof Checker".\\
  {{{arXiv(2104.12224)}}}, 18 pages.
  - Formalizes Isabelle's Metalogic /in Isabelle!/
- Richard Schmoetten, Jacques D. Fleuriot,\\
  "A Construction of the Lie Algebra of a Lie Group in Isabelle/HOL".\\
  {{{arXiv(2407.19211)}}}, 29 pages.
- Mary Southern,\\
  "A Framework for Reasoning About LF Specifications".\\
  PhD Thesis, University of Minnesota, [[https://arxiv.org/abs/2105.04110][arXiv:2105.04110]], 188 pages.
  Also presents a unique variant of Canonical LF in chapter 2.
- Bas Spitters, Eelis van der Weegen,\\
  "Type Classes for Mathematics in Type Theory".\\
  {{{arXiv(1102.1323)}}}, 30 pages.
- Christian Williams, Michael Stay,\\
  "Native Type Theory".\\
  {{{arXiv(2102.04672)}}}, 12 pages.
  + "We propose a unifying method of reasoning for programming
    languages: model a language as a theory, form the category of
    presheaves, and use the internal language of the topos."
  + "Virtually any language can be modelled as a structured category: the
    most comprehensive reference I’ve found is /Categorical Logic and Type Theory/ by Bart Jacobs."
- Bohua Zhan,\\
  "Formalization of the fundamental group in untyped set theory using auto2".\\
  {{{arXiv(1707.04757)}}}, 17 pages.
  + One of the few formalizations using *both* /untyped/ set theory *and* Isabelle
- Tesla Zhang,\\
  "Type theories in category theory".\\
  {{{arXiv(2107.13242)}}}, 39 pages.

*** Verification of ML-like languages
:PROPERTIES:
:CUSTOM_ID: h-1aab67dd-78f6-46ee-9913-8bd458f0708b
:END:

- Laila El-Beheiry, Giselle Reis, Ammar Karkour,\\
  "SMLtoCoq: Automated Generation of Coq Specifications and Proof Obligations from SML Programs with Contracts".\\
  {{{arXiv(2107.07664)}}}, 17 pages
- Mário Pereira, António Ravara,\\
  "Cameleer: a Deductive Verification Tool for OCaml (extended version)".\\
  {{{arXiv(2104.11050)}}}, 24 pages
- Don Syme,\\
  "Reasoning with the Formal Definition of Standard ML in HOL".\\
  In /HUG1993/ pp.43--60 {{{doi(10.1007/3-540-57826-9_124)}}}, [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.35.1838][citeseer]]

*** Algebraic Effects
:PROPERTIES:
:CUSTOM_ID: h-6bb6de2b-ffee-44e9-a5f0-5b97f9dd4dac
:END:

- Birthe van den Berg, Tom Schrijvers,\\
  "A Framework for Higher-Order Effects & Handlers".\\
  {{{arXiv(2302.01415)}}}, 48 pages
- Gordon Plotkin and Matija Pretnar,\\
  "Handling Algebraic Effects".\\
  {{{arXiv(1312.1399)}}}, 36 pages.
- Tiago Soares, Mário Pereira,\\
  "A Framework for the Automated Verification of Algebraic Effects and Handlers (extended version)".\\
  {{{arXiv(2302.01265)}}}, 13 pages

** CS.PL Programming Languages
:PROPERTIES:
:CUSTOM_ID: h-1700895e-0a22-4131-8528-cef6269bcae0
:END:

- Arthur Adjedj, Meven Lennon-Bertrand, Kenji Maillard, Pierre-Marie Pédrot, Loïc Pujet,\\
  "Martin-Löf à la Coq".\\
  {{{arXiv(2310.06376)}}}, 15 pages
- Sandra Alves, Miguel Ramos,\\
  "An ML-style record calculus with extensible records".\\
  {{{arXiv(2108.06296)}}}, 35 pages.
- Andreas Abel,\\
  "Normalization by Evaluation".\\
  Habilitation thesis, 96 pages, [[https://www.cse.chalmers.se/~abela/habil.pdf][PDF]]. (2015?)
- Michael Borkowski, Niki Vazou, Ranjit Jhala,\\
  "Mechanizing Refinement Types (extended)".\\
  {{{arXiv(2207.05617)}}}, 32 pages.
- Chris Casinghino,\\
  "Strong Normalization for the Calculus of Constructions".\\
  {{{arXiv(2210.11240)}}}, 39 pages.
- Yulong Huang, Jeremy Yallop,\\
  "Defunctionalization with Dependent Types".\\
  {{{arXiv(2304.04574)}}}, 30 pages.
- Michael Kölling,\\
  "Principles of Educational Programming Language Design".\\
  {{{doi(10.15388/infedu.2024.29)}}}, 14 pages
  - Stresses the need for "simplicity" (in the sense there's "one way"
    to do something) for an educational programming
    language (in the sense that it's used to teach people their first
    programming language), but "simplicity" means something else for
    "real" programming languages (usually: there's an /elegant/ way to
    do something)
- Marco Paviotti, Nicolas Wu,\\
  "Full Abstraction for Free".\\
  {{{arXiv(2303.09358)}}}, 20 pages.
- Arjen Rouvoet,\\
  "Correct by Construction".
  PhD Thesis, [[https://ajrouvoet.github.io/files/thesis.pdf][pdf]], 244 pages
- KC Sivaramakrishnan, Stephen Dolan, Leo White, Tom Kelly, Sadiq Jaffer, Anil Madhavapeddy,\\
  "Retrofitting Effect Handlers onto OCaml".\\
  [[https://arxiv.org/abs/2104.00250][arXiv:2104.00250]], 16 pages
- Jonathan Sterling,\\
  "Reflections on existential types".\\
  {{{arXiv(2210.00758)}}}, 21 pages.
- Roger C. Su, Robert J. Colvin,\\
  "Weak Memory Model Formalisms: Introduction and Survey".\\
  {{{arXiv(2508.04115)}}}, 50 pages
- Michael Wessel,\\
  "Notes on Refactoring Exponential Macros in Common Lisp".\\
  {{{arXiv(2305.02991)}}}
- Han Xu, Zhenjiang Hu,\\
  "Analytical Differential Calculus with Integration".\\
  [[https://arxiv.org/abs/2105.02632][arXiv:2105.02632]], 42 pages; discusses differential lambda calculus
  with integrals.
- Litao Zhou, Qianyong Wan, Bruno C. d. S. Oliveira,\\
  "Full Iso-recursive Types".\\
  {{{arXiv(2407.00941)}}}, 25 pages
  - Proposes a *generalization* of iso-recursive types called "full
    iso-recursive types".

** Symbolic Computation
:PROPERTIES:
:CUSTOM_ID: h-5b88ae4b-23c9-4ba5-a3d2-b56f9105e02c
:END:

- Thomas Fischbacher,\\
  "A novel approach to symbolic algebra".\\
  [[https://arxiv.org/abs/cs/0406002][arXiv:cs/0406002]], 15 pages, discusses an approach using MzScheme.

* Math
:PROPERTIES:
:CUSTOM_ID: h-25791061-4fd7-4f31-9172-1c2505e13dc9
:END:

** Math.AG Algebraic Geometry
:PROPERTIES:
:CUSTOM_ID: h-420b41c1-0679-47b7-abe2-808d4ad68781
:END:

- Aravind Asok, Jean Fasel,\\
  "Vector bundles on algebraic varieties".\\
  {{{arXiv(2111.03107)}}}, 20 pages.
- J.-F. Pommaret,\\
  "Differential Galois Theory and Hopf Algebras for Lie Pseudogroups".\\
  {{{arXiv(2308.03759)}}}, 33 pages.
- Ravi Vakil's [[http://math.stanford.edu/~vakil/216blog/][Rising Sea]] lecture notes

** Math.AP Analysis of PDEs
:PROPERTIES:
:CUSTOM_ID: h-0c32530b-a377-482c-aa9c-6381085d035d
:END:

- Alexander V. Aksenov, Andrei D. Polyanin,\\
  "Construction of complex solutions to nonlinear partial differential equations using simpler solutions".\\
  [[https://arxiv.org/abs/2102.04815][arXiv:2102.04815]], 49 pages
- Thomas Doehrman, David Glickenstein,\\
  "Determinant of the finite volume Laplacian".\\
  {{{arXiv(2108.07308)}}}, 14 pages, discusses determinant of discrete Laplacian.
- Boris Khesin, Gerard Misiolek, Alexander Shnirelman,\\
  "Geometric Hydrodynamics in Open Problems".\\
  {{{arXiv(2205.01143)}}}, 37 pages.
- D. Maroncelli, E. Collins,\\
  "Weakly Nonlocal Boundary Value Problems with Application to Geology".\\
  [[https://arxiv.org/abs/2103.09095][arXiv:2103.09095]], 15 pages
- Friedrich Philipp, Timo Reis, Manuel Schaller,\\
  "Infinite-dimensional port-Hamiltonian systems -- a system node approach".\\
  {{{arXiv(2302.05168)}}}, 37 pages.
- Emmett L. Wyman, Yakun Xi,\\
  "Can you hear your location on a manifold?".\\
  {{{arXiv(2304.04659)}}}, 26 pages.
- Peicheng Zhu, Lei Yu, Yang Xiang,\\
  "Weak solutions to an initial-boundary value problem for a continuum equation of motion of grain boundaries".\\
  {{{arXiv(2204.13325)}}}, 25 pages.

*** Euler Flow
:PROPERTIES:
:CUSTOM_ID: h-893ae18c-39ea-4aad-91b4-834832946cb4
:END:

- Jiajie Chen, Thomas Y. Hou,\\
  "Stable nearly self-similar blowup of the 2D Boussinesq and 3D Euler equations with smooth data I: Analysis".\\
  {{{arXiv(2210.07191)}}}, 145 pages
- Jiajie Chen, Thomas Y. Hou,\\
  "Stable nearly self-similar blowup of the 2D Boussinesq and 3D Euler equations with smooth data II: Rigorous Numerics".\\
  {{{arXiv(2305.05660)}}}, 141 pages
- Tarek M Elgindi,\\
  "Finite-Time Singularity Formation for $C^{1,\alpha}$ Solutions to the
  Incompressible Euler Equations on R^3".\\
  [[https://arxiv.org/abs/1904.04795][arXiv:1904.04795]], 60 pages; see also follow up paper [[https://arxiv.org/abs/1910.14071][arXiv:1910.14071]].
- Evan Miller,\\
  "On the regularity of axisymmetric, swirl-free solutions of the Euler equation in four and higher dimensions".\\
  {{{arXiv(2204.13406)}}}, 52 pages
- Matthew Rosenzweig,\\
  "On the Rigorous Derivation of the Incompressible Euler Equation from Newton's Second Law".\\
  [[https://arxiv.org/abs/2104.11723][arXiv:2104.11723]], 20 pages.
- Luigi De Rosa, Marco Inversi, Giorgio Stefani,\\
  "Weak-strong uniqueness and vanishing viscosity for incompressible Euler equations in exponential spaces".\\
  {{{arXiv(2204.12779)}}}, 22 pages

*** Navier-Stokes Equations
:PROPERTIES:
:CUSTOM_ID: h-3998242d-365c-425f-98a3-d71d383c3e0b
:END:

- Dallas Albritton, Elia Brué, Maria Colombo,\\
  "Non-uniqueness of Leray solutions of the forced Navier-Stokes equations".\\
  {{{arXiv(2112.03116)}}}, 31 pages.
- Lorenzo Brandolese,\\
  "Hexagonal structures in 2D Navier-Stokes flows".\\
  [[https://arxiv.org/abs/2102.00728][arXiv:2102.00728]], 25 pages
- Yuxi Hu, Reinhard Racke,\\
  "Global existence versus blow-up for multi-d hyperbolized compressible Navier-Stokes equations".\\
  {{{arXiv(2204.13080)}}}, 26 pages.
- Jiaxu Li, Jing Li, Boqiang Lü,\\
  "Global Classical Solutions to the Full Compressible Navier-Stokes System in 3D Exterior Domains".\\
  {{{arXiv(2208.11925)}}}, 53 pages.
- Yanlin Liu, Ping Zhang,\\
  "On the global stability of large Fourier mode for 3-D Navier-Stokes equations".\\
  {{{arXiv(2305.05272)}}}, 53 pages.
- Paolo Maremonti, Francesca Crispo, Carlo Romano Grisanti,\\
  "Navier-Stokes equations: a new estimate of a possible gap related to the energy equality of a suitable weak solution".\\
  {{{arXiv(2204.11359)}}}, 13 pages
- Sarka Necasova, Justyna Ogorzaly, Jan Scherz,\\
  "The compressible Navier-Stokes equations with slip boundary conditions of friction type".\\
  {{{arXiv(2305.00822)}}}, 17 pages
  - Claims to prove the global existence of weak solutions to
    Navier-Stokes with specified boundary conditions.
- Gregory Seregin,\\
  "Remarks on Type II blowups of solutions to the Navier-Stokes equations".\\
  {{{arXiv(2304.04045)}}}, 27 pages.
- Chao Wang, Yuxi Wang, Zhifei Zhang,\\
  "Zero-viscosity limit of the compressible Naiver-Stokes equations in the analytic setting".\\
  {{{arXiv(2305.09393)}}}, 43 pages.

*** In Geophysics
:PROPERTIES:
:CUSTOM_ID: h-88000a50-18d6-4894-8f08-8bdc327d9034
:END:

- Diego Berti, Luca Bisconti, Davide Catania,\\
  "Global existence for a 3D Tropical Climate Model with damping and small initial data in H^{1/2}(ℝ^{3})".\\
  {{{arXiv(2305.07964)}}}, 20 pages.
- Bogdan-Vasile Matioc, Luigi Roberti,\\
  "Weak and classical solutions to an asymptotic model for atmospheric flows".\\
  {{{arXiv(2304.08985)}}}, 18 pages.

** Math.CA Classical Analysis
:PROPERTIES:
:CUSTOM_ID: h-c09523ff-ba33-4ef9-ac67-9adddde406ce
:END:

- Felix Hummel, Peter Ashwin, Christian Kuehn,\\
  "Reduction Methods in Climate Dynamics -- A Brief Review".\\
  {{{arXiv(2209.12240)}}}, 48 pages.

** Math.CO Combinatorics
:PROPERTIES:
:CUSTOM_ID: h-e5b7653c-61c9-4ab3-bc0d-7fc41f162ea9
:END:

- Gerald Hoehn,\\
  "Self-dual Codes over the Kleinian Four Group".\\
  {{{arXiv(math/0005266)}}}, 26 pages.
- Himadri Shekhar Chakraborty, Tsuyoshi Miezaki, Manabu Oura, Yuuho Tanaka,\\
  "Jacobi polynomials and design theory I".\\
  {{{arXiv(2207.10911)}}}, 23 pages.
- Himadri Chakraborty, Reina Ishikawa, Yuuho Tanaka,\\
  "Jacobi polynomials and design theory II".\\
  {{{arXiv(2304.06220)}}}, 28 pages.
  
** Math.CT Category Theory
:PROPERTIES:
:CUSTOM_ID: h-4f2e35f6-82de-4cb6-b32f-f6f39edd0b30
:END:

- Antoine Allioux, Eric Finster, Matthieu Sozeau,\\
  "Types are Internal ∞-Groupoids".\\
  [[https://arxiv.org/abs/2105.00024][arXiv:2105.00024]], 16 pages.
- Jose Avila,\\
  "A categorical view of varieties and equations".\\
  {{{arXiv(2310.07055)}}}, 17 pages --- refers to Birkhoff varieties (from
  universal algebra), /not/ algebraic varieties (from algebraic geometry).
- Ingo Blechschmidt,\\
  "Exploring mathematical objects from custom-tailored mathematical
  universes".\\
  {{{arXiv(2204.00948)}}}, 32 pages.
- Carmen Constantin, Tobias Fritz, Paolo Perrone, Brandon Shapiro,\\
  "Weak cartesian properties of simplicial sets".\\
  [[https://arxiv.org/abs/2105.04775][arXiv:2105.04775]], 48 pages.
- Ivan Contreras, Molly Keller, Rajan Amit Mehta,\\
  "Frobenius objects in the category of spans".\\
  [[https://arxiv.org/abs/2106.14743][arXiv:2106.14743]], 31 pages
  - Frobenius objects generalize Frobenius algebras, which describe
    TQFTs. Rajan Amit Mehta seems to have discussed them earlier in
    [[https://arxiv.org/abs/1907.00702][arXiv:1907.00702]] crediting their invention to:
    Joachim Kock, {{{book-title(Frobenius algebras and 2D topological quantum field theories)}}}, CUP, 2004.
  - The category *Rel* acts like a "toy symplectic category" without any
    of the difficulties.
- Ivo Dell'Ambrogio,\\
  "Green 2-functors".
  {{{arXiv(2107.09478)}}}, 41 pages.
  - Mackey 2-functors introduced in {{{arXiv(1808.04902)}}} (213 pages,
    "many beautiful figures").
- Fabrizio Genovese, Fosco Loregian, \\
  "Differential 2-rigs". \\
  [[https://arxiv.org/abs/2103.00938][arXiv:2103.00938]], 32 pages.
- James Hefford, Mario Román,\\
  "Optics for Premonoidal Categories".\\
  {{{arXiv(2305.02906)}}}
- Matias del Hoyo, Giorgio Trentinaglia,\\
  "Simplicial vector bundles and representations up to homotopy".\\
  {{{arXiv(2109.01062)}}}, 66 pages.
- Giulio Lo Monaco,\\
  "Vopěnka's principle in ∞-categories".\\
  [[https://arxiv.org/abs/2105.04251][arXiv:2105.04251]], 22 pages.
- Louis Martini, Sebastian Wolf,\\
  "Internal higher topos theory".\\
  {{{arXiv(2303.06437)}}}, 52 pages.
- Nima Rasekh,\\
  "Non-Standard Models of Homotopy Type Theory".\\
  {{{arXiv(2508.07736)}}}, 21 pages
- Yuri Shimizu,\\
  "∞-cosheafification".\\
  [[https://arxiv.org/abs/2106.14135][arXiv:2106.14135]], 11 pages.
- Taichi Uemura,\\
  "A General Framework for the Semantics of Type Theory".\\
  {{{arXiv(1904.04097)}}}, 57 pages.
- Yasuhiro Wakabayashi,\\
  "On the category of structure species".\\
  {{{arXiv(2201.11273)}}}, 21 pages
- Zhen Huan,\\
  "2-Representations of Lie 2-groups and 2-Vector Bundles".\\
  {{{arXiv(2208.10042)}}}, 62 pages.

** Math.DG Differential Geometry
:PROPERTIES:
:CUSTOM_ID: h-6db90c1a-f521-4efe-9c2a-fc00d37070b3
:END:

- Max Chemtov, Spiro Karigiannis,\\
  "Observations about the Lie algebra 𝔤2⊂𝔰𝔬(7), associative 3-planes, and 𝔰𝔬(4) subalgebras".\\
  {{{arXiv(2209.10613)}}}, 21 pages.
- Mathieu Desbrun, Anil N. Hirani, Melvin Leok, Jerrold E. Marsden,\\
  "Discrete Exterior Calculus".\\
  [[https://arxiv.org/abs/math/0508341][arXiv:math/0508341]], 53 pages
- Rui Loja Fernandes, Marius Crainic,\\
  "Lectures on Integrability of Lie Brackets".\\
  {{{arXiv(math/0611259)}}}, 95 pages; see especially \sect3.2 for a proof
  of Lie's third theorem using homotopic equivalence classes of paths.
- Andreas Mueller,\\
  "Review of the Exponential and Cayley Map on SE(3) as relevant for Lie Group Integration of the Generalized Poisson Equation and Flexible Multibody Systems".\\
  {{{arXiv(2303.07928)}}}, 21 pages.
- Olaf Müller,\\
  "Functors in Lorentzian geometry -- three variations on a theme".\\
  {{{arXiv(2205.01617)}}}, 12 pages.
- José Figueroa-O'Farrill,\\
  "Non-Lorentzian Spacetimes".\\
  {{{arXiv(2204.13609)}}}, 18 pages.
- Ichiro Yokota,\\
  "Exceptional Lie groups".\\
  {{{arXiv(0902.0431)}}}, 204 pages.

** Math.DS Dynamical Systems
:PROPERTIES:
:CUSTOM_ID: h-3886892d-739e-499e-89e0-0b5209831a30
:END:

- Roberto Camassa, Richard M. McLaughlin,\\
  "Tauberian identities and the connection to Wile E. Coyote physics".\\
  {{{arXiv(2304.06127)}}}, 14 pages.

** Math.GR Group Theory
:PROPERTIES:
:CUSTOM_ID: h-5f6e5a83-f5db-4e97-8cde-16ac0f77d9d1
:END:

- [[https://kourovka-notebook.org/][Kourovka Notebook]] of unsolved problems in group theory

- Daniel Allcock, Tathagata Basak,\\
  "The Deligne-Mostow 9-ball, and the monster".\\
  {{{arXiv(2309.00148)}}}, 29 pages.
- Simon André, Vincent Guirardel,\\
  "Finitely generated simple sharply 2-transitive groups".\\
  {{{arXiv(2212.06020)}}}, 21 pages
- Martin van Beek,\\
  "Exotic Fusion Systems Related to Sporadic Simple Groups".\\
  {{{arXiv(2201.01790)}}}, 40 pages.
- Martin van Beek,\\
  "Saturated Fusion Systems on Sylow p-subgroups of Rank 2 Simple Groups of Lie Type".\\
  {{{arXiv(2302.02222)}}}, 44 pages.
- Christopher P. Bendel,\\
  "Cohomology of algebraic groups, Lie algebras, and finite groups of Lie type".\\
  {{{arXiv(2209.01140)}}}, 22 pages.
- Carl-Fredrik Nyberg Brodda,\\
  "The Adian-Rabin Theorem -- An English translation".\\
  {{{arXiv(2208.08560)}}}, 89 pages.
- Peter J. Cameron,\\
  "Graphs defined on groups".\\
  {{{arXiv(2102.11177)}}}, 81 pages, review paper.
- Antoine Chambert-Loir,\\
  "Formalizing the proof of an intermediate-level algebra theorem -- An experiment".\\
  {{{arXiv(2303.12404)}}}, 18 pages.
- Jacques Darné, Martin Palmer, Arthur Soulié,\\
  "When the lower central series stops".\\
  {{{arXiv(2201.03542)}}}, 86 pages.
- Tevian Dray, Corinne A. Manogue, Robert A. Wilson,\\
  "A New Division Algebra Representation of $E_{6}$".\\
  {{{arXiv(2309.00078)}}}, 9 pages.
- Tevian Dray, Corinne A. Manogue, Robert A. Wilson,\\
  "A New Division Algebra Representation of $E_{7}$".\\
  {{{arXiv(2401.10534)}}}, 11 pages.
- Misha Gavrilovich,\\
  "Expressing the statement of the Feit-Thompson theorem with diagrams in the category of finite groups".\\
  {{{arXiv(1608.05927)}}}, 8 pages
- Oussama Hamza,\\
  "Isotypical study of Zassenhaus and lower central filtrations on pro-p groups".\\
  {{{arXiv(2207.12372)}}}, 25 pages.
- Kadeem Harrigan,\\
  "Aschbacher's Theorem for the General Linear Group".\\
  {{{arXiv(2112.02430)}}}, 49 pages; MSc thesis submitted at Imperial College London.
- Omar Hatem, Daoud Siniora,
  "A Group with Exactly One Noncommutator".\\
  {{{arXiv(2511.00541)}}}, 5 pages
  - Solves problem 17.76 of the Kourovka notebook
- Caleb Ji,\\
  "A note on regular polyhedra over finite fields".\\
  {{{arXiv(2304.03345)}}}, 8 pages.
- Andreas Kollross,\\
  "The bracket of the exceptional Lie algebra E8".\\
  {{{arXiv(2504.16513)}}}, 13 pages
- Dilpreet Kaur, Amit Kulshrestha,\\
  "Strongly real special 2-groups".\\
  {{{arXiv(1210.3790)}}}, 16 pages
- Dilpreet Kaur, Saikat Panja\\
  "Rational conjugacy classes and rational characters for some finite simple groups".\\
  {{{arXiv()}}}, 14 pages
- Dimitri Leemans, Klara Stokes,\\
  "Incidence geometries with trialities coming from maps with Wilson trialities".\\
  {{{arXiv(2208.08215)}}}, 13 pages.
- Alastair J. Litterick, David I. Stewart, Adam R. Thomas,\\
  "Complete reducibility and subgroups of exceptional algebraic groups".\\
  {{{arXiv(2209.11310)}}}, 42 pages.
- Nicolas Magaud,\\
  "Spreads and Packings of PG(3,2), Formally!"\\
  {{{arXiv(2201.00541)}}}, 9 pages, discusses Coq formalization.
- Leo Margolis,\\
  "The Modular Isomorphism Problem: a survey".\\
  {{{arXiv(2202.11412)}}}, 31 pages.
- Alexander Moretó,\\
  "Methods and questions in character degrees of finite groups".\\
  {{{arXiv(2209.09221)}}}, 19 pages.
- Yannick Neyt, James Parkinson, Hendrik Van Maldeghem, Magali Victoor,\\
  "Automorphisms and opposition in spherical buildings of exceptional type, IV: The E7 case".\\
  {{{arXiv(2402.04323)}}}, 68 pages
- Yannick Neyt, James Parkinson, Hendrik Van Maldeghem,\\
  "Automorphisms of Lie incidence geometries with spectral gaps".
  {{{arXiv(2511.01119)}}}, 26 pages
- Graham A. Niblo, Roger Plymen, Nick Wright,\\
  "Centralisers, complex reflection groups and actions in the Weyl group E6".\\
  {{{arXiv(2205.08230)}}}, 47 pages
- James Parkinson, Hendrik Van Maldeghem,\\
  "Automorphisms and opposition in spherical buildings of classical type".\\
  {{{arXiv(2303.07707)}}}, 41 pages
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The BMS Group".\\
  {{{arXiv(2106.12513)}}}, 27 pages.
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The NU Group".\\
  {{{arXiv(2109.11476)}}}, 38 pages
- Benjamin Sambale,\\
  "On the converse of Gaschütz' complement theorem".\\
  {{{arXiv(2303.00254)}}}, 13 pages.
- Markus J. Stroppel,\\
  "A unital in the generalized hexagon of order two, and an exceptional isomorphism between finite groups of Lie type".\\
  {{{arXiv(2412.09081)}}}, 18 pages
- Michael Turner,\\
  "Skew Axial Algebras of Monster Type".\\
  {{{arXiv(2303.09345)}}}, 26 pages.
- Nicholas J. Werner,\\
  "A Note on Finite Nilpotent Groups".\\
  {{{arXiv(2407.05498)}}}, 3 pages.
  - New characterization of nilpotent finite groups as: for each
    subgroup $H$ of $G$ and for all $x\in G$ we have $x^{[G:H]}\in H$
    if and only if $G$ is nilpotent.
- Robert A. Wilson,\\
  "Comparison of group-theoretical strategies for unification of 3+1 structures in physics".\\
  {{{arXiv(2108.04675)}}}, 8 pages.
- Robert A. Wilson,\\
  "Possible uses of the binary icosahedral group in grand unified theories".\\
  {{{arXiv(2109.06626)}}}, 28 pages.
- R. A. Wilson,\\
  "Integer versions of Yang-Mills theory".\\
  {{{arXiv(2202.08263)}}}, 13 pages.
- Robert A. Wilson,\\
  "Uniqueness of an E8 model of elementary particles".\\
  {{{arXiv(https://arxiv.org/abs/2407.18279)}}}, 12 pages.
- R. A. Wilson, T. Dray, C. A. Manogue,\\
  "An octonionic construction of E8 and the Lie algebra magic square".\\
  {{{arXiv(2204.04996)}}}, 19 pages.
- Yu Zeng, Dongfang Yang,\\
  "A characterization of finite groups by certain Galois conjugacy class of irreducible characters".\\
  {{{arXiv(2208.07782)}}}, 15 pages.

*** Algebraic Groups
:PROPERTIES:
:CUSTOM_ID: h-301b95cc-a6a0-42c2-a61e-3f4f274e03f8
:END:

- Benjamin Martin,\\
  "Algebraic groups and G-complete reducibility: a geometric approach".\\
  {{{arXiv(2207.12169)}}}, 28 pages.

*** Finite Groups
:PROPERTIES:
:CUSTOM_ID: h-519655a5-272d-441b-a718-06c3412d1064
:END:

- Sylvia Bayard, Justin Lynd,\\
  "Realizing Finite Groups as Automizers".\\
  {{{arXiv(2203.14413)}}}, 9 pages
- Yiming Bing, Bright Hu, Ronni Hu, Rhianna Li, Stefan Lu, Finn McDonald, Michael Sun, Nicholas Wolfe, Joshua Yao, Leon Zhou, Nathan Zhou,\\
  "The Mathieu group $M_{23}$ as additive functions on the finite field of size $2^{11}$".\\
  {{{arXiv(2201.00108)}}}, 15 pages.
- Thomas Breuer, Kay Magaard, Robert A. Wilson,\\
  "Verification of the conjugacy classes and ordinary character table of the Monster".\\
  {{{arXiv(2412.12182)}}}, 11 pages
  - Details are discussed in their companion paper
    {{{arXiv(2412.09313)}}}, 43 pages
- Eloisa Detomi, Andrea Lucchini,\\
  "Strongly generating elements in finite and profinite groups".\\
  {{{arXiv(2208.05761)}}}, 9 pages.
- Heiko Dietrich, Melissa Lee, Tomasz Popiel,\\
  "PGL2(13) is a maximal subgroup of the Monster".\\
  {{{arXiv(2304.14646)}}}, 9 pages.
- Heiko Dietrich, Melissa Lee, Tomasz Popiel,\\
  "Indeed, the Monster has no almost simple maximal subgroups with socle PSL2(16) or PSU3(4)".\\
  {{{arXiv(2310.03317)}}}, 9 pages
- Wenbin Guo, Danila O. Revin, Andrey V. Vasil'ev,\\
  "On embedding theorems for 𝔛-subgroups".\\
  {{{arXiv(2206.10267)}}}, 8 pages
- Neha Malik, Steven Spallone,\\
  "Stiefel-Whitney Classes of Representations of SL(2,q)".\\
  {{{arXiv(2208.05813)}}}, 24 pages.
- Gunter Malle,\\
  "Subnormalisers of semisimple elements in finite groups of Lie type".\\
  {{{arXiv(2511.01557)}}}, 28 pages
- John McKay, Yang-Hui He,\\
  "Kashiwa Lectures on 'New Approaches to the Monster'".\\
  [[https://arxiv.org/abs/2106.01162][arXiv:2106.01162]], 42 pages.
- Peter M. Neumann,\\
  "Primitive permutation groups of degree 3p".\\
  {{{arXiv(2204.06926)}}}, 43 pages; unpublished manuscript from 1969.
- Peter M. Neumann,\\
  "Infinite Permutation Groups".\\
  {{{arXiv(2307.11564)}}}, lectures notes, 135 pages
- Wolfram Neutsch,\\
  "Lyons Taming".\\
  {{{arXiv(2307.11399)}}}, 42 pages.
- Parveen, Jitender Kumar, Siddharth Singh, Xuanlong Ma,\\
  "Certain properties of the enhanced power graph associated with a finite group".\\
  {{{arXiv(2207.05075)}}}, 8 pages.
- Zhengtian Qiu, Guiyun Chen, Jianjun Liu,\\
  "On L-Pi-property of subgroups of finite groups".\\
  {{{arXiv(2310.09814)}}}, 10 pages.
- Danila Revin, Evgeny Vdovin,\\
  "Frattini Argument for Hall subgroups".\\
  {{{arXiv(1401.7719)}}}, 9 pages.
- Eliana Rodrigues, Emerson de Melo, Gülin Ercan,\\
  "Nilpotent Residual of a Finite Group".\\
  {{{arXiv(2305.04993)}}}, 14 pages.
- Martin Seysen,\\
  "A computer-friendly construction of the monster".\\
  {{{arXiv(2002.10921)}}}, 34 pages.
- Pablo Spiga,\\
  "An explicit upper bound on the number of subgroups of a finite group".\\
  {{{arXiv(2210.02972)}}}, 9 pages; claims the upper bound is $7.3722\cdot|G|^{1.5315+(\lg|G|)/4}$


**** ATLAS of Finite Groups
:PROPERTIES:
:CUSTOM_ID: h-39744a7a-ccec-4024-868e-d850ff724237
:END:

- Thomas Breuer,\\
  "Constructing the ordinary character tables of some Atlas groups using
  character theoretic methods".\\
  {{{arXiv(1604.00754)}}}, 90 pages.
- Thomas Breuer, Kay Magaard, Robert Wilson,\\
  "Verification of the ordinary character table of the Baby Monster".\\
  {{{arXiv(1902.07758)}}}, 17 pages. (The first draft had proved the
  Schur multiplier of the Monster is trivial, which was replaced by a
  citation in the second draft.)

**** Finite Groups of Lie Type
:PROPERTIES:
:CUSTOM_ID: h-0c8bd087-71d9-40dc-8b40-22f2b8ba8b46
:END:

- Hannah Knight,\\
  "The essential p-dimension of finite simple groups of Lie type".\\
  {{{arXiv(2109.02698)}}}, 65 pages
- Timothy C. Burness, Adam R. Thomas,\\
  "Normalisers of maximal tori and a conjecture of Vdovin".\\
  {{{arXiv(2207.09495)}}}, 33 pages.
- A. Pachera,\\
  "Embeddings of PSL2(q) in exceptional groups of Lie type over a field of characteristic ≠2,3".\\
  {{{arXiv(2212.08505)}}}, 88 pages.
  
**** Sylow p-Subgroups and Hall \pi-Subgroups
:PROPERTIES:
:CUSTOM_ID: h-fa155afc-5c2c-47cd-aeff-27b881b14a70
:END:

- Timothy C. Burness, Robert M. Guralnick,\\
  "On the generation of simple groups by Sylow subgroups".\\
  {{{arXiv(2204.04311)}}}, 17 pages.
- Wenbin Guo, Alexander N. Skiba,\\
  "On Hall subgroups of a finite group".\\
  {{{arXiv(1205.2496)}}}, 14 pages.
- N. N. Hung, A. Maróti, J. Martínez,\\
  "Classes of π-elements and nilpotent/abelian Hall π-subgroups".\\
  {{{arXiv(2207.04988)}}}, 18 pages.
- Gabriel Navarro, Benjamin Sambale,\\
  "Characters, Commutators and Centers of Sylow Subgroups".\\
  {{{arXiv(2204.04407)}}}, 18 pages
- Nomina Ch. Manzaeva, Danila O. Revin, Evgeny P. Vdovin,\\
  "The Hall property Dπ is inherited by overgroups of π-Hall subgroups".\\
  {{{arXiv(1808.03536)}}}, 27 pages
- Primoz Moravec,\\
  "The powerful class of Sylow subgroups of finite groups".\\
  {{{arXiv(2410.15348)}}}, 7 pages
- D.O.Revin, E.P.Vdovin,\\
  "On the number of classes of conjugate Hall subgroups in finite simple groups".\\
  {{{arXiv(0912.1922)}}}, 54 pages.
- Ruslan Skuratovskii,\\
  "The commutator and centralizer description of Sylow 2-subgroups of alternating and symmetric groups".\\
  {{{arXiv(1712.01401)}}}, 19 pages.

*** Loops
:PROPERTIES:
:CUSTOM_ID: h-6a030b53-5592-478b-8f2b-a7f745fa267c
:END:

A loop is a "group without requiring associativity". It's useful for
error correcting codes and, in particular, constructing sporadic
groups. (See Aschbacher's {{{book-title(Sporadic Groups)}}} (CUP, 1994)
for details.)

- Tim Hsu,\\
  "Class 2 Moufang loops, small Frattini Moufang loops, and code loops".\\
  {{{arXiv(math/9611214)}}}, 31 pages
- Ben Nagy, David Michael Roberts,\\
  "(Re)constructing Code Loops".\\
  {{{arXiv(1903.02748)}}}, 10 pages
- E.A. O'Brien, Petr Vojtěchovský,\\
  "Code loops in dimension at most 8".\\
  {{{arXiv(1712.06524)}}}, 15 pages

** Math.HO History and Overview
:PROPERTIES:
:CUSTOM_ID: h-b63c6476-fd76-48f4-b419-4ecd2770303b
:END:

- Piotr Błaszczyk, Anna Petiurenko,\\
  "Euler's Series for Sine and Cosine. An Interpretation in Nonstandard Analysis".\\
  {{{arXiv(2304.01353)}}}, 34 pages.
- Andy Eskenazi, Kevin You, Will Vauclain, Robin Murugadoss,\\
  "A Beginner's Guide to Homological Algebra: An Introduction for Intermediate and Advanced Mathematicians".\\
  {{{arXiv(2208.11199)}}}, 32 pages
- Andrew Granville,\\
  "Accepted proofs: Objective truth, or culturally robust".\\
  {{{arXiv(2305.02115)}}}, 48 pages.
- Emmy Noether, (tr. Colin McLarty),\\
  "The finiteness theorem for invariants of a finite group".
  {{{arXiv(1503.07849)}}}, 3 pages
- Andrei Rodin,\\
  "Kolmogorov's Calculus of Problems and Its Legacy".\\
  {{{arXiv(2307.09202)}}}, 66 pages.
  - Kolmogorov discussed intuitionistic logic, not in terms of
    "propositions", but in terms of "problems"...which is a *very clever*
    spin on things.
- Benjamin Sambale,\\
  "An invitation to formal power series".\\
  {{{arXiv(2205.00879)}}}, 61 pages.

** Math.LO Logic
:PROPERTIES:
:CUSTOM_ID: h-77765895-8b26-4057-b243-06f594378e59
:END:

- David Asperó, Ralf Schindler,\\
  "MM^{++} implies ~(*)~".\\
  {{{arXiv(1906.10213)}}}, 48 pages.
- Jeremy Avigad,\\
  "Foundations".\\
  {{{arXiv(2009.09541)}}}, 54 pages
- Vasco Brattka,\\
  "On the Complexity of Computing Gödel Numbers".\\
  {{{arXiv(2302.04213)}}}, 23 pages
- Merlin Carl,\\
  "Recognizable Realizability".\\
  {{{arXiv(2408.07030)}}}, 21 pages.
- Jason Chen, Toby Meadows,\\
  "Teasing apart definitional equivalence".\\
  {{{arXiv(2508.03956)}}}, 12 pages
- Walter Dean, Hidenori Kurokawa,\\
  "On the methodology of informal rigour: set theory, semantics, and intuitionism".\\
  [[https://arxiv.org/abs/2104.14887][arXiv:2104.14887]], 83 pages.
  - This is the second paper which references Georg Kreisel's paper on
    ZFC_{2} (ZFC formulated in second-order logic), specifically:\\
    G. Kreisel,\\
    "Informal Rigour and Completeness Proofs".\\
    In I. Lakatos, editor, {{{book-title(Problems in the philosophy of mathematics: Proceedings of the International Colloquium in the Philosophy of Science)}}},
    London, 1965, pages 138--186. North-Holland, Amsterdam, 1967.
- Adrián Portillo Fernández,\\
  "Canonical quotients in model theory".\\
  {{{arXiv(2412.14862)}}}, PhD thesis, 120 pages
- Gabriel Goldberg,\\
  "Reinhardt cardinals in inner models".\\
  {{{arXiv(2107.13119)}}}, 4 pages.
- Joel David Hamkins,\\
  "The set-theoretic multiverse".\\
  {{{arXiv(1108.4223)}}}, 35 pages.
- Joel David Hamkins, Theodor Nenu,\\
  "Did Turing prove the undecidability of the halting problem?".\\
  {{{arXiv(2407.00680)}}}, 18 pages.
  - See also Salvador Lucas, "The origins of the halting problem"
    /J. of Log. and Alg. Methods in Program./ *121* (2021)
    {{{doi(10.1016/j.jlamp.2021.100687)}}}
- Daniil Kozhemiachenko,\\
  "Generalisation of proof simulation procedures for Frege systems by M.L.~Bonet and S.R.~Buss".\\
  {{{arXiv(2403.09119)}}}, 21 pages
  - Discusses ideas related to "proof simulation" from one proof
    calculus within another
- Hunter Monroe,\\
  "Average-Case Hardness of Proving Tautologies and Theorems".\\
  {{{arXiv(2205.07803)}}}, 15 pages.
- Hoang Kim Nguyen, Taichi Uemura,\\
  "∞-type theories".\\
  {{{arXiv(2205.00798)}}}, 55 pages
- J. Julian Pulgarín, Andrés F. Uribe-Zapata,\\
  "Which came first, set theory or logic?".\\
  {{{arXiv(2311.11032)}}}, 16 pages.
  - Works through bootstrapping a finitist metatheory for defining
    first-order logic, and thereby ZFC axioms.
- David Pym, Eike Ritter, Edmund Robinson,\\
  "Categorical Proof-Theoretic Semantics".\\
  {{{arXiv(2302.09031)}}}, 25 pages
  - Seems to describe proof-theoretic semantics using topoi via presheaves.
- Alec Rhea,\\
  "An axiomatic approach to higher order set theory".\\
  {{{arXiv(2206.10060)}}}, 14 pages.
  - This is basically an explicit way to show that Tarski--Grothendieck
    set theory formalizes the intuition of "Coll++ being the collection
    of all Coll".
- Egbert Rijke,\\
  "Introduction to Homotopy Type Theory".\\
  {{{arXiv(2212.11082)}}}, 359 pages
- Yasha Savelyev,\\
  "Incompleteness theorems via Turing category".\\
  {{{arXiv(2412.14084)}}}, 21 pages
  - See also Hofstra and Cockett's [[https://www.di.ens.fr/users/longo/files/Cockett-TuringCateg.pdf][Introduction to Turing categories]]
    for more about Turing categories and the discussion in the [[https://golem.ph.utexas.edu/category/2019/08/turing_categories.html][nCafe]]
- Saharon Shelah,\\
  "Logical Dreams".\\
  {{{arXiv(math/0211398)}}}, 34 pages
- S. Swierczkowski,\\
  "Finite sets and Gödel's incompleteness theorems".\\
  /Dissertationes Mathematicae/ *422* (2003), pp.1-58
  [[https://www.impan.pl/en/publishing-house/journals-and-series/dissertationes-mathematicae/all/422//88124/finite-sets-and-godel-s-incompleteness-theorems][Eprint]]
- Claudio Ternullo,\\
  "Higher-Order Platonism and Multiversism".\\
  {{{arXiv(2310.05852)}}}, 24 pages
- Jouko Väänänen,\\
  "Sort logic and foundations of mathematics".\\
  {{{arXiv(2302.05947)}}}, 14 pages.

*** Model Theory
:PROPERTIES:
:CUSTOM_ID: h-b06df2e0-7304-4551-b98d-07aac80ab9fc
:END:

- Adrián Portillo Fernández,
  "Canonical quotients in model theory".\\
  {{{arXiv(2412.14862)}}}, PhD thesis, 120 pages

** Math.MG Metric Geometry
:PROPERTIES:
:CUSTOM_ID: h-61e9a3d9-2633-4f33-8a6a-a3aa1fdd365c
:END:

- Laith Rastanawi, Günter Rote,\\
  "Towards a Geometric Understanding of the 4-Dimensional Point Groups".\\
  {{{arXiv(2205.04965)}}}, 109 pages.
** Math.MP Mathematical Physics
:PROPERTIES:
:CUSTOM_ID: h-e1914301-bc40-4737-abbb-7eb782a529eb
:END:
- Luis J. Boya,\\
  "Introduction to Sporadic Groups".\\
  {{{arXiv(1101.3055)}}}, 18 pages
** Math.NA Numerical Analysis
:PROPERTIES:
:CUSTOM_ID: h-ac731c25-c32a-4b24-8f8e-fd09a0edb2d4
:END:
- M. Antoñana, E. Alberdi, J.Makazaga, A. Murua,\\
  "An implicit symplectic solver for high-precision long term integrations of the Solar System".\\
  {{{arXiv(2204.01539)}}}, 26 pages
- David Berghaus, Hartmut Monien, Danylo Radchenko,\\
  "On the computation of modular forms on noncongruence subgroups".\\
  {{{arXiv(2207.13365)}}}, 30 pages.
  - Nice use of mixed precision arithmetic in computational number theory, in this case using machine precision preconditioning to speed up arbitrary precision solving by orders of magnitude.
- Fedor Bukreev, Stephan Simonis, Adrian Kummerländer, Julius Jeßberger,
  Mathias J. Krause,\\
  "Consistent lattice Boltzmann methods for the volume averaged Navier-Stokes equations".\\
  {{{arXiv(2208.09267)}}}, 22 pages.
- Jérôme Droniou, Todd A. Oliynyk, Jia Jia Qian,\\
  "A polyhedral discrete de Rham numerical scheme for the Yang-Mills equations".\\
  {{{arXiv(2208.12009)}}}, 24 pages.
- João Guilherme Caldas Steinstraesser, Pedro da Silva Peixoto, Martin Schreiber,\\
  "A second-order semi-Lagrangian exponential scheme with application to the shallow-water equations on the rotating sphere".\\
  {{{arXiv(2405.02237)}}}, 35 pages
- Tomoya Kemmochi,\\
  "Lp-resolvent estimate for finite element approximation of the Stokes operator".\\
  {{{arXiv(2208.11892)}}}, 21 pages
- Manuel Liebchen, Utku Kaya, Christian Lessig, Thomas Richter,\\
  "An adaptive finite element multigrid solver using GPU acceleration".\\
  {{{arXiv(2405.05047)}}}, 25 pages
- A. Melman,\\
  "Root finding techniques that work".\\
  {{{arXiv(2204.02326)}}}, 15 pages

*** Numerical Linear Algebra
:PROPERTIES:
:CUSTOM_ID: h-0bb6ff47-c9d5-41dd-85f0-b08d1fbacf86
:END:

- Anil Damle, Silke Glas, Alex Townsend, Annan Yu,\\
  "How to reveal the rank of a matrix?".\\
  {{{arXiv(2405.04330)}}}, 35 pages.
- James Demmel, Ioana Dumitriu, Olga Holtz,\\
  "Fast linear algebra is stable".\\
  {{{arXiv(math/0612264)}}}, 26 pages
- Jun Lu,\\
  "Numerical Matrix Decomposition".\\
  {{{arXiv(2107.02579)}}}, 646 pages
- Michael W. Mahoney,\\
  "Lecture Notes on Randomized Linear Algebra".\\
  {{{arXiv(1608.04481)}}}, 188 pages.
- Riley Murray, James Demmel, Michael W. Mahoney, N. Benjamin Erichson, Maksim Melnichenko, Osman Asif Malik, Laura Grigori, Piotr Luszczek, Michał Dereziński, Miles E. Lopes, Tianyu Liang, Hengrui Luo, Jack Dongarra,\\
  "Randomized Numerical Linear Algebra : A Perspective on the Field With an Eye to Software".\\
  {{{arXiv(2302.11474)}}}, 202 pages.

** Math.NT Number Theory
:PROPERTIES:
:CUSTOM_ID: h-8b819207-58a1-476c-b108-cafb437af04b
:END:
- Samuel DeHority, Xavier Gonzalez, Neekon Vafa, Roger Van Peski,\\
  "Moonshine for All Finite Groups".\\
  {{{arXiv(1707.05249)}}}, 34 pages
** Math.QA Quantum Algebra
:PROPERTIES:
:CUSTOM_ID: h-fdf4a178-51f0-48ce-88aa-3c71749dbebf
:END:

- Scott Carnahan, Hayate Kobayashi,\\
  "Automorphism group schemes of lattice vertex operator algebras".\\
  {{{arXiv(2502.06121)}}}, 20 pages.
  - Contains an excellent review of lattice vertex operator algebras,
    and citations to the literature.
- R. W. Gebert,\\
  "Introduction to Vertex Algebras, Borcherds Algebras, and the Monster Lie Algebra".\\
  {{{arXiv(hep-th/9308151)}}}, 55 pages.
- Bin Gui,\\
  "Lectures on Vertex Operator Algebras and Conformal Blocks".\\
  {{{arXiv(2305.03822)}}}, 181 pages.
- Yi-Zhi Huang,\\
  "Conformal-field-theoretic analogues of codes and lattices".\\
  {{{arXiv(math/0104150)}}}, 23 pages.
- Yi-Zhi Huang, James Lepowsky,\\
  "Vertex operator algebras and operads".\\
  {{{arXiv(hep-th/9301009)}}}, 16 pages.
- Chongying Dong,\\
  "Introduction to vertex operator algebras I".\\
  {{{arXiv(q-alg/9504017)}}}, 26 pages
- Haisheng Li,\\
  "Introduction to vertex operator algebras II".\\
  {{{arXiv(q-alg/9504018)}}}, 27 pages
- Yi-Zhi Huang,\\
  "Introduction to vertex operator algebras III".\\
  {{{arXiv(q-alg/9504019)}}}, 28 pages
- James Lepowsky,\\
  "Vertex operator algebras and the zeta function".\\
  {{{arXiv(math/9909178)}}}, 21 pages.
- Andrew Schopieray,\\
  "Categorification of integral group rings extended by one dimension".\\
  {{{arXiv(2208.07319)}}}, 25 pages.

** Math.RA Rings and Algebras
:PROPERTIES:
:CUSTOM_ID: h-fdda27db-b4c5-4f8d-89e1-aee0139e1c7e
:END:
- L. Caston, R. Fioresi,\\
  "Mathematical Foundations of Supersymmetry".\\
  {{{arXiv(0710.5742)}}}, 122 pages.
- Apurba Das, Abdenacer Makhlouf,\\
  "Embedding tensors on Hom-Lie algebras".\\
  {{{arXiv(2304.04178)}}}, 25 pages.
- Cristina Draper,\\
  "Notes on G2: The Lie algebra and the Lie group".\\
  {{{arXiv(1704.07819)}}}, 50 pages.
- Artem Lopatin, Alexandr N. Zubkov,\\
  "Separating G_2-invariants of several octonions".\\
  {{{arXiv(2209.12620)}}}, 21 pages.
  + In \sect2, there's a fascinating construction of the Octonions.
- Justin McInroy, Sergey Shpectorov,\\
  "Axial algebras of Jordan and Monster type".\\
  {{{arXiv(2209.08043)}}}, 39 pages.
- Toshikazu Miyashita,\\
  "On realizations of the complex Lie groups $(E_{6,R})^{C}$, $(E_{6,C})^{C}$, $(E_{6,H})^{C}$, and those real forms".\\
  {{{arXiv(2508.02716)}}}, 36 pages
- Laura P. Schaposnik, Sebastian Schulz,\\
  "Triality for Homogeneous Polynomials".\\
  {{{arXiv(2009.13573)}}}, 14 pages.
  + Also note: it discusses the Higgs bundle, which is interesting.
    NJ Hitchin's "The self-duality equations on a Riemann surface"
    first introduced the notion.

** Math.RT Representation Theory
:PROPERTIES:
:CUSTOM_ID: h-b4106499-8cbd-44aa-87aa-940ff1bfb2e5
:END:

- Enrique Arrondo,\\
  "Representation theory of finite groups through (basic) algebraic geometry".\\
  {{{arXiv(2009.02774)}}}, 32 pages.
- John C. Baez,\\
  "Young Diagrams and Classical Groups".\\
  {{{arXiv(2302.07971)}}}, 19 pages.
- John C. Baez, Joe Moeller, Todd Trimble,\\
  "Schur Functors and Categorified Plethysm".\\
  {{{arXiv(2106.00190)}}}, 53 pages.
  - See also: https://golem.ph.utexas.edu/category/2023/10/the_free_2rig_on_one_object.html#more
- Dan Barbasch, Kayue Daniel Wong,\\
  "Dirac Series for complex E8".\\
  {{{arXiv(2305.03254)}}}, 24 pages.
- Anthony Britto,\\
  "A Mathematical Construction of an E6 Grand Unified Theory".\\
  [[https://arxiv.org/abs/2102.13465][arXiv:2102.13465]], 81 pages, master's thesis.
- Olivier Brunat, Frank Lübeck,\\
  "On defining characteristic representations of finite reductive groups".\\
  {{{arXiv(1211.3692)}}}, 22 pages
  + Gives parameterizations of the irreducible representations of finite
    groups of Lie type in their defining characteristic.
- Lisa Carbone, Elizabeth Jurisich, Scott H. Murray,\\
  "A Lie group analog for the Monster Lie algebra".\\
  {{{arXiv(2311.11078)}}}, 38 pages.
- Scott Carnahan,\\
  "Why do the symmetries of the monster vertex algebra form a finite simple group?".\\
  {{{arXiv(2206.15391)}}}, 22 pages.
- Alexandru Chirvasitu,\\
  "Lie-algebra centers via de-categorification".\\
  {{{arXiv(2207.11338)}}}, 20 pages
- Yi-Hao Ding, Chao-Ping Dong,\\
  "Dirac Series of $E_{7(-25)}$".\\
  {{{arXiv(2204.07902)}}}, 23 pages.
- Yihao Ding, Hongfeng Zhang,\\
  "Dirac series of GL(n,ℍ)".\\
  {{{arXiv(2208.09903)}}}, 31 pages.
- Christopher M. Drupieski, Jonathan R. Kujawa,\\
  "The Lie superalgebra of transpositions".\\
  {{{arXiv(2310.01555)}}}, 30 pages.
- George Egorov,\\
  "How to superize 𝔤𝔩(∞)".\\
  {{{arXiv(2205.07046)}}}, 15 pages.
- Matthew Fayers, Lucia Morotti,\\
  "Irreducible spin representations of symmetric and alternating groups which remain irreducible in characteristic 3".\\
  {{{arXiv(2208.05207)}}}, 28 pages.
- Maria Gorelik, Vladimir Hinich, Vera Serganova,\\
  "Root groupoid and related Lie superalgebras".\\
  {{{arXiv(2209.06253)}}}, 58 pages
  + Suggests replacing Weyl group with "root groupoid" for Lie superalgebras.
- Jonas Hetz,\\
  "On the generalised Springer correspondence for groups of type E8".\\
  {{{arXiv(2207.06382)}}}, 28 pages.
- Jonas Hetz,\\
  "The values of unipotent characters at unipotent elements for groups of type E8".\\
  {{{arXiv(2309.09915)}}}, 33 pages.
- Christian Liedtke,\\
  "A McKay Correspondence in Positive Characteristic".\\
  {{{arXiv(2207.06286)}}}, 43 pages.
- Craig McRae,\\
  "Exploring Triality Explicitly: Convenient bases for SO(8), Spin(1,7), and G2".\\
  {{{arXiv(2502.14016)}}}, 15 pages
- Youssef Mousaaid,\\
  "Trivalent Categories for Adjoint Representations of Exceptional Lie Algebras".\\
  {{{arXiv(2204.13642)}}}, 25 pages.
- Anupam Singh,\\
  "Representation Theory of Finite Groups".\\
  {{{arXiv(1001.0462)}}}, 57 pages.
- Michel Rausch de Traubenberg, M J Slupinski,\\
  "Commutation relations of 𝔤_2 and the incidence geometry of the Fano plane".\\
  {{{arXiv(2207.13946)}}}, 38 pages.
- Steven V Sam, Andrew Snowden, Philip Tosteson,\\
  "Polynomial representations of the Witt Lie algebra".\\
  {{{arXiv(2210.00399)}}}, 25 pages.
- Benjamin Sambale,\\
  "Fusion systems in representation theory".\\
  {{{arXiv(2302.09016)}}}, 17 pages.
- Jack Saunders,\\
  "Cohomology and Ext for rank one finite groups of Lie type in cross characteristic".\\
  {{{arXiv(2208.11937)}}}, 19 pages.
- Houssein El Turkey, Jonathan R. Kujawa,\\
  "Presenting Schur superalgebras".\\
  {{{arXiv(1209.6327)}}}, 28 pages
- Jim Humphreys, [[https://mathoverflow.net/q/136880/22457][Definition of "finite group of Lie type"?]]

* Physics
:PROPERTIES:
:CUSTOM_ID: h-fa5b64f4-e7d5-4046-8fda-63f54dd93864
:END:

- Susan Fowler's [[https://www.susanjfowler.com/blog/2016/8/13/so-you-want-to-learn-physics][So You Want To Learn Physics...]], an annotated bibliography

** Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-d8af8a2e-ffde-4e10-a897-18a54a28bdb1
:END:

- Aymeric Spiga, Sandrine Guerlet, Ehouarn Millour, Mikel Indurain, Yann Meurdesoif, Simon Cabanes, Thomas Dubos, Jérémy Leconte, Alexandre Boissinot, Sébastien Lebonnois, Mélody Sylvestre, Thierry Fouchet,\\
  "Global climate modeling of Saturn's atmosphere. Part II: multi-annual
  high-resolution dynamical simulations".\\
  [[https://arxiv.org/abs/1811.01250][arXiv:1811.01250]], 68 pages.
- Sandrine Guerlet, Aymeric Spiga, Thierry Fouchet, Hugues Delattre,\\
  "Radiative-equilibrium model of Jupiter's atmosphere and application to estimating stratospheric circulations"\\
  [[https://arxiv.org/abs/1907.04556][arXiv:1907.04556]], 72 pages, for a 1-dimensional seasonal radiative model.

** Atmospheric and Oceanic Physics
:PROPERTIES:
:CUSTOM_ID: h-a055c4a4-e9b7-4ef0-9af8-accad7acdbc4
:END:

- V. Balaji, Fleur Couvreux, Julie Deshayes, Jacques Gautrais, Frédéric Hourdin, Catherine Rio,\\
  "Are GCMs Obsolete?".\\
  {{{arXiv(2204.06957)}}}, 9 pages + 93 citations
- Redouane Lguensat, Julie Deshayes, Homer Durand, V. Balaji,\\
  "Semi-automatic tuning of coupled climate models with multiple intrinsic timescales: lessons learned from the Lorenz96 model".\\
  {{{arXiv(2208.06243)}}}, 30 pages.
- Francois Louchet, Jerome Faillettaz,\\
  "Should we trust climate change predictions?"\\
  {{{arXiv(2204.11619)}}}, 5 pages
  + The authors seem confused and muddled, their argument self-defeating.
- Valerio Lucarini, Mickaël Chekroun,\\
  "Hasselmann's Program and Beyond: New Theoretical Tools for Understanding the Climate Crisis".\\
  {{{arXiv(2303.12009)}}}, 16 pages.

** Earth and Planetary Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-0694a5d9-fe8d-4af2-a571-9622720e3a21
:END:

- Tao Cai, Kwing L. Chan, Hans G. Mayr, \\
  "Deep, Closely-Packed, Long-Lived Cyclones on Jupiter's Poles".\\
  [[https://arxiv.org/abs/2103.08824][arXiv:2103.08824]], 33 pages
- Russell Deitrick, João M. Mendonça, Urs Schroffenegger, Simon L. Grimm, Shang-Min Tsai, Kevin Heng,\\
  "THOR 2.0: Major Improvements to the Open-Source General Circulation Model".\\
  [[https://arxiv.org/abs/1911.13158][arXiv:1911.13158]], 57 pages
- Soumya Sengupta,\\
  "Atmospheric Thermal Emission Effect on Chandrasekhar's Finite Atmosphere Problem".\\
  {{{arXiv(2208.06656)}}}, 12 pages.

** Fluids
:PROPERTIES:
:CUSTOM_ID: h-641b95a3-9114-4784-aca0-4e755aca9ca6
:END:

- Alexander T Bradley, C. Rosie Williams, Adrian Jenkins, Robert Arthern,\\
  "Asymptotic Analysis of Subglacial Plumes in Stratified Environments".\\
  [[https://arxiv.org/abs/2103.09003][arXiv:2103.09003]], 33 pages
- Gui-Qiang G. Chen, Yucong Huang, Shengguo Zhu,\\
  "Global Spherically Symmetric Solutions of the Multidimensional Full Compressible Navier-Stokes Equations with Large Data".\\
  {{{arXiv(2208.05094)}}}, 85 pages
- C. Cottin-Bizonne, B. Cross, A. Steinberger, and E. Charlaix,\\
  "Boundary Slip on Smooth Hydrophobic Surfaces: Intrinsic Effects and Possible Artifacts".\\
  /Phys. Rev. Lett./ *94*, 056102 – Published 10 February 2005
  https://doi.org/10.1103/PhysRevLett.94.056102
- Eduard Feireisl, Young Sam Kwon,\\
  "Taylor-Couette flow with temperature fluctuations: Time periodic solutions".\\
  {{{arXiv(2208.04543)}}}, 24 pages.
- Mamdouh S. Mohamed, Anil N. Hirani, Ravi Samtaney,\\
  "Discrete exterior calculus discretization of incompressible
  Navier-Stokes equations over surface simplicial meshes".\\
  [[https://arxiv.org/abs/1508.01166][arXiv:1508.01166]], 35 pages
- F.S. Pereira, F.F. Grinstein, D.M. Israel, L. Eca, \\
  "Verification and Validation: the Path to Predictive Scale-Resolving Simulations of Turbulence".\\
  [[https://arxiv.org/abs/2103.09899][arXiv:2103.09899]], 30 pages.
- K.R. Sreenivasan, V. Yakhot,\\
  "Dynamics of three-dimensional turbulence from Navier-Stokes equations".\\
  {{{arXiv(2106.01293)}}}, 17 pages.

** GR-QC General Relativity and Quantum Cosmology
:PROPERTIES:
:CUSTOM_ID: h-c21a4f00-2a6d-48a7-9a6a-f30ce1805d78
:END:
- H. Andréka, J. X. Madarász, I. Németi, G. Székely,\\
  "What are the numbers in which spacetime?".\\
  {{{arXiv(1204.1350)}}}, 28 pages
- Edwin Beggs and Shahn Majid,\\
  "General relativistic quantum mechanics".\\
  {{{arXiv(2412.07757)}}}, 44 pages
  - Discusses quantum mechanics on curved spacetime, points out that the
    differential structure of the manifold has "hidden non-associativity
    for product of 1-forms at order of $\hbar^{2}$", which is quite interesting
- Martin Bojowald, Erick I. Duque, Aiden Shah,\\
  "Hypersurface deformations".\\
  {{{arXiv(2410.18807)}}}, 45 pages
- Robert Brandenberger, Paola C. M. Delgado, Alexander Ganz, Chunshan Lin,\\
  "Graviton to Photon Conversion via Parametric Resonance".\\
  {{{arXiv(2205.08767)}}}, 7 pages.
- Alireza Faraji, Zahra Molaee, Ahmad Shirzad,\\
  "Generators of Local Lorentz Transformation in ADM-Vielbein Formalism of Gravitational Relativity".\\
  {{{arXiv(2412.00128)}}}, 19 pages.
- Steffen Gielen,\\
  "Hilbert space formalisms for group field theory".\\
  {{{arXiv(2412.07847)}}}, 20 pages.
  - Oriented towards quantum gravity phenomonology
- Henrique Gomes, Tim Koslowski,\\
  "Symmetry Doubling: Doubly General Relativity".\\
  {{{arXiv(1206.4823)}}}, 24 pages.
  - "Doubly General Relativity" in one line: There is a hidden
    BRST-invariance in gravity due to Shape Dynamics
- Jie Jiang, Deog Ki Hong, Dong-han Yeom,\\
  "Numerical Study of Wheeler-Dewitt Equation beyond Slow-roll approximation".\\
  {{{arXiv(2503.21339)}}}, 11 pages
- Valerio De Luca, Justin Khoury, Sam S. C. Wong,\\
  "Gravitational memory and Ward identities in the local detector frame".\\
  {{{arXiv(2412.12273)}}}, 40 pages
- Luca Marchetti, Edward Wilson-Ewing,\\
  "Relational Observables in Group Field Theory".\\
  {{{arXiv(2412.14622)}}}, 34 pages.
- Flavio Mercati,\\
  "A Shape Dynamics Tutorial".\\
  {{{arXiv(1409.0105)}}}, 133 pages.
- Aristotelis Panagiotopoulos, George Sparling, Marios Christodoulou,\\
  "Incompleteness Theorems for Observables in General Relativity".\\
  {{{arXiv(2305.04818)}}}, 5 pages.
  - Traces the problem of observables back to locality. Uses descriptive
    set theory.

*** Experimentally Testing "Torsion-Free" condition
:PROPERTIES:
:CUSTOM_ID: h-5312d755-c7ac-4855-90fa-c23d3458dc20
:END:

Supergravity requires using a connection form with torsion (I learned
this from James Isenberg, David Bao & Philip B. Yasskin "Classical Supergravity"
contribution to /Mathematical Aspects of Superspace/, page 176).
This led me to wonder if we ever devised some experimental test
measuring the degree of..."torsion-ness" of spacetime.

- Sean M. Carroll, George B. Field,\\
  "Consequences of Propagating Torsion in Connection-Dynamic Theories of Gravity".\\
  {{{arXiv(gr-qc/9403058)}}}, 16 pages
  - Torsion must fall off quickly as we move away from the source of
    the gravitational field.
- Eanna E. Flanagan, Eran Rosenthal,\\
  "Can Gravity Probe B usefully constrain torsion gravity theories?".\\
  {{{arXiv(0704.1447)}}}, 13 pages
  - See also Mao's PhD thesis https://arxiv.org/abs/0808.2063
- Riccardo March, Giovanni Bellettini, Roberto Tauraso, Simone Dell'Agnello,\\
  "Constraining spacetime torsion with the Moon and Mercury".\\
  {{{arXiv(1101.2789)}}}, 33 pages


** HEP-TH High Energy Theory
:PROPERTIES:
:CUSTOM_ID: h-3b3061e0-e6b9-47a3-93fb-0bd0fbd86222
:END:

- Goncalo Araujo-Regado, Philipp A. Hoehn, Francesco Sartini, Bilyana Tomova,\\
  "Soft edges: the many links between soft and edge modes".\\
  {{{arXiv(2412.14548)}}}, 69 pages
- Thomas Bartsch, Mathew Bullimore, Andrea Grigoletto,\\
  "Higher representations for extended operators".\\
  {{{arXiv(2304.03789)}}}, 60 pages
- Diego Buccio, Roberto Percacci,\\
  "Renormalization Group flows between Gaussian Fixed Points".\\
  {{{arXiv(2207.10596)}}}, 18 pages.
- A. Connes,\\
  "Gravity coupled with matter and foundation of non-commutative geometry".\\
  {{{arXiv(hep-th/9603053)}}}, 30 pages.
- Marc Gillioz,\\
  "Conformal field theory for particle physicists".\\
  {{{arXiv(2207.09474)}}}, 69 pages
- Anamaria Hell,\\
  "The strong couplings of massive Yang-Mills theory".\\
  {{{arXiv(2111.00017)}}}, 23 pages.
  - Argues massive Yang-Mills nonrenormalizability originates from
    longitudinal modes.
- A. Kempf,\\
  "A Generalized Shannon Sampling Theorem, Fields at the Planck Scale as Bandlimited Signals".\\
  {{{arXiv(hep-th/9905114)}}}
- Kirill Krasnov, \\
  "SO(9) characterisation of the Standard Model gauge group". \\
  [[https://arxiv.org/abs/1912.11282][arXiv:1912.11282]], 19 pages
- Petr Kravchuk, Jiaxin Qiao, Slava Rychkov,\\
  "Distributions in CFT II. Minkowski Space".\\
  {{{arXiv(2104.02090)}}}, 88+18 pages.
- Aleksandar Mikovic, Marko Vojinovic, \\
  "Standard Model and 4-groups". \\
  [[https://arxiv.org/abs/2008.06354][arXiv:2008.06354]], 6 pages.
- José M. Figueroa-O'Farrill,\\
  "Higher-dimensional kinematical Lie algebras via deformation theory".\\
  {{{arXiv(1711.07363)}}}, 18 pages
- Álvaro Pastor-Gutiérrez, Jan M. Pawlowski, Manuel Reichert,\\
  "The Asymptotically Safe Standard Model: From quantum gravity to dynamical chiral symmetry breaking".\\
  {{{arXiv(2207.09817)}}}, 38 pages.
- Robert A. Wilson,\\
  "Chirality in an E8 model of elementary particles".\\
  {{{arXiv(2210.06029)}}}, 21 pages.
  + Sequel to "Octions: An E8 description of the Standard Model"
    {{{arXiv(2204.05310)}}}, 15 pages.
- Edward Witten,\\
  "Light Rays, Singularities, and All That".\\
  {{{arXiv(1901.03928)}}}, 104 pages.
  - [[https://www.youtube.com/playlist?list=PLwWlDvl8lCT4ntvF7TKWMyBfxtVGWDuVQ][Lectures]] on YouTube
- Peter Woit,\\
  "Spacetime is Right-handed".\\
  {{{arXiv(2311.00608)}}}, 11 pages
- Yong Zhang,\\
  "On the New Factorizations of Yang-Mills Amplitudes".\\
  {{{arXiv(2412.15198)}}}, 37 + 17 pages


** HEP-PH High Energy Physics Phenomenology
:PROPERTIES:
:CUSTOM_ID: h-3e299f15-1852-449d-b5ea-d108990f3eb9
:END:

- John Collins,\\
  "A new approach to the LSZ reduction formula".\\
  {{{arXiv(1904.10923)}}}, 42 pages.
** MATH-PH Mathematical Physics
:PROPERTIES:
:CUSTOM_ID: h-6231092f-ce4a-46a0-989b-56b0da7277f7
:END:

- Cecilia Flori,\\
  "Review of the Topos Approach to Quantum Theory".\\
  {{{arXiv(1106.5660)}}}, 24 pages.
  - Reviews Doering and Isham's approach to quantum theory using
    toposes, which was introduced in a series of papers:
    {{{arXiv(quant-ph/0703060)}}}, {{{arXiv(quant-ph/0703062)}}},
    {{{arXiv(quant-ph/0703064)}}}, {{{arXiv(quant-ph/0703066)}}},
  - Kochen-Specker theorem in this framework:
    {{{arXiv(quant-ph/9803055)}}}, {{{arXiv(quant-ph/9808067)}}},
    {{{arXiv(quant-ph/9911020)}}}, {{{arXiv(quant-ph/0107123)}}}
- Mo Huang,\\
  "Finite 2-group gauge theory and its 3+1D lattice realization".\\
  {{{arXiv(2508.04693)}}}, 41 pages
- Jean Petitot,\\
  "Noncommutative geometry and physics".\\
  {{{arXiv(1505.00132)}}}, 38 pages.
- Bert Schroer,\\
  "Causality and dispersion relations and the role of the S-matrix in the ongoing research".\\
  {{{arXiv(1102.0168)}}}, 47 pages.

  
** QUANT-PH Quantum Physics
:PROPERTIES:
:CUSTOM_ID: h-8c0a726f-98b8-472e-84eb-39f444d68a5b
:END:

- Brian C. Hall,\\
  "Holomorphic Methods in Mathematical Physics".\\
  {{{arXiv(quant-ph/9912054)}}}, 59 pages.
- Gerard 't Hooft,\\
  "The Cellular Automaton Interpretation of Quantum Mechanics".\\
  {{{arXiv(1405.1548)}}}, 259 pages.
- Daniela Frauchiger, Renato Renner,\\
  "Quantum theory cannot consistently describe the use of itself".\\
  {{{arXiv(1604.07422)}}}, 19 pages
  - See also: Alexandru Baltag, Sonja Smets,\\
    "Logic meets Wigner's Friend (and their Friends)".\\
    {{{arXiv(2307.01713)}}}, 27 pages.
- Igor Frolov, Albert Schwarz,\\
  "Quantum mechanics and quantum field theory. Algebraic and geometric approaches".\\
  {{{arXiv(2301.03804)}}}, 100 pages.
- Ahmed Shalabi, Matheus H. Zambianco, T. Rick Perche,\\
  "The effect of curvature on local observables in quantum field theory".\\
  {{{arXiv(2412.12294)}}}, 8+3 pages
- Augusto Facundes da Silva, Kayman Jhosef Goncalves, Giorgio Torrieri,\\
  "The quantum Newton's bucket: Active and passive rotations in quantum theory".\\
  {{{arXiv(2502.21298)}}}, 20 pages
- S. A. Torres,\\
  "Einstein's Equivalence Principle in Nonrelativistic Quantum Mechanics".\\
  {{{arXiv(2502.20416)}}}, 14 pages

