#+TITLE: Bookmarks
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-01-15T14:26:11-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5 num:nil
#+HTML_DOCTYPE: html5
#+INCLUDE: org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ./index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
# Created Friday January 15, 2021 at  2:26PM

#+begin_quote
Where must we go... \\
we who wander this Wasteland \\
in search of our better selves? \\
--- /The First History of Man/
#+end_quote

* Blogs
:PROPERTIES:
:CUSTOM_ID: h-0643e128-8ed0-4882-a621-e5117128d5a8
:END:

- [[https://robwilson1.wordpress.com/][Robert A Wilson's blog]], the group theorist who wrote the book
  {{{book-title(The Finite Simple Groups)}}}.
- [[https://fredrikj.net/blog/][Fredrik Johansson's blog]], interesting symbolic computation blog
- [[https://bernsteinbear.com/][Max Bernstein's blog]] for more on programming language theory
- [[https://www.easterbrook.ca/steve/][Steve Easterbrooks blog]] discusses climate models
- [[https://nhigham.com/blog/][Nick Higham's blog]] on numerical linear algebra, and related topics
- [[https://mathproblems123.wordpress.com/category/numerical-analysis/][Beni Bogosel's blog]] on numerical analysis
- [[https://lawrencecpaulson.github.io/][Lawrence Paulson's blog]] on theorem provers

* Programming and Computers
:PROPERTIES:
:CUSTOM_ID: h-2dd9593d-2bf8-4a41-8295-15b4c234c7cf
:END:

- Scott Walck,\\
  "Learn Physics by Programming in Haskell".\\
  [[https://arxiv.org/abs/1412.4880][arXiv:1412.4880]], 11 pages

** CS.LO Logic in Computer Science
:PROPERTIES:
:CUSTOM_ID: h-616db70f-0194-4a3e-adcb-1d56a7ee9cd7
:END:

- Danil Annenkov, Mikkel Milo, Jakob Botsch Nielsen, Bas Spitters,\\
  "Extracting functional programs from Coq, in Coq".\\
  {{{arXiv(2108.02995)}}}, 57 pages
- Laila El-Beheiry, Giselle Reis, Ammar Karkour,\\
  "SMLtoCoq: Automated Generation of Coq Specifications and Proof Obligations from SML Programs with Contracts".\\
  {{{arXiv(2107.07664)}}}, 17 pages
- Herman Geuvers,\\
  "The Calculus of Constructions and Higher Order Logic".\\
  In /The Curry-Howard isomorphism/ (ed. Ph. de Groote)\\
  [[http://www.cs.ru.nl/~herman/PUBS/CC_CHiso.pdf][Preprint]], discusses inconsistency in extensions of HOL (e.g., HOL +
  (prop = type) is inconsistent).
  - Geuvers actually uses this as grounds for arguing ~prop != type~ in
    general (Automath experiment also shows if ~prop = type~, then the
    law of double negation acts like a Hilbert choice operator, due to
    proof irrelevance being "the same" as type non-emptiness --- another
    reason why ~prop != type~ is a good idea).
- Robert Harper,\\
  "An Equational Logical Framework for Type Theories".\\
  [[https://arxiv.org/abs/2106.01484][arXiv:2106.01484]], 9 pages.
- Patricia Johann, Enrico Ghiorzi, Daniel Jeffries,\\
  "GADTs, Functoriality, Parametricity: Pick Two".\\
  [[https://arxiv.org/abs/2105.03389][arXiv:2105.03389]], 16 pages.
- Mary Southern,\\
  "A Framework for Reasoning About LF Specifications".\\
  PhD Thesis, University of Minnesota, [[https://arxiv.org/abs/2105.04110][arXiv:2105.04110]], 188 pages.
  Also presents a unique variant of Canonical LF in chapter 2.
- Don Syme,\\
  "Reasoning with the Formal Definition of Standard ML in HOL".\\
  In /HUG1993/ pp.43--60 {{{doi(10.1007/3-540-57826-9_124)}}}, [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.35.1838][citeseer]]
- Christian Williams, Michael Stay,\\
  "Native Type Theory".\\
  {{{arXiv(2102.04672)}}}, 12 pages.
  + "We propose a unifying method of reasoning for programming
    languages: model a language as a theory, form the category of
    presheaves, and use the internal language of the topos."
  + "Virtually any language can be modelled as a structured category: the
    most comprehensive reference I’ve found is /Categorical Logic and Type Theory/ by Bart Jacobs."
- Bohua Zhan,\\
  "Formalization of the fundamental group in untyped set theory using auto2".\\
  {{{arXiv(1707.04757)}}}, 17 pages.
  + One of the few formalizations using *both* /untyped/ set theory *and* Isabelle
- Tesla Zhang,\\
  "Type theories in category theory".\\
  {{{arXiv(2107.13242)}}}, 39 pages.


** CS.PL Programming Languages
:PROPERTIES:
:CUSTOM_ID: h-1700895e-0a22-4131-8528-cef6269bcae0
:END:

- Sandra Alves, Miguel Ramos,\\
  "An ML-style record calculus with extensible records".\\
  {{{arXiv(2108.06296)}}}, 35 pages.
- KC Sivaramakrishnan, Stephen Dolan, Leo White, Tom Kelly, Sadiq Jaffer, Anil Madhavapeddy,\\
  "Retrofitting Effect Handlers onto OCaml".\\
  [[https://arxiv.org/abs/2104.00250][arXiv:2104.00250]], 16 pages
- Han Xu, Zhenjiang Hu,\\
  "Analytical Differential Calculus with Integration".\\
  [[https://arxiv.org/abs/2105.02632][arXiv:2105.02632]], 42 pages; discusses differential lambda calculus
  with integrals.
- Arjen Rouvoet,\\
  "Correct by Construction".
  PhD Thesis, [[https://ajrouvoet.github.io/files/thesis.pdf][pdf]], 244 pages

** Symbolic Computation
:PROPERTIES:
:CUSTOM_ID: h-5b88ae4b-23c9-4ba5-a3d2-b56f9105e02c
:END:

- Thomas Fischbacher,\\
  "A novel approach to symbolic algebra".\\
  [[https://arxiv.org/abs/cs/0406002][arXiv:cs/0406002]], 15 pages, discusses an approach using MzScheme.

* Math
:PROPERTIES:
:CUSTOM_ID: h-25791061-4fd7-4f31-9172-1c2505e13dc9
:END:

** Math.AG Algebraic Geometry
:PROPERTIES:
:CUSTOM_ID: h-420b41c1-0679-47b7-abe2-808d4ad68781
:END:

- Aravind Asok, Jean Fasel,\\
  "Vector bundles on algebraic varieties".\\
  {{{arXiv(2111.03107)}}}, 20 pages.
- Ravi Vakil's [[http://math.stanford.edu/~vakil/216blog/][Rising Sea]] lecture notes

** Math.AP Analysis of PDEs
:PROPERTIES:
:CUSTOM_ID: h-0c32530b-a377-482c-aa9c-6381085d035d
:END:

- Thomas Doehrman, David Glickenstein,\\
  "Determinant of the finite volume Laplacian".\\
  {{{arXiv(2108.07308)}}}, 14 pages, discusses determinant of discrete Laplacian.
- Tarek M Elgindi,\\
  "Finite-Time Singularity Formation for $C^{1,\alpha}$ Solutions to the
  Incompressible Euler Equations on R^3".\\
  [[https://arxiv.org/abs/1904.04795][arXiv:1904.04795]], 60 pages; see also follow up paper [[https://arxiv.org/abs/1910.14071][arXiv:1910.14071]].
- Alexander V. Aksenov, Andrei D. Polyanin,\\
  "Construction of complex solutions to nonlinear partial differential equations using simpler solutions".\\
  [[https://arxiv.org/abs/2102.04815][arXiv:2102.04815]], 49 pages
- Lorenzo Brandolese,\\
  "Hexagonal structures in 2D Navier-Stokes flows".\\
  [[https://arxiv.org/abs/2102.00728][arXiv:2102.00728]], 25 pages
- D. Maroncelli, E. Collins,\\
  "Weakly Nonlocal Boundary Value Problems with Application to Geology".\\
  [[https://arxiv.org/abs/2103.09095][arXiv:2103.09095]], 15 pages
- Matthew Rosenzweig,\\
  "On the Rigorous Derivation of the Incompressible Euler Equation from Newton's Second Law".\\
  [[https://arxiv.org/abs/2104.11723][arXiv:2104.11723]], 20 pages.

** Math.CT
:PROPERTIES:
:CUSTOM_ID: h-4f2e35f6-82de-4cb6-b32f-f6f39edd0b30
:END:

- Antoine Allioux, Eric Finster, Matthieu Sozeau,\\
  "Types are Internal ∞-Groupoids".\\
  [[https://arxiv.org/abs/2105.00024][arXiv:2105.00024]], 16 pages.
- Carmen Constantin, Tobias Fritz, Paolo Perrone, Brandon Shapiro,\\
  "Weak cartesian properties of simplicial sets".\\
  [[https://arxiv.org/abs/2105.04775][arXiv:2105.04775]], 48 pages.
- Fabrizio Genovese, Fosco Loregian, \\
  "Differential 2-rigs". \\
  [[https://arxiv.org/abs/2103.00938][arXiv:2103.00938]], 32 pages.
- Matias del Hoyo, Giorgio Trentinaglia,\\
  "Simplicial vector bundles and representations up to homotopy".\\
  {{{arXiv(2109.01062)}}}, 66 pages.
- Giulio Lo Monaco,\\
  "Vopěnka's principle in ∞-categories".\\
  [[https://arxiv.org/abs/2105.04251][arXiv:2105.04251]], 22 pages.
- Ivan Contreras, Molly Keller, Rajan Amit Mehta,\\
  "Frobenius objects in the category of spans".\\
  [[https://arxiv.org/abs/2106.14743][arXiv:2106.14743]], 31 pages
  - Frobenius objects generalize Frobenius algebras, which describe
    TQFTs. Rajan Amit Mehta seems to have discussed them earlier in
    [[https://arxiv.org/abs/1907.00702][arXiv:1907.00702]] crediting their invention to:
    Joachim Kock, {{{book-title(Frobenius algebras and 2D topological quantum field theories)}}}, CUP, 2004.
  - The category *Rel* acts like a "toy symplectic category" without any
    of the difficulties.
- Ivo Dell'Ambrogio,\\
  "Green 2-functors".
  {{{arXiv(2107.09478)}}}, 41 pages.
  - Mackey 2-functors introduced in {{{arXiv(1808.04902)}}} (213 pages,
    "many beautiful figures").
- Yuri Shimizu,\\
  "∞-cosheafification".\\
  [[https://arxiv.org/abs/2106.14135][arXiv:2106.14135]], 11 pages.
- Yasuhiro Wakabayashi,\\
  "On the category of structure species".\\
  {{{arXiv(2201.11273)}}}, 21 pages

** Math.DG Differential Geometry
:PROPERTIES:
:CUSTOM_ID: h-6db90c1a-f521-4efe-9c2a-fc00d37070b3
:END:

- Mathieu Desbrun, Anil N. Hirani, Melvin Leok, Jerrold E. Marsden,\\
  "Discrete Exterior Calculus".\\
  [[https://arxiv.org/abs/math/0508341][arXiv:math/0508341]], 53 pages
- Rui Loja Fernandes, Marius Crainic,\\
  "Lectures on Integrability of Lie Brackets".\\
  {{{arXiv(math/0611259)}}}, 95 pages; see especially \sect3.2 for a proof
  of Lie's third theorem using homotopic equivalence classes of paths.
- Ichiro Yokota,\\
  "Exceptional Lie groups".\\
  {{{arXiv(0902.0431)}}}, 204 pages.

** Math.GR Group Theory
:PROPERTIES:
:CUSTOM_ID: h-5f6e5a83-f5db-4e97-8cde-16ac0f77d9d1
:END:
- Sylvia Bayard, Justin Lynd,\\
  "Realizing Finite Groups as Automizers".\\
  {{{arXiv(2203.14413)}}}, 9 pages
- Martin van Beek,\\
  "Exotic Fusion Systems Related to Sporadic Simple Groups".\\
  {{{arXiv(2201.01790)}}}, 40 pages.
- Yiming Bing, Bright Hu, Ronni Hu, Rhianna Li, Stefan Lu, Finn McDonald, Michael Sun, Nicholas Wolfe, Joshua Yao, Leon Zhou, Nathan Zhou,\\
  "The Mathieu group $M_{23}$ as additive functions on the finite field of size $2^{11}$".\\
  {{{arXiv(2201.00108)}}}, 15 pages.
- Peter J. Cameron,\\
  "Graphs defined on groups".\\
  {{{arXiv(2102.11177)}}}, 81 pages, review paper.
- Jacques Darné, Martin Palmer, Arthur Soulié,\\
  "When the lower central series stops".\\
  {{{arXiv(2201.03542)}}}, 86 pages.
- Misha Gavrilovich,\\
  "Expressing the statement of the Feit-Thompson theorem with diagrams in the category of finite groups".\\
  {{{arXiv(1608.05927)}}}, 8 pages
- Kadeem Harrigan,\\
  "Aschbacher's Theorem for the General Linear Group".\\
  {{{arXiv(2112.02430)}}}, 49 pages; MSc thesis submitted at Imperial College London.
- Nicolas Magaud,\\
  "Spreads and Packings of PG(3,2), Formally!"\\
  {{{arXiv(2201.00541)}}}, 9 pages, discusses Coq formalization.
- Leo Margolis,\\
  "The Modular Isomorphism Problem: a survey".\\
  {{{arXiv(2202.11412)}}}, 31 pages.
- John McKay, Yang-Hui He,\\
  "Kashiwa Lectures on 'New Approaches to the Monster'".\\
  [[https://arxiv.org/abs/2106.01162][arXiv:2106.01162]], 42 pages.
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The BMS Group".\\
  {{{arXiv(2106.12513)}}}, 27 pages.
- David Prinz, Alexander Schmeding,\\
  "Lie Theory for Asymptotic Symmetries in General Relativity: The NU Group".\\
  {{{arXiv(2109.11476)}}}, 38 pages
- Robert A. Wilson,\\
  "Comparison of group-theoretical strategies for unification of 3+1 structures in physics".\\
  {{{arXiv(2108.04675)}}}, 8 pages.
- Robert A. Wilson,\\
  "Possible uses of the binary icosahedral group in grand unified theories".\\
  {{{arXiv(2109.06626)}}}, 28 pages.
- R. A. Wilson,\\
  "Integer versions of Yang-Mills theory".\\
  {{{arXiv(2202.08263)}}}, 13 pages.
- R. A. Wilson, T. Dray, C. A. Manogue,\\
  "An octonionic construction of E8 and the Lie algebra magic square".\\
  {{{arXiv(2204.04996)}}}, 19 pages.

*** Sylow p-Subgroups
:PROPERTIES:
:CUSTOM_ID: h-f2aaf2e4-288a-40f6-9397-53a2875cdc30
:END:

- Timothy C. Burness, Robert M. Guralnick,\\
  "On the generation of simple groups by Sylow subgroups".\\
  {{{arXiv(2204.04311)}}}, 17 pages.
- Gabriel Navarro, Benjamin Sambale,\\
  "Characters, Commutators and Centers of Sylow Subgroups".\\
  {{{arXiv(2204.04407)}}}, 18 pages
- Nomina Ch. Manzaeva, Danila O. Revin, Evgeny P. Vdovin,\\
  "The Hall property Dπ is inherited by overgroups of π-Hall subgroups".\\
  {{{arXiv(1808.03536)}}}, 27 pages
- Ruslan Skuratovskii,\\
  "The commutator and centralizer description of Sylow 2-subgroups of alternating and symmetric groups".\\
  {{{arXiv(1712.01401)}}}, 19 pages.

** Math.LO Logic
:PROPERTIES:
:CUSTOM_ID: h-77765895-8b26-4057-b243-06f594378e59
:END:

- Jeremy Avigad,\\
  "Foundations".\\
  {{{arXiv(2009.09541)}}}, 54 pages
- Walter Dean, Hidenori Kurokawa,\\
  "On the methodology of informal rigour: set theory, semantics, and intuitionism".\\
  [[https://arxiv.org/abs/2104.14887][arXiv:2104.14887]], 83 pages.
  - This is the second paper which references Georg Kreisel's paper on
    ZFC_{2} (ZFC formulated in second-order logic), specifically:\\
    G. Kreisel,\\
    "Informal Rigour and Completeness Proofs".\\
    In I. Lakatos, editor, {{{book-title(Problems in the philosophy of mathematics: Proceedings of the International Colloquium in the Philosophy of Science)}}},
    London, 1965, pages 138--186. North-Holland, Amsterdam, 1967.
- Gabriel Goldberg,\\
  "Reinhardt cardinals in inner models".\\
  {{{arXiv(2107.13119)}}}, 4 pages.
- Saharon Shelah,\\
  "Logical Dreams".\\
  {{{arXiv(math/0211398)}}}, 34 pages
- S. Swierczkowski,\\
  "Finite sets and Gödel's incompleteness theorems".\\
  /Dissertationes Mathematicae/ *422* (2003), pp.1-58
  [[https://www.impan.pl/en/publishing-house/journals-and-series/dissertationes-mathematicae/all/422//88124/finite-sets-and-godel-s-incompleteness-theorems][Eprint]]

** Math.MP Mathematical Physics
:PROPERTIES:
:CUSTOM_ID: h-e1914301-bc40-4737-abbb-7eb782a529eb
:END:
- Luis J. Boya,\\
  "Introduction to Sporadic Groups".\\
  {{{arXiv(1101.3055)}}}, 18 pages
** Math.NA Numerical Analysis
:PROPERTIES:
:CUSTOM_ID: h-ac731c25-c32a-4b24-8f8e-fd09a0edb2d4
:END:
- M. Antoñana, E. Alberdi, J.Makazaga, A. Murua,\\
  "An implicit symplectic solver for high-precision long term integrations of the Solar System".\\
  {{{arXiv(2204.01539)}}}, 26 pages
- A. Melman,\\
  "Root finding techniques that work".\\
  {{{arXiv(2204.02326)}}}, 15 pages
** Math.NT Number Theory
:PROPERTIES:
:CUSTOM_ID: h-8b819207-58a1-476c-b108-cafb437af04b
:END:
- Samuel DeHority, Xavier Gonzalez, Neekon Vafa, Roger Van Peski,\\
  "Moonshine for All Finite Groups".\\
  {{{arXiv(1707.05249)}}}, 34 pages
** Math.QA Quantum Algebra
:PROPERTIES:
:CUSTOM_ID: h-fdf4a178-51f0-48ce-88aa-3c71749dbebf
:END:

- R. W. Gebert,\\
  "Introduction to Vertex Algebras, Borcherds Algebras, and the Monster Lie Algebra".\\
  {{{arXiv(hep-th/9308151)}}}, 55 pages.
- Yi-Zhi Huang,\\
  "Conformal-field-theoretic analogues of codes and lattices".\\
  {{{arXiv(math/0104150)}}}, 23 pages.
- Yi-Zhi Huang, James Lepowsky,\\
  "Vertex operator algebras and operads".\\
  {{{arXiv(hep-th/9301009)}}}, 16 pages.
- Chongying Dong,\\
  "Introduction to vertex operator algebras I".\\
  {{{arXiv(q-alg/9504017)}}}, 26 pages
- Haisheng Li,\\
  "Introduction to vertex operator algebras II".\\
  {{{arXiv(q-alg/9504018)}}}, 27 pages
- Yi-Zhi Huang,\\
  "Introduction to vertex operator algebras III".\\
  {{{arXiv(q-alg/9504019)}}}, 28 pages
- James Lepowsky,\\
  "Vertex operator algebras and the zeta function".\\
  {{{arXiv(math/9909178)}}}, 21 pages.

** Math.RA Rings and Algebras
:PROPERTIES:
:CUSTOM_ID: h-fdda27db-b4c5-4f8d-89e1-aee0139e1c7e
:END:
- L. Caston, R. Fioresi,\\
  "Mathematical Foundations of Supersymmetry".\\
  {{{arXiv(0710.5742)}}}, 122 pages.
- Cristina Draper,\\
  "Notes on G2: The Lie algebra and the Lie group".\\
  {{{arXiv(1704.07819)}}}, 50 pages.

** Math.RT Representation Theory
:PROPERTIES:
:CUSTOM_ID: h-b4106499-8cbd-44aa-87aa-940ff1bfb2e5
:END:

- Enrique Arrondo,\\
  "Representation theory of finite groups through (basic) algebraic geometry".\\
  {{{arXiv(2009.02774)}}}, 32 pages.
- Anthony Britto,\\
  "A Mathematical Construction of an E6 Grand Unified Theory".\\
  [[https://arxiv.org/abs/2102.13465][arXiv:2102.13465]], 81 pages, master's thesis.
- Olivier Brunat, Frank Lübeck,\\
  "On defining characteristic representations of finite reductive groups".\\
  {{{arXiv(1211.3692)}}}, 22 pages
  + Gives parameterizations of the irreducible representations of finite
    groups of Lie type in their defining characteristic.
- Anupam Singh,\\
  "Representation Theory of Finite Groups".\\
  {{{arXiv(1001.0462)}}}, 57 pages.

- Jim Humphreys, [[https://mathoverflow.net/q/136880/22457][Definition of "finite group of Lie type"?]]

* Physics
:PROPERTIES:
:CUSTOM_ID: h-fa5b64f4-e7d5-4046-8fda-63f54dd93864
:END:

- Susan Fowler's [[https://www.susanjfowler.com/blog/2016/8/13/so-you-want-to-learn-physics][So You Want To Learn Physics...]], an annotated bibliography

** Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-d8af8a2e-ffde-4e10-a897-18a54a28bdb1
:END:

- Aymeric Spiga, Sandrine Guerlet, Ehouarn Millour, Mikel Indurain, Yann Meurdesoif, Simon Cabanes, Thomas Dubos, Jérémy Leconte, Alexandre Boissinot, Sébastien Lebonnois, Mélody Sylvestre, Thierry Fouchet,\\
  "Global climate modeling of Saturn's atmosphere. Part II: multi-annual
  high-resolution dynamical simulations".\\
  [[https://arxiv.org/abs/1811.01250][arXiv:1811.01250]], 68 pages.
- Sandrine Guerlet, Aymeric Spiga, Thierry Fouchet, Hugues Delattre,\\
  "Radiative-equilibrium model of Jupiter's atmosphere and application to estimating stratospheric circulations"\\
  [[https://arxiv.org/abs/1907.04556][arXiv:1907.04556]], 72 pages, for a 1-dimensional seasonal radiative model.

** Earth and Planetary Astrophysics
:PROPERTIES:
:CUSTOM_ID: h-0694a5d9-fe8d-4af2-a571-9622720e3a21
:END:

- Tao Cai, Kwing L. Chan, Hans G. Mayr, \\
  "Deep, Closely-Packed, Long-Lived Cyclones on Jupiter's Poles".\\
  [[https://arxiv.org/abs/2103.08824][arXiv:2103.08824]], 33 pages
- Russell Deitrick, João M. Mendonça, Urs Schroffenegger, Simon L. Grimm, Shang-Min Tsai, Kevin Heng,\\
  "THOR 2.0: Major Improvements to the Open-Source General Circulation Model".\\
  [[https://arxiv.org/abs/1911.13158][arXiv:1911.13158]], 57 pages

** Fluids
:PROPERTIES:
:CUSTOM_ID: h-641b95a3-9114-4784-aca0-4e755aca9ca6
:END:

- Alexander T Bradley, C. Rosie Williams, Adrian Jenkins, Robert Arthern,\\
  "Asymptotic Analysis of Subglacial Plumes in Stratified Environments".\\
  [[https://arxiv.org/abs/2103.09003][arXiv:2103.09003]], 33 pages
- Mamdouh S. Mohamed, Anil N. Hirani, Ravi Samtaney,\\
  "Discrete exterior calculus discretization of incompressible
  Navier-Stokes equations over surface simplicial meshes".\\
  [[https://arxiv.org/abs/1508.01166][arXiv:1508.01166]], 35 pages
- F.S. Pereira, F.F. Grinstein, D.M. Israel, L. Eca, \\
  "Verification and Validation: the Path to Predictive Scale-Resolving Simulations of Turbulence".\\
  [[https://arxiv.org/abs/2103.09899][arXiv:2103.09899]], 30 pages.
- K.R. Sreenivasan, V. Yakhot,\\
  "Dynamics of three-dimensional turbulence from Navier-Stokes equations".\\
  {{{arXiv(2106.01293)}}}, 17 pages.

** High Energy Theory
:PROPERTIES:
:CUSTOM_ID: h-3b3061e0-e6b9-47a3-93fb-0bd0fbd86222
:END:

- Kirill Krasnov, \\
  "SO(9) characterisation of the Standard Model gauge group". \\
  [[https://arxiv.org/abs/1912.11282][arXiv:1912.11282]], 19 pages
- Petr Kravchuk, Jiaxin Qiao, Slava Rychkov,\\
  "Distributions in CFT II. Minkowski Space".\\
  {{{arXiv(2104.02090)}}}, 88+18 pages.
- Aleksandar Mikovic, Marko Vojinovic, \\
  "Standard Model and 4-groups". \\
  [[https://arxiv.org/abs/2008.06354][arXiv:2008.06354]], 6 pages.
