#+TITLE: Computation and Science
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-05T10:42:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5 toc:nil num:nil
#+HTML_DOCTYPE: html5
#+INCLUDE: ./org-macros.org
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./css/stylesheet.css" />

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-edc81f70-7384-4b45-aae9-dee82e4c9e73
:END:

I want to write my notes on physics, mathematics, and computer
science in such a manner that their relationships are explicit
among each other. That is to say: in my work on physics, I use
numerical methods implemented in either my computer science or
mathematics notes.

This is more an experiment with org-mode than the actual notes.

** Organization/Contents
:PROPERTIES:
:CUSTOM_ID: h-0b2f2e85-3dea-404c-bb03-b1d99332f7cc
:END:

There is a clean-ish separation of concerns between the domains of
mathematics and science, but muddled separations among
sciences. I'm also uncertain where to divide mathematics and
computer science. But so far as Lisp cares, all the mathematics
code should be compiled before the science code. Where we draw the
line demarcating mathematics and computer science remains vague.

The current directory structure:

- [[file:physics/index.org][/physics]] for all physics-related notes
- [[file:math/index.org][/math]] for all mathematics notes
- [[file:comp-sci/index.org][/comp-sci]] for all computer science notes

As I continue working through my readings, I will add more
directories. For subfields (like, I don't know, astronomy) I will
add subdirectories where appropriate.

** Scope
:PROPERTIES:
:CUSTOM_ID: h-740aa239-de0a-40ee-a66c-604fff24c692
:END:

The scope for my endeavor is rather open-ended. It may extend from
physics to [hard] science more generally. The computer science
aspects may be downplayed, or expanded, depending on my
curiosity. The underlying drive is to understand how the Earth
works, and how the solar system evolves in time.

Hopefully I will be able to create something useful, though these
are just notes and sketches of computer program fragments.

** Also See
:PROPERTIES:
:CUSTOM_ID: h-dbf20712-ae86-4aeb-9812-406a263b41b1
:END:

- [[file:bookmarks.org][Bookmarks]] for other pages I should read later
- [[file:meta.org][Meta]] about note taking