#+TITLE: Meta-Notes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at  5:41PM

* Introduction

Notes about these notes.

* Org-Mode

Regarding org-mode commands and quirks.

** Exporting Source code

If I add to the header of an org file:

#+begin_example
 #+begin_src lang tangle: my-file.lisp ...
#+end_example

Then by default, all source code blocks will be evaluated /as if/
it had =tangle: my-file.lisp=. 

*** Keeping the Noweb labels in documentation

If we want to keep the noweb labels inlined in the code blocks when
exporting to HTML or whatever, then we should also add:

#+begin_example
 #+begin_src lang :noweb no-export ...
#+end_example

It appears that the Noweb label can include whitespace, though it
may be useful to use =snake_case=. When we want to define or append
code to a noweb label, we write

#+begin_example
 #+begin_src lang ... :noweb-ref [label]
#+end_example

It seems like it must be the last element in the "begin source"
line. 


* Subject Classification

I'm not sure how best to organize my notes. There are a number of
classification systems for the subjects I am interested in studying.
These are too coarse, not quite right, but interesting
nevertheless, so I'm sticking them in my meta-notes.

** Mathematical Subject Classification

- General, foundations
- Discrete mathematics, algebra
- Analysis
- Geometry and Topology
- Applied mathematics, other

** Physics and Astronomy Classification System

- General
- The Physics of Elementary Particles and Fields
- Nuclear Physics
- Atomic and Molecular Physics
- Electromagnetism, Optics, Acoustics, Heat Transfer, Classical
  Mechanics, and Fluid Dynamics
- Physics of Gases, Plasmas, and Electric Discharges
- Condensed Matter: Structure, Mechanical and Thermal Properties
- Condensed Matter: Electronic Structure, Electrical, Magnetic, and
  Optical Properties
- Interdisciplinary Physics and Related Areas of Science and Technology
- Geophysics, Astronomy, and Astrophysics

** ACM Computing Classification System

1. General and reference
2. Hardware
3. Computer System Organization
4. Networks
5. Software and its engineering
6. Theory of computation
7. Mathematics of computing
8. Information Systems
9. Security and Privacy
10. Human-centered computing
11. Computing Methodologies
12. Applied computing
13. Social and professional topics
