#+TITLE: Random Quotes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Monday June 21, 2021 at  9:11AM

* T.S. Eliot
:PROPERTIES:
:CUSTOM_ID: h-531ac70d-4f21-4d1e-a4ce-a5903008170b
:END:

#+begin_verse
We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
Through the unknown, remembered gate
When the last of earth left to discover
Is that which was the beginning;
At the source of the longest river
The voice of the hidden waterfall
And the children in the apple-tree

Not known, because not looked for
But heard, half-heard, in the stillness
Between two waves of the sea.
Quick now, here, now, always--
A condition of complete simplicity
(Costing not less than everything)
And all shall be well and
All manner of thing shall be well
When the tongues of flames are in-folded
Into the crowned knot of fire
And the fire and the rose are one.

("Little Gidding" in /Four Quartets/)
#+end_verse

* Edward Gibbon
:PROPERTIES:
:CUSTOM_ID: h-569c7a3c-f222-4ab2-a7fe-055bb6ccb924
:END:

** Ch 35
:PROPERTIES:
:CUSTOM_ID: h-f40791c0-3112-43d9-a713-04f79ed6215a
:END:

#+begin_quote
The revolution of ages may bring round the same calamities; but ages may
revolve without producing a Tacitus to describe them. (Footnote 110)
#+end_quote

* Isaac Newton
:PROPERTIES:
:CUSTOM_ID: h-dd149007-bdbf-455f-9460-47fea388ef00
:END:

** Arithmetica Universalis (1707)
:PROPERTIES:
:CUSTOM_ID: h-61725785-eed3-4f1c-af07-31f091eb4065
:END:

#+begin_quote
In learning the sciences examples are of more use than precepts.

(Post script to solving problem LXI; page 191 of Joseph Raphson's 1721
English translation)
#+end_quote

* Black Library Books
:PROPERTIES:
:CUSTOM_ID: h-78c48777-e79e-41db-a109-35673d1c0d24
:END:

** Cyper: Lord of the Fallen

#+begin_quote
You don't become a mystery without learning a few secrets. (17)
#+end_quote

#+begin_quote
Hypocrisy, it seems, is the one coin that never loses its value. (38)
#+end_quote

#+begin_quote
Which is more important, the truth or what people believe? Most would
say the truth, but that is too easy. No one actually /wants/ the
truth. Not in this universe. Hearing the truth is like looking on the
face of a god --- you have a moment of pure revelation, and then you are
ash carried away to oblivion, knowing nothing, seeing nothing.  When
people say they want the truth, they mean that they want something they
can understand, something that fits, that they can carry around in their
thoughts like a relic, to touch and take away the fear of what they are
living.

Am I a traitor? Am I one soul, or am I many? Have I had many names or
only the one? Do I wish redemption or vengeance? It's comforting to be
able to pick one, and then see everything fall into line behind it ---
villain-hero, right-wrong, on and on. That's what people want when they
ask for the truth. They want the lie that makes the world simple.

But you are not like that, are you? You know that it is better not to
ask for the truth. That what you should ask for are secrets. (pg 111)
#+end_quote

** Twice Dead King: Reign
:PROPERTIES:
:CUSTOM_ID: h-2cc5e6fb-0298-4802-813f-16c9b90624eb
:END:

#+begin_quote
The warlock sought only to break the limits of the possible, for no
reason other than the pleasure of the breaking. They were the worst kind
of mad. (Ch.11)
#+end_quote

#+begin_quote
"You are quite mad, Zultanekh," replied Oltyx eventually. "I suspect I will
come to miss it."

"Does one have to settle on one sort of madness or another," Zultanekh
pondered, "in order to endure eternity? Yes, I think so. I have settled
comfortably into mine. I hope that you find peace in your own, young Oltyx."
(Epilogue)
#+end_quote

** The Carrion Throne
:PROPERTIES:
:CUSTOM_ID: h-185c70c9-a4cc-4334-b600-a61f91f3523d
:END:

#+begin_quote
That would be neat and helpful, and I don't think life is neat
and helpful. It's never been that way for me, anyway.
#+end_quote

** Horus Rising
:PROPERTIES:
:CUSTOM_ID: h-419b87d6-2727-41d7-a0e3-df3f3a9d935a
:END:

#+begin_quote
"Then it occurs to me, Garviel, that only a weapon which questions its
use could be of any value in that role. To be a member of the Mournival,
you need to have concerns. You need to have wit, and most certainly you
need to have doubts. Do you know what a naysmith is?"

"No."

"In early Terran history, during the dominance of the Sumaturan dynasts,
naysmiths were employed by the ruling classes. Their job was to
disagree. To question everything. To consider any argument or policy and
find fault with it, or articulate the counter position. They were highly
valued."
(Pg 68?)
#+end_quote

** Galaxy in Flames
:PROPERTIES:
:CUSTOM_ID: h-17446d97-bd2c-4131-a9c4-a8beb637e069
:END:

#+begin_quote
Watching the light of understanding rekindled in Iacton Qruze reminded
Sindermann that there was still hope.

And there is nothing more dangerous in the galaxy than a little hope.

(Chapter 13, pg 297 of paperback.)
#+end_quote

** Saturnine
:PROPERTIES:
:CUSTOM_ID: h-1d71719a-7630-497c-94e6-bfeafffef5f0
:END:

#+begin_quote
If stories ever end, then this story ends here. [...]

I think, though it is not my field of specialisation, that some stories
end, but others carry on. They are eternal. They secretly carry on after
the story appears to be finished, continuing in silence. They do not
talk. They are never heard. I think my story may be like that.

[...]

And I think my story ends here too. Soon.

I would have liked to tell it to someone. Share it. But that sort of
connection is something I have never been allowed.

Here are the things I would have said.

I am fighting to the end in a battle that cannot be won. I am fighting
to the end in a battle that I knew could not be won before it even began.
I am doing this, not because I am brave, or because I am foolish, but
because it was the only thing to do. If we give up on the doomed, we
give up on ourselves.

My presence, the curse of my company, has kept the doomed souls alive a
little longer than fate had planned. I have not driven off the daemons
or the night, for they are too strong for even me. But I have held them
at bay for a while. I have made the daemons wary. (Pg 531)
#+end_quote

#+begin_quote
At the Eternity Wall space port, late in a very long life, I have
discovered to my joy that my presence, the curse of my company, can also
be a blessing.  This is new to me, and unfamiliar. I have fought to
protect these people, who cannot see me, but the mystery of me --- for it
appears it can be a mystery as well as a curse --- has inspired them. The
fact of my absence is a place they cannot explain, so they have filled
it with stories and ideas, and those stories and ideas have given them
strength and hope and courage.

I never planned for that. I did not set out to do it. It simply
happened.  These are strange times.

I will confess, now, because no one is listening, that this has been the
greatest accomplishment of my life. It is completely unexpected. My
whole life, I have stood apart, and wherever I have gone, I have spread
only fear and discomfort. But here, briefly and unexpectedly, I have
affected people in another way. I have been an unlikely conduit for
strength and unity. I have been a mystery that has compelled them to
stand up and believe, not cower and shrink in fear.

I have been able to touch them.

This is my fortune. It is all I have ever wanted.

I wish it could continue, but it will not. As I have said, this is a
story that is reaching its end. (Pp. 532--533)
#+end_quote

** Echoes of Eternity
:PROPERTIES:
:CUSTOM_ID: h-57839cfb-92ff-40d5-b68c-5a4921b4b3f5
:END:

#+begin_quote
Humanity has always managed to summon a poetic turn of phrase for the
projected end of everything. Scribes love to speak of how things fall
apart, the centre unable to hold --- contrasting the rise of oceans with
the fall of empires. Philosophers claim the end will come not with a
bang, but with a whimper. And of death? Nothing to fear, they
promise. Death is merely another path.

These sentiments are always composed by men and women far removed from
any experience of what the end of all things would really be. It's easy
to fall back on sanguine philosophy when you can't comprehend the
truth. Yes, the centre cannot hold, but its dissolution means the
genocide of trillions. Yes, death is another path, but that path leads
to the soul of every man, woman and child sliding into the open mouths
of mad gods.

Had the ancient wise ones seen such things with their own eyes, perhaps
their scrawls would have been somewhat less serene.

But a coin has two sides. Twinned with the serenity of ignorance is the
spectre of hope. People will resist the end, even against the evidence
of their eyes and the workings of their minds. Logic plays no part in
it. This is the arena of hope, with survival instincts baked into the
brain of every living being. Emotions like that burn through anything as
cold and blunt as reason. (Chapter 8)
#+end_quote

** The Talon of Horus
:PROPERTIES:
:CUSTOM_ID: h-5c08cf65-db9b-48a6-a0c1-6bfba7451a06
:END:

#+begin_quote
So defiant. So certain. So ignorant. The pride of those who have nothing
worth fighting for. (222)
#+end_quote

#+begin_quote
No soul is as self-righteous as the one that believes it gazes into the
future. (295)
#+end_quote

#+begin_quote
No one ever said enlightenment came without cost. (304)
#+end_quote
