#+TITLE: Random Quotes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Monday June 21, 2021 at  9:11AM

* T.E. Lawrence ("of Arabia")
:PROPERTIES:
:CUSTOM_ID: h-eb9e67fc-e1e7-450f-8be8-fbf6c31771cc
:END:

#+begin_quote
You wonder what I am doing? Well, so do I, in truth. Days seem to dawn,
suns to shine, evenings to follow, and then I sleep. What I have done,
what I am doing, what I am going to do, puzzle and bewilder me. Have you
ever been a leaf and fallen from your tree in autumn and been really
puzzled about it? That's the feeling.

--- Letter to Eric Kennington (6 May 1935)
#+end_quote

* Michael Mahoney
:PROPERTIES:
:CUSTOM_ID: h-2048a743-d171-45e7-ba9b-3465403cdbe1
:END:

#+begin_quote
...episodes of intense emotional distress and disorder often reflect
natural (and, yes, even healthy) expressions of an individual's
struggles toward reorganization. Such struggles are not always
successful, of course, but they may be viewed with substantially less
fear and impatience if they are construed as the activities of an open,
developing system in search of a "more extensive balance" with its
world.
(/Human Change Processes/)
#+end_quote

* T.S. Eliot
:PROPERTIES:
:CUSTOM_ID: h-531ac70d-4f21-4d1e-a4ce-a5903008170b
:END:

#+begin_verse
We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
Through the unknown, remembered gate
When the last of earth left to discover
Is that which was the beginning;
At the source of the longest river
The voice of the hidden waterfall
And the children in the apple-tree

Not known, because not looked for
But heard, half-heard, in the stillness
Between two waves of the sea.
Quick now, here, now, always--
A condition of complete simplicity
(Costing not less than everything)
And all shall be well and
All manner of thing shall be well
When the tongues of flames are in-folded
Into the crowned knot of fire
And the fire and the rose are one.

("Little Gidding" in /Four Quartets/)
#+end_verse

* Edward Gibbon
:PROPERTIES:
:CUSTOM_ID: h-569c7a3c-f222-4ab2-a7fe-055bb6ccb924
:END:

** Ch 35
:PROPERTIES:
:CUSTOM_ID: h-f40791c0-3112-43d9-a713-04f79ed6215a
:END:

#+begin_quote
The revolution of ages may bring round the same calamities; but ages may
revolve without producing a Tacitus to describe them. (Footnote 110)
#+end_quote

* Isaac Newton
:PROPERTIES:
:CUSTOM_ID: h-dd149007-bdbf-455f-9460-47fea388ef00
:END:

** Arithmetica Universalis (1707)
:PROPERTIES:
:CUSTOM_ID: h-61725785-eed3-4f1c-af07-31f091eb4065
:END:

#+begin_quote
In learning the sciences examples are of more use than precepts.

(Post script to solving problem LXI; page 191 of Joseph Raphson's 1721
English translation)
#+end_quote

* Black Library Books
:PROPERTIES:
:CUSTOM_ID: h-78c48777-e79e-41db-a109-35673d1c0d24
:END:

** Cyper: Lord of the Fallen
:PROPERTIES:
:CUSTOM_ID: h-424ca920-63a8-49cd-8478-7cd4a53ac1be
:END:

#+begin_quote
You don't become a mystery without learning a few secrets. (17)
#+end_quote

#+begin_quote
Hypocrisy, it seems, is the one coin that never loses its value. (38)
#+end_quote

#+begin_quote
Which is more important, the truth or what people believe? Most would
say the truth, but that is too easy. No one actually /wants/ the
truth. Not in this universe. Hearing the truth is like looking on the
face of a god --- you have a moment of pure revelation, and then you are
ash carried away to oblivion, knowing nothing, seeing nothing.  When
people say they want the truth, they mean that they want something they
can understand, something that fits, that they can carry around in their
thoughts like a relic, to touch and take away the fear of what they are
living.

Am I a traitor? Am I one soul, or am I many? Have I had many names or
only the one? Do I wish redemption or vengeance? It's comforting to be
able to pick one, and then see everything fall into line behind it ---
villain-hero, right-wrong, on and on. That's what people want when they
ask for the truth. They want the lie that makes the world simple.

But you are not like that, are you? You know that it is better not to
ask for the truth. That what you should ask for are secrets. (pg 111)
#+end_quote

** Twice Dead King: Reign
:PROPERTIES:
:CUSTOM_ID: h-2cc5e6fb-0298-4802-813f-16c9b90624eb
:END:

#+begin_quote
The warlock sought only to break the limits of the possible, for no
reason other than the pleasure of the breaking. They were the worst kind
of mad. (Ch.11)
#+end_quote

#+begin_quote
"You are quite mad, Zultanekh," replied Oltyx eventually. "I suspect I will
come to miss it."

"Does one have to settle on one sort of madness or another," Zultanekh
pondered, "in order to endure eternity? Yes, I think so. I have settled
comfortably into mine. I hope that you find peace in your own, young Oltyx."
(Epilogue)
#+end_quote

** The Carrion Throne
:PROPERTIES:
:CUSTOM_ID: h-185c70c9-a4cc-4334-b600-a61f91f3523d
:END:

#+begin_quote
That would be neat and helpful, and I don't think life is neat
and helpful. It's never been that way for me, anyway.
#+end_quote

** Horus Rising
:PROPERTIES:
:CUSTOM_ID: h-419b87d6-2727-41d7-a0e3-df3f3a9d935a
:END:

#+begin_quote
"Then it occurs to me, Garviel, that only a weapon which questions its
use could be of any value in that role. To be a member of the Mournival,
you need to have concerns. You need to have wit, and most certainly you
need to have doubts. Do you know what a naysmith is?"

"No."

"In early Terran history, during the dominance of the Sumaturan dynasts,
naysmiths were employed by the ruling classes. Their job was to
disagree. To question everything. To consider any argument or policy and
find fault with it, or articulate the counter position. They were highly
valued."
(Pg 68?)
#+end_quote

** Galaxy in Flames
:PROPERTIES:
:CUSTOM_ID: h-17446d97-bd2c-4131-a9c4-a8beb637e069
:END:

#+begin_quote
Watching the light of understanding rekindled in Iacton Qruze reminded
Sindermann that there was still hope.

And there is nothing more dangerous in the galaxy than a little hope.

(Chapter 13, pg 297 of paperback.)
#+end_quote

** Saturnine
:PROPERTIES:
:CUSTOM_ID: h-1d71719a-7630-497c-94e6-bfeafffef5f0
:END:

#+begin_quote
Olly Piers simmered for a moment, then straightened his shako, and
glared at him.

"Look around. Look at the shit around you, boy. *This is what the very*
*edge looks like. The very brink. This is what it looks like when you're*
*holding on so desperately there's no skin left on your*
*finger­bones. This is when it matters most. This is when it makes the*
*difference between living and dying. You take whatever you can to blaze*
*up your spirits. Anything. A truth, a lie, it doesn't matter. You use*
*whatever you can to keep you going, and you share it with whoever's with*
*you. Whatever you've got, you understand? Whatever keeps you going one*
*more step. That's how you live. That's how you win. That's how you*
*survive, and how your friends and your comrades survive with you, so you*
*can all tell glory tales afterwards, and make even more bullshit up to*
*get you through shitstorms to come.*"

"Piers, that's a really cynical way of---"

"Oh, piss yourself off a cliff, you precious little high-minded
historian shit-streak, and take your pious little notion of what truth
and history means with you! It's your pissing history books that prove
my case! *The power of myths and lies and frigging stories have got us*
*through thirty frigging thousand years of shit, so I'm gonna go out on a*
*limb and suggest it's a pretty effective bloody formula!*

"Besides," he added, slumping back against the trench wall, his voice
dropping, "it frigging well /was/ Mythrus. [...]"

[...]

He slithered forward, keeping his head below the trench lip as a volley
of shots went over. He grabbed Hari by the shoulder roughly, turned him
around, and pointed along the trench.

"What's that, eh?"

Hari looked. Twenty metres away, a squad of Auxilia were man­handling a
battle banner upright. The Emperor Ascendant, in a sunburst.

"A banner," said Hari.

"And look, boy, how it takes four...no, five, look...men to get it
upright and displayed. That's five soldiers who could be firing rifles
at enemy targets. But the idea matters more. It rallies us. It reminds
us why we're here. It could be anything. It could be a picture of a
giant rabbit. It could be a picture of my hairy frigging arse. Doesn't
matter. *It reminds us, plain and simple, that there's a point to what*
*we're doing, and a reason to keep doing it. Without it, we're just a*
*bunch of frigging idiots shitting ourselves in a ditch. Now think on*
*that, and get your sodding arse out of here.*"

(Emphasis mine)
#+end_quote

#+begin_quote
Hari blinked. He had no idea why soldiers lied. If this was war, the
actual inside of war, then why did they make shit up? No tall tale, not
even one spun by a skilled, serial liar like Olly Piers, could ever hope
to match the astonishing truth of war. Lies were smaller than war. No
lie, no matter how cocky and outrageous, was ever going to take war on
and win.

War was a scream in capital letters. It was a noise. It wasn't even
words. It had no syntax, no adjectives, no subtext, no context. It
communicated itself as suddenly, simply and unequivocally as a punch in
the face. It was a thing, not a story.

Then maybe that was why. That was why soldiers lied. It was the only
way, the only meagre, insufficient way they could talk about what they
had endured. It was the only way they could give voice to something that
defied articulation. War was so big, soldiers needed to get it out of
themselves, spew it out, purge themselves, and lies were the only things
that worked. It was either that, or punch someone else in the face.

Unless...

Hari blinked again. Now he grasped it. The lies weren't exorcism. At
least, not completely. They were protection. After the fact, after the
brute scream of war, the lies weren't a means to talk about something
that defied words. They weren't approximate expression. They were
curative. They were comfort. The lies were lies of glory and heroism,
achievement and success. They weren't born out of arrogance or boasting
or self-aggrandisement. They were just ways to talk about something that
was otherwise unbearable. They were coping strategies to insulate
survivors against the madness and the punch in the face. They were ways
to make war feel like it had some point, some value, some lasting
worth. Lies made war better for those unlucky enough to survive it.

Lies gave soldiers something to think about, and talk about, and
cherish, so they would never have to...never, ever have to think about
the truth.

"It's a stupid bloody time to figure that out..." Hari murmured to
himself. He laughed, for want of anything else to do.

"What?" Piers yelled. "What did you say?"

Hari looked at him. Olly Piers, shako on crooked, meal-tin spills down
the front of his coat, rancid of breath, half-covered in dirt and
grease, too old by far to be having to do this all over again. What a
horrible life you must have lived, Piers, to have become such a
magnificent liar. What terrible things you must have seen to make you
need to lie so much. That's what you were telling me all along, and I
was too stupid to comprehend. I had no frame of reference.

I have it now, thought Hari. I wish I didn't. I would give anything not
to have had this experience, and not to be here. There is no truth here,
no story, no words. There's nothing to take from this of any worth, and
all my high-minded ambitions to come along and brave the dangers in
order to capture something valuable were bullshit.

There is nothing here to cherish. Nothing here to learn. War is noise,
sensory overload, pain, terror, horror. That's it. It's an inarticulate
obscenity. It can't be communicated, and even if it could be, it
shouldn't be.
#+end_quote

#+begin_quote
"What's Olly short for?" Hari asked.

"Why, boy?"

"I'm writing your story," said Hari. "I wanted to get your name right."

"I don't have a story," Piers rumbled, and went back to scrubbing. "I
have stories, plural. Many fine stories. But not /a/ story. I am a
complicated man. I will not be reduced or abbreviated."

"Except to Olly."

"Shut your hole, clever clogs."
#+end_quote

#+begin_quote
If stories ever end, then this story ends here. [...]

I think, though it is not my field of specialisation, that some stories
end, but others carry on. They are eternal. They secretly carry on after
the story appears to be finished, continuing in silence. They do not
talk. They are never heard. I think my story may be like that.

[...]

And I think my story ends here too. Soon.

I would have liked to tell it to someone. Share it. But that sort of
connection is something I have never been allowed.

Here are the things I would have said.

I am fighting to the end in a battle that cannot be won. I am fighting
to the end in a battle that I knew could not be won before it even began.
I am doing this, not because I am brave, or because I am foolish, but
because it was the only thing to do. If we give up on the doomed, we
give up on ourselves.

My presence, the curse of my company, has kept the doomed souls alive a
little longer than fate had planned. I have not driven off the daemons
or the night, for they are too strong for even me. But I have held them
at bay for a while. I have made the daemons wary. (Pg 531)
#+end_quote

#+begin_quote
At the Eternity Wall space port, late in a very long life, I have
discovered to my joy that my presence, the curse of my company, can also
be a blessing.  This is new to me, and unfamiliar. I have fought to
protect these people, who cannot see me, but the mystery of me --- for it
appears it can be a mystery as well as a curse --- has inspired them. The
fact of my absence is a place they cannot explain, so they have filled
it with stories and ideas, and those stories and ideas have given them
strength and hope and courage.

I never planned for that. I did not set out to do it. It simply
happened.  These are strange times.

I will confess, now, because no one is listening, that this has been the
greatest accomplishment of my life. It is completely unexpected. My
whole life, I have stood apart, and wherever I have gone, I have spread
only fear and discomfort. But here, briefly and unexpectedly, I have
affected people in another way. I have been an unlikely conduit for
strength and unity. I have been a mystery that has compelled them to
stand up and believe, not cower and shrink in fear.

I have been able to touch them.

This is my fortune. It is all I have ever wanted.

I wish it could continue, but it will not. As I have said, this is a
story that is reaching its end. (Pp. 532--533)
#+end_quote

#+begin_quote
If the boy had been there, he'd have asked Piers if he was
afraid. Because he always asked such stupid questions. But Piers would
have answered him. He'd have said "no".

Because he always lied.
#+end_quote

** Echoes of Eternity
:PROPERTIES:
:CUSTOM_ID: h-57839cfb-92ff-40d5-b68c-5a4921b4b3f5
:END:

#+begin_quote
Humanity has always managed to summon a poetic turn of phrase for the
projected end of everything. Scribes love to speak of how things fall
apart, the centre unable to hold --- contrasting the rise of oceans with
the fall of empires. Philosophers claim the end will come not with a
bang, but with a whimper. And of death? Nothing to fear, they
promise. Death is merely another path.

These sentiments are always composed by men and women far removed from
any experience of what the end of all things would really be.
*It's easy to fall back on sanguine philosophy when you can't comprehend
the truth.* Yes, the centre cannot hold, but its dissolution means the
genocide of trillions. Yes, death is another path, but that path leads
to the soul of every man, woman and child sliding into the open mouths
of mad gods.

Had the ancient wise ones seen such things with their own eyes, perhaps
their scrawls would have been somewhat less serene.

But a coin has two sides. Twinned with the serenity of ignorance is the
spectre of hope. People will resist the end, even against the evidence
of their eyes and the workings of their minds. Logic plays no part in
it. This is the arena of hope, with survival instincts baked into the
brain of every living being. Emotions like that burn through anything as
cold and blunt as reason. (Chapter 8, emphasis mine)
#+end_quote

** The Talon of Horus
:PROPERTIES:
:CUSTOM_ID: h-5c08cf65-db9b-48a6-a0c1-6bfba7451a06
:END:

#+begin_quote
So defiant. So certain. So ignorant. The pride of those who have nothing
worth fighting for. (222)
#+end_quote

#+begin_quote
No soul is as self-righteous as the one that believes it gazes into the
future. (295)
#+end_quote

#+begin_quote
No one ever said enlightenment came without cost. (304)
#+end_quote

** The Founding (Gaunt's Ghosts Omnibus)
:PROPERTIES:
:CUSTOM_ID: h-76c8fda5-bd7d-4a3c-96a8-6d58cf800d9b
:END:

#+begin_quote
Sometimes there just isn't the opportunity or the willingness to make
things better. Sometimes you can't simply have another go. You make a
choice, and it's a bad one, and you're left with it. No amount of trying
again will fix it. Don't expect anyone to feel sorry for you, to cut you
slack; you make a mistake you'll have to live with. (317--318, "Of the
lives in the ruins of the cities")
#+end_quote
