#+TITLE: Random Quotes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Monday June 21, 2021 at  9:11AM

* Edward Gibbon
:PROPERTIES:
:CUSTOM_ID: h-569c7a3c-f222-4ab2-a7fe-055bb6ccb924
:END:

** Ch 35
:PROPERTIES:
:CUSTOM_ID: h-f40791c0-3112-43d9-a713-04f79ed6215a
:END:

#+begin_quote
The revolution of ages may bring round the same calamities; but ages may
revolve without producing a Tacitus to describe them. (Footnote 110)
#+end_quote

* Isaac Newton
:PROPERTIES:
:CUSTOM_ID: h-dd149007-bdbf-455f-9460-47fea388ef00
:END:

** Arithmetica Universalis (1707)
:PROPERTIES:
:CUSTOM_ID: h-61725785-eed3-4f1c-af07-31f091eb4065
:END:

#+begin_quote
In learning the sciences examples are of more use than precepts.

(Post script to solving problem LXI; page 191 of Joseph Raphson's 1721
English translation)
#+end_quote

* Black Library Books
:PROPERTIES:
:CUSTOM_ID: h-78c48777-e79e-41db-a109-35673d1c0d24
:END:

** Horus Rising
:PROPERTIES:
:CUSTOM_ID: h-419b87d6-2727-41d7-a0e3-df3f3a9d935a
:END:

#+begin_quote
"Then it occurs to me, Garviel, that only a weapon which questions its
use could be of any value in that role. To be a member of the Mournival,
you need to have concerns. You need to have wit, and most certainly you
need to have doubts. Do you know what a naysmith is?"

"No."

"In early Terran history, during the dominance of the Sumaturan dynasts,
naysmiths were employed by the ruling classes. Their job was to
disagree. To question everything. To consider any argument or policy and
find fault with it, or articulate the counter position. They were highly
valued."
(Pg 68?)
#+end_quote

** Galaxy in Flames
:PROPERTIES:
:CUSTOM_ID: h-17446d97-bd2c-4131-a9c4-a8beb637e069
:END:

#+begin_quote
Watching the light of understanding rekindled in Iacton Qruze reminded
Sindermann that there was still hope.

And there is nothing more dangerous in the galaxy than a little hope.

(Chapter 13, pg 297 of paperback.)
#+end_quote

** Saturnine
:PROPERTIES:
:CUSTOM_ID: h-1d71719a-7630-497c-94e6-bfeafffef5f0
:END:

#+begin_quote
If stories ever end, then this story ends here. [...]

I think, though it is not my field of specialisation, that some stories
end, but others carry on. They are eternal. They secretly carry on after
the story appears to be finished, continuing in silence. They do not
talk. They are never heard. I think my story may be like that.

[...]

And I think my story ends here too. Soon.

I would have liked to tell it to someone. Share it. But that sort of
connection is something I have never been allowed.

Here are the things I would have said.

I am fighting to the end in a battle that cannot be won. I am fighting
to the end in a battle that I knew could not be won before it even began.
I am doing this, not because I am brave, or because I am foolish, but
because it was the only thing to do. If we give up on the doomed, we
give up on ourselves.

My presence, the curse of my company, has kept the doomed souls alive a
little longer than fate had planned. I have not driven off the daemons
or the night, for they are too strong for even me. But I have held them
at bay for a while. I have made the daemons wary. (Pg 531)
#+end_quote

#+begin_quote
At the Eternity Wall space port, late in a very long life, I have
discovered to my joy that my presence, the curse of my company, can also
be a blessing.  This is new to me, and unfamiliar. I have fought to
protect these people, who cannot see me, but the mystery of me --- for it
appears it can be a mystery as well as a curse --- has inspired them. The
fact of my absence is a place they cannot explain, so they have filled
it with stories and ideas, and those stories and ideas have given them
strength and hope and courage.

I never planned for that. I did not set out to do it. It simply
happened.  These are strange times.

I will confess, now, because no one is listening, that this has been the
greatest accomplishment of my life. It is completely unexpected. My
whole life, I have stood apart, and wherever I have gone, I have spread
only fear and discomfort. But here, briefly and unexpectedly, I have
affected people in another way. I have been an unlikely conduit for
strength and unity. I have been a mystery that has compelled them to
stand up and believe, not cower and shrink in fear.

I have been able to touch them.

This is my fortune. It is all I have ever wanted.

I wish it could continue, but it will not. As I have said, this is a
story that is reaching its end. (Pp. 532--533)
#+end_quote
