#+TITLE: Heat Equation for Atmospheric Dynamics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-04-12T10:39:01-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Tuesday April 12, 2022 at 10:39AM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-2acf6524-6528-401d-bec7-1dc426830ce6
:END:

J. David Neelin's {{{book-title(Climate Change and Climate Modeling)}}}
give the following description of the equation governing atmospheric
thermodynamics (it's the heat equation plus a term describing how an air
parcel's volume increases as it elevates):

\begin{equation}
c_{p}\frac{\mathrm{D}T}{\mathrm{D}t}-\frac{1}{\rho}\frac{\mathrm{D}p}{\mathrm{D}t}
= Q
\end{equation}

where $c_{p}$ is the heat capacity of air at constant pressure, and $Q$
is the heating term. For us, the heating term has several contributions

\begin{equation}
Q = Q_{\text{solar}} + Q_{\text{IR}} + Q_{\text{convection}} +
Q_{\text{mixing}}.
\end{equation}

Beyond this, I'm relatively stumped, to be completely honest.
This can also be found in, e.g., Vallis's
{{{book-title(Atmospheric and Oceanic Fluid Dynamics)}}}, chapter 1 \S6.
It seems Vallis discusses radiative transfer in chapter 18, but it's...a
bit of work to get to some expression for $Q$ out of it.

* References
:PROPERTIES:
:CUSTOM_ID: h-e98f5f49-6026-4942-8417-8db77f4749bb
:END:

- J. David Neelin,\\
  {{{book-title(Climate Change and Climate Modeling)}}}.\\
  CUP, 2011; see especially \sect3.3.2 for the heat equation for air.