#+TITLE: Effective Temperature
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-05T19:31:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5 toc:nil
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at  7:31PM
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />

* Problem
:PROPERTIES:
:CUSTOM_ID: h-126b94b0-bfb9-4b5f-9768-8b8446cb87a0
:END:

Given the Sun acts like a black body radiating at a constant luminosity,
determine the effective temperature of the Earth. Assume the Earth has
no atmosphere.

* Overview
:PROPERTIES:
:CUSTOM_ID: h-266f1897-6dd7-4e7b-9dd1-e8692ab5764d
:END:

** Computing the Approximate Temperature of the Earth
:PROPERTIES:
:CUSTOM_ID: h-47370783-5efa-4873-9124-8a68f2bb5669
:END:

*Identify*. We use the Stefan--Boltzmann law for the Sun's luminosity,
then considering the Irradiance of the Earth receiving this radiation,
we assume the Earth is in a steady state...so its luminosity (from the
Stefan--Boltzmann law) of radiation emitted equals its irradiance
received from the Sun.

*Setup and Execute.* We use the Stefan--Boltzmann law for black-body
temperature, the Luminosity of the sun is then stipulated to be:

\begin{equation}
L_{\odot} = 4\pi R_{\odot}^{2}\sigma T_{\odot}^{4}.
\end{equation}

The Earth is a distance $a_{0}$ from the Sun, the irradiance received by
a single point at this distance would be

\begin{equation}
E_{\oplus} = \frac{L_{\odot}}{4\pi a_{0}^{2}}.
\end{equation}

The radiance flux absorbed by the Earth would be given by treating the
Earth as a disc ("broadside of a barn") which is hit by the Sun's rays.
That is to say, integrating the irradiance by the cross-sectional area
of the Earth, or

\begin{equation}
\Phi_{abs} = \pi R_{\oplus}^{2}E_{\oplus}.
\end{equation}

In a steady state, the Luminosity emitted by the Earth is equal to the irradiance
received, giving us

\begin{equation}
4\pi R_{\oplus}^{2}\sigma T_{\oplus}^{4} = \pi R_{\oplus}^{2}E_{\oplus}.
\end{equation}

We substitute in the value of $E_{\oplus}$ to the right-hand side,
giving us

\begin{equation}
4\pi R_{\oplus}^{2}\sigma T_{\oplus}^{4} = \pi R_{\oplus}^{2}\frac{L_{\odot}}{4\pi a_{0}^{2}}.
\end{equation}

The luminosity of the Sun transforms the right-hand side into

\begin{equation}
4\pi R_{\oplus}^{2}\sigma T_{\oplus}^{4} = \pi R_{\oplus}^{2}\frac{4\pi R_{\odot}^{2}\sigma T_{\odot}^{4}}{4\pi a_{0}^{2}}.
\end{equation}

Now we solve for the temperature of the Earth $T_{\oplus}$

\begin{equation}
T_{\oplus}^{4} = \frac{R_{\odot}^{2}T_{\odot}^{4}}{4a_{0}^{2}}
\end{equation}

which simplifies to

\begin{equation}
T_{\oplus} = T_{\odot}\sqrt{\frac{R_{\odot}}{2a_{0}}}.
\end{equation}

We can plug in empirical values for these quantities to get an estimate
for the temperature of the Earth.

#+begin_src emacs-lisp :exports both
(let ((sun-temperature 5772.0) ;; K
      (sun-radius 695700.0) ;; km
      (earth-distance 149596000.0)) ;; km
  (* sun-temperature (sqrt (/ sun-radius (* 2.0 earth-distance)))))
#+end_src

#+RESULTS:
: 278.3314843147163

Thus the temperature of the Earth $T_{\odot}\approx 278\mbox{ K}$ or
about 5 degrees Celsius on the surface of the Earth, assuming the Earth
absorbs all of the Sun's rays and the Earth has no atmosphere.

*Evaluate.* Does this make sense? Well, as the distance of the Earth
increases $a_{0}\to\infty$ we see the surface temperature for the Earth
decreases $T_{\oplus}\to0$, as we would expect. Similarly, for
decreasing the radius of the Sun $R_{\odot}\to0$, we see the Earth
would receive decreasing radiance hence decreasing temperature
$T_{\oplus}\to0$, as we would expect.
