#+TITLE: Hierarchy of Climate Models
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-05-22T12:43:27-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday May 22, 2021 at 12:43PM

This is an annotated bibliography of the available software for climate
models. It seems that each component has been independently developed by
different groups and agencies.

* Radiative Transfer Models
:PROPERTIES:
:CUSTOM_ID: h-78f8baee-6f4b-4f02-95f7-3ab2697eaffb
:END:

** Atmospheric & Environmental Research (AER) Working Group
:PROPERTIES:
:CUSTOM_ID: h-b411b9fa-b776-4b87-a0f0-58a5ca2b2fb1
:END:

This group seems to have standardized the abbreviations for many models
of radiative transfer.

- [[https://web.archive.org/web/20210413060526/http://www.rtweb.aer.com/][rtweb.aer.com]] (archived)
- [[https://www.aer.com/science-research/atmosphere/radiative-transfer/][aer.com]]

* Atmospheric General Circulation Models
:PROPERTIES:
:CUSTOM_ID: h-bf370b6d-78a9-4e61-a2f8-43149b238ea1
:END:


There's a plethora of models here. I'm following Paul Edwards's
{{{book-title(A Vast Machine: Computer Models, Climate Data, and the Politics of Global Warming)}}}
appendix (also available [[https://pne.people.si.umich.edu/vastmachine/agcm.html][online]]) and the [[https://web.archive.org/web/20040825054939/http://www.aip.org/history/gcm/][AIP's history of GCMs]].

** Primordial Models
:PROPERTIES:
:CUSTOM_ID: h-b472bf21-5aa6-4620-86e6-e0f07ac8360e
:END:

Edwards classified the models in the 1955--1965 period as consisting of
four families of general circulation models:

1. Norman Phillips' model, apparently called the GCRS model (named after
   where he worked: the general circulation research section)
2. the UCLA Models
3. Lawrence Livermore model, referred to as LAM ("Leith Atmospheric Model" or "Livermore Atmospheric Model")
4. National Center for Atmospheric Research (NCAR)

Pre-internet computer-based research had this pattern of: one institute
came up with some program, then proselytized it on the "academic
circuit" (i.e., at conferences, seminars, etc.), sharing the source
code. Then followed a Cambrian explosion of innovation. Rather, rinse,
repeat.

*** General Circulation Research Section [GCRS] (1956)
:PROPERTIES:
:CUSTOM_ID: h-65de0020-de60-4547-8d19-4afd58ebfa11
:END:

Note: I've seen this referred to as the "GCRS" model, but no one really
expands on what that acronym abbreviates. It turns out to abbreviate
"General Circulation Research Section" (which was the forerunner to the
GFDL group).

This was the first published general circulation model. It was a proof
of concept, starting with simplifying assumptions like barotropy and
quasi-geostrophy, then removing them one by one.

- Norman Phillips,\\
  "The general circulation of the atmosphere: a numerical experiment".\\
  /Q. J. of the Roy. Met. Soc./ *82*, 352 (1956) 123--164;
- J.M. Lewis,\\
  "Clarifying the Dynamics of the General Circulation: Phillips's 1956 Experiment".\\
  /Bulletin of the American Meteorological Society/ *79*, no.1 (1998) 39--60. 

*** UCLA Models
:PROPERTIES:
:CUSTOM_ID: h-66c4aeb3-885f-4c50-b41c-29f704a12dbf
:END:

Yale Mintz recruited Akio Arakawa (of Tokyo University) to team up and
make a model. Well, it was a happy family of models, more properly.

#+begin_remark
The numbering scheme for the models seems inconsistent to me. In the
book {{{book-title(A Vast Machine)}}}, Paul Edwards enumerates them from
I, to V; but on his [[https://pne.people.si.umich.edu/vastmachine/i.UCLA.html][website]] he starts at "prototype", then numbers them
I to IV. I'll follow his book's conventions.
#+end_remark

**** Model I (1960?--1965)
:PROPERTIES:
:CUSTOM_ID: h-3cba208b-e58a-4dc8-9443-834c78e2ef38
:END:

The initial model was completed in 1963 then abandoned in 1965.

The first Mintz/Arakawa model was a 2-level global, primitive-equation
GCM at a 7° latitude x 9° longitude horizontal resolution. It included
realistic land-sea distributions and surface topography. Mintz never
learned to program computers; Arakawa carried out all the model coding.
The UCLA prototype model has been credited as inspiring the European
Centre for Medium-Range Weather Forecasts (ECMWF) model.

- Y. Mintz,\\
  "Design of Some Numerical General Circulation Experiments".\\
  /Bulletin of the Research Council of Israel/ *76* (1958) 67--114.
- W.E. Langlois and H.C.W. Kwok,\\
  "Description of the Mintz-Arakawa Numerical General Circulation Model".\\
  (Dept. of Meteorology, University of California at Los Angeles, 1969).
- A. Arakawa,\\
  "Numerical Simulation of Large-Scale Atmospheric Motions".\\
  /Numerical Solution of Field Problems in Continuum Physics/
  (SIAM-AMS Proceedings, American Mathematical Society) *2* (1970) 24--40.

**** Model II (1965--1972??)
:PROPERTIES:
:CUSTOM_ID: h-02d3e4e2-f2b0-4c57-9a5d-156a4adc293f
:END:

This extended the first model with more vertical layers. A 3-layer and
9-layer version were made.

This model inspired RAND's model pretty directly.

Edwards describes this system's characteristics:

#+begin_quote
When Arakawa returned to UCLA from Japan in 1965, he and Mintz began
work on the first-generation "production" UCLA GCM. It increased model
resolution to 4° latitude x 5° longitude, although it still had only two
vertical levels, and introduced a new horizontal grid structure (the
Arakawa/Lamb "B" grid).[5] This was an extremely influential GCM. About
1970 Lawrence Gates, a UCLA graduate, carried the model with him to the
RAND Corporation, where he used it in a series of studies sponsored by
the Advanced Research Projects Agency of the U.S. Defense Dept. The RAND
version of the model was eventually carried to Oregon State
University.[6]
#+end_quote

The citations Edwards gives are:

- A. Arakawa and V.R. Lamb,\\
  "Computational Design of the Basic Dynamical Processes of the UCLA General Circulation Model".\\
  In {{{book-title(General Circulation Models of the Atmosphere)}}}, ed. J. Chang,
  Methods in Computational Physics: Advances in Research and Applications
  (San Francisco: Academic Press, 1977), 173--265.
- D. Randall,\\
  "Colorado State University General Circulation Model: Introduction".\\
  (n.d.) available from http://kiwi.atmos.colostate.edu/BUGS/BUGSintro.html.

**** Model III (1972??--mid 1970s)
:PROPERTIES:
:CUSTOM_ID: h-51e23b0c-ac21-4ea2-966c-20e65107f585
:END:

This incorporated Arakawa/Lamb "C" finite-difference horizontal grid.
In a nutshell: the velocity vectors are evaluated at the grid-edges.
It was a 12-level model. Two variants were built in the mid-1970s.

- A.Arakawa, V.R. Lamb,\\
  "Computational design of the basic dynamical processes of the UCLA general circulation model".\\
  /Methods in Computational Physics: Advances in Research and Applications/ *17* (1977) pp.173--265. doi:10.1016/B978-0-12-460817-7.50009-4. ISBN 9780124608177.

**** Model IV (late 1970s)
:PROPERTIES:
:CUSTOM_ID: h-2238ffc9-cdc5-49e2-9633-2a8ca2b2cd2a
:END:

This model employed a new vertical coordinate system which used the
planetary boundary layer as a coordinate surface, and extended vertical
resolution to 15 layers.

**** Model V (c.1990-????)
:PROPERTIES:
:CUSTOM_ID: h-c9ea2a8e-de5c-46c9-bc11-af09d963719a
:END:

A heavily modified version of UCLA III with up to 29 vertical levels.

*** The Livermore Atmospheric Model "LAM" (1960--1965)
:PROPERTIES:
:CUSTOM_ID: h-32736c4d-9f84-4ca5-9d8f-2a9738b2da11
:END:

Cecil Leith began working on a GCM while at Lawrence Livermore National
Laboratories. Due to the nature of Lawrence Livermore (working on
classified research most of the time), Leith's only unclassified
publication occurred when he was ending his work on the model.

But Leith's contributions are non-negligible: he would talk at
conferences about the innovative visualizations techniques, which other
models began copying.

Edwards describes the [[https://pne.people.si.umich.edu/vastmachine/llnl-lam.html][model's characteristics]] as:

#+begin_quote
The initial model was based on the Bjerknes/Richardson primitive
equations. It had five vertical levels and used a 5° x 5° horizontal
grid. It covered only the northern hemisphere, with a "slippery wall" at
60°N. In order to damp the effects of small-scale atmospheric waves,
Leith introduced an artificially high viscosity, which caused serious
problems and stimulated Leith's career-long interest in turbulence
problems.
#+end_quote

Although this model began around 1960, the first unclassified
publication appears in 1965, when Leith abandoned the project. But
Leith's influence was felt in talks and presentations at conferences,
where his visualization techniques were adopted by the field.

- C.E. Leith,\\
  "Numerical Simulation of the Earth's Atmosphere".
  In {{{book-title(Methods in Computational Physics)}}},
  eds. B. Alder, S. Fernbach, and M. Rotenberg
  (New York: Academic Press, 1965), 1--28.
- [[https://pne.people.si.umich.edu/vastmachine/llnl-lam.html][Characteristics]]


*** The National Center for Atmospheric Research (1964--????)

There are two families of models NCAR produced. One used finite
difference schemes (generically referred to as NCAR family of models),
the other used spectral schemes (the Community Climate Model Series, CCM).

**** NCAR 1 (1964--1967?)

A simple 2-layer atmosphere global model with 5-degree horizontal
resolution. Although they began working on the model in 1964, the first
publication on it appeared in 1967.

- A. Kasahara and W.M. Washington,\\
  "NCAR Global General Circulation Model of the Atmosphere".\\
  /Monthly Weather Review/ *95*, no.7 (1967) pp.389--402.

**** NCAR 2 (1967?--1970)

he basic model had a 5° horizontal, 6-layer resolution, but it could
also be run at resolutions as fine as 0.625° horizontal over a limited
domain, with up to 24 vertical layers.

- J.E. Oliger /et al/.,\\
  "Description of NCAR Global Circulation Model".
  National Center for Atmospheric Research, 1970
- A. Kasahara and W. M. Washington,\\
  "General Circulation Experiments with a Six-Layer NCAR Model, Including Orography, Cloudiness and Surface Temperature Calculations".\\
  /Journal of the Atmospheric Sciences/ *28*, no. 5 (1971) pp.657--701;
- A. Kasahara /et al/.,\\
  "Simulation Experiments with a 12-Layer Stratospheric Global Circulation Model. I. Dynamical Effect of the Earth's Orography and Thermal  Influence of Continentality".\\
  /Journal of Atmospheric Sciences/ *30*, no.7 (1973) pp.1229--51.

**** NCAR 3 (1970?--1973)

NCAR 3, finished about 1973, also allowed multiple resolutions,
including a user-specifiable vertical increment. The most significant
changes, however, involved improved finite-difference schemes.
 
- W.M. Washington /et al/.,\\
  "Preliminary Atmospheric Simulation with the Third-Generation NCAR General Circulation Model: January and July".\\
  In /Report of the JOC Conference on Climate Models: Performance, Intercomparison, and Sensitivity Studies/,
  (ed. W. Lawrence), WMO/ICSU Joint Organizing Committee and Global Atmospheric Research Programme, 1979. 


**** CCM-0A (197?--1977?)

The initial version of the Community Climate Model was based on the
spectral model of the Australian Numerical Meteorological Research
Centre. One member of the ANMRC team (K. Puri) brought the model to NCAR
during an extended visit. Later, it was extensively revised.

- W. Bourke /et al/.,\\
  "Global Modeling of Atmospheric Flow by Spectral Methods".\\
  In /General Circulation Models of the Atmosphere/,
  Methods in Computational Physics: Advances in Research and Applications
  (San Francisco: Academic Press, 1977), pp.267--324.

**** CCM-0B (1981--198?)

Initial code for CCM-0B came from an early version of the European
Center for Medium Range Weather Forecasts model. Physical
parameterizations, including the radiation and cloud routines of
Ramanathan, and numerical approximations were added from CCM-0A.
Energy balance and flux prescriptions from the early GFDL models were
incorporated, while the finite difference scheme was derived from the
Australian spectral model that was the basis for CCM-0A.

- V. Ramanathan /et al/.,\\
  "The Response of a Spectral General Circulation Model to Refinements in Radiative Processes".\\
  /Journal of Atmospheric Sciences/ *40* (1983) pp.605--630.

**** CCM-1 (1987?--????)

CCM-1 evolved from CCM-0B in the mid-1980s. The primary differences were
changed parameterizations, new horizontal and vertical diffusion
schemes, and changes to moisture adjustment and condensation schemes.


- D.L. Williamson /et al/.,\\
  "Description of NCAR Community Climate Model (CCM1)".
  (National Center for Atmospheric Reasearch, 1987).


** Australian  Numerical  Meteorological  Research  Centre [ANMRC] (1977)
:PROPERTIES:
:CUSTOM_ID: h-1a943d30-650d-4ad9-819b-620b7af5f6ea
:END:

Innovative use of spectral methods, which inspired NCAR's CCM-0A model.

- Bourke, W.P., B. McAvaney, K. Puri, and R. Thurling, 1977:\\
  "Global modelling of atmospheric flow by spectral methods".\\
  In {{{book-title(Methods in Computational Physics)}}}, 17, J. Chang (ed.), Academic Press, New York,
  267--324.
- McAvaney, B.J., W. Bourke, and K. Puri,\\
  "A global spectral model for simulation of the general circulation".\\
  /J. Atmos. Sci./ *35* (1978) 1557--1583.
