#+TITLE: Exercises
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-06T11:18:10-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday March  6, 2021 at 11:18AM

* Advanced Integrals

** Anastasios' Exercises
Taken from [[https://www.mathematica.gr/forum/viewtopic.php?f=9&t=7842&sid=d0eea48a8810d3fb029855a8b594ceca][mathematica.gr]],

#+begin_exercise
Computer $\displaystyle \int^{1/2}_{0}\frac{\ln(1-x)\ln(x)}{x(1-x)}\D x$
([[https://www.mathematica.gr/forum/viewtopic.php?f=9&t=7842&sid=d0eea48a8810d3fb029855a8b594ceca#p43790][Anastasios]]).
#+end_exercise

#+begin_exercise
Let $p$ be a positive real, $n\in\NN_{0}$. Compute
$\displaystyle\int^{\infty}_{0}\frac{\sin^{n}(x)}{\E^{px}}\D x$.
#+end_exercise

#+begin_exercise
Let $m\in\NN_{0}$. Compute
$\displaystyle \int^{\infty}_{0}x^{m}\E^{-x}\sin(x)\,\D x$.
#+end_exercise

#+begin_exercise
Let $a > b > 0$. Compute
$\displaystyle\int^{\infty}_{0}\frac{\E^{ax}-\E^{bx}}{x(\E^{ax}+1)(\E^{bx}+1)}\D x$.
#+end_exercise

# 5
#+begin_exercise
Let $n\in\NN$, $k=0,1,\dots,2n-2$. Define
\begin{equation}
I_{k} = \int^{\infty}_{0}\frac{x^{k}}{x^{2n}+x^{n}+1}\D x.
\end{equation}
Show $I_{k}\geq I_{n-1}$ for $k=0, 1,\dots, 2n-2$.
#+end_exercise

# 6
#+begin_exercise
Compute $\displaystyle\int^{1}_{0}\int^{1}_{0}\frac{1}{1-xy}\D x\,\D y$.
#+end_exercise

# 7
#+begin_exercise
Compute $\displaystyle\int^{1}_{0}\frac{\ln(x)\ln^{2}(1-x)}{x}\D x$.
#+end_exercise

# 8
#+begin_exercise
Let $k\in\NN$. Compute
$\displaystyle\int^{\infty}_{0}\frac{\sin(kx)\cos^{k}(x)}{x}\D x$.
#+end_exercise

# 9
#+begin_exercise
How does $\displaystyle \int^{\infty}_{0}\frac{1}{x+1}\D x$ converge or diverge?
#+end_exercise

# 10
#+begin_exercise
Prove $\displaystyle\int^{0}_{-1}\frac{\ln(1+t)}{t}\D t$ converges or diverges.
#+end_exercise

#+begin_exercise
Prove the following integral converges or diverges:
$\displaystyle \int^{\E}_{1}\frac{\D x}{x\sqrt{\ln(x)}}$
#+end_exercise

#+begin_exercise
For what $a,b\in\RR$ does the following integral converge:
$\displaystyle\int^{1}_{0}\frac{\D x}{x^{a}(-\ln(x))^{b}}$.
#+end_exercise

# 13
#+begin_exercise
1. Calculate
   $\displaystyle\int^{\infty}_{0}\frac{x^{a}}{(m+x^{b})^{c}}\D x$
   for $a > -1$, $b > 0$, $m > 0$, $c > (1 + a)/b$
2. Calculate
   $\displaystyle\int^{\infty}_{0}\E^{-a^{2}x^{2}}\cos(bx)\,\D x$
   where $ab\neq0$.
#+end_exercise

# 14
#+begin_exercise
Let $b>0$, $-\pi/2\lt\varphi\lt\pi/2$, compute
$\displaystyle\int^{\infty}_{0}\E^{-t\cos(\varphi)}t^{b-1}\sin(t\sin(\varphi))\,\D t$
#+end_exercise

# 15
#+begin_exercise
Let $b\gt 0$ and $-\pi/2\lt\varphi\lt\pi/2$, compute
$\displaystyle\int^{\infty}_{0}\E^{-t\cos(\varphi)}t^{b-1}\cos(t\sin(\varphi))\,\D t$
#+end_exercise

# 16
#+begin_exercise
Determine the convergence of
$\displaystyle\int^{\infty}_{0}\tan\left(\frac{x}{\sqrt{x^{2}+x^{3}}}\right)\frac{\ln(1+\sqrt{x})}{x}\D x$.
#+end_exercise

# 17
#+begin_exercise
Concerning Frullani integrals.
Let $a\gt b\gt0$, $f\colon[0,\infty)\to\RR$ be continuous such that

1. $\displaystyle\int^{\infty}_{1}\frac{f(t)}{t}\D t$ converges,
2. $f(x+T)=f(x)$ for some $T\gt 0$ and for all $x\geq0$
3. $\displaystyle\lim_{x\to+\infty}f(x)=\ell\in\RR$.

Then calculate $\displaystyle\int^{\infty}_{0}\frac{f(ax)-f(bx)}{x}\D x$.
#+end_exercise

# 18
#+begin_exercise
Calculate the following integrals:
1. $\displaystyle\int^{\infty}_{0}\frac{\sin(x)}{1 + x^{2}}\D x$
2. $\displaystyle\int^{\infty}_{0}\frac{\cos(x)}{1 + x^{2}}\D x$
#+end_exercise

# 19
#+begin_exercise
Determine the convergence of $\displaystyle\int^{\infty}_{0}\frac{\D x}{1+x^{2}\sin^{2}(x)}$.
#+end_exercise

# 20
#+begin_exercise
Recall $\displaystyle\operatorname{erf}(x) = \frac{2}{\sqrt{\pi}}\int^{x}_{0}\E^{-t^{2}}\,\D t$.
Compute $\displaystyle\int^{\infty}_{0}\operatorname{erf}^{2}(\sqrt{x})\E^{-x}\,\D x$.
#+end_exercise

# 21
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{x^{2}}{2x^{4} + 5x^{2} + 2}\D x$.
#+end_exercise

# 22
#+begin_exercise
Compute $\displaystyle\int^{\infty}_{0}\left(\frac{x}{\E^{x}-\E^{-x}}-\frac{1}{2}\right)\frac{1}{x^{2}}\D x$.
#+end_exercise

# 23
#+begin_exercise
Calculate $\displaystyle\int^{\infty}_{-\infty}\E^{\I kx}\frac{1 - \E^{x}}{\E^{x} + 1}\D x$.
#+end_exercise

# 24
#+begin_exercise
Let $k\in\RR$, calculate
$\displaystyle\int^{\pi/2}_{0}\cos\bigl(k\cdot\ln(\tan(x))\bigr)\,\D x$.
#+end_exercise

# 25
#+begin_exercise
Let $n\in\NN$, calculate
$\displaystyle\int^{\infty}_{0}x^{n}\sin(\sqrt[4]{x})\E^{-\sqrt[4]{x}}\D x$.
#+end_exercise

# 26
#+begin_exercise
Calculate
$\displaystyle\int^{\pi/2}_{0}x\ln(\tan(x))\,\D x$.
#+end_exercise

# 27
#+begin_exercise
Calculate
$\displaystyle\int^{\pi/2}_{0}\ln^{2}(\cos(x))\,\D x$.
#+end_exercise

# 28
#+begin_exercise
Let $|a|\lt 1$. Compute
$\displaystyle\int^{\pi/2}_{0}\frac{\tan^{-1}(a\sin(x))}{\sin(x)}\D x$.
#+end_exercise

# 29
#+begin_exercise
Calculate
$\displaystyle\int^{1}_{0}\frac{\sqrt{1-x^{2}}}{1 - x^{2}\sin^{2}(x)}\D x$.
#+end_exercise

# 30
#+begin_exercise
Let $m\in\RR$ and $-1\lt a\lt 1$, compute
$\displaystyle\int^{2\pi}_{0}\frac{\E^{m\cos(\theta)}\bigl(\cos(m\sin(\theta))-a\sin(m\sin(\theta)+\theta)\bigr)}{1-2a\sin(\theta)+a^{2}}\D\theta$.
#+end_exercise

# 31
#+begin_exercise
For $0\lt a\lt\pi/2$, calculate
$\displaystyle\int^{\infty}_{-\infty}\frac{\tan^{-1}(x)}{x^{2} - 2x\sin(a)+1}\D x$.
#+end_exercise

# 32 - original, provie integral is \pi/4
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{\sin(x)}{x\E^{x}}\D x$.
#+end_exercise

# 33 - original, prove integral is \pi^{2}/8
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\int^{\infty}_{0}\int^{\infty}_{0}\frac{\D x\,\D y\,\D z}{(x^{1} + y^{2} + z^{2} + 1)^{2}}$.
#+end_exercise

# 34 - original, prove integral is (2\pi/81)(\pi - 3\sqrt{3})
#+begin_exercise
Compute
$\displaystyle\int^{\infty}_{0}\frac{x\ln(x)}{(1 + x^{2})(1 + x^{3})^{2}}\D x$.
#+end_exercise

# 35
#+begin_exercise
Evaluate
$\displaystyle\int^{\infty}_{0}\frac{\sqrt{x}\ln(x)}{1 + x^{2}}\D x$.
#+end_exercise

# 36
#+begin_exercise
Let $a_{1},\dots, a_{n}, b_{1},\dots, b_{m}, b\in\RR$ such that
\begin{equation}
b\gt\sum^{n}_{i=1}|a_{i}| + \sum^{m}_{j=1}|b_{j}|
\end{equation}
Calculate
$\displaystyle\int^{\infty}_{0}\left(\prod^{n}_{i=1}\frac{\sin(a_{i}x)}{x}\right)\left(\prod^{m}_{j=1}\cos(b_{j}x)\right)\frac{\sin(bx)}{x}\D x$.
#+end_exercise

# 37 - prove it is \gamma/2
#+begin_exercise
Compute $\displaystyle\int^{\infty}_{0}\frac{\cos(x^{2})-\cos(x)}{x}\D x$.
#+end_exercise

# 38
#+begin_exercise
Prove or find a counter-example
\begin{equation}
\int^{\infty}_{0}\frac{(1 + z)^{-n}}{\log^{2}(z) + \pi^{2}}\D z
  = (-1)^{n-1}\int^{1}_{0}\binom{t}{n}\, \D t
\end{equation}
where $n\in\NN$, and
$$ \binom{t}{n} = \frac{t(t-1)(\dots)(t - n + 1)}{n!} $$
#+end_exercise

# 39
#+begin_exercise
Compute
$\displaystyle\int^{\infty}_{-\infty}\frac{x\sin(x)}{x^{2}+4x+20}\D x$.
#+end_exercise

# 40
#+begin_exercise
Let $\lambda\in\RR$, compute
$\displaystyle\int^{\infty}_{0}\frac{4\cos(\lambda x)}{\E^{x} + \E^{-x}}\D x$.
#+end_exercise

# 41
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{-\infty}\frac{\E^{-\I x}}{x^{2}-2x+4}\D x$.
#+end_exercise

# 42, prove it is (1/2) \pi/(3\sqrt{3})
#+begin_exercise
Compute
$\displaystyle\int^{\infty}_{0}\frac{x}{(x^{2}+1)(x^{4}+x^{2}+1)}\D x$.
#+end_exercise

# 43, prove it's \pi/(2(1 + \sqrt{2}))
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{1}{(x^{4} + (1 + \sqrt{2})x^{2} + 1)(x^{100}-x^{98}+\dots+1)}\D x$.
#+end_exercise

# 44, prove it's (2n)!\sqrt{\pi}/(2^{2n+1}n!p^{n+1/2})
#+begin_exercise
Let $n\in\NN$ and $p\gt0$,
calculate
$\displaystyle\int^{\infty}_{0}x^{2n}\E^{-px^{2}}\,\D x$.
#+end_exercise

#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{-\infty}\left(1 + \frac{x^{2}}{n-1}\right)^{-n/2}\D x$.
#+end_exercise

# 46, it's 11\pi\zeta(4)/16
#+begin_exercise
Calculate
$\displaystyle\int^{\pi/2}_{0}x^{2}\ln^{2}(2\cos(x))\,\D x$.
#+end_exercise

# 47
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{x^{2}}{x^{4} + 30x^{2} + 1}\D x$.
#+end_exercise

# 48, \frac{(2a + 3)\pi}{2^{7/2}(a + 1)^{3/2}}
#+begin_exercise
Compute
$\displaystyle\int^{\infty}_{0}\frac{1}{(x^{4} + 2ax^{2} + 1)^{2}}\D x$.
#+end_exercise

# 49, \frac{14!}{2(16!)5^{15}49^{2}}
#+begin_exercise
Evaluate
$\displaystyle\int^{\infty}_{0}\frac{x^{29}}{(5x^{2}+49)^{17}}\D x$.
#+end_exercise

# 50, \frac{5(60 + 7\sqrt{3}\ln(7 - 4\sqrt{3}))}{20736}
#+begin_exercise
Evaluate
$\displaystyle\int^{\infty}_{0}\frac{3x^{3}}{(x^{4} + 4x^{2}+1)^{5}}\D x$.
#+end_exercise

# 51
#+begin_exercise
$\displaystyle\int^{\pi/2}_{0}\ln(\cos(x))\ln(\sin(x))\sin(2x)\,\D x$.
#+end_exercise

# 52
#+begin_exercise
$\displaystyle\int^{1}_{0}\frac{\ln(x)}{x^{2}-x-1}\D x$.
#+end_exercise

# 53
#+begin_exercise
Prove, if $a\in\CC$ is such that $0\lt|\operatorname{Im}(a)|<2\pi$,
then
$\displaystyle\int^{\infty}_{0}\frac{\sin(ax)}{\exp(2\pi x)-1}\D x=\frac{-1}{2a^{2}}+\frac{1}{4}\frac{\E^{a}+1}{\E^{a}-1}$.
#+end_exercise

# 54
#+begin_exercise
Let $\lambda\in\RR$, calculate
$\displaystyle\int^{\infty}_{-\infty}x\E^{-\lambda x^{2}}\,\D x$.
#+end_exercise

# 55
#+begin_exercise
Prove
$2\sqrt{2}\log(1 + \sqrt{2}) = \displaystyle\int^{\infty}_{-\infty}\int^{\infty}_{-\infty}\operatorname{sgn}(x)\operatorname{sgn}(y)\E^{-(x^{2}+y^{2})/2}\sin(xy)\,\D x\,\D y$
where
$$ \operatorname{sgn}(x) = \begin{cases} 1, & x\gt0\\ 0, & x=0\\ -1, & x\lt0\end{cases} $$
#+end_exercise

# 56
#+begin_exercise
Compute
$\displaystyle\int^{\infty}_{0}\frac{\cos(t^{2}) - \sin(t^{2})}{1 + t^{4}}\D t$.
#+end_exercise

# 57
#+begin_exercise
Let $a\gt 0$, compute
$\displaystyle\int^{\infty}_{-\infty}\frac{\cos(x)-1}{x^{2}(x^{2}+a)}\D x$.
#+end_exercise

# 58
#+begin_exercise
Prove
\begin{equation}
\int^{\infty}_{0}\prod^{\infty}_{n=1}\frac{1 + \left(\frac{x}{b+n}\right)^{2}}{1 + \left(\frac{x}{a+n-1}\right)^{2}}\D x
= \frac{\sqrt{\pi}}{2}\frac{\Gamma(a + 1/2)}{\Gamma(a)}\frac{\Gamma(b+1)}{\Gamma(b + 1/2)}\frac{\Gamma(b-a+1/2)}{\Gamma(b-a+1)}
\end{equation}
#+end_exercise

# 59
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{\E^{-ax^{2}}-1}{x^{2}}\D x$
and determine where it converges.
#+end_exercise

# 60
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{-\infty}\frac{(3x+1)\sin(ax)}{9x^{2}+6x+10}\D x$
and determine where it converges.
#+end_exercise

# 61
#+begin_exercise
Calculate
$\displaystyle\int^{\infty}_{0}\frac{\ln(2x)}{x^{2}+9}\D x$.
#+end_exercise

# 62
#+begin_exercise
Let $n\in\NN$ be greater than 1, calculate
$\displaystyle\int^{\infty}_{0}\frac{1}{x^{n}+1}\D x$.
#+end_exercise

# 63 https://www.mathematica.gr/forum/viewtopic.php?f=9&t=7842&start=120