#+TITLE: Integrals
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-06T08:48:16-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday March  6, 2021 at  8:48AM

* Methods of Computation
:PROPERTIES:
:CUSTOM_ID: h-01ccd6b3-7836-475f-975d-60efd14e4f98
:END:

The only way we can do integration analytically is from the fundamental
theorem of calculus.

#+begin_theorem
Let $f\colon[a,b]\to\RR$, and $F\colon[a,b]\to\RR$
differentiable such that $F'(x)=f(x)$ for each $x\in[a,b]$. Then
\begin{equation}
\int^{b}_{a}f(x)\,\D x = F(b)-F(a).
\end{equation}
#+end_theorem

#+begin_corollary
Let $f\colon[a,b]\to\RR$ be continuous and $F$ its antiderivative. Then
for any $x\in[a,b]$, we have
\begin{equation}
\frac{\D}{\D x}\int^{x}_{a}f(t)\,\D t = f(x).
\end{equation}
#+end_corollary

Now the two main methods of computing integrals may be deduced immediately.

** Method of Substitution
:PROPERTIES:
:CUSTOM_ID: h-628ead07-4911-4b0e-a5a5-0c3861211978
:END:

Let $\varphi$ be differentiable, $f$ some function. Then
\begin{equation}
\int f(\varphi(t))\varphi'(t)\,\D t
 = \int f(u)\,\D u.
\end{equation}
Definite integration similarly is defined
\begin{equation}
\int^{b}_{a} f(\varphi(t))\varphi'(t)\,\D t
 = \int^{\varphi(b)}_{\varphi(a)} f(u)\,\D u.
\end{equation}

The heuristic is $\D u = \varphi'(t)\,\D t$, and the boundary of
integration is determined by $\varphi([a,b])$.

** Integration by Parts
:PROPERTIES:
:CUSTOM_ID: h-5fde8826-ac10-4c10-b723-7b0ca78ebd7e
:END:

#+begin_theorem
Let $f,g\colon[a,b]\to\RR$ be such that $g$ is differentiable on $[a,b]$
whose first derivative is integrable, and $f$ differentiable on $[a,b]$
(possibly with at most countably many discontinuities), then
\begin{equation}
\int^{b}_{a}f(x)g'(x)\,\D x = f(b)g(b)-f(a)g(a)-\int^{b}_{a}f'(x)g(x)\,\D x.
\end{equation}
#+end_theorem

#+begin_proof
This may be obtained by the fundamental theorem of calculus applied to
the product rule:
\begin{equation}
\int^{b}_{a}\frac{\D}{\D x}\bigl(f(x)g(x)\bigr)\D x = f(b)g(b)-f(a)g(a)
\end{equation}
and expanding the left-hand side using the product rule
\begin{equation}
\int^{b}_{a}\frac{\D}{\D x}\bigl(f(x)g(x)\bigr)\D x
 = \int^{b}_{a}f'(x)g(x)\,\D x + \int^{b}_{a}f(x)g'(x)\,\D x.
\end{equation}
Setting these two equal give us
\begin{equation}
\int^{b}_{a}f'(x)g(x)\,\D x + \int^{b}_{a}f(x)g'(x)\,\D x
 = f(b)g(b)-f(a)g(a).
\end{equation}
The result follows immediately.
#+end_proof

#+begin_theorem
Let $f,g\colon\RR\to\RR$ be "sufficiently nice" functions. Then
for indefinite integrals, we have
\begin{equation}
\int f(x)g'(x)\,\D x = f(x)g(x) - \int f'(x)g(x)\,\D x.
\end{equation}
#+end_theorem

* Tricks
:PROPERTIES:
:CUSTOM_ID: h-f76fbe31-426f-4a0e-b0df-1ce5970e7f45
:END:

#+begin_theorem
Let $a>0$ and $f\colon[-a,a]\to\RR$ be continuous. If $f$ is even, then
\begin{equation}
\int^{a}_{-a}\frac{f(x)}{1 + \E^{x}}\D x = \int^{a}_{0}f(x)\,\D x.
\end{equation}
#+end_theorem

(I first saw this on [[https://math.stackexchange.com/q/60045][math.SX]])

#+begin_proof
Only the even part survives, so
\begin{equation}
h(x) = \frac{1}{2}\left(\frac{f(x)}{1 + \E^{x}} + \frac{f(-x)}{1 + \E^{-x}}\right)
\end{equation}
But we see
\begin{equation}
\frac{1}{1+\E^{x}} + \frac{1}{1+\E^{-x}} = \frac{2 + \E^{x} +
\E^{-x}}{1 + \E^{x} + \E^{-x} + 1} = 1
\end{equation}
hence
\begin{equation}
h(x) = \frac{1}{2}(f(x) + f(-x)) = f(x).
\end{equation}
So the integral becomes
\begin{equation}
2\int^{a}_{0}h(x)\,\D x = 2\int^{a}_{0}f(x)\,\D x
\end{equation}
as desired.
#+end_proof

#+begin_remark
There was nothing special about using $(1 + \E^{x})$, we could use any
$(1 + c^{x})$ for positive real number $c\gt0$.
#+end_remark

** Weierstrass Substitution
:PROPERTIES:
:CUSTOM_ID: h-3ff44236-6302-4e93-ab80-e4d4a5b42fa1
:END:

Take $t = \tan(\theta/2)$, then

\begin{equation}
\sin(\theta)=\frac{2t}{1+t^{2}},\quad\cos(\theta)=\frac{1-t^{2}}{1+t^{2}}
\end{equation}

and in particular

\begin{equation}
\D\theta = \frac{2\,\D t}{1 + t^{2}}.
\end{equation}

* References
:PROPERTIES:
:CUSTOM_ID: h-ee4b1d68-eddc-4480-97b0-cec462ccbcb0
:END:

- Michael Dougherty,
  [[https://web.archive.org/web/20180127095831/http://faculty.swosu.edu/michael.dougherty/book/chapter07.pdf][Advanced Integration Techniques]], 76 pages.
- Victor Moll's [[http://dauns01.math.tulane.edu/~vhm/pap-scientia.html][papers]] about the proofs of Gradshteyn and Ryzhik
- Keith Conrad,
  [[https://web.archive.org/web/20140514090620/https://www.warwickmaths.org/files/gamma.pdf][The Gamma Function]].

** Treatises
:PROPERTIES:
:CUSTOM_ID: h-a510c87d-98a4-4465-838b-c83136b85402
:END:

- Joseph Edward,
  {{{book-title( A treatise on the integral calculus; with applications, examples and problems)}}}.
  [[https://archive.org/details/treatiseonintegr01edwauoft][vol 1]], [[https://archive.org/details/treatiseonintegr02edwauoft][vol 2]] 1921--1922.
# pg 52 of pdf for vol 1