#+TITLE: Finite Difference Schemes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-04-03T15:38:25-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday April  3, 2021 at  3:38PM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-6234d0d8-1e6d-450f-9339-48607d4807b8
:END:

The basic idea of finite difference schemes to numerically approximate
PDEs is to take your PDE, then transform the partial derivatives into
finite differences of the exact solution by Taylor expanding, and then
replace the Taylor expanded terms by the numerical approximations. I'm a
little sloppy here, but we should also prove /consistency/ (in the sense
that as the finite differences $\Delta x\to 0$, $\Delta y\to 0$, etc.,
we recover the exact solution from the numerical approximation).

We should check for stability (possibly comparing results from implicit
methods like [[https://en.wikipedia.org/wiki/Backward_Euler_method][backward Euler]]).

* Instabilities
:PROPERTIES:
:CUSTOM_ID: h-25c0e29d-9129-4c34-83bc-0612c00dcaea
:END:

For instabilities arising from finite differences, see Rouson and
friends "A grid-free abstraction of the Navier-Stokes equation" (2008)
wherein are "provided a more subtle example inwhich information that
appeared to have been lost during the discretization process was
actually missing from the original PDE."

After reading the paper carefully, it seems Rousson and friends do the
following:

1. Review a version of the incompressible Navier-Stokes
   equation. Specifically, one which reduces down to 2 equations in 2
   unknowns. 
2. Consider the Fourier spectral method for numerical analysis.
3. Show the equations from step 1 have problems at wavelength $\vec{k}=0$,
   which reflects a loss of information.
4. *Assert* this loss of information occurs in every consistent scheme.

* References
:PROPERTIES:
:CUSTOM_ID: h-e0b472f5-872d-4956-8089-71b3dea060da
:END:

- DWI Rouson, R Rosenberg, X Xu, I Moulitsas, and SC Kassinos,\\
  "A grid-free abstraction of the Navier-Stokes equation in FORTRAN
  95/2003."\\
  /ACM Transactions on Mathematical Software/ *34*, 1 (2008) 33 pages.
  {{{doi(10.1145/1322436.1322438)}}}
- J.W. Thomas,\\
  {{{book-title(Numerical Partial Differential Equations: Finite Difference Methods)}}}.\\
  Springer, 1995.
- Douglas Arnold,\\
  "Stability, consistency, and convergence of numerical
  discretizations".\\
  Notes, 9 pages [[https://www-users.cse.umn.edu/%7Earnold//papers/stability.pdf][PDF]]
- Eitan Tadmor,\\
  "A review of numerical methods for nonlinear partial differential equations".\\
  Bulletin of the AMS *49* no.4 (2012) 48 pages, [[https://www.ams.org/journals/bull/2012-49-04/S0273-0979-2012-01379-4/S0273-0979-2012-01379-4.pdf][PDF]]
- Gilbert Strang,
  "Accurate partial difference methods".
  Two parter, I can't find free LEGAL PDFs anywhere.


