#+TITLE: HOL
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-02-18T11:58:29-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Friday February 18, 2022 at 11:58AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-070367d6-dc23-4abb-99a3-759d21627cb2
:END:

Broadly, HOL refers to a /family/ of theorem provers which emerged out
of LCF, using similar techniques applied to higher-order logic as Church
presented it in his article on simple-type theory.

It turns out HOL is a metalogical framework. One way to encode inductive
datatypes, for example, may be found in John Harrison's [[https://www.cl.cam.ac.uk/~jrh13/hol-light/tutorial.pdf][tutorial]] on HOL
Light in section 15.

* References
:PROPERTIES:
:CUSTOM_ID: h-ab06ccd5-6dec-499e-a5e3-88c804c83a10
:END:

- Mike Gordon,\\
  "HOL: A Machine Oriented Formulation of Higher Order Logic".\\
  [[https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-68.pdf][Tech Report 68]], Cambridge University, July 1985.
- Thomas F. Melham,\\
  "Automating Recursive Type Definitions in Higher Order Logic".\\
  In /Current Trends in Hardware Verification and Automated Theorem Proving/,
  edited by G. Birtwistle and P. A. Subrahmanyam
  (Springer-Verlag, 1989), pp. 341--386. [[http://www.cs.ox.ac.uk/tom.melham/pub/Melham-1989-ART.pdf][PDF]]
- M. J. C. Gordon and T. F. Melham,\\
  /Introduction to HOL: A theorem proving environment for higher order logic/.\\
  Cambridge University Press, 1993.
- Anthony Bordg, Lawrence Paulson, Wenda Li,\\
  "Simple Type Theory is not too Simple: Grothendieck's Schemes without Dependent Types".\\
  {{{arXiv(2104.09366)}}}, 31 pages

** Simple Type Theory
:PROPERTIES:
:CUSTOM_ID: h-68cf3a82-20c7-4098-9569-0f57892faa7b
:END:

- Lawrence Paulson,\\
  "A Formulation of the Simple Theory of Types (for Isabelle)".\\
  Tech. Rept. UCAM-CL-TR-175, dated 2 August 1989, [[https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-175.pdf][eprint]]; 32 pages.
- [[https://plato.stanford.edu/entries/type-theory-church/][Church’s Type Theory]], entry in Stanford Encyclopedia of Philosophy
- Alanzo Church,\\
  "A Formulation of the Simple Theory of Types".\\
  /The Journal of Symbolic Logic/ *5*, no.2 (1940) 56–68.
  [[https://www.jstor.org/stable/2266170][JSTOR]].