#+TITLE: Isabelle
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-01-27T10:26:50-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Thursday January 27, 2022 at 10:26AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-339b8860-4143-4c7a-b833-ceffc14b673a
:END:

Isabelle is a +metalogical+ [[file:logical-framework.org][logical framework]] (but Isabelle/HOL /is/ a
metalogical framework, which is a logical framework that allows us to prove results
about deductive systems; this is because HOL is a metalogical framework).
Recall, logical frameworks reason within deductive systems. Isabelle is
a bit like a tool to create proof assistants, which is why we often see
things like ~Isabelle/X~ for various choices of ~X~.

* Earley Parsing
:PROPERTIES:
:CUSTOM_ID: h-5fd08e66-0648-4579-bdcd-5331dfabc3a8
:END:

The "object logic" is parsed using an Earley parser, as noted in the
section "Parsing and unparsing" of [[https://www.cl.cam.ac.uk/research/hvg/Isabelle/dist/library/Doc/Implementation/Syntax.html][Documentation about Syntax]]
(Chapter 3 of the [[https://www.cl.cam.ac.uk/research/hvg/Isabelle/dist/library/Doc/Implementation/implementation.pdf][PDF]] version of the documentation):

#+begin_quote
Actual parsing is based on traditional lexical analysis and Earley parsing
for arbitrary context-free grammars.
#+end_quote

I always wondered if the rumours were true about Isabelle using an
Earley parser, now we know.

* References
:PROPERTIES:
:CUSTOM_ID: h-b085c5b8-be9c-4578-b7b6-828c11924bf6
:END:

** Early Papers
:PROPERTIES:
:CUSTOM_ID: h-afac14c8-4dde-4cc2-b55f-a266832367a7
:END:

- Lawrence Paulson,\\
  "The Foundation of a Generic Theorem Prover".\\
  {{{arXiv(cs/9301105)}}}, 37 pages.
  - Introduces Isabelle/Pure as a fragment of intuitionistic higher-order logic.
- Lawrence Paulson,\\
  "Isabelle: The Next 700 Theorem Provers".\\
  {{{arXiv(cs/9301106)}}}
- Lawrence Paulson,\\
  "Natural Deduction as Higher-Order Resolution".\\
  {{{arXiv(cs/9301104)}}}

** Set Theory in Isabelle
:PROPERTIES:
:CUSTOM_ID: h-a0bc1fc1-f37d-454e-a07c-f843bac1cabb
:END:

- Florian Rabe and Mihnea Iancu,\\
  "A Formalized Set-Theoretical Semantics of Isabelle/HOL".\\
  [[https://kwarc.info/people/frabe/Research/RI_isabelle_10.pdf][PDF]], 20 pages
- Bohua Zhan,\\
  "Formalization of the fundamental group in untyped set theory using auto2".\\
  {{{arXiv(1707.04757)}}}, 17 pages.
  + One of the few formalizations using *both* /untyped/ set theory *and* Isabelle
