#+TITLE: Mizar
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-11-21T10:30:09-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Sunday November 21, 2021 at 10:30AM

* Useful Definitions
:PROPERTIES:
:CUSTOM_ID: h-6bd8d47a-d34f-4cfa-b541-e1cf3bcac9f7
:END:

- ~Element of X~ is defined in [[http://www.mizar.org/version/current/html/subset_1.html][~subset_1.miz~]] , lines 67 /et seq/.
- ~Subset of X~ is defined in [[http://www.mizar.org/version/current/html/subset_1.html][~subset_1.miz~]] (line 99), but it just means
  ~Element of bool X~; and ~bool X~ is defined in [[http://www.mizar.org/version/current/html/zfmisc_1.html][~zfmisc_1.miz~]]
  (line 71) as ~bool X -> set means Z in it iff Z c= X~ (and ~c=~ is the
  subset operator, defined in [[http://mizar.org/version/current/html/tarski.html][~tarski.miz~]], as we would expect its
  meaning $X\subseteq Y\iff (\forall x, x\in X\implies x\in Y)$)

** Group Theory
:PROPERTIES:
:CUSTOM_ID: h-9f5cf940-9a00-4b52-886d-f414fb02838d
:END:

- Nilpotent groups are discussed in  [[http://mizar.org/version/current/html/grnilp_1.html][~grnilp_1.miz~]]
- Solvable groups discussed in  [[http://mizar.org/version/current/html/grsolv_1.html][~grsolv_1.miz~]]
- Some Properties of $p$-Groups and Commutative $p$-Groups  [[http://mizar.org/version/current/html/groupp_1.html][~groupp_1.miz~]]
- Cayley's theorem proven in [[http://mizar.org/version/current/html/cayley.html][~cayley.miz~]]
  - Symmetric group on a set $X$ is defined on line 145 of [[http://mizar.org/version/current/html/cayley.html][~cayley.miz~]]
- A lot of properties proved in [[http://mizar.org/version/current/html/group_8.html][~group_8.miz~]]
- Jordon-Holder theorem in [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]]

*** Definitions
:PROPERTIES:
:CUSTOM_ID: h-9a4b3e2e-01b9-42a2-a500-bd576e9efca7
:END:
- Inverse operator is denoted by double quotes, so ~x"~ denotes $x^{-1}$
  as defined in [[http://mizar.org/version/current/html/group_1.html][~group_1.miz~]] line 210 (~func h" -> Element of G means h * it = 1_G & it * h = 1_G;~)
  - This is also extended to, for a group $G$, subsets $A\subset G$
    we'd have ~A"~ be the collection of ~g"~ for ~g in A~, i.e.,
    $A^{-1}=\{g^{-1}|g\in A\}$; see line 57 of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]
    #+begin_example
let G be Group;
let A be Subset of G;
func A " -> Subset of G equals :: GROUP_2:def 1
{ (g ") where g is Element of G : g in A } ;
    #+end_example
- the mode definition ~Subgroup of G~, line 853 of  [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]; for
  some reason, if $H\lt G$, then ~carr(H)~ is defined as the subset of the
  underlying set of $G$ equal to the set underlying $H$
- If $H_{1}\lt G$ and $H_{2}\lt G$, then $H_{1}\cap H_{2}$ is defined on line
  1563 of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]
- The trivial subgroup of $G$ is denoted ~(1).G~, defined on line 1258
  of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]] as
  #+begin_example
  func (1).G -> strict Subgroup of G means
  :Def7:
  the carrier of it = {1_G};
  #+end_example
  - "strict" is a weird meta-term (c.f., [[http://mizar.uwb.edu.pl/forum/archive/0701/msg00008.html][discussion]]),
    #+begin_quote
"strict" doesn't have its own definition as it is a special (in a way "meta" attribute) - it means that a term which has a structure type <Theta> has exactly the same selectors (fields) as introduced in the definition of the type <Theta>, so in your case only the selectors of a doubleLoopStr - any extension to that would break the "strictness". So you may think of a vector space as of a group, but it's not a "strict" group.
    #+end_quote
  - "strict" for subgroup is on line 1011 of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]; it's a
    registration of a cluster. I believe it refers to being a proper
    subgroup.

- ~(Omega).G~ (line of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]) seems to be the other trivial subgroup of $G$, i.e., $G$ itself
  - This seems to be following notation introduced in  [[http://mizar.org/version/current/html/rlsub_1.html][~rlsub_1.miz~]],
    line 764; a comment before it notes this notation is used for
    improper subspaces
- Left cosets are defined on line 2448 of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]] (right cosets
  are defined on line 2468)
- The index of a subgroup $H\lt G$ is defined as the cardinality of left
  cosets of $H$  on line 2789 of [[http://mizar.org/version/current/html/group_2.html][~group_2.miz~]]

- Conjugation of $a$ by $b$ (both elements of $G$) is denoted
  ~a |^ b~, defined on lines 299--300 of [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]]
  - This is extended to subsets $A$ and $B$ of $G$, ~A |^ B~ is the
    collection of conjugating elements of $A$ by elements of $B$
    ~func A |^ B -> Subset of G equals {g |^ h : g in A & h in B};~
  - We also have ~g |^ A~ and ~A |^ g~ for conjugating an element by
    members of a subset, and conjugating a subset by an element
- Conjugate subgroup to $H\lt G$ is defined lines 897 /et seq/ of
  [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]] as ~H |^ a~ (conjugate subgroup of a finite group is
  itself finite, as registration on line 1068 notes)
- ~a,b are_conjugated~ defined on line 1270 of [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]] if there is a $g\in G$ such
  that ~a = b |^ g~ (and two subsets are conjugated, defined on line
  1523; for two subgroups on line 1738)
- Conjugacy class of $a\in G$ is defined as the subset of $G$ given by
  ~a |^ carr (Omega).G~ around line 1367 of [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]] (and the
  conjugacy class of a subset of $G$ is defined around line 1615; the
  conjugacy class for a subgroup defined on line 1810)
  - ~conjugate_Classes G~ defined line 1131 of [[http://mizar.org/version/current/html/weddwit.html][~weddwit.miz~]]
- A normal subgroup is defined on line 1956 of [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]] as
  ~for a holds IT |^ a = the multMagma of IT~ and then it is registered
  as ~strict normal~
- The normalizer for a subset $A\subset G$ is defined on line 2419 of [[http://mizar.org/version/current/html/group_3.html][~group_3.miz~]]
  as ~func Normalizer A -> strict Subgroup of G means :Def14: the carrier of it = {h : A |^ h = A};~
  (normalizer of a subgroup is defined on line 2638)
- If $A$ is a subset of a group $G$, the ~gr A~ seems to be the smallest
  subgroup containing $A$
- Frattini subgroup is tricky. Relevant code starts around 1371 of  [[http://mizar.org/version/current/html/group_4.html][~group_4.miz~]]
  #+begin_example
::$N Frattini subgroup
  func Phi(G) -> strict Subgroup of G means
  :Def7:
  the carrier of it = meet{A
where A is Subset of G : ex H being strict Subgroup of G st A = the carrier of
H & H is maximal} if ex H being strict Subgroup of G st H is maximal otherwise
  it = the multMagma of G;
  #+end_example
- The notation $H_{1}\wedge H_{2}$ for the smallest group containing
  both $H_{1}$ and $H_{2}$ (defined line 1877 [[http://mizar.org/version/current/html/group_4.html][~group_4.miz~]]) it is given
  the name ~SubJoin~ on line 2636; dually, the submeet is defined on
  line 2680
- Lattice of subgroups defined line 2795 of [[http://mizar.org/version/current/html/group_4.html][~group_4.miz~]]
- Commutator of group elements line 331 of [[http://mizar.org/version/current/html/group_5.html][~group_5.miz~]]; ~commutators(A,B)~ for
  subsets of $G$ on line 964; ~commutators(H1,H2)~ of subgroups defined on line 1091;
  and ~commutators G~ is defined as the commutator of the underlying set
  of $G$ with itself
- A triple $[a,b,c]=[[a,b],c]$ line 662 of [[http://mizar.org/version/current/html/group_5.html][~group_5.miz~]]
- the smallest group containing ~commutators(A,B)~ is defined as ~[.A,B.]~
  on line 1262; and similarly for subgroups ~[.H1,H2.]~ defined on line 1297
- the derived group is define on line 1578 of [[http://mizar.org/version/current/html/group_5.html][~group_5.miz~]]
- the center of $G$ is defined on line 1775 of [[http://mizar.org/version/current/html/group_5.html][~group_5.miz~]]
  as a strict subgroup of $G$ consisting of ~{a : for b holds a * b = b * a};~
  - The Centralizer of an element $a\in G$ is defined line 739 of
    [[http://mizar.org/version/current/html/weddwit.html][~weddwit.miz~]]
  - The center for a skew-field $R$ is defined on line 1508 of [[http://mizar.org/version/current/html/weddwit.html][~weddwit.miz~,]]
    and the centralizer for an element of $R$ is defined on line 1978
- a group $G$ is "simple" if ~IT is not trivial~ and there is no
  nontrivial normal subgroup $H\triangleleft G$ (i.e., $H\neq 1$ and
  $H\neq G$) line 998 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]]
- The quotient group $G/N$ is denoted as ~G./.N~ in Mizar, and it is
  defined on line 1469 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]]; the canonical mapping of $N\to G/N$
  is defined on line 1759 as the ~nat_hom~
- Two groups $G$ and $H$ ~are_isomorphic~ if there exists a bijective
  group morphism between them (line 1693 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]])
- The kernel of a morphism of groups-with-operators is defined on line
  2137 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]]
- The chunk of text dealing with composition series begins on line 6701
  of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]] (the ~composition_series~ is defined on line 6708)
- The Jordan-Holder attribute for composition series of $G$
  (line 6821 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]])
- Equivalence of composition series is defined (line 6835 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]])
- Schreier refinement theorem begins (line 10378 of [[http://mizar.org/version/current/html/group_9.html][~group_9.miz~]]);
  ~the_schreier_series_of~ is defined 10383
- ~p-subgroup~ defined on line 1786 of [[http://mizar.org/version/current/html/group_10.html][~group_10.miz~]]
- ~is_Sylow_p-subgroup_of_prime~ defined line 2196 of [[http://mizar.org/version/current/html/group_10.html][~group_10.miz~]]
- ~the_sylow_p-subgroups_of_prime(p,G)~ defined line 3109 of [[http://mizar.org/version/current/html/group_10.html][~group_10.miz~]]

* Random
:PROPERTIES:
:CUSTOM_ID: h-19c0ab35-60e3-4d69-9ec4-9eb1bf8cef89
:END:
- Cayley-Dickson construction in [[http://mizar.org/version/current/html/cayldick.html][~cayldick.miz~]]


* Lessons Learned
:PROPERTIES:
:CUSTOM_ID: h-afdc709c-b5e8-4cb9-9cee-81984c7a3c09
:END:

** Vocabulary Files
:PROPERTIES:
:CUSTOM_ID: h-c0226382-31df-4572-891b-e9ae20a09b98
:END:

When defining new terms, well, we should get started by doing something
like:

#+begin_example
user@computer:~/$ mkdir -p work/first-article/
user@computer:~/$ cd work/first-article/
user@computer:~/work/first-article/$ mkdir DICT
user@computer:~/work/first-article/$ mkdir TEXT
user@computer:~/work/first-article/$ mkdir PREL
#+end_example

Now for a "Hello World" type Mizar file: just create a new predicate
~foobar~. We do this by creating ~first-article/DICT/TMP.voc~ and
sticking one line in it:

#+begin_example
Rfoobar
#+end_example

Then in ~first-article/TEXT/TMP.miz~ we would have:

#+begin_example
environ
vocabularies TMP; :: this is important! Without it, you get an error


begin

definition
  let a,b be set;
  pred a,b foobar means
  :Def1:
  a = b;
end;
#+end_example

Without the ~vocabularies TMP;~ line, you'll get a "301: Predicate
symbol expected" error, basically Mizar telling you that you forgot to
include ~foobar~ as a predicate in your vocabulary file.

* Installing on Raspberry Pi
:PROPERTIES:
:CUSTOM_ID: h-db11b193-c42a-415b-b960-c4efc7dacd50
:END:

This was surprisingly simple. I usually keep source code related stuff
in =~/src/=, so here's the bash commands that got me cooking:

#+begin_example
alex@pi:~$ cd src
alex@pi:~/src/$ mkdir mizar
alex@pi:~/src/$ cd mizar
alex@pi:~/src/mizar/$ wget http://mizar.uwb.edu.pl/~softadm/pub/system/arm-linux/mizar-8.1.09_5.59.1363-arm-linux.tar
alex@pi:~/src/mizar/$ tar -xvf mizar-8.1.09_5.59.1363-arm-linux.tar
README
install.sh
mizbin.tar.gz
mizdoc.tar.gz
mizshare.tar.gz

alex@pi:~/src/mizar$ ls

install.sh                            mizbin.tar.gz  mizshare.tar.gz
mizar-8.1.09_5.59.1363-arm-linux.tar  mizdoc.tar.gz  README

alex@pi:~/src/mizar$ sudo ./install.sh --default
...
#+end_example

Then I added one line of code to my =~/.bash_profile=:

#+begin_example
# at the end of ~/.bash_profile
MIZFILES=/usr/local/share/mizar
#+end_example

And, /voilà/, once we've =source ~/.bash_profile= we'll be able to start
proving in no time. Unfortunately, I still have problems trying to get
it working on my Raspberry Pi.

* References
:PROPERTIES:
:CUSTOM_ID: h-5b2a23b4-8625-4b20-a0b0-a13c66678638
:END:

- Freek Wiedijk's [[http://mizar.org/project/mizman.pdf][Write a Mizar Article in 9 Easy Steps]]
- Adam Grabowski, Artur Kornilowicz, and Adam Naumowicz,\\
  [[https://jfr.unibo.it/article/view/1980/1356][Mizar in a Nutshell]].
- [[https://math.stackexchange.com/a/2806593/31693][Getting to Know the Mizar Math Library]], math stackexchange thread,
  worth reading
  
  

  