#+TITLE: Category Theory
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-27T16:10:37-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday December 27, 2020 at  4:10PM

* "Overview"

I'm not going to pretend to talk about why category theory is useful.
I've written such notes before, it'd be a distraction to re-hash them now.
(It gives us a template to describe mathematical gadgets, basically.
This template itself is a mathematical gadget, so it can be used on
itself.)

Category theory exposes the magic underpinning relations like Monstrous
Moonshine, Galois theory, or the Langlands programme (and many many
more).

* Categorification

Categorification is the process of finding category theoretic
counterparts to classical mathematics. A seemingly dull example is how
finite sets are categorified natural numbers. When we consider formal
power series whose coefficients are particular natural numbers, the
categorified counterpart is Feynman diagrams.

* References

- Mac Lane's {{{book-title(Category Theory for the Working Mathematician)}}}
  is the standard text.

** Fun

- John Baez and Michael Shulman,
  [[https://math.ucr.edu/home/baez/cohomology.pdf][Lectures on n-Categories and Cohomology]].
- Theo Johnson-Freyd,
  "Spin, statistics, orientations, unitarity".
  [[https://arxiv.org/abs/1507.06297][arXiv:1507.06297]], offers a categorification of Galois theory.
  (See also [[http://categorified.net/handout-PI-oct2015.pdf][handout]])
- Deligne's "Categories Tensorielles"
  [[http://categorified.net/Deligne-CategoriesTensorielles-English.pdf][English translation]] also discusses categorified Galois theory.