#+TITLE: Category Theory
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-27T16:10:37-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday December 27, 2020 at  4:10PM

* "Overview"

I'm not going to pretend to talk about why category theory is useful.
I've written such notes before, it'd be a distraction to re-hash them now.
(It gives us a template to describe mathematical gadgets, basically.
This template itself is a mathematical gadget, so it can be used on
itself.)

Category theory exposes the magic underpinning relations like Monstrous
Moonshine, Galois theory, or the Langlands programme (and many many
more).

* Categorification

Categorification is the process of finding category theoretic
counterparts to classical mathematics. A seemingly dull example is how
finite sets are categorified natural numbers. When we consider formal
power series whose coefficients are particular natural numbers, the
categorified counterpart is Feynman diagrams.

* References

- Mac Lane's {{{book-title(Category Theory for the Working Mathematician)}}}
  is the standard text.
- Jiří Adámek, Horst Herrlich, George Strecker,
  [[http://www.tac.mta.ca/tac/reprints/articles/17/tr17abs.html][Abstract and Concrete Categories: The Joy of Cats]]
  ([[http://katmat.math.uni-bremen.de/acc/acc.pdf][PDF]]), a free ebook, pretty good...but it's no Mac Lane.

** Examples of Categorification

- John Baez and Michael Shulman,
  [[https://math.ucr.edu/home/baez/cohomology.pdf][Lectures on n-Categories and Cohomology]].
- Theo Johnson-Freyd,
  "Spin, statistics, orientations, unitarity".
  [[https://arxiv.org/abs/1507.06297][arXiv:1507.06297]], offers a categorification of Galois theory.
  (See also [[http://categorified.net/handout-PI-oct2015.pdf][handout]])
- Deligne's "Categories Tensorielles"
  [[http://categorified.net/Deligne-CategoriesTensorielles-English.pdf][English translation]] also discusses categorified Galois theory.
- Mikhail Khovanov, "Heisenberg algebra and a graphical calculus."
  Eprint: [[https://arxiv.org/abs/1009.3295][arXiv:1009.3295]] [math.RT], 45 pages.
- Mikhail Khovanov, Radmila Sazdanovic,
  "Categorification of the polynomial ring."
  Eprint: [[https://arxiv.org/abs/1101.0293][arXiv:1101.0293]] [math.QA], 29 pages.
- Alexander Kirillov Jr,
  "On the modular functor associated with a finite group."
  Eprint: [[https://arxiv.org/abs/math/0310087][arXiv:math/0310087]] [math.QA], 7 pages.
- Ingo Runkel, Jurgen Fuchs, Christoph Schweigert,
  "Categorification and correlation functions in conformal field theory."
  Eprint: [[https://arxiv.org/abs/math/0602079][arXiv:math/0602079]] [math.CT], 16 pages.
  _International Congress of Mathematicians._ Vol. III, pages 443–458, Eur. Math. Soc., Zürich, 2006.
- Jeffrey C. Morton,
  "2-Vector Spaces and Groupoids".
  [[https://arxiv.org/abs/0810.2361][arXiv:0810.2361]], 44 pages.

** Higher Category Theory

- Tom Leinster,
  "A Survey of Definitions of n-Category."
  Eprint: [[https://arxiv.org/abs/math/0107188][arXiv:math/0107188]] [math.CT], 67 pages.
  [[https://www.emis.de/journals/TAC/volumes/10/1/10-01abs.html][Theory Appl. Categ.]] **10** (2002), 1–70.
