#+TITLE: Category Theory
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-27T16:10:37-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday December 27, 2020 at  4:10PM

* "Overview"
:PROPERTIES:
:CUSTOM_ID: h-e5f7360b-fb8e-42d5-81c1-09ebe76adfed
:END:

I'm not going to pretend to talk about why category theory is useful.
I've written such notes before, it'd be a distraction to re-hash them now.
(It gives us a template to describe mathematical gadgets, basically.
This template itself is a mathematical gadget, so it can be used on
itself.)

Category theory exposes the magic underpinning relations like Monstrous
Moonshine, Galois theory, or the Langlands programme (and many many
more).

* Categorification
:PROPERTIES:
:CUSTOM_ID: h-635e48a8-14c9-4acd-80c7-042dac344386
:END:

Categorification is the process of finding category theoretic
counterparts to classical mathematics. It's defined by
/decategorification/ reproducing a given mathematical gadget.

A seemingly dull example is how finite sets are categorified natural
numbers. When we consider formal power series whose coefficients are
particular natural numbers, the categorified counterpart is Feynman
diagrams.

This can be related to the process of [[file:category-theory/internalization.org][internalization]].

* References
:PROPERTIES:
:CUSTOM_ID: h-dab505ba-dc33-4821-afd9-a61026f21d21
:END:

- Mac Lane's {{{book-title(Category Theory for the Working Mathematician)}}}
  is the standard text.
- Jiří Adámek, Horst Herrlich, George Strecker,
  [[http://www.tac.mta.ca/tac/reprints/articles/17/tr17abs.html][Abstract and Concrete Categories: The Joy of Cats]]
  ([[http://katmat.math.uni-bremen.de/acc/acc.pdf][PDF]]), a free ebook, pretty good...but it's no Mac Lane.

** Examples of Categorification
:PROPERTIES:
:CUSTOM_ID: h-0cbb1a17-04c0-43d5-96b0-796a13e41527
:END:

- John Baez and Michael Shulman,\\
  [[https://math.ucr.edu/home/baez/cohomology.pdf][Lectures on n-Categories and Cohomology]].
- Mikhail Khovanov,\\
  "Heisenberg algebra and a graphical calculus."\\
  Eprint: [[https://arxiv.org/abs/1009.3295][arXiv:1009.3295]] [math.RT], 45 pages.
- Alexander Kirillov Jr,\\
  "On the modular functor associated with a finite group."\\
  Eprint: [[https://arxiv.org/abs/math/0310087][arXiv:math/0310087]] [math.QA], 7 pages.
- Jacob Lurie,\\
  "Categorification of Fourier Theory".\\
  [[https://youtu.be/w3f8KEcv4RE][Youtube lecture]], 2015
- Ingo Runkel, Jurgen Fuchs, Christoph Schweigert,\\
  "Categorification and correlation functions in conformal field theory."\\
  Eprint: [[https://arxiv.org/abs/math/0602079][arXiv:math/0602079]] [math.CT], 16 pages.
  _International Congress of Mathematicians._ Vol. III, pages 443–458, Eur. Math. Soc., Zürich, 2006.

*** 2-Vector Spaces
:PROPERTIES:
:CUSTOM_ID: h-fce4a7ed-5719-4013-ad56-03335949fca1
:END:

- John C. Baez and Alissa S. Crans,\\
  "Higher-Dimensional Algebra VI: Lie 2-Algebras".\\
  [[http://www.tac.mta.ca/tac/volumes/12/15/12-15abs.html][TAC]], 48 pages
- Jeffrey C. Morton,\\
  "2-Vector Spaces and Groupoids".\\
  [[https://arxiv.org/abs/0810.2361][arXiv:0810.2361]], 44 pages.

*** Galois Theory
:PROPERTIES:
:CUSTOM_ID: h-195ba4a7-7c60-4042-8ce2-8cd6a9933c35
:END:

- Theo Johnson-Freyd,\\
  "Spin, statistics, orientations, unitarity".\\
  [[https://arxiv.org/abs/1507.06297][arXiv:1507.06297]], offers a categorification of Galois theory.
  (See also [[http://categorified.net/handout-PI-oct2015.pdf][handout]])
- Deligne's "Categories Tensorielles"\\
  [[http://categorified.net/Deligne-CategoriesTensorielles-English.pdf][English translation]] also discusses categorified Galois theory.

*** Number Theory and Stuff
:PROPERTIES:
:CUSTOM_ID: h-a492e195-db18-4872-b961-1c8e864bc279
:END:

- Quoc P. Ho, Penghui Li,
  "Eisenstein series via factorization homology of Hecke categories".
  [[https://arxiv.org/abs/2103.10137][arXiv:2103.10137]]

*** Polynomials
:PROPERTIES:
:CUSTOM_ID: h-a2463813-f502-4be1-bbc4-a3c977a5713c
:END:

- Syu Kato, Anton Khoroshkin, Ievgen Makedonskyi,
  "Categorification of DAHA and Macdonald polynomials".
  [[https://arxiv.org/abs/2103.10009][arXiv:2103.10009]], 37 pages
- Mikhail Khovanov, Radmila Sazdanovic,
  "Categorification of the polynomial ring."
  Eprint: [[https://arxiv.org/abs/1101.0293][arXiv:1101.0293]] [math.QA], 29 pages.

** Higher Category Theory
:PROPERTIES:
:CUSTOM_ID: h-17051e84-5b54-4288-9f67-67d7bc0848c8
:END:

- Tom Leinster,
  "A Survey of Definitions of n-Category."
  Eprint: [[https://arxiv.org/abs/math/0107188][arXiv:math/0107188]] [math.CT], 67 pages.
  [[https://www.emis.de/journals/TAC/volumes/10/1/10-01abs.html][Theory Appl. Categ.]] **10** (2002), 1–70.
