#+TITLE: Complex Analysis
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-20T11:01:44-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Sunday December 20, 2020 at 11:01AM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Idea
:PROPERTIES:
:CUSTOM_ID: h-a72fed5d-a6cf-4afe-8c85-57ae69b98bf0
:END:

We use complex variables $z=x+\I y$, then do calculus with it, and we
transform 2-dimensional problems into something as simple as
one-dimensional calculus.

* Derivatives
:PROPERTIES:
:CUSTOM_ID: h-a1837e71-0361-4dea-9e31-9d0e39778891
:END:

The differential operators we work with are written in the coordinates
$z=x + \I y$ and its complex conjugate $\bar{z} = x - \I y$. The
derivatives in these coordinates may be written as

\begin{equation}
\frac{\partial}{\partial z}
 = \frac{1}{2} \left(\frac{\partial}{\partial x}
                     - \I\frac{\partial}{\partial y}\right)
\end{equation}

and

\begin{equation}
\frac{\partial}{\partial \bar{z}}
 = \frac{1}{2} \left(\frac{\partial}{\partial x}
                     + \I\frac{\partial}{\partial y}\right).
\end{equation}

Often these derivatives are written $\partial$ and $\bar{\partial}$.

#+ATTR_HTML: :id rmk-wirtinger-derivative
#+begin_remark
I've seen these called Wirtinger derivatives, but I thought Wirtinger
derivatives were operators on functions of specifically /multiple/ complex variables.
#+end_remark

#+ATTR_HTML: :id defn-holomorphic
#+begin_definition
We call a complex function $f(z,\bar{z})$ {{{define(Holomorphic)}}} if

\begin{equation}
\frac{\partial}{\partial\bar{z}}f(z,\bar{z}) = 0
\end{equation}

everywhere.
#+end_definition
