#+TITLE: Infinities
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at 11:53AM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Real Infinity

There are two infinities on the real number line, positive and
negative infinity. In Lisp, these are represented by the constants

#+begin_example
GSLL:+POSITIVE-INFINITY+

GSLL:+NEGATIVE-INFINITY+
#+end_example

The exact nature of infinity is debatable (e.g., is it a number or
a label for nonconvergent series?). As far as computation is
concerned, it acts like a number.

** Extended Real Numbers

We can treat them like numbers, which gives us the extended real
number line. The extended reals have the additional rules for
operators when at most 1 operand is infinite. The basic operations are

- $a+\infty = \infty + a = \infty$ for finite $a$
- $a-\infty = -\infty+ a = -\infty$ for finite $a$
- $a\times(\pm\infty) = \pm\infty$ for $0\lt a\lt+\infty$
- $a\times(\pm\infty) = \mp\infty$ for $-\infty\lt a\lt 0$
- $a/(\pm\infty) = 0$ for finite $a$
- $(\pm\infty)/a = \pm\infty$ for $0\lt a\lt\infty$
- $(\pm\infty)/a = \mp\infty$ for $-\infty\lt a\lt 0$
- $a^{\infty} = \infty$ and $a^{-\infty}=0$ for $1\lt a\lt\infty$
- $0^{a} = 0$ and $(+\infty)^{a}=\infty$ for $0\lt a\lt\infty$
- $0^{a} = \infty$ and $(+\infty)^{a}=0$ for $-\infty\lt a\lt 0$

When both are infinite in disagreeable ways, like $\infty - \infty$,
the operation is undefined. For agreeable situations, we could
define the operation, like $\infty + \infty = \infty$.

#+begin_exercise
Prove or find a counter-example: the extended reals form a monoid.
#+end_exercise

** Projective Real Number Line

Another approach is to use the projective real number
line. Intuitively, look at the plane $\mathbb{R}^{2}$ and take the
$x$-axis as the real number system. Now construct a unit circle
centered at the point $(0, 1)$.

We can associate each point on the $x$-axis with a point on the
circle by constructing a line from our point $(x,0)$ and connecting
it to the North pole of the circle $(0, 2)$. This line will
intersect the circle exactly once (besides the North pole), and
that intersection point is identified with the point on the number
line.

We can then "complete" the number line with an additional infinity,
namely, the North pole of this circle.

But this identifies positive infinity with negative infinity:
they're both mapped to the North pole.


** Hyperreal and Infinitesimals

We could use hyperreals to extend the real number system with
infinitesimals and, for closure under division, infinities. This
attempts to emulate the use of infinitesimals we find in Leibniz
and Newton.

Dual numbers are slightly simpler, and correspond to
$\mathbb{R}[\varepsilon]/(\varepsilon^{2})$. Or if you prefer,
adding a number $\varepsilon$ treated as a variable, but whose
square is zero. We can extend smooth functions on the real number
system to the dual reals by $f\colon\mathbb{R}\to\mathbb{R}$ having
$f(a+\varepsilon b) = f(a) + b\varepsilon f'(a)$ where $f'(x)$ is
the derivative of $f$.

The mathematicians who study hyperreals use insanely sophisticated
methods (I'm thinking of smooth infinitesimal analysis, which
requires category theory for simple calculus). I'm not sure the
juice is worth the squeeze.

* History

- John Wallis introduced the symbol $\infty$ for infinity in his book
  /De sectionibus conicis/ (1655)
- Isaac Newton wrote about them in his work
  /De analysi per aequationes numero terminorum infinitas/ (1699).


* References

- Michael Beeson and Freek Wiedijk
  [[http://www.cs.ru.nl/~freek/pubs/limits.pdf][The meaning of infinity in calculus and computer algebra systems]]
