#+TITLE: Infinities
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-05T11:53:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at 11:53AM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Real Infinity
:PROPERTIES:
:CUSTOM_ID: h-5fcbc798-db30-462d-a27b-f72463fcdb16
:END:

There are two infinities on the real number line, positive and
negative infinity. In Lisp, these are represented by the constants

#+ATTR_HTML: :id ex-lisp-infty
#+begin_example
GSLL:+POSITIVE-INFINITY+

GSLL:+NEGATIVE-INFINITY+
#+end_example

The exact nature of infinity is debatable (e.g., is it a number or
a label for nonconvergent series?). As far as computation is
concerned, it acts like a number.

** IEEE Floating Point
:PROPERTIES:
:CUSTOM_ID: h-96a7c44d-37d7-47b7-b9f5-d1a61046afac
:END:

There are two infinities in IEEE-754 floating point, a positive and a
negative infinity. For any finite positive $x$, we have

- Addition/Subtraction rules
  - $\pm x+\infty = \infty$
  - $\pm x-\infty = -\infty$
  - $\infty + \infty = \infty - (-\infty) = \infty$
  - $-\infty - \infty = -\infty + (-\infty) = -\infty$
- Multiplication rules
  - $x\infty = (-x)(-\infty) = \infty$
  - $(-x)\infty = x(-\infty) = -\infty$
  - $(-\infty)\infty = \infty(-\infty) = -\infty$
  - $\infty\infty = (-\infty)(-\infty) = \infty$
- Division rules
  - $\pm x/\infty = \pm x/(-\infty) = 0$
  - $\pm x/0 = \pm\infty$
  - $\pm x/(-0) = \mp\infty$
  - $0/\infty = 0$

All other operations produce a ~NaN~ ("Not-a-Number") special value.

** Extended Real Numbers
:PROPERTIES:
:CUSTOM_ID: h-7200bf6a-9a3e-4f8b-b62e-693a46d22564
:END:

We can treat them like numbers, which gives us the extended real
number line. The extended reals have the additional rules for
operators when at most 1 operand is infinite. The basic operations are

- $a+\infty = \infty + a = \infty$ for finite $a$
- $a-\infty = -\infty+ a = -\infty$ for finite $a$
- $a\times(\pm\infty) = \pm\infty$ for $0\lt a\lt+\infty$
- $a\times(\pm\infty) = \mp\infty$ for $-\infty\lt a\lt 0$
- $a/(\pm\infty) = 0$ for finite $a$
- $(\pm\infty)/a = \pm\infty$ for $0\lt a\lt\infty$
- $(\pm\infty)/a = \mp\infty$ for $-\infty\lt a\lt 0$
- $a^{\infty} = \infty$ and $a^{-\infty}=0$ for $1\lt a\lt\infty$
- $0^{a} = 0$ and $(+\infty)^{a}=\infty$ for $0\lt a\lt\infty$
- $0^{a} = \infty$ and $(+\infty)^{a}=0$ for $-\infty\lt a\lt 0$

When both are infinite in disagreeable ways, like $\infty - \infty$,
the operation is undefined. For agreeable situations, we could
define the operation, like $\infty + \infty = \infty$.

#+ATTR_HTML: :id xca-extended-reals-monoid
#+begin_exercise
Prove or find a counter-example: the extended reals form a monoid.
#+end_exercise

** Projective Real Number Line
:PROPERTIES:
:CUSTOM_ID: h-e283f7af-bd02-4836-a659-5f6713eb49e5
:END:

Another approach is to use the projective real number
line. Intuitively, look at the plane $\mathbb{R}^{2}$ and take the
$x$-axis as the real number system. Now construct a unit circle
centered at the point $(0, 1)$.

We can associate each point on the $x$-axis with a point on the
circle by constructing a line from our point $(x,0)$ and connecting
it to the North pole of the circle $(0, 2)$. This line will
intersect the circle exactly once (besides the North pole), and
that intersection point is identified with the point on the number
line.

We can then "complete" the number line with an additional infinity,
namely, the North pole of this circle.

But this identifies positive infinity with negative infinity:
they're both mapped to the North pole.


** Hyperreal and Infinitesimals
:PROPERTIES:
:CUSTOM_ID: h-d7baa693-13dc-46bf-b09e-f335603570d5
:END:

We could use hyperreals to extend the real number system with
infinitesimals and, for closure under division, infinities. This
attempts to emulate the use of infinitesimals we find in Leibniz
and Newton.

Dual numbers are slightly simpler, and correspond to
$\mathbb{R}[\varepsilon]/(\varepsilon^{2})$. Or if you prefer,
adding a number $\varepsilon$ treated as a variable, but whose
square is zero. We can extend smooth functions on the real number
system to the dual reals by $f\colon\mathbb{R}\to\mathbb{R}$ having
$f(a+\varepsilon b) = f(a) + b\varepsilon f'(a)$ where $f'(x)$ is
the derivative of $f$.

The mathematicians who study hyperreals use insanely sophisticated
methods (I'm thinking of smooth infinitesimal analysis, which
requires category theory for simple calculus). I'm not sure the
juice is worth the squeeze.

* Complex Infinity
:PROPERTIES:
:CUSTOM_ID: h-a531f251-74c6-4411-9af9-00c23e551476
:END:

Wolfram's /Mathematica/ uses $\widetilde{\infty}$ as an infinite
numerical quantity whose direction in the complex plane is unknown or
undetermined, called [[https://functions.wolfram.com/Constants/ComplexInfinity/introductions/Symbols/ShowAll.html][Complex Infinity]]. (This is idiosyncratic terminology.)
On the Riemann sphere, it is the north pole. In the
projective complex plane, it is the line at infinity.

It has the property that, for any finite positive $x$,
\begin{equation}
\widetilde{\infty}\pm x = \widetilde{\infty}
\end{equation}
\begin{equation}
\widetilde{\infty}\times\widetilde{\infty}=\widetilde{\infty}
\end{equation}
\begin{equation}
x/\widetilde{\infty}=0/\widetilde{\infty}=0
\end{equation}

But the following operations are undefined:

\begin{equation}
\widetilde{\infty}\pm\widetilde{\infty}=\mathtt{NaN}
\end{equation}
\begin{equation}
\widetilde{\infty}/\widetilde{\infty}=\mathtt{NaN}
\end{equation}
\begin{equation}
\widetilde{\infty}/x=\widetilde{\infty}/0=\mathtt{NaN}
\end{equation}
\begin{equation}
\widetilde{\infty}\times0=0\times\widetilde{\infty}=\mathtt{NaN}
\end{equation}

#+begin_puzzle
Is this equivalent to defining $\widetilde{\infty}=\lim_{w\to0}w^{-1}$?
#+end_puzzle
#+begin_puzzle
Are these equations consistent? Do they lead to a contradiction?
#+end_puzzle

* History
:PROPERTIES:
:CUSTOM_ID: h-02fd2774-db86-4ec4-aa92-2257c9c0c77a
:END:

- John Wallis introduced the symbol $\infty$ for infinity in his book
  /De sectionibus conicis/ (1655)
- Isaac Newton wrote about them in his work
  /De analysi per aequationes numero terminorum infinitas/ (1699).
- Wolfram claims Weierstrass was the first to treat infinity as a
  quantity in 1876, though I cannot verify this; if true, it would either
  be in his /Lecture courses on analytic functions/ or
  /Lecture courses on elliptic functions/ (it seems like those were the
  only things Weierstrass published in 1876).

* References
:PROPERTIES:
:CUSTOM_ID: h-92c628a0-014d-40ef-9356-8ec5dfa417b3
:END:

- Michael Beeson and Freek Wiedijk
  [[http://www.cs.ru.nl/~freek/pubs/limits.pdf][The meaning of infinity in calculus and computer algebra systems]]
- Fredrik Johansson, [[https://fredrikj.net/blog/2021/01/infinity-in-calcium-and-fungrim/][Infinity in Calcium and Fungrim]] (2021-01-25)
- Mathematica Documentation about [[https://functions.wolfram.com/Constants/ComplexInfinity/introductions/Symbols/ShowAll.html][~ComplexInfinity~]]
