#+TITLE:
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-04-11T19:21:54-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday April 11, 2021 at  7:21PM

* Principles
:PROPERTIES:
:CUSTOM_ID: h-d8254e7e-326c-40c6-8b31-8fc0077feb87
:END:

*Effective Thinking Principle.*
/Seek Different Views of the Same Result./
Understanding a theorem often resides in the proof rather than
the statement. So alternative proofs provide additional insight—look for
them.

*Effective Thinking Principle.*
/Do Special Cases./
By doing special cases, particularly simple cases, you teach yourself
how to do harder problems.

*Effective Thinking Principle.*
/Understand Simple Things Deeply./
Understanding basic ideas with great depth often leads to great
insights.

*Effective Thinking Principle.*
/Definitions Should Capture Essentials./
After we have isolated essential features of a concept, pin
them down with a definition that contains those essentials and as
little else as possible.

*Effective Thinking Principle.*
/Explore Consequences of Definitions./
After making a definition, identify immediate implications of the
definition in order to understand its meaning.

*Effective Thinking Principle.*
/Create Examples./
When learning any definition in mathematics, one helpful step is to
construct several examples that illustrate the meaning of the definition.

*Effective Thinking Principle.*
/Imagine Alternative Worlds./
One way to create concepts is to imagine our world but with some feature
altered, and then follow the consequences.

*Effective Thinking Principle.*
/Push Analogies./
When using an analogy to
create an idea, see whether the analogy can be refined by looking at
more specific features

*Effective Thinking Principle.*
/Settle on an Idea and Explore the Consequences./
After identifying essential elements, make a definition
and explore the implications.

*Effective Thinking Principle.*
/Generalizations Should Generalize./
If a definition is intended to generalize a specific example, check to make
certain it does so.

*Effective Thinking Principle.*
/Draw a Picture./
Part of the value of drawing a picture is to see features in your picture
that you did not intentionally put there. For example, if you draw a
triangle without thinking about it, the sum of the angles will equal 180
degrees. A picture can suggest insights that will help with your
argument. Get in the habit of drawing pictures!

*Effective Thinking Principle.*
/Extending Theorems./
A habit that will help you to understand mathematics is always to look
for the extent to which a theorem can be extended or not.

*Effective Thinking Principle.*
/Borrow Strategies from Other Fields./
Powerful concepts from other fields can inspire new insights either
directly or by analogy

*Effective Thinking Principle.*
/Consider the Converse./
We can deepen our understanding of a theorem by considering whether or
not the converse is true.

*Effective Thinking Principle.*
/Find Examples to Distinguish Concepts./
We have now been introduced to a collection of new definitions. A good
way to get accustomed to new definitions is to find examples that
manifest the differences in the various properties.

*Effective Thinking Principle.*
/Consider Ideas at Different Scales./
One of the strategies of mathematics is, after conceiving of a property
at some level,to consider whether that same idea could be valuable at a
different scale.

*Effective Thinking Principle.*
/Look for Implications of Definitions./
Sometimes a definition immediately implies an apparently stronger
version or versions of the definition. Seek them out and formulate them.

*Effective Thinking Principle.*
/Explore Limits of Theorems; Add Hypotheses./
When you discover a theorem, explore its limitations and possible
extensions by systematically weakening the hypotheses and checking to see
whether the theorem is still true and strengthening the conclusion to see
whether you can deduce more than you originally thought.

*Effective Thinking Principle.*
/Add a Hypothesis./
When you can’t prove aconjecture, create additional hypotheses that
would allow you to prove it.

*Effective Thinking Principle.*
/Look at Examples to Understand Theorems./
One of the best ways to make a theorem more meaningful is to see its
implications in specific cases.

*Effective Thinking Principle.*
/Consider Related Spaces./
Once you haveproved a theorem for one space, see whether it is true for
related spaces.

*Effective Thinking Principle.*
/Consider Analogies of Previous Results./
After developing variations of previous concepts, look at previous
results and see what analogous results hold.

*Effective Thinking Principle.*
/Weaken Hypotheses if Possible./
To understand theorems better and to improve them if possible, identify
exactly what aspects of the hypotheses were actually used in the proof.

*Effective Thinking Principle.*
/Look at Examples./
After learning new concepts, investigate examples to see how those
properties manifest themselves.

*Effective Thinking Principle.*
/Bring to Mind All Equivalent Formulations./
After learning that a concept has equivalent formulations, get in the
habit of consciously considering each one in order to select the most
convenient option in a given situation.

*Effective Thinking Principle.*
/Ask About Local Versions of Global Concepts./
After defining a concept for a whole space, investigate whether there is
a local version of that concept.

*Effective Thinking Principle.*
/Investigate How Properties are Related by Transformations./
After defining structure-respecting transformations, investigate what
properties are preserved by those functions.

*Effective Thinking Principle.*
/Check the Necessity of Hypotheses./
After you prove a theorem, check that all the hypotheses are necessary.

*Effective Thinking Principle.*
/Understand Proofs, Not Just Statements, of Theorems./
Understanding the proofs of theorems rather than just the statements of
theorems gives you power.

*Effective Thinking Principle.*
/Extend Results./
After proving a theorem, see if it can be improved or modified.

# 36
*Effective Thinking Principle.*
/Seek Equivalences./
After isolating a concept or a definition, seek equivalences with the
goal of understanding the idea from different perspectives.

*Effective Thinking Principle.*
/Look at Examples to Make Definitions Meaningful./
After creating or encountering a definition, look at a range of
specific examples to help you understand the definition more deeply.

# 38
*Effective Thinking Principle.*
/Connect New Ideas with Old Ideas./
After isolating a new idea, consider previous concepts and constructions
and explore how the new idea relates to them.

# 40
*Effective Thinking Principle.*
/Consider Opposite Questions./
When studying a topic, it is often illuminating to consider the opposite
questions.

*Effective Thinking Principle.*
/Start with Simple Cases./
George Polya said, "If you can't solve a problem, then there is an
easier problem you can’t solve. Find it."

*Effective Thinking Principle.*
/Opposite Extremes./
After creating a concept, explore its opposite as well.
