#+TITLE: Rings and Things
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-24T08:42:31-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Thursday December 24, 2020 at  8:42AM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Generalization of Number Systems
:PROPERTIES:
:CUSTOM_ID: h-a5f46763-8b18-4933-b942-e03c7c95db54
:END:

The study of rings generalizes the study of number systems. The
archetypical number systems include our favorites: the integers, the
rationals, the reals, and the complex numbers. But not the natural
numbers (because we want to include subtraction).

#+NAME: defn-ring
#+begin_definition
A {{{define(Ring)}}} consists of

- a set $R$

equipped with

- addition $+\colon R\times R\to R$
- negation $-\colon R\to R$
- a zero-like object $0\in R$
- multiplication $-\cdot-\colon R\times R\to R$
- a one-like object $1\in R$

such that

- Addition is associative $(x + y) + z = x + (y + z)$
- Addition is commutative $x + y = y + x$
- Zero is the unit for addition: $x + 0 = 0 + x = x$
- Negation gives the additive inverse: $x + (-x) = 0$
- Multiplication is associative $x\cdot(y\cdot z) = (x\cdot y)\cdot z$
- One is the unit for multiplication $x\cdot1=1\cdot x=x$
- Multiplication distributes over addition $(x + y)z = xz + yz$

If, in addition, multiplication is commutative, then we call the ring a
{{{define(Commutative Ring)}}}.
#+end_definition

#+begin_remark
If we abandon the existence of a multiplicative identity, then we have a
non-unital ring.
#+end_remark

There are probably a few more properties I'm forgetting about.

#+begin_remark
(Internalization, category theoretic definition.)
We could define a "ring object" as a monoid object in the category
{{{cat(Ab)}}} of Abelian groups. (For this reason, we could have defined
a ring as consisting of an Abelian group equipped with multiplication.)
This gives us a sense of the important properties: we need to have an
underlying Abelian group. We can give up, e.g., commutativity for
multiplication (we could even give up associativity!), but we really
want to have commutativity for addition.
#+end_remark

** Examples
:PROPERTIES:
:CUSTOM_ID: h-03deb5e7-4e53-4c2a-bfd8-fdbcf9ba4078
:END:

#+begin_math-example
The integer $\ZZ$ is the epitome of a ring, as are the rationals $\QQ$,
and the reals $\RR$.
#+end_math-example

#+begin_math-example
Let $R$ be a commutative ring, then the collection of polynomials in a single
indeterminate $z$ with coefficients in $R$ is a ring...called the
{{{define(Polynomial Ring)}}} over $R$, denoted $R[z]$.

We can generalize the polynomial ring in a number of ways: we could
consider rational polynomials $R(z) = \{f(z)/g(z)\mid f,g\in R[z], g\neq0\}$;
or formal power series $R[{[z]}]$; or the formal Laurent series $R((z))$
which intuitively is $R[z^{-1}] + R[{[z]}]$.

But not the formal
distributions over $R$, i.e., $R[{[z,z^{-1}]}]$ because multiplication
is not consistent (this pops up in vertex operator algebras).
#+end_math-example

#+begin_math-example
Let $R$ be a ring, and $n\in\NN$ a natural number greater than zero.
Then the set of \(n\)-by-\(n\) matrices with entries in $R$, denoted
$M(n,R)$, forms another ring under matrix addition and matrix
multiplication.

This is an important example, because for $n\gt1$ the ring is
noncommutative.
#+end_math-example

#+begin_math-example
Let $X$ be some non-empty set, and $R$ a ring. Then the function space
$\hom(X,R)$ of \(R\)-valued functions on $X$ forms a ring. Addition is
defined pointwise $f+g$ is the function $(f+g)(x) = f(x)+g(x)$,
as are multiplication $(f\times g)(x)=f(x)g(x)$. The additive identity is the
constant function $Z(x) = 0$ for all $x\in X$, and the multiplicative
identity is the function $e(x) = 1$ for all $x\in X$.
#+end_math-example

#+begin_math-example
If $X$ is a topological space, then continuous real-valued functions
form a ring. (Continuous complex-valued functions form another ring.)
#+end_math-example

#+begin_exercise
Let $R$ be a noncommutative ring. Can we extend the notion of a
polynomial ring to $R[x]$?
#+end_exercise

#+begin_exercise
Let $n\in\NN$ be greater than 1, $R$ some fixed commutative ring.
Is $M(n, R[z])$ the same ring as $(M(n, R))[z]$?
What happens for noncommutative rings $R$?
#+end_exercise

** Special Elements in a Ring
:PROPERTIES:
:CUSTOM_ID: h-6b3e4190-1cb1-41dc-960b-24cedee5bb0d
:END:

#+begin_definition
Let $r\in R$ be an element in a ring. We call it {{{define(Nilpotent)}}}
if there exists some $k\in\NN$ such that $r^{k}=0$.
#+end_definition

We could consider nilpotents as modeling "infinitesimals" of yore.

#+begin_definition
Let $r\in R$ be an element in a ring. We call it {{{define(Idempotent)}}}
if $r^{2}=r$.
#+end_definition

** Ring Morphisms
:PROPERTIES:
:CUSTOM_ID: h-440ddc6d-4548-4e18-b747-e1f40b0f4f4e
:END:

#+begin_definition
Let $R$ and $S$ be rings. A {{{define(Ring Morphism)}}} is a function of
the underlying sets $f\colon R\to S$ such that

1. it preserves addition $f(a+b) = f(a) + f(b)$
2. it preserves multiplication $f(ab) = f(a)f(b)$
3. it preserves "one" $f(1_{R})=1_{S}$.
#+end_definition

As a consequence of preserving addition, we have $f(0+0)=f(0)+f(0)=f(0)$
which implies $f(0)=0$. Further $f(0-a) = f(0) + f(-a) = f(-a)$ and
$f(a-a) = f(a) + f(-a) = 0$ implies $f(-a)=-f(a)$.

#+begin_math-example
Let $R$ be a ring. Then we always have a morphism $f\colon\ZZ\to R$
defined by $f(0)=0$, $f(1)=1$, $f(2)=f(1)+f(1)$, and more generally for
$n\in\NN$ we have

\begin{equation}
f(n) = \sum^{n}_{j=1}f(1).
\end{equation}

Sometimes we abuse notation and write $f(n)=nf(1)$.
#+end_math-example

#+begin_math-example
Let $R$ be a ring, $r\in R$ some fixed element. Then we have a natural
morphism $e_{r}\colon R[z]\to R$ by evaluating a polynomial at $z=r$,
i.e., $e_{r}(p(z)) = p(r)$.
#+end_math-example

#+begin_math-example
For a ring $R$ and the polynomial ring $R[z]$, the inclusion mapping
$R\to R[z]$ mapping $r\in R$ to $r\in R[z]$ is a ring morphism.

*But* the function mapping a polynomial to its roots in $R$,
$\rho\colon R[z]\to\mathcal{P}(R)$, is *not* a ring morphism. How can we
see this? Well, the codomain isn't necessarily a ring (what's the
additive inverse? What's addition?), but $\rho(p(z) + q(z))$ is not
necessarily mapped to $\rho(p(z)) + \rho(q(z))$.
#+end_math-example

#+begin_definition
Let $R$ and $S$ be rings, we call the ring morphism $f\colon R\to S$
a {{{define(Ring Isomorphism)}}} (or just /isomorphism/) if there is a
morphism $g\colon S\to R$ such that $g\circ f=\mathrm{id}_{R}$ and
$f\circ g=\mathrm{id}_{S}$ (i.e., an inverse morphism exists).
#+end_definition

A ring isomorphism, like all isomorphisms, tells us when two rings are
"the same".

** Subrings, Adjoining Elements
:PROPERTIES:
:CUSTOM_ID: h-b18f1c1f-bad7-4f83-be69-f4b8e8d9e06a
:END:

#+begin_definition
Let $R$ be a ring, $S\subset R$ some subset of $R$. We call $S$ a
{{{define(Subring)}}} of $R$ if

1. $S$ is a subgroup of $R$ under addition,
2. $S$ is closed under multiplication from $R$,
3. $1\in S$.
#+end_definition

#+begin_math-example
The integers $\ZZ$ are a subring of the rationals $\QQ$; the rationals
are a subring of the reals $\RR$; the reals are again a subring of the
complex numbers $\CC$.
#+end_math-example

#+begin_math-example
A non-example: the modular ring $\ZZ/(24)$ of hours in a day, this is
not a subring of $\ZZ$. The operators are distinct.
#+end_math-example

#+begin_definition
Let $S$ be a subring of a commutative ring $R$.
We can {{{define(Adjoin an Element)}}}
$r\in R$ to $S$ --- denoted $S[r]$ ---
by taking the subring of formal polynomials $S[z]\subset R[z]$
and the evaluation morphism $e_{r}\colon R[z]\to R$ restricted to the
subring $S[z]\subset R[z]$ gives us $S[r] = e_{r}(S[z])\subset e_{r}(R[z])$.
#+end_definition

#+begin_math-example
We can consider $\ZZ\subset\CC$ as a subring, then adjoining
$\I=\sqrt{-1}$ to $\ZZ$ gives us the {{{define(Gaussian Integers)}}}
$\ZZ[\I]$. We basically treat $\I$ as a variable, then replace $\I^{2}$
by $-1$ (and commutativity lets us factor $\I^{n+2}=\I^{2}\I^{n}$ to
iterate this heuristic). An arbitrary Gaussian integer looks like $a+\I b$
for arbitrary integers $a,b\in\ZZ$. Multiplication is defined as

\begin{equation}
(a + \I b)(x + \I y) = (ax - by) + \I(ay + bx).
\end{equation}

Addition is defined component-wise.
#+end_math-example

#+begin_remark
We can generalize this example to any square-free number $d\in\NN$, then
$\ZZ[\sqrt{-d}]$ is another ring adjoined with a new element. (The
example of $\ZZ[\sqrt{-5}]$ is thrown around a lot because in that ring,
$6=2\cdot3=(1-\sqrt{-5})(1+\sqrt{-5})$ has two distinct factorizations.)
#+end_remark

** Ideals
:PROPERTIES:
:CUSTOM_ID: h-e35ff4ad-70ff-422e-8fd3-bc8a0da7bd51
:END:

#+begin_definition
Let $f\colon R\to S$ be a ring morphism, $0_{S}\in S$ be the additive
identity ("zero") of $S$. We define the {{{define(Kernel)}}} of $f$ to
be the subset

\begin{equation}
\ker(f) = \{r\in R\mid f(r) = 0_{S}\}.
\end{equation}
#+end_definition

Observe that the kernel of a ring morphism is closed under addition ---
if $x,y\in\ker(f)$, then $f(x+y) = f(x) + f(y) = 0+0 = 0$ --- and
multiplication. Moreover, for any $r\in R$ and for any $x\in\ker(f)$, we
see that $f(xr)=f(x)f(r)=0$, and $f(rx)=f(r)f(x)=0$; i.e., that the kernel is closed under
multiplication by elements of the domain on the right and left, respectively.

This idea is captured by the following definition:

#+NAME: defn-ideal
#+begin_definition
Let $R$ be a ring.

1. A {{{define(Left Ideal)}}} in $R$ is a subset $I_{L}\subset R$
   is such that (a) $0\in I_{L}$, (b) $x+y\in I_{L}$ whenever both $x\in I_{L}$
   and $y\in I_{L}$, (c) $ry\in I_{L}$ whenever $y\in I_{L}$ for any
   $r\in R$.
2. A {{{define(Right Ideal)}}} in $R$ is a subset $I_{R}\subset R$
   is such that (a) $0\in I_{R}$, (b) $x+y\in I_{R}$ whenever both $x\in I_{R}$
   and $y\in I_{R}$, (c) $xr\in I_{R}$ whenever $x\in I_{R}$ for any
   $r\in R$.
3. A {{{define(Two-Sided Ideal)}}} in $R$ is a subset $I\subset R$
   is such that (a) $0\in I$, (b) $x+y\in I$ whenever both $x\in I$
   and $y\in I$, (c) $xy\in I_{L}$ whenever $x\in I$ /or/ $y\in I$.

Further, we call the ideal {{{define(Proper)}}} if the ideal is a proper
subse of the ring.
#+end_definition

For commutative rings, these three coincide, and we just speak of
"Ideals". It's for noncommutative rings we need to distinguish them.
Whenever results depend on the kind of ideal, we make note of it.
Otherwise, we say "ideal" with the understanding it may mean any of the
three kinds.

#+begin_theorem
Let $I$ be an ideal of $R$. Then $I$ is a subgroup of the underlying
Abelian group of $R$ (equipped with addition).
#+end_theorem

#+begin_math-example
Let $R\subset R'$ be a proper subring, and $q\in R'$ an element not in $R$.
Then $R[q]$ is a ring obtained by taking $R[z]\subset R'[z]$,
then applying the evaluation morphism $e_{q}\colon R'[z]\to R'$
restricted to $R[z]$. That is to say, $e_{q}(R[z])\subseteq R'$.

#+end_math-example

It's not uncommon to see things like, if $r\in R$, then $rR = \{rx\mid x\in R\}$.

#+NAME: defn-generated-ideal
#+begin_definition
Let $R$ be a ring, $S\subset R$ some nonempty subset.
We describe the {{{define(Ideal Generated by \(S\))}}} to be the sums of
elements of the form $xsy$ where $s\in S$ and $x,y\in R$.
#+end_definition

For commutative rings, we can use commutativity to rewrite $xsy=xys$ and
thus $(S) = RS$.

#+begin_remark
Let $I$ and $J$ be ideals of $R$.
Notation:

1. Then we denote the ideal generated by $I\cup J$ as $I+J$.
2. We also denote $IJ$ is the ideal generated by elements of the form
   $ab$ for $a\in I$ and $b\in J$.
#+end_remark

#+begin_exercise
(Jacobson) Let $I$, $J$, $K$ be ideals of $R$. Does distributivity hold
for "ideal arithmetic"? I.e., is $(I+J)K$ equal to $IK + JK$?
#+end_exercise

#+begin_exercise
Let $R$ be a ring, $I$ an ideal of $R$. Prove or find a counter-example:
$IR\subseteq I$. Is this true for noncommutative rings?
#+end_exercise

** Integral Domain
:PROPERTIES:
:CUSTOM_ID: h-1fb500b5-9715-4693-8feb-f1fb5db1e16a
:END:

#+begin_definition
An {{{define(Integral Domain)}}} is a unital ring with no nonzero
divisors, i.e., if $ab = 0$ then either $a=0$ or $b=0$.
#+end_definition

#+begin_remark
Constructive mathematicians would phrase this differently, as saying
$ab\neq0$ whenever $a\neq0$ and $b\neq0$.
#+end_remark

#+begin_math-example
The integers $\ZZ$, rationals $\QQ$, reals $\RR$, and complex numbers
are integral domains.
#+end_math-example

#+begin_math-example
Let $X$ be a non-empty set with at least 2 disjoint subsets $X_{1}$, $X_{2}$;
and let $R$ be any ring. Then $\hom(X,R)$ is *not an integral domain.*
To see this, consider

\begin{equation}
f(x) = \begin{cases}
1 & x\in X_{0}\\
0 & x\notin X_{0}
\end{cases}
\end{equation}

and

\begin{equation}
g(x) = \begin{cases}
1 & x\in X_{1}\\
0 & x\notin X_{1}.
\end{cases}
\end{equation}

Then we have

\begin{equation}
(fg)(x) = f(x)g(x) = 0
\end{equation}

since $X_{0}\cap X_{1}=\emptyset$. Although both $f\neq0$ and $g\neq0$,
we have $fg=0$.
#+end_math-example

#+begin_math-example
The ring $\ZZ[\sqrt{-5}]$ is an integral domain.
#+end_math-example

*** Factors
:PROPERTIES:
:CUSTOM_ID: h-738b2d99-d841-4742-8dec-4cec26ed04ab
:END:

#+begin_definition
Let $R$ be an integral domain, and $x,y\in R$. We say that $x$
{{{define(Divides)}}} $y$, and write $x\mid y$, if $y=xt$ for some $t\in R$.
#+end_definition

#+begin_definition
We call an element $x\in R$ a {{{define(Unit)}}} if $x\mid 1$. The set
of units of $R$ is denoted $R^{*}$.
#+end_definition

#+NAME: defn-gcd
#+begin_definition
We say $z\in R$ is  a {{{define(Greatest Common Divisor)}}} of $x_{1}$,
..., $x_{n}$ and write $z=\gcd(x_{1},\dots, x_{n})$ if

1. $z\mid x_{j}$ for $1\leq j\leq n$
2. for any $t\in R$, $t\mid x_{j}$ for $1\leq j\leq n$ implies $t\mid z$.

Further, +stealing+ borrowing terminology from number theory, we say
that $x$ and $y$ are {{{define(Coprime)}}} if there exists a unit $u\in R^{*}$
which is a gcd of $x$ and $y$.
#+end_definition


#+begin_lemma
Let $R$ be an integral domain, and $x,y\in R$.
If  $z$ and $t$ are both GCDs of $x$ and $y$, then there exists a $u\in R$
such that $z=ut$.
#+end_lemma
#+begin_proof
- Assume $z = \gcd(x,y)$, $t=\gcd(x,y)$, and $t\neq z$.
- Then $t\mid x$ and $t\mid y$ by [[defn-gcd][definition of gcd]].
- Then $t\mid z$ by $z=\gcd(x,y)$.
- Thus $z=ut$ for some $u\in R$.
#+end_proof

#+begin_theorem
(Bronstein, 1.1.1)
Let $R$ be an integral domain, and $x,y\in R$.
If $z$ and $t$ are both GCDs of $x$ and $y$, then $z=ut$ and $t=vz$ for
some units $u,v\in R^{*}$.
#+end_theorem

#+begin_proof
- Assume $z = \gcd(x,y)$, $t=\gcd(x,y)$, and $t\neq z$.
- Consider $u\in R$ such that $z=ut$ by the previous lemma.
- Consider $v\in R$ such that $t=vz$ by the previous lemma.
- Then $z=ut=u(vz)$.
- If $z\neq0$, then $u,v\in R^{*}$.
- If $z=0$, then $t=1z$ and $z=1t$.
- Thus $u,v\in R^{*}$.
#+end_proof

#+begin_definition
In an integral domain $R$, let $a,b\in R$. If $a$ divides $b$, and $b$
divides $a$, then we call them {{{define(Associates)}}}. Equivalently,
if there is some unit $u\in R^{*}$ such that $a=ub$.
#+end_definition

*** Prime, Irreducible Elements
:PROPERTIES:
:CUSTOM_ID: h-b90357b9-9646-4544-aa00-4059af933f2b
:END:

#+begin_definition
Let $R$ be an integral domain.
A nonzero element $p\in R\setminus R^{*}$ is called {{{define(Prime)}}}
if for any $a,b\in R$, $p\mid ab$ implies $p\mid a$ or $p\mid b$.
#+end_definition

#+begin_definition
Let $R$ be an integral domain.
A nonzero element $p\in R\setminus R^{\ast}$ is called {{{define(Irreducible)}}}
if for any $a,b\in R$, $p = ab$ implies $a\in R^{\ast}$ or $b\in R^{\ast}$.
#+end_definition

#+begin_theorem
Let $R$ be an integral domain.
Then every prime $p\in R$ is irreducible.
#+end_theorem

#+begin_proof
- Let $p\in R$ be prime.
- Assume $a,b\in R$ satisfy $p=ab$.
- Per cases $p\mid a$ or $p\mid b$ by definition of prime.
- Suppose $p\mid a$;
  - Then $a=q_{a}p$;
  - Thus $1=q_{a}b$;
  - Thus $b\mid 1$;
  - Thus $b\in R^{\ast}$ is a unit.
- Suppose $p\mid b$; then $a\in R^{\ast}$ is a unit (by the exact same reasoning).
- Hence $p$ is irreducible.
#+end_proof

#+begin_remark
In any integral domain, a prime is always irreducible. The converse is
not always true.
#+end_remark

** Unique Factorization Domain
:PROPERTIES:
:CUSTOM_ID: h-0a367193-227e-413a-ae7d-8a42cfc8bebd
:END:

#+begin_definition
A {{{define(Unique Factorization Domain)}}} consists of an integral
domain such that for any nonzero $x\in R\setminus R^{\ast}$ there is
some unit $u\in R^{\ast}$ and coprime irreducibles $p_{1},\dots,p_{n}\in R$
and positive integers $e_{1},\dots, e_{n}$ such that

\begin{equation}
x=u p_{1}^{e_{1}}\dots p_{n}^{e_{n}}
\end{equation}

Furthermore, this factorization is unique up to multiplication of $u$
and $p_{j}$'s by units and up to permutation of indices.
#+end_definition

#+begin_theorem
Let $R$ be a unique factorization domain, then every irreducible $p\in R$
is prime.
#+end_theorem

#+begin_theorem
If $R$ is a UFD, then any $x,y\in R$ has a gcd in $R$.
#+end_theorem

#+begin_theorem
If $R$ is a UFD, then the polynomial ring $R[x_{1},\dots,x_{n}]$ is a UFD.
#+end_theorem

** Principal Ideal Domain
:PROPERTIES:
:CUSTOM_ID: h-c8386128-fe00-4c69-8489-1e127df235e1
:END:

#+begin_definition
Let $R$ be a ring, $I$ an ideal of $R$. We call $I$
{{{define(Principal)}}} if it is generated by a single element. In this
case, we have $I=(g)$ where $g\in R$ is the generator of the ideal.
#+end_definition

#+begin_definition
We call a ring $R$ a {{{define(Principal Ideal Domain)}}} if

1. it is an integral domain
2. every ideal in $R$ is a principal ideal.
#+end_definition

#+begin_theorem
Every principal ideal domain is a UFD.
#+end_theorem

#+begin_theorem
If $R$ is a PID, then $(x,y) = (\gcd(x,y))$ for any $x,y\in R$.
#+end_theorem

* Fields
:PROPERTIES:
:CUSTOM_ID: h-d35432ca-44af-42ab-a269-4301147f0ccc
:END:
** Basic Idea
:PROPERTIES:
:CUSTOM_ID: h-30cc20ad-a3a4-4721-9704-fcf9c6e0febb
:END:

We often want to divide by a nonzero number, which requires forming the
multiplicative inverse operation.

#+begin_definition
A {{{define(Field)}}} consists of a commutative (unital) ring $R$ equipped
with a multiplicative inverse operation $(-)^{-1}\colon R\setminus\{0\}\to R$.
#+end_definition

Usually we construct fields from rings using the field of fractions. We
take for granted that $\QQ$, $\RR$, and $\CC$ are fields.

*** Field of Fractions
:PROPERTIES:
:CUSTOM_ID: h-4d677afa-ddc1-45b6-8d3e-aaf25e4c80c7
:END:

Given an [[*Integral Domain][integral domain]] $R$, its field of fractions $\mathbb{F}$ may be
formed by considering equivalence classes of pairs $R\times (R\setminus\{0\})$
formed by the relation

\begin{equation}
(a,b)\sim(x,y)\iff ay = bx.
\end{equation}

Intuition suggests these describe the same fraction "\(a/b\)".

#+begin_math-example
The rational numbers $\QQ$ are formed from the integers $\RR$ in this manner.
#+end_math-example

#+begin_math-example
If $\mathbb{F}$ is any field, then the field of fractions for
$\mathbb{F}[x]$ is the field of rational functions $\mathbb{F}(x)$
("fractions of polynomials").
#+end_math-example

*** Uses, Galois Theory
:PROPERTIES:
:CUSTOM_ID: h-bd0ee557-d0fe-4143-9ecd-e01300ba426d
:END:

The basic question we want to answer concerns, given a field
$\mathbb{F}$, consider a polynomial $p\in\mathbb{F}[x]$. Is there some
$r\in\mathbb{F}$ such that $p(r)=0$? In other words, does a root exist
in the field?

This isn't always the case. For example, consider $p\in\QQ[x]$ be
defined as

\begin{equation}
p(x) = x^{2}-2.
\end{equation}

Its solution is $x=\pm\sqrt{2}$, which is famously irrational. So no
root exists in $\QQ$, but what about $\QQ[\sqrt{-5}]$? Or $\ZZ[\sqrt{-7}]$?

Galois theory studies such problems by examining symmetries of such
field extensions.

* References
:PROPERTIES:
:CUSTOM_ID: h-b86f3414-cef0-486c-a961-cb63fa8d0861
:END:

- Manuel Bronstein, {{{book-title(Symbolic Integration 1: Transcendental Functions)}}}.
  Springer, second ed., 1996.
  Chapter 1 particularly reviews polynomial rings.
- Nathan Jacobson,
  {{{book-title(Basic Algebra I)}}}.
  Chapter 2.
- Serge Lang, {{{book-title(Algebra)}}}.
  Springer, third ed., GTM., 2002.
  Chapter 2.
- James McIvor,
  [[https://math.berkeley.edu/~gmelvin/math113su14/math113su14notes2.pdf][Lecture Notes on Ring Theory]].
  UC Berkeley, Math 113, Summer 2014.

** Involving Theorem Provers
:PROPERTIES:
:CUSTOM_ID: h-4b23ee29-7f00-4b12-b5ae-e942d3cb4238
:END:

- Piotr Rudnicki, Christoph Schwarzweller, Andrzej Trybulec,
  "Commutative Algebra in the Mizar System".
  /J. of Symbolic Computation/ *32* no.1--2 (2001) pp 143--169
  doi:[[https://doi.org/10.1006/jsco.2001.0456][10.1006/jsco.2001.0456]]
