#+TITLE: Set Theory
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-21T10:47:11-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday March 21, 2021 at 10:47AM

* Overview

A foundation for mathematics, set theory asserts everything may be
encoded using sets (like how on computers everything is encoded using
bits). Although mathematicians believe they use sets as their
foundations, few can really enumerate their axioms. Realistically, it
seems the foundations employed in practice is some amalgam of set theory
equipped with a soft type system, in "$(1+\varepsilon)$-order logic" for
$0\lt\varepsilon\ll1$.

* Classes

We might also want to use a "many-sorted logic" to treat proper classes
as a different "sort" than proper sets. Confusingly, this treatment is
referred to as "second-order set theory" in the literature (as opposed
to "two-sorted set theory", which would make more sense).

* References

- Thomas Jech, \\
  {{{book-title(Set Theory: The Third Millennium Edition, revised and expanded)}}}. \\
  Springer, 2003.
- Thomas Jech and K. Hrbáček, \\
  {{{book-title(Introduction to Set Theory)}}}. \\
  Marcel Dekker, 3rd edition, 1999.
- Mike Shulman, \\
  "Set theory for category theory". \\
  [[https://arxiv.org/abs/0810.1279][arXiv:0810.1279]]

** Many-Sorted Models of Sets and Classes

- V. Gitman,\\
  [[https://victoriagitman.github.io/talks/2018/01/03/the-emerging-zoo-of-second-order-set-theories.html][The emerging zoo of second-order set theories]]
- Kameryn J Williams, \\
  "The Structure of Models of Second-order Set Theories". \\
  [[https://arxiv.org/abs/1804.09526][arXiv:1804.09526]], 209 pages.