#+TITLE: Set Theory
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-21T10:47:11-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday March 21, 2021 at 10:47AM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-9c5c0d57-a7b0-497f-9b3a-e367ec7658a6
:END:

A foundation for mathematics, set theory asserts everything may be
encoded using sets (like how on computers everything is encoded using
bits). Although mathematicians believe they use sets as their
foundations, few can really enumerate their axioms. Realistically, it
seems the foundations employed in practice is some amalgam of set theory
equipped with a soft type system, in "$(1+\varepsilon)$-order logic" for
$0\lt\varepsilon\ll1$.

* Classes
:PROPERTIES:
:CUSTOM_ID: h-a673cdab-3aa3-4979-85cf-03e70fe530a9
:END:

We might also want to use a "many-sorted logic" to treat proper classes
as a different "sort" than proper sets. Confusingly, this treatment is
referred to as "second-order set theory" in the literature (as opposed
to "two-sorted set theory", which would make more sense).

* Tarski--Grothendieck Set Theory
:PROPERTIES:
:CUSTOM_ID: h-cd10efca-0ee5-4666-b0de-f24ba41391ac
:END:

We could instead start with some family of collections, "Coll", which
obeys the obvious ZF axioms. Then we form the NBG completion of this
theory, giving us "Coll+". But we could iterate this, getting "Coll++", ..., "Coll + $n$",
for example. Taking the limit of this, well that's precisely what
Tarski--Grothendieck set theory does, and it treats all these
collections as sets. It's useful for handling [[file:category-theory/large-cats.org][large categories]].

The formal definition of Tarski--Grothendieck set theory is just ZF + Universes.
That is to say, given any set $X$, we can find a Grothendieck universe $\mathcal{U}$
containing $X$. What is a "Grothendieck universe"? It is a set
$U$ such that:

1. It is transitive: for each $X\in U$ and $x\in X$, we have $x\in U$
2. For each $X\in U$, its power set $\mathcal{P}(X)\in U$
3. It contains the empty set: $\emptyset\in U$
4. Let $I\in U$, let $\{X_{\alpha}\}_{\alpha\in I}$ be a family of
   elements of $U$. Then their union $\bigcup_{\alpha\in I}X_{\alpha}\in U$.

The exact axioms vary. Some omit the inclusion of the empty set, others
require the inclusion of the natural numbers instead. But with the
axioms we have given, we see every Grothendieck universe is a model for
ZF set theory.

See:

- [[https://ncatlab.org/nlab/show/Grothendieck+universe][Grothendieck Universe]] on nLab
- [[https://en.wikipedia.org/wiki/Grothendieck_universe][Grothendieck Universe]] on Wikipedia
- [[https://en.wikipedia.org/wiki/Tarski%E2%80%93Grothendieck_set_theory][Tarski--Grothendieck set theory]] on Wikipedia

* Consistency
:PROPERTIES:
:CUSTOM_ID: h-8ff0ad00-3c76-46eb-a08d-a259b858fedb
:END:

There have been some explorations of the consistency of ZF using Turing
machines and Godel encodings. (Adding the axiom of choice does not
affect consistency, i.e., Con(ZF) iff Con(ZFC) is a tautology.)

- https://turingmachinesimulator.com/shared/vgimygpuwi
- https://github.com/sorear/metamath-turing-machines/blob/master/zf2.nql
 

* References
:PROPERTIES:
:CUSTOM_ID: h-6dbb1f0d-dfc1-49a4-ae43-453ecf63a7bd
:END:

- Thomas Jech, \\
  {{{book-title(Set Theory: The Third Millennium Edition, revised and expanded)}}}. \\
  Springer, 2003.
- Thomas Jech and K. Hrbáček, \\
  {{{book-title(Introduction to Set Theory)}}}. \\
  Marcel Dekker, 3rd edition, 1999.
- Mike Shulman, \\
  "Set theory for category theory". \\
  [[https://arxiv.org/abs/0810.1279][arXiv:0810.1279]]

** Many-Sorted Models of Sets and Classes
:PROPERTIES:
:CUSTOM_ID: h-912813df-2c88-4a03-aa81-3fa855993460
:END:

- V. Gitman,\\
  [[https://victoriagitman.github.io/talks/2018/01/03/the-emerging-zoo-of-second-order-set-theories.html][The emerging zoo of second-order set theories]]
- Kameryn J Williams, \\
  "The Structure of Models of Second-order Set Theories". \\
  [[https://arxiv.org/abs/1804.09526][arXiv:1804.09526]], 209 pages.