#+TITLE: Writing Mathematics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2024-06-04T09:19:05-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Tuesday June  4, 2024 at  9:19AM

These are random notes from various places, and my experiences at
writing mathematics.

* Steenrod, Halmos, Schiffer, Dieudonne, "How to write mathematics"
:PROPERTIES:
:CUSTOM_ID: h-6a990418-85d7-4714-b7ee-20043a38da59
:END:

** Steenrod's essay
:PROPERTIES:
:CUSTOM_ID: h-9ec74949-7351-48f9-a21f-d280d8f656aa
:END:

- Steenrod distinguishes {{{dfn(formal structure)}}} in mathematical
  writing from {{{dfn(informal structure)}}} and asserts "This division
  of the material should be conspicuously maintained in any mathematical
  presentation" because it makes the logical structure clear.
  - Formal structure: definitions, theorems, proofs
  - Informal structure: motivations, analogies, examples,
    "metamathematical explanations"
- The primary purpose of a book is to present the formal structure.
- A secondary purpose (almost as important) is to offer the reader a
  method whereby they can fit the new structure into what they already
  know. It is here, in this secondary purpose, that authors exhibit
  greatest variations in skill and art.
  - What are the basic questions that will be answered?
  - What are the crucial examples that motivate development?
  - What are vaguely formulated principles from which the entire theory
    seems to unroll effortlessly?
- Huge danger in writing /about/ mathematics instead of /doing it/

*** Expository problems of formal structure
:PROPERTIES:
:CUSTOM_ID: h-348f482d-88c6-4725-80fb-0552de84f428
:END:

- "Normal readers" start at the beginning, read every page, all the way
  until the end.
- "Grasshopper readers" read a book to fill gaps in knowledge

#+begin_quote
The needs of the grasshoppers are served by a good map of the
territory, an adequate directory, numerous sign posts, and an index
of locations. By a /map/ I mean an outline of the results of the book,
such as can be given in an introductory chapter (see the next section
where this is discussed). By a /directory/ I mean the table of contents;
to be adequate, it should contain section headings as well as chapter
titles. (By a /section/ I mean a unit whose average length is three to
five pages.) The /sign posts/ are the chapter titles, section headings,
the paragraph headings such as Definition, Theorem, etc., and the
numbers of these and other important statements.
#+end_quote

- Steenrod vociferously advocates paragraph numbering, with the numbers
  living in the left margin (apparently he believes this makes it easier
  to locate the paragraph): "Actually it would be most convenient to
  have the numbers appear in the left margins, but this requires
  exceptionally expensive setting of type. The next best procedure is to
  use boldface numbers close to the left margin. Authors must deal
  firmly with editors who complain of the ugliness of the boldface
  splotches running down the page."
  - Actually, thinking about this some more, I would argue that the
    number should be in the "outer margin" for books (and in footnote
    size), and/or following the dictionary with the "start section" and
    "final section" [if different] in the header of the page. This would
    satisfy the desire for "quickly being able to locate a paragraph by
    number".  
- If we recall our reading habits, most mathematicians are grasshoppers
  (or so Steenrod asserts). So we should write for grasshoppers.

*** The informal structure
:PROPERTIES:
:CUSTOM_ID: h-2eb40d30-9038-4870-b479-b2f1fd0043a5
:END:

- With informal structure, the restrictions are minimal and guidelines
  are difficult to discern.
- The introductory parts discuss the following kinds of informal
  material:
  1. brief reviews of background material to set the stage,
  2. presentation of motivations or leading questions,
  3. considerations of examples to derive conjectures,
  4. rough descriptions of examples to be obtained and methods to be used,
  5. an outline of the book by chapters.
- Informal items which follow related formal material:
  1. connections with other subjects,
  2. discussions of alternative treatments, and
  3. historical comments.
- Weyl's /The Classical Groups/ is cited as exemplary in providing
  historical notes and bibliographical references.
- Do we really need an introductory chapter?
- There are two ways a student learns material, which anachronistically
  seem to correspond to bottom-up programmind and top-down programming:
  1. (Bottom-up) Ask the reader to examine hte lumber, bricks, and small structural
     members out of which the building is to be made, then to make
     subassemblies, and finally erect the building from these.
  2. (Top-down) Describe the building roughly but globally and provide a
     framework for viewing it, then examine the construction of the
     building in detail.
- Steenrod advocates the "top-down" approach to exposition which he
  calls "successive refinement".
     
*** Successive Refinements
:PROPERTIES:
:CUSTOM_ID: h-9da8c34a-1936-4d01-9485-75e08b860ea0
:END:

- This is an incomplete section, and it's unclear what Steenrod is
  really advocating here.

** Halmos's Essay
:PROPERTIES:
:CUSTOM_ID: h-d767e507-f335-4eac-b937-89968dff4e2a
:END:

This is probably the most famous entry in the book, and can be found if
you google for it. The essay spans pages 19--48 (so, roughly 29 of the
64 pages of the book, nearly half the book is Halmos's essay!). The
essay consists of 21 sections, beginning with section 0 "Preface".

1. Have something to say
   - The problem is to communicate an idea. To do so, and to do it
     clearly, you must:
     - have something to say,
     - have someone to say it to,
     - organize what you want to say,
     - arrange it in the order you want it said in,
     - write it, rewrite it, re-rewrite it several times,
     - be willing to think hard about it and work hard on the mechanical
       details (e.g., diction, notation, punctuation, etc.).
   - That's basically it.
2. Say something
   - Problem 1: you have nothing to say.
   - Problem 2: you have too much to say.
     - Calculus textbooks have this problem because "calculus" isn't a
       single subject, it's an alloy: a mixture of
       many interesting subjects.
   - "To have something to say is by far the most important ingredient
     of good exposition".
3. Speak to someone
   - This determines:
     - the amount of motivation you need to put in,
     - the extent of informality you may allow yourself,
     - the fussiness of the detail that is necessary,
     - the number of times things have to be repeated.
   - All writing is influenced by the audience. But given the audience,
     an author's problem is then to communicate with it as best they can.
   - Anticipate and avoid the reader's difficulties.
4. Organize first
   - Organize and arrange the material so as to (a) minimize the resistance
     and maximize the insight of the reader, (b) keep the reader on
     track with no unintended distractions.
   - Why prefer a book over a stack of papers?
     - Efficient and pleasant arrangement
     - Emphasis where emphasis is needed
     - Indication of interconnections
     - Description of examples and counter-examples on which the theory
       is based.
   - These are precisely "organization".
   - Once you know what you want to say (and to whom you want to say
     it), the next step is to make an outline.
   - To organize a subject means: to decide what the main headings and
     subheadings are, what goes under each, and what are the connections
     among them. (A diagram of the organization is a graph, probably a
     tree, but not a linear chain.) There are many ways to organize a
     subject.
     - We then arrange the results of the method of organization in a
       linear fashion.
     - Organization > Arrangement.
   - The preparation of an outline can take years (or, at the very
     least, many weeks).
   - Halmos remarks that when he does his daily work, he daydreams about
     the project, and as ideas occur he jots them down on loose slips of
     paper then places them "helter-skelter" in a folder. Ideas could be
     what fields of math to include, it could be a proof, it may be a
     witticism. Then when Halmos writes, he "plays solitaire" with the
     slips in the folder. (Page 25, first full paragraph of the page.)
   - "What to put in?" is as important as what to leave out.
5. Think about the alphabet
   - Think hard about the symbols you use, the notation used, because if
     it's adopted...then it's impossible to change.
   - Halmos says he writes tables of notation before writing a book,
     with different letters in different fonts and what they correspond to.
   - Personally, I'm not as pessimistic as Halmos. When he says
     something like "Who would dare write 'Let 6 be a group.'?", well
     finite group theorists do this! So perhaps we should not be quite
     as paranoid as Halmos when it comes to notation, but we should
     abstract away notational choices as LaTeX macros.
6. Write in spirals
   - It's impossible to know what to write until after it's done. You
     know what to put in chapter 1 (or how it should've been written)
     only once you've completed your draft and have moved on to
     chapter 2. But once you've finished chapter 2, you realize how much
     better it could have been if you had only written Chapter 1
     slightly differently.
   - Halmos says this is fine and natural, and that the correct order
     for writing a book is: 1, 2; 1, 2, 3; 1, 2, 3, 4; etc.
   - But the first step in writing, rewriting, re-rewriting, etc., is
     writing.
   - "There is no better incentive for writing a good book than a bad book."
   - In the first draft of each chapter, Halmos recommends that "you
     spill your heart, write quickly, violate all rules, write with hate
     or with pride, be snide, be confused, be 'funny' if you must, be
     unclear, be ungrammatical---just keep on writing."
   - Do not edit, but rewrite.
7. Organize always
   - Spiral writing goes hand-in-hand with spiral organizing
   - Review the material introduced in section 1 in future sections (as
     examples, limitations, generalizations, etc.). The material in
     sections 1 and 2 should be reviewed in section 3 (as examples,
     counter-examples, epitomizing various properties, etc.), and so on.
   - But in this process, you may realize there are important examples
     which should have been given in section 1 for use later on
   - This seems to be the gist of "spiral organizing"
8. Write good English
9. Honesty is the best policy
10. Down with the irrelevant and the trivial
11. Do and do not repeat
12. The editorial we is not all bad
13. Use words correctly
14. Use technical terms correctly
15. Resist symbols
16. Use symbols correctly
17. All communication is exposition
18. Defend your style
19. Stop
20. The last word

** Menahem M Schiffer's Essay
:PROPERTIES:
:CUSTOM_ID: h-80a67b77-d30c-4544-a2db-ce2d3d4c5692
:END:

1. Schiffer writes "more as a reader...than as an author". But there is
   no universal prescription for writing in a clear, informative,
   attractive manner.
2. When planning, the author must determine their audience and what
   amount (and type) of information the author wishes to
   transmit. Schiffer partitions the space of writing into four types of
   expositions: research paper, monograph, survey, textbooks.
3. *Research Paper.*
   - Generous quotation of sources, clear stating of facts used, precise
     definitions, complete proofs (if proofs are given at all).
   - It is very important to write a good introduction. You must help
     the reader determine if the paper is relevant to their research as
     quickly as possible.
4. *Monographs.*
   - Requires much more planning and attention than the research paper.
   - Since monographs have a longer lifetime than research papers, it's
     more important to plan and write well.
   - A monograph should include the background and motivation for basic
     concepts, the growth of ideas and methods, more detailed proofs
     should be provided, an extensive bibliography is a must.
   - A good introductory chapter should whet the appetite of the reader.
   - A historic and genetic approach may yield a good general guideline
     for organizing the monograph.
   - A monograph is not written to show how erudite and clever the
     author is, but to teach the reader some new material.
5. *Surveys.*
   - A survey is an invitation to a field of research, not an introduction.
   - Motivation, background, history, and problems should be displayed.
6. *Textbooks.* (This is the longest, or second longest, section of the piece)
   - Schiffer restricts discussion to writing advanced textbooks for
     senior or graduate level.
   - The purpose of a textbook is to take a student (with a specific
     amount of preparation) and introduce them to a new field of
     mathematical endeavor. Therefore the presupposed knowledge of the
     reader should be precisely realized, and the treatment of the
     textbook takes this carefully into consideration.
   - The textbook should rise from the known to the unknown in easy
     steps. It should start from the special and intuitive to the
     general and abstract.
   - Applications and examples should be generously given.
   - A real textbook should contain more material than could be covered
     in a single course. This allows teachers a certain amount of
     flexibility when using the textbook.
   - "The main desideratum would be that the solution to all significant
     problems in the exercise section should be given, or at least
     hinted at."
   - The textbook author should "aim for clear and interesting
     exposition rather than for completeness or novelty."
7. Now, instead of discussing "what book to write", Schiffer turns to
   the question "How to write it?"
   - Plans change and the production of any book is a process of
     successive approximation.
   - The worst moment in preparation of a book (or any writing) is the
     first moment staring at a blank sheet.
   - Schiffer's advice: start with a chapter which interests you the
     most, in which you think you can be most original and helpful.
   - Then ask yourself what material is needed to bridge from the
     presupposed knowledge of the reader to that chapter you've just
     written?
   - The auxiliary chapters are probably dry, unintersting, and consists
     of most of the text you've written. These chapters have to be
     fleshed out. "The important principle is that no chapter shall be
     entirely auxiliary and be the servant of some other chapter."
   - Schiffer contrasts this to how Polya writes his books. Polya uses a
     system which Polya calls "skeleton writing". Prepare the book
     according to your plan, but in a very sketch and incomplete
     way. Once the skeleton is ready, flesh it out and bring it to life.
   - Use the manuscript as the basis for a course to test (1) the clearness
     of exposition and (2) the logic of the arrangement.
   - Final advice: "Enjoy your writing and relax while doing so. Write
     in a natural style and leave the officialese and formal style to
     administrators and government departments."
     
** Dieudonne's Essay
:PROPERTIES:
:CUSTOM_ID: h-c2d89fe2-64b5-4ac8-a048-fecb8a294a8c
:END:

- This is a short essay (a mere 3 pages!) disagreeing with everything
  Steenrod advocates.

* Knuth, Larrabee, Roberts, "Mathematical Writing"
:PROPERTIES:
:CUSTOM_ID: h-3b77b4ed-12c1-4e96-b7dc-f4c6f448fc1b
:END:

This is a bunch of lecture notes, with all the shorthand and frustrating
cryptic ambiguity that lecture notes possess. The lectures have been
thrown up on [[https://youtube.com/playlist?list=PLABJEFgj0PWV22nvw3YKXvR_n1NB6fn5D&feature=shared][Youtube]] (and [[https://youtube.com/playlist?list=PLOdeqCXq1tXihn5KmyB2YTOqgxaUkcNYG&feature=shared][here]]). A draft [[https://jmlr.csail.mit.edu/reviewing-papers/knuth_mathematical_writing.pdf][PDF]] is online too.

** Lecture 10: Presenting Algorithms
:PROPERTIES:
:CUSTOM_ID: h-6a57ac3a-c0d6-4d90-be37-3c4961d24ccd
:END:

There's frustratingly little of use in this lecture.

*** About Algorithms
:PROPERTIES:
:CUSTOM_ID: h-0289f012-bf77-4cfa-8dea-76e6f2ccbaf4
:END:

My personal observations, reading Knuth's /Art of Computer Programming/,
is that the book is written about assembly programs. The "algorithm"
environments are really extended comments about the programs, rephrased
in complete generality so it resembles Theorems and could be applied in
any programming language. (I say this after having read a good chunk of
the book without even glancing at the MIXAL code; then revisiting the
books intent on learning MIXAL to transcribe some IBM-704 assembly.)

The numbered steps in the algorithms are useful when keeping track of
"where we are" in a MIXAL program.

The parenthetical remarks are invariants used in a formal proof of
correctness.

*** About ~WEB~
:PROPERTIES:
:CUSTOM_ID: h-cc41d351-971a-4d9b-82f6-69e4cb294a2f
:END:

Knuth introduces the ~WEB~ system in this lecture. It's based on two
principles of writing:

1. The correct way to explain a complex thing is to break it into parts
   and then explaineach part;
2. Things should be explained twice (formally and informally).

These two principles naturally led to programs made of modules that
begin with text (informal explanation) and finish with Pascal (formal
explanation).

** Lecture 11: Literate Programming
:PROPERTIES:
:CUSTOM_ID: h-cb32061d-d5c9-49fd-911f-43369b0d4638
:END:

A lot of rules about Pascal programming in ~WEB~. Perhaps the only gem
in this lecture is: "We are trying to convey an intuition of what is going on, so a high-level account
is much more helpful."

Each module/section/chunk of code should be manageable in size. Knuth
thinks about a dozen lines of code is just about the right size.