#+TITLE: NaN Boxing
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2023-08-23T10:56:13-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Wednesday August 23, 2023 at 10:56AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-55385882-0ba1-4181-8cb2-ef3d7c2cfaec
:END:

The basic idea is that, if we are writing an interpreter or virtual
machine, then how can we distinguish a pointer from...anything else?

One idea is to just use a naive data structure encoding the possible
values. At best, we would have an overhead of an additional 64-bits (on
a 64-bit system), doubling the size of a pointer.

But if we use a NaN, we can encode any 51-bit pointer (or 42-bit pointer
and we get $2^{9}=512$ possible constants).

There is another alternative, to use tagged pointers.

** Summary of NaN-Boxing
:PROPERTIES:
:CUSTOM_ID: h-8e806502-9bba-4a35-9640-b4a3406a1e41
:END:

More explicitly, there are 2 types of NaN values (the sign bit is
arbitrary for NaN in both cases):

1. Quiet NaN: the exponent bits are all 1, the bit after the exponent is
   "set" (i.e., equal to 1), and then the rest of the 51 bits in the Mantissa are arbitrary
2. Signaling NaN: the exponents are all 1, the bit after the exponent is
   "unset" (i.e., equal to 0), and then the rest of the 51 bits are 0.

There are 51 free bits in the quiet NaN, so we use it to store information.

* Problems with NaN-Boxing
:PROPERTIES:
:CUSTOM_ID: h-d3cd56d2-092d-40c5-b462-224f2f02143d
:END:

** Equality Fails
:PROPERTIES:
:CUSTOM_ID: h-316355cb-7ab7-436a-9c24-52e3e4877f58
:END:

We cannot meaningfully compare 2 NaN values, so equality fails. We'd
have to change it to a 64-bit integer for equality to work as
expected. This is a problem in Java, for example.

- [[http://ppkwok.blogspot.com/2012/11/java-cafe-1-never-write-nan-nan_24.html][Java Cafe 1: Never write ~NaN == NaN~ (they're not equal)]]

* Alternatives
:PROPERTIES:
:CUSTOM_ID: h-1d641dab-d665-441e-9aee-68d8e1fac6f9
:END:

** Pointer Tagging
:PROPERTIES:
:CUSTOM_ID: h-6b6285ee-a96e-42e1-b1ec-dd1a95184df7
:END:

When we have a 64-bit system, it turns out that not all 64-bits are
necessary for pointers. After all, $2^{30}$ bytes is a Gibibyte, and
$20^{40}$ bytes is a Tebibyte, so a 40-bit pointer can access 1 Tebibyte
of memory; and $2^{50}$ bytes is a Pebibyte. If we use 8 bits to store
metadata and 56 bits for information (the "payload"), then we can refer
to 64 Pebibytes (72.057 Petabytes) of memory.

For reference:
- in May 2017, HP announced it built a computer with 160 Terabytes of RAM ([[https://www.bbc.com/news/technology-39936975][BBC]]).
- The architectural specifications for Intel64 and AMD64 specify 52-bit
  pointer size for virtual memory addresses.
- ARMv8.2 has a larger VA space of up to 52-bits, before this ARM had
  48-bit virtual address size. (The bits 63:48 are set to 0 for
  user-space, and 1 for kernel space.)

I have the feeling we may end up staggering into a false sense of
security, unwittingly imitating Bill Gates's 1985 remark to InfoWorld,
"When we set the upper limit of PC-DOS at 640K, we thought nobody would
ever need that much memory."

We may or may not even need 8 bits for metadata (heck, 3 bits may suffice).
  
** Pointer Tagging + Memory Management
:PROPERTIES:
:CUSTOM_ID: h-eda564c0-559a-43dc-9a56-deacbe9a40b4
:END:

The basic idea is that we will implement our own garbage collector,
which basically allocates an "arena" of memory (a glorified array of
contiguous bytes), then use our own "pointer" type (which is just an
index to our array of contiguous bytes). This basically rolls our own
[[https://en.wikipedia.org/wiki/Virtual_address_space][Virtual address space]].

** Pointer Alignment
:PROPERTIES:
:CUSTOM_ID: h-d246718d-172f-4309-b2a0-0474ac03ff74
:END:

We can [[https://en.wikipedia.org/wiki/Data_structure_alignment][recall]] that a memory address $A$ is {{{dfn(n-byte aligned)}}}
when $A$ is a multiple of $n$. This means $A$ has a minimum of
$\log_{2}(n)$ least-significant zeros when expressed in binary.

So a 64-bit address (= 8-byte address) is aligned if at least
$\log_{2}(8)=3$ least-significant bits are zeros when expressed in binary.

If we stipulate pointers are always from a ~malloc~ (and we are using a
64-bit computer), then we have 3 bits which we can use for metadata.

- Max Bernstein, [[https://bernsteinbear.com/blog/small-objects/][Small objects and pointer tagging]] 11 Feb 2021

* References
:PROPERTIES:
:CUSTOM_ID: h-7d6a332d-1eef-4a35-9ba1-28f0e9211547
:END:

- [[https://anniecherkaev.com/the-secret-life-of-nan][the secret life of NaN]]
- Leonard Schütz [[https://leonardschuetz.ch/blog/nan-boxing/][Dynamic Typing and NaN Boxing]] 8 September 2020
- [[https://piotrduperas.com/posts/nan-boxing][NaN boxing or how to make the world dynamic]]
- [[http://ppkwok.blogspot.com/2012/11/java-cafe-1-never-write-nan-nan_24.html][Java Cafe 1: Never write ~NaN == NaN~ (they're not equal)]]
- [[https://bernsteinbear.com/blog/compiling-a-lisp-2/][Compiling a Lisp: Integers]]
- [[https://bernsteinbear.com/blog/compiling-a-lisp-3/][Compiling a Lisp: Booleans, characters, nil]]
- Bob Nystrom, [[https://craftinginterpreters.com/optimization.html][Crafting Interpreters]] chapter 30 on optimization
- Nikita Popov, [[https://www.npopov.com/2012/02/02/Pointer-magic-for-efficient-dynamic-value-representations.html][Pointer magic for efficient dynamic value representations]] 
  2 February 2012, discusses examples with C++ code
- Albert Yang, [[https://albertnetymk.github.io/2016/08/06/nan_boxing/][NaN Boxing]] 6 Aug 2016 for example C code
- [[http://wingolog.org/archives/2011/05/18/value-representation-in-javascript-implementations][value representation in javascript implementations]] 18 May 2011
- David Gudeman's "Representing Type Information in Dynamically Typed
  Languages" October 1993 [[https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.39.4394&rep=rep1&type=pdf][PDF]]
- https://webkit.org/blog/7846/concurrent-javascript-it-can-work/
- https://stackoverflow.com/questions/57348783/how-does-v8-store-integers-like-5
- https://stackoverflow.com/questions/16198700/using-the-extra-16-bits-in-64-bit-pointers
- https://v8.dev/blog/pointer-compression

** Example Implementations
:PROPERTIES:
:CUSTOM_ID: h-7205480f-c3ae-40a8-b026-f60cbf467bc7
:END:

- zuiderkwast's [[https://github.com/zuiderkwast/nanbox][nanboxing]] single header library for C
- Femtolisp's [[https://github.com/JeffBezanson/femtolisp/blob/master/flisp.h][object implementation]]
- https://source.chromium.org/chromium/v8/v8.git/+/46afc4f9a6008c3880fcc00783b4210cb467aa9a:src/objects/smi.h;l=23
- Chicken Scheme's [[https://wiki.call-cc.org/man/4/Data%20representation][data representation]]