#+TITLE: Numerical Analysis
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-07T20:57:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Monday December  7, 2020 at  8:57PM
#+include: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

#+begin_quote
Numerical analysis is the blackest of the black arts. (Gerald Sussman)
#+end_quote

* Overview

The basic problem numerical analysis addresses: given some
computation we want to perform in mathematics, how can we get the
computer to do it? Specifically when we approximate real numbers by
floating-point arithmetic, and we do not perform any symbolic
manipulation.

- [[file:numerical-analysis/index.org][Index of Topics]]

* References

- Richard L. Burden and J. Douglas Faires,
  {{{book-title(Numerical Analysis)}}}.
  8th ed., Thomson, 2005.
- David Goldberg,
  "What Every Computer Scientist Should Know About Floating-Point Arithmetic".
  March 1991, [[https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html][eprint]].
- Peter Olver,
  [[https://www-users.math.umn.edu/~olver/num.html][Lecture notes on Numerical Analysis]].

** Numerical Differenial Equations

- J. C. Butcher,
  {{{book-title(Numerical Methods for Ordinary Differential Equations)}}}.
  3rd Edition
- David F. Griffiths, Desmond J. Higham,
  {{{book-title(Numerical Methods for Ordinary Differential Equations: Initial Value Problems)}}}.


** Theorem Provers and Numerical Analysis

- Sylvie Boldo, Claude Marché,
  "Formal verification of numerical programs: from C annotated programs to mechanical proofs".
  [[https://hal.inria.fr/hal-00777605/document][Eprint]], 2013, 18 pages.
- Ruben Antonio Gamboa,
  "Mechanically Verifying Real-Valued Algorithms in ACL2".
  PhD thesis, U. Texas at Austin, [[https://www.cs.utexas.edu/ftp/boyer/diss/gamboa.pdf][PDF]]
- David M Russinoff,
  {{{book-title(Formal Verification of Floating-Point Hardware Design: A Mathematical Approach)}}}.
  Springer, 2018.

** Numerical Linear Algebra

- G.W. Stewart, {{{book-title(Matrix Algorithms)}}}. 2 volumes
- James Demmel, {{{book-title(Applied Numerical Linear Algebra)}}}.
- Trefethen and Bau, {{{book-title(Numerical linear algebra)}}}.