#+TITLE: Computer Science
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December 12, 2020 at  1:15PM
#+INCLUDE: ../org-macros.org

* Overview

Computer science has emerged into a sprawling field. Although I am
trying to focus on numerical analysis (to think further about
solving math and physics problems), the entire domain of
programming and computer science are rather fascinating.

Right now, I am working my way through the =scmutils= library used
in {{{booktitle(The Structure and Interpretation of Classical Mechanics)}}}.
As I read through it, I'm thinking about how to implement the
algorithms in Common Lisp.

- [[/numerical-analysis.org][Numerical Analysis]] for all my computational needs
- [[./literate-programming.org][Literate Programming]] is one method to programming, as espoused by
  Donald Knuth
- [[./abstract-machines.org][Abstract Machines]] as virtual machines for functional programming
  languages, began originally as pen-and-paper models of computer hardware
  + [[./abstract-machines/secd.org][SECD Machine]] the primordial abstract machine which started it all
- [[./lisp.org][Lisp]], the second-oldest language around, is my preferred language
  for programming most things
  + [[./generic-dispatch.org][Generic Dispatch]] for multimethods, which can be implemented in
    various different ways
  + [[./mal.org][Make a Lisp]] a literate program experiment, using a generic blub (C)
    to implement a Lisp interpreter.

  
