#+TITLE: Standard ML
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-25T15:31:25-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Thursday March 25, 2021 at  3:31PM

* Overview

The primordial "statically typed functional programming language",
Standard ML was invented to program theorem provers. The language
consists of two parts:

1. The Core Language = the typed-lambda calculus equipped with algebraic
   data types
2. The module language = the signatures, structures, functors

This is incredibly minimalistic compared to, say, Haskell.

#+begin_remark
The "pure" fragment of the core language is called {{{define(PCF)}}}
(Programming Computable Functions) for historic reasons, which is itself
an interesting little language.
#+end_remark

* References

** PCF
  Plotkin  in  [61]  (see  also  [65]  and  [67]
There are concerns about whether the operational semantics of PCF
coincides with its denotational semantics; if so, then it's a property
called [[https://plato.stanford.edu/entries/games-abstraction/]["full abstraction"]] (Stanford encyclopedia of philosophy entry).

- Gordon Plotkin,
  "LCF considered as a programming language".
  /Theoretical Computer Science/ *5*, 3 (1977) 223–255.
  [[https://homepages.inf.ed.ac.uk/gdp/publications/LCF.pdf][PDF]]
- Robin Milner,
  "Fully abstract models of typed λ-calculi".
  /Theoretical Computer Science/ *4* (1977) 1–22.
- Samson Abramsky, Radha Jagadeesan, Pasquale Malacaria,
  "Full Abstraction for PCF".
  [[https://arxiv.org/abs/1311.6125][arXiv:1311.6125]], 50 pages.
- JME Hyland, CHL Ong,
  "On Full Abstraction for PCF: I, II, and III".
  Eprint: [[https://ora.ox.ac.uk/objects/uuid:63c54392-39f3-46f1-8a68-e6ff0ec90218/download_file?file_format=pdf&safe_filename=1-s2.0-S0890540100929171-main.pdf&type_of_work=Journal+article][pdf]], 124 pages.
- Vladimir Sazonov,
  "Inductive Definition and Domain Theoretic Properties of Fully Abstract Models for PCF and PCF+".
  [[https://arxiv.org/abs/0707.3170][arXiv:0707.3170]], 50 pages.

** Category Theory

One major unresolved issue, for me, is whether we can articulate
Standard ML in terms of category theory. It's equally unclear to me if
Haskell can be articulated in terms of /genuine/ category theory (*Hask*
is not a category).

- G. Bellè, C. B. Jay, E. Moggi,
  "Functorial ML".
  /PLILP 1996: Programming Languages: Implementations, Logics, and Programs/
  pp 32-46
  [[https://doi.org/10.1007/3-540-61756-6_75][eprint]]
- Edward Kmett, "On *Hask*". [[https://youtu.be/Klwkt9oJwg0][Youtube]], 18 July 2014 (1 hr 2 min)
- Moggi, "An Abstract View of Programming Languages" [[https://www.ics.uci.edu/~jajones/INF102-S18/readings/09_Moggi.pdf][PDF]]
