#+TITLE: TeX Notes
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-10-24T09:48:24-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Sunday October 24, 2021 at  9:48AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-84848014-a2ce-403a-9dec-20a86af11ca5
:END:

These are random observations about TeX and LaTeX.

* Poor Man's LaTeX
:PROPERTIES:
:CUSTOM_ID: h-f706e3fa-e88f-4439-9095-907b9b20d0e2
:END:

I've been curious about how LaTeX is built out of TeX macros for a while
now. These are just some observations about it.

** Environments
:PROPERTIES:
:CUSTOM_ID: h-61eb6d82-0759-480a-ac89-743dd455f86d
:END:

Someone asked on tex.stackexchange about how environments in LaTeX are
implemented using only plain TeX. David Carlisle's [[https://tex.stackexchange.com/a/572575][answer]] was quite
enlightening: ~\begin{foo}~ executes ~\foo~, and ~\end{foo}~ executes
~\endfoo~. But this requires redefining plain TeX's ~\end~ primitive,
setting it to be ~\@@end~ in LaTeX.

This sparked a curiousity about LaTeX's implementation details. They can
be found, for texlive users, in
~/usr/share/texlive/texmf-dist/tex/latex-dev/base/latex.ltx~ or somewhere
similar.

If one imitates LaTeX, and writes something like ~\let\@@end\end~, then
one needs to redefine ~\bye~ to be something like:

#+begin_src tex
\def\makeatletter{\catcode`\@11\relax}
\def\makeatother{\catcode`\@12\relax}
\makeatletter
\let\@@end\end
\outer\def\bye{\par\vfill\supereject\@@end}

% define environment syntax
\def\begin#1{\begingroup\csname#1\endcsname}
\def\end#1{\csname end#1\endcsname\endgroup}
\makeatother
#+end_src

*** What LaTeX does
:PROPERTIES:
:CUSTOM_ID: h-d37b46ee-efb8-4b81-8c1c-0afc91010dbb
:END:

In ~latex.ltx~ around lines 4400, we find

#+begin_src tex
\DeclareRobustCommand\begin[1]{%
  \@ifundefined{#1}%
    {\def\reserved@a{\@latex@error{Environment #1 undefined}\@eha}}%
    {\def\reserved@a{\def\@currenvir{#1}%
     \edef\@currenvline{\on@line}%
     \csname #1\endcsname}}%
  \@ignorefalse
  \begingroup\@endpefalse\reserved@a}
\edef\end
  {\unexpanded{%
     \romannumeral
       \ifx\protect\@typeset@protect
       \expandafter       %1
         \expandafter        %2
       \expandafter       %1
           \expandafter         %3 expands the \csname inside \end<space>
       \expandafter       %1
         \expandafter        %2  expands \end<space>
       \expandafter       %1     expands the \else
           \z@
       \else
         \expandafter\z@\expandafter\protect
       \fi
   }%
   \expandafter\noexpand\csname end \endcsname
  }
\@namedef{end }#1{%
  \csname end#1\endcsname\@checkend{#1}%
  \expandafter\endgroup\if@endpe\@doendpe\fi
  \if@ignore\@ignorefalse\ignorespaces\fi}
\def\@checkend#1{\def\reserved@a{#1}\ifx
      \reserved@a\@currenvir \else\@badend{#1}\fi}
\let\@currenvline\@empty
% ...
% 4907:
\def\@doendpe{\@endpetrue
     \def\par{\@restorepar
              \clubpenalty\@clubpenalty
              \everypar{}\par\@endpefalse}\everypar
               {{\setbox\z@\lastbox}%
                \everypar{}\@endpefalse}}
#+end_src

** Equations
:PROPERTIES:
:CUSTOM_ID: h-481e8d2b-e5e1-41be-a892-ebba10a94b60
:END:

The implementation is fairly straightforward.

#+begin_src tex
%% LaTeX's implementation:
%%
%% \def\stepcounter#1{%
%%   \addtocounter{#1}\@ne
%%   \begingroup
%%     \let\@elt\@stpelt
%%     \csname cl@#1\endcsname
%%   \endgroup}
%% \def\@definecounter#1{\expandafter\newcount\csname c@#1\endcsname
%%      \setcounter{#1}\z@
%%      \global\expandafter\let\csname cl@#1\endcsname\@empty
%%      \@addtoreset{#1}{@ckpt}%
%%      \global\expandafter\let\csname p@#1\endcsname\@empty
%%      \expandafter
%%      \gdef\csname the#1\expandafter\endcsname\expandafter
%%           {\expandafter\@arabic\csname c@#1\endcsname}}
\def\stepcounter#1{
    \expandafter\global\expandafter\advance\csname c@#1\endcsname by1
}
\def\setcounter#1#2{
    \expandafter\global\csname c@#1\endcsname=#2
}
\def\@definecounter#1{
    \expandafter\newcount\csname c@#1\endcsname
    \setcounter{#1}{0}
    \expandafter
    \gdef\csname the#1\expandafter\endcsname\expandafter
         {\expandafter\number\csname c@#1\endcsname}
}

\@definecounter{equation}
\def\equation{$$\refstepcounter{equation}}
\def\endequation{\eqno \hbox{\@eqnnum}$$\@ignoretrue}
\def\@eqnnum{{\normalfont \normalcolor (\theequation)}}
#+end_src
* Math Gallery
:PROPERTIES:
:CUSTOM_ID: h-9003bdc5-57ad-4ef9-aa76-5b45c8f1f8ab
:END:

** Normal Ordering Operators
:PROPERTIES:
:CUSTOM_ID: h-024d8f89-6eec-4422-8e82-ba3e2e15a117
:END:

In Quantum Field Theory (and Vertex Operator Algebras, and related
subjects), we need normal ordering of operators. This has been discussed
at least [[https://tex.stackexchange.com/q/214347][once]] on tex.stackexchange, and the answers are quite good.

** Tractatus Numbering in Plain TeX
:PROPERTIES:
:CUSTOM_ID: h-952ca320-c41f-4992-8f2f-03b63e69c307
:END:

Someone asked for this in plain TeX, and David Carlisle's [[https://tex.stackexchange.com/a/500105/14751][solution]]
fits my needs perfectly.

#+begin_src tex
\newcount\zzdepth
\newcount\zza
\edef\zzbase{\the\allocationnumber}
\zzdepth\allocationnumber
\newcount\zzb
\newcount\zzc
\newcount\zzd

\def\thezz{{%
\ifnum\zzdepth>\zzbase\relax
\advance\zzdepth-1 %
\expandafter\thezz
\fi
}\the\count\zzdepth.%
}

\everypar{{\bf\thezz} }



\def\on{\advance\count\zzdepth 1\relax}
\def\eatstar*{}
\def\down{\futurelet\tmp\xxdown}
\def\xxdown{%
\ifx*\tmp
\advance\zzdepth 1 \count\zzdepth 0\relax
\expandafter\eatstar
\else
\advance\zzdepth 1 \count\zzdepth 1\relax
\fi}

\def\up{\advance\zzdepth -1 \advance\count\zzdepth 1\relax}

\on
This is the first paragraph, paragraph number 1.

\on
This is paragraph number 2.

\down
This is paragraph number 2.1

\down*
This is 2.10

\up
This is 2.2

\down
This is 2.2.1

\up\up
This is 3

\bye
#+end_src

I liked this, but wanted to hack something together more suitable for my
own personal purposes:

#+begin_src tex
\newcount\zzdepth
\newcount\zza
\edef\zzbase{\the\allocationnumber}
\zzdepth\allocationnumber
\newcount\zzb
\newcount\zzc
\newcount\zzd

\def\thezz{{%
\ifnum\zzdepth>\zzbase\relax
\advance\zzdepth-1 %
\expandafter\thezz
\fi
}\the\count\zzdepth.%
}
\def\theM{{\bf\thezz}\quad\ignorespaces}

\def\None#1{\advance\count\zzdepth 1\relax\theM{\bf#1.}\quad\ignorespaces}
\def\Nmany[#1]#2{\advance\zzdepth by#1
  \ifnum#1<0\advance\count\zzdepth 1
  \else\count\zzdepth 1
  \fi\relax
  {\bf\thezz\ #2.}\quad\ignorespaces}
\def\xN{\ifx\tmp[\expandafter\Nmany\else\None\fi}
\def\N{\medbreak\noindent\ignorespaces\futurelet\tmp\xN}

\def\Mone{\advance\count\zzdepth 1\relax\theM}
\def\Mmany[#1]{\advance\zzdepth by#1
  \ifnum#1<0\advance\count\zzdepth 1
  \else\count\zzdepth 1
  \fi\relax\theM}
\def\xM{\ifx\tmp[\expandafter\Mmany\else\Mone\fi}
\def\M{\medbreak\noindent\ignorespaces\futurelet\tmp\xM}


\M
Paragraph 1, reporting!

\M
Paragraph 2, alert!

\N[1]{Theorem}
{\it Paragraph {2.1} should be present.}

\M
This is the first paragraph, paragraph number 1.

\M
This is paragraph number 2.

\M[1]
This is paragraph number 2.1

\M[1]
This is 2.10

\M[-1]
This is 2.3.2

\M[1]
This is 2.2.1

\M[2]
This is, uh, 2.2.1.1.1?

\M[-1]
Wait, what does this do?

\M[-4]
This is 3

Spam and eggs test!

\bye
#+end_src
* Equation Indent
:PROPERTIES:
:CUSTOM_ID: h-f5b3ca7f-2d1e-42ad-a914-d73877c1f0a6
:END:

Sometimes it is useful to have equations be indented by the same amount
(as opposed to being centered). This is done using the ~fleqn~ document
option, usually. For the base classes, this introduces a new dimension
~\mathindent~, which is equal to the length of the ~\leftmargini~ dimension.
In the ~article~ document class, ~\leftmargini~ is 2em for two-column
documents, and 2.5em for single column documents.

