#+TITLE: Classification of Finite Simple Groups
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-02-14T11:09:53-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Monday February 14, 2022 at 11:09AM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-503293b3-12c9-4e7e-a9ad-e3f0089ec368
:END:

This is usually given as the world record for longest proof. The first
proof took around 15000 pages in over a decade of journal articles. The
second generation proof (by Gorenstein, Lyons, and Solomon) is still in progress, and should take around
7000 pages. Although daunting, it involves extraordinarily beautiful
mathematics.

Aschbacher, in his article [[https://www.ams.org/notices/200407/fea-aschbacher.pdf]["The Status of the Classification of the Finite Simple Groups"]] 
(2004) has called the work on the classification problem by
[[https://users.math.msu.edu/users/meierfra/][Ulrich Meierfrankenfeld]], Bernd Stellmacher, Gernot Stroth, and a few
others, a third generation program using the amalgam method as the main
tool. This works appears to be [[https://www2.mathematik.uni-halle.de/stroth/class.html][on Stroth's website]] and continued on
[[https://users.math.msu.edu/users/meierfra/Preprints/CGP/cgp_abstract.html][Meierfrankenfeld's site]] (See also {{{arXiv(1906.07216)}}}.)


* References
:PROPERTIES:
:CUSTOM_ID: h-29bf0074-0324-4028-8386-65a5cf94e149
:END:

** Second Generation Proof
:PROPERTIES:
:CUSTOM_ID: h-919f32fe-ad5e-4f78-ac8d-2e90381410e7
:END:

This is a series of books published by AMS.

- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups/.\\
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.:
  American Mathematical Society, 1994.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 2/.\\
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.:
  American Mathematical Society, 1996.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 3/.\\
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.:
  American Mathematical Society, 1998.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 4. Part II, Chapters 1-4: Uniqueness Theorems/.\\
  Mathematical Surveys and
  Monographs, vol. 40, Providence, R.I.: American Mathematical Society, 1999.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 5/.\\
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.:
  American Mathematical Society, 2002.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 6: Part IV: The Special Odd Case/.\\
  Mathematical Surveys and Monographs, vol. 40,
  Providence, R.I.: American Mathematical Society, 2005.
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The classification of the finite simple groups, Number 7: Part III, Chapters 7–11: The Generic Case, Stages 3b and 4a/.\\
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.: American
  Mathematical Society, 2018
- Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The Classification of the Finite Simple Groups, Number 8: Part III, Chapters 12–17: The Generic Case, Completed/.\\
  Mathematical Surveys and
  Monographs, vol. 40, Providence, R.I.: American Mathematical Society, 2018.
- Inna Capdeboscq and Daniel Gorenstein and Richard Lyons and Ronald Solomon,\\
  /The Classification of the Finite Simple Groups, Number 9: Part V, Chapters 1-8: Theorem $C_{5}$ and Theorem $C_{6}$, Stage 1/.
  Mathematical Surveys and Monographs, vol. 40, Providence, R.I.: American
  Mathematical Society, 2021
