#+TITLE: Unique Factorization Domains
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-02-14T12:20:45-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Sunday February 14, 2021 at 12:20PM

#+ATTR_HTML: :id defn-ufd
#+begin_definition
A {{{define(Unique Factorization Domain)}}} consists of an integral
domain such that for any nonzero $x\in R\setminus R^{\ast}$ there is
some unit $u\in R^{\ast}$ and coprime irreducibles $p_{1},\dots,p_{n}\in R$
and positive integers $e_{1},\dots, e_{n}$ such that

\begin{equation}
x=u p_{1}^{e_{1}}\dots p_{n}^{e_{n}}
\end{equation}

Furthermore, this factorization is unique up to multiplication of $u$
and $p_{j}$'s by units and up to permutation of indices.
#+end_definition

#+ATTR_HTML: :id thm-in-ufd-every-irreducible-is-prime
#+begin_theorem
Let $R$ be a unique factorization domain, then every irreducible $p\in R$
is prime.
#+end_theorem

#+ATTR_HTML: :id thm-in-ufd-gcd-exists
#+begin_theorem
If $R$ is a UFD, then any $x,y\in R$ has a gcd in $R$.
#+end_theorem

#+ATTR_HTML: :id thm-polynomial-ring-over-ufd-isa-ufd
#+begin_theorem
If $R$ is a UFD, then the polynomial ring $R[x_{1},\dots,x_{n}]$ is a UFD.
#+end_theorem

* References
:PROPERTIES:
:CUSTOM_ID: h-3e39cf13-7bf0-43e9-9d18-ad4c9fba20a1
:END:

- Manuel Bronstein, {{{book-title(Symbolic Integration 1: Transcendental Functions)}}}.
  Springer, second ed., 1996.
  Chapter 1 particularly reviews polynomial rings.
- Nathan Jacobson,
  {{{book-title(Basic Algebra I)}}}.
  Chapter 2.
- Serge Lang, {{{book-title(Algebra)}}}.
  Springer, third ed., GTM., 2002.
  Chapter 2.
- James McIvor,
  [[https://math.berkeley.edu/~gmelvin/math113su14/math113su14notes2.pdf][Lecture Notes on Ring Theory]].
  UC Berkeley, Math 113, Summer 2014.
