#+TITLE: Climate Models
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-05T19:31:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at  7:31PM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Energy Balance Model

Typically using a zero-dimensional model via Stefan-Boltzmann
equation and empirical parameters. This can be made more
complicated with 1-dimensional or 2-dimensional models, assuming
the energy budget changes with latitude and/or longitude.

Using Stefan-Boltzmann's law, we would have something like
\begin{equation}
\frac{\D T(t)}{\D t} \sim R - \sigma T(t)^{4}
\end{equation}
where $R$ is net solar influx, $\sigma$ is the Stefan-Boltzmann
constant, $T(t)$ is the temperature of the Earth at time $t$.

** Stochastic Feedback

The first modification to Stefan-Boltzmann's law is to consider a
system of coupled stochastic differential equations accounting for
the concentration of greenhouse gases $c(t)$:
\begin{equation}
\rho C_{P}H \frac{\D T(t)}{\D t} \sim R(c) - \sigma(1 - g(c)) T(t)^{4} + \widehat{f}_{T}(t)
\end{equation}
where now:
- $\rho$ is the density of atmosphere
- $C_{P}$ is specific heat
- $H$ is the depth of the atmosphere
- $g(c)$ is the feedback parameter (modifying the Stefan-Boltzmann
  law)
- $\widehat{f}_{T}(t)$ is a Gaussian forcing term, representing
  fast uncorrelated changes in temperature

We also have
\begin{equation}
\tau_{c}\frac{\D c(t)}{\D t} = -c(t)+\widehat{q}(t) + \widehat{f}_{c}(t)
\end{equation}
where
- $q$ is the addition of greenhouse gases per unit volume to the atmosphere
- $f_{c}(t)$
- $\tau_{c}$ is some appropriate scaling constant

These equations crop up repeatedly in climate science. See, for
example:

+ L. Mahadevan and J.M. Deutch, "Influence of feedback on the
  stochastic evolution of simple climate systems".
  /Proc. of Royal Soc. A/ (2009) [[http://web.mit.edu/chemistry/deutch/technical/pdf15/151ProcRSocA-online%282009%29.pdf][Eprint]]

The argument is that the probability distributions of important
climate variables have fat tails, such that the their expected
values do not exist.

#+begin_puzzle
Can full-fledged general circulation models reproduce this result?
(It remains an open problem.)
#+end_puzzle

*** Integration factor

For the second equation, we may write
\begin{equation}
\frac{\D c(t)}{\D t} + \frac{1}{\tau_{c}}c(t)
= \frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}
\end{equation}
Multiplying through by a multiplication factor $\mu(t)$
\begin{equation}
\mu(t)\frac{\D c(t)}{\D t} + \frac{\mu(t)}{\tau_{c}}c(t)
= \mu(t)\frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}
\end{equation}
If we then let
\begin{equation}
\mu(t) = \exp(t/\tau_{c})
\end{equation}
we necessarily would have
\begin{equation}
e^{-t/\tau_{c}}\frac{\D}{\D t}(e^{t/\tau_{c}}c(t))
= \frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}.
\end{equation}
This doesn't get us very far, however. We would have
\begin{equation}
e^{t/\tau_{c}}c(t) - e^{t_{0}/\tau_{c}}c(t_{0})
\sim\frac{1}{\tau_{c}}\int e^{t/\tau_{c}}\widehat{q}(t)\,\D t
\end{equation}
ignoring the gaussian noise term.

* Earth System Models of Intermediate Complexity (EMICs)

Basically, everything in between the simplest "Energy Balance"
model and the most complicated "General Circulation" model.

* General Circulation Model

The most complicated sort of model, the Cadillac of climate models.
It models climate using the Navier-Stokes equation. As we do not
have a solution to the NS equation, we are forced to do a lot of
difficult numerical analysis, and that sucks.


* References
- L. Mahadevan and J.M. Deutch, "Influence of feedback on the
  stochastic evolution of simple climate systems".
  /Proc. of Royal Soc. A/ (2009) [[http://web.mit.edu/chemistry/deutch/technical/pdf15/151ProcRSocA-online%282009%29.pdf][Eprint]]
- J. David Neelin,
  {{{book-title(Climate Change and Climate Modeling)}}}.
  Cambridge University Press, 2011.
