#+TITLE: Climate Models
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-05T19:31:00-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Saturday December  5, 2020 at  7:31PM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Energy Balance Model

Typically using a zero-dimensional model via Stefan-Boltzmann
equation and empirical parameters. This can be made more
complicated with 1-dimensional or 2-dimensional models, assuming
the energy budget changes with latitude and/or longitude.

Using Stefan-Boltzmann's law, we would have something like
\begin{equation}
C\frac{\D T(t)}{\D t} = R - \varepsilon\sigma T(t)^{4}
\end{equation}
where:
- $C$ is the effective heat capacity of the Earth (apparently
  $C\approx2.08\times10^{8}J K^{-1}m^{-2}$)
- $R\approx 231.4 W/m^{2}$ is net solar influx,
- $\varepsilon$ is the emissivity of the Earth, a unitless number
  between 0 (perfectly reflective) and 1 (blackbody), for the Earth it's
  somewhere in between 0.6 and 1 ([[https://www.jpl.nasa.gov/spaceimages/details.php?id=PIA18833][NASA]])...we could use
  $\sqrt{0.6}\approx 0.7745$ as an estimate.
- $\sigma$ is the Stefan-Boltzmann constant,
- $T(t)$ is the temperature of the Earth at time $t$.

We can treat $T(t) = T_{0} + \Delta T(t)$ where $T_{0}$ is constant
(using [[file:climate/effective-temperature.org][the Effective Temperature]] of the Earth for $T_{0}\approx 278 K$),
then to first order we in $\Delta T$ we have

\begin{equation}
C\frac{\D\Delta T(t)}{\D t}
= R - \varepsilon\sigma 4T_{0}^{3}\,\Delta T(t).
\end{equation}

(Note: $4\sigma T_{0}^{3}\approx 4.873$, which is about 47.5 times
smaller than $R$.)
This has the general solution

\begin{equation}
\Delta T(t) = \frac{R}{4\varepsilon\sigma CT_{0}^{3}} + c_{0}\exp(-4\varepsilon\sigma CT_{0}^{3}(t-t_{0}))
\end{equation}

where $c_{0}$ is some integration constant. If we had some initial
condition, like $T(t_{0}) = T_{0}$, then we could determine $c_{0}$.
Taking $T(t_{0}) = T_{0}$, we find

\begin{equation}
\Delta T(t) = \frac{R}{4\varepsilon\sigma CT_{0}^{3}}\left(1 - \exp(-4\varepsilon\sigma CT_{0}^{3}(t-t_{0}))\right)
\end{equation}

so $\Delta T(t_{0}) = 0$, and as $t\to\infty$ we see
$\Delta T(t)\to R/4\varepsilon\sigma CT_{0}^{3}$ is strictly increasing.

** Stochastic Feedback

The first modification to Stefan-Boltzmann's law is to consider a
system of coupled stochastic differential equations accounting for
the concentration of greenhouse gases $c(t)$:
\begin{equation}
\rho C_{P}H \frac{\D T(t)}{\D t} \sim R(c) - \sigma(1 - g(c)) T(t)^{4} + \widehat{f}_{T}(t)
\end{equation}
where now:
- $\rho$ is the density of atmosphere
- $C_{P}$ is specific heat
- $H$ is the depth of the atmosphere
- $g(c)$ is the feedback parameter (modifying the Stefan-Boltzmann
  law)
- $\widehat{f}_{T}(t)$ is a Gaussian forcing term, representing
  fast uncorrelated changes in temperature

We also have
\begin{equation}
\tau_{c}\frac{\D c(t)}{\D t} = -c(t)+\widehat{q}(t) + \widehat{f}_{c}(t)
\end{equation}
where
- $q$ is the addition of greenhouse gases per unit volume to the atmosphere
- $f_{c}(t)$
- $\tau_{c}$ is some appropriate scaling constant

These equations crop up repeatedly in climate science. See, for
example:

+ L. Mahadevan and J.M. Deutch, "Influence of feedback on the
  stochastic evolution of simple climate systems".
  /Proc. of Royal Soc. A/ (2009) [[http://web.mit.edu/chemistry/deutch/technical/pdf15/151ProcRSocA-online%282009%29.pdf][Eprint]]

The argument is that the probability distributions of important
climate variables have fat tails, such that the their expected
values do not exist.

#+begin_puzzle
Can full-fledged general circulation models reproduce this result?
(It remains an open problem.)
#+end_puzzle

*** Integration factor

For the second equation, we may write
\begin{equation}
\frac{\D c(t)}{\D t} + \frac{1}{\tau_{c}}c(t)
= \frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}
\end{equation}
Multiplying through by a multiplication factor $\mu(t)$
\begin{equation}
\mu(t)\frac{\D c(t)}{\D t} + \frac{\mu(t)}{\tau_{c}}c(t)
= \mu(t)\frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}
\end{equation}
If we then let
\begin{equation}
\mu(t) = \exp(t/\tau_{c})
\end{equation}
we necessarily would have
\begin{equation}
e^{-t/\tau_{c}}\frac{\D}{\D t}(e^{t/\tau_{c}}c(t))
= \frac{\widehat{q}(t) + \widehat{f}_{c}(t)}{\tau_{c}}.
\end{equation}
This doesn't get us very far, however. We would have
\begin{equation}
e^{t/\tau_{c}}c(t) - e^{t_{0}/\tau_{c}}c(t_{0})
\sim\frac{1}{\tau_{c}}\int e^{t/\tau_{c}}\widehat{q}(t)\,\D t
\end{equation}
ignoring the gaussian noise term.

* Earth System Models of Intermediate Complexity (EMICs)

Basically, everything in between the simplest "Energy Balance"
model and the most complicated "General Circulation" model.

* General Circulation Model

The most complicated sort of model, the Cadillac of climate models.
It models climate using the Navier-Stokes equation. As we do not
have a solution to the NS equation, we are forced to do a lot of
difficult numerical analysis, and that sucks.


* References
- L. Mahadevan and J.M. Deutch, "Influence of feedback on the
  stochastic evolution of simple climate systems".
  /Proc. of Royal Soc. A/ (2009) [[http://web.mit.edu/chemistry/deutch/technical/pdf15/151ProcRSocA-online%282009%29.pdf][Eprint]]
- J. David Neelin,
  {{{book-title(Climate Change and Climate Modeling)}}}.
  Cambridge University Press, 2011.

** Energy Balance Models

- [[https://www.e-education.psu.edu/meteo469/node/135][Modeling of the Climate System]], PSU Meteo 469, Lesson 4,
- [[https://www.e-education.psu.edu/meteo469/node/137][Simple Climate Models]], PSU Meteo 469
- [[https://ocw.mit.edu/courses/earth-atmospheric-and-planetary-sciences/12-810-dynamics-of-the-atmosphere-spring-2008/][Dynamics of the Atmosphere]], MIT OCW course 12.810
- [[https://www.acs.org/content/acs/en/climatescience/atmosphericwarming/singlelayermodel.html][A Single-Layer Atmosphere Model]], ACS
