#+TITLE: Fluid Dynamics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-13T20:08:49-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Sunday December 13, 2020 at  8:08PM
#+INCLUDE: ../org-macros.org

* Quickstart, Ideal Fluids

** Basic Quantities

Basically, the idea is to model "infinitesimal parcels" of a fluid,
so we think in terms of densities(?). There are 5 quantities which
determine the state of a fluid:

- $\vec{v}$ the 3 components of the velocity vector for a fluid parcel
- $p$ fluid pressure
- $\rho$ mass density

We think of the velocity vector as a vector field parametrized by
time.

#+begin_remark
Landau and Lifshitz note the pressure and density, plus the
equations of state, determine the thermodynamics properties of the
fluid (L&L, vol.6, \sect1). 
#+end_remark

*** Continuity Equation

The conservation of mass induces the {{{define(Continuity Equation)}}}:

\begin{equation}
\partial_{t}\rho + \vec{\nabla}\cdot(\rho\vec{v}) = 0.
\end{equation}

** Euler's equations

From Newton's second law, we have $\rho d\vec{v}/dt = -\vec\nabla p$.
The derivative of the velocity vector, in this case, becomes the
material derivative since $\vec{v}=\vec{v}(\vec{x}(t), t)$ so the
total derivative is just $\partial_{t}\vec{v} + (\vec{v}\cdot\vec\nabla)\vec{v}$.
We also add the force of gravity $\rho \vec{g}$ to get
{{{define(Euler's equations)}}}, if we divide through by $\rho$

\begin{equation}
\partial_{t}\vec{v} + (\vec{v}\cdot\vec\nabla)\vec{v}
 = \frac{-1}{\rho}\vec\nabla p + \vec{g}.
\end{equation}

*** Adiabatic Fluids

Note we didn't consider viscosity in deriving this equation, we
just used Newton's second law modified for fluid packets (to give
us the material derivative of velocity as the
"acceleration"). Since we didn't consider viscosity, there is no
heat exchange between different parts of the fluid, nor between the
fluid and its environment.

#+begin_corollary
This absence of heat exchange between components of the fluid (and
between the fluid and its environment) implies the motion is
adiabatic throughout the fluid. As a consequence, the motion of an
ideal fluid must necessarily be supposed adabiatic.
#+end_corollary

L&L note in adiabatic motion, the entropy of any particle of fluid
remains constant as that particle moves around in space. So if $s$
denotes the entropy per unit mass, we can express the adabiatic
condition as

\begin{equation}
\frac{ds}{dt} = \partial_{t}s + (\vec{v}\cdot\vec\nabla)s = 0.
\end{equation}

L&L refer to the quantity $\rho s\vec{v}$ as the
{{{define(Entropy Flux Density)}}} because we have the "equation of
continuity" for entropy in terms of it:

\begin{equation}
\partial_{t}(\rho s) + \vec{\nabla}\cdot(\rho s\vec{v}) = 0.
\end{equation}

*** Isentropic Fluids

If, "as usually happens", the entropy is constant throughout the
volume of the fluid at some initial instant, it retains everywhere
the same constant value at all times and for any subsequent motion
of the fluid. In this case we can write the adiabatic condition as

\begin{equation}
s = \mbox{constant}
\end{equation}

and L&L usually does so. In this case, such a motion is said to be
{{{define(Isentropic)}}}.

#+begin_theorem
The Euler equations of motion for an isentropic fluid may be
rewritten as

\begin{equation}
\partial_{t}(\vec{\nabla}\times\vec{v}) = \vec{\nabla}\times(\vec{v}\times(\vec{\nabla}\times\vec{v})).
\end{equation}

which involves only the velocity.
#+end_theorem

This requires some boundary condition. For an ideal fluid, this
boundary condition is simply "the fluid cannot penetrate a surface
solid". I.e., the component of the fluid velocity normal to the
bounding surface must vanish if that surface is at rest:

\begin{equation}
v_{\vec{n}} = 0.
\end{equation}

In general, for the case when the surface is moving, $v_{n}$ must
be equal to the corrsponding component of the velocity of the surface.

#+begin_remark
This derivation of Euler's equations, and isentropic stuff, comes from L&L, vol.6, \sect2.
#+end_remark

The next steps are to study this equation when
$\vec{v}=0$ (hydrostatics) and when
$\partial_{t}\vec{v}=0$ is constant (Bernoulli's law).

** Hydrostatics

Consider a fluid at rest in a uniform gravitational field. Then
Euler's equation takes the form

\begin{equation}
\vec{\nabla}p = \rho \vec{g}.
\end{equation}

This equation describes the mechanical equilibrium of the fluid.

#+NAME: mechanical-equilibrium
#+begin_definition
We say a fluid is in {{{define(Mechanical Equilibrium)}}} if it
exhibits no macroscopic motion. (L&L, vol.6, \sect4)
#+end_definition

#+begin_remark
If there are no external forces, then this equation becomes
$\vec{\nabla}p=0$ or equivalently $p = \mbox{constant}$. The
pressure is the same everywhere in the fluid.
#+end_remark

*** Case: Constant Density

When we have $\rho$ be constant throughout the fluid, we can solve
the simplified Euler's equation. Taking $z$ as the vertical axis,
so $\vec{g} = -g\widehat{z}$, then we have

\begin{equation}
\partial_{x}p = \partial_{y}p = 0
\end{equation}

and

\begin{equation}
\partial_{z} = -\rho g.
\end{equation}

Hence the general solution for this system of equations is

\begin{equation}
p = -\rho g z + \mbox{constant}.
\end{equation}

If further the fluid is at rest has a free surface at height $h$,
to which an external pressure $p_{0}$ (the same at every point) is
applied, this surface must be the horizontal plane $z = h$. From
the condition $p = p_{0}$ for $z = h$, we find the constant is
$p_{0} + \rho gh$, so in this case

\begin{equation}
p = p_{0} + \rho g(h - z).
\end{equation}

But again, this is the special case of a special case: when density
is constant.

*** Nonconstant Densities in Thermal Equilibrium

When our fluid is a gas, or we have large amounts of our liquid,
then we cannot approximate density as constant. This is especially
true for gases like the atmosphere.

But we may suppose the fluid is in mechanical and thermal
equilibrium. So the temperature is the same at every point. We use
the thermal relation

\begin{equation}
d\Phi = -s\,dT + V\,dp
\end{equation}

where $\Phi$ is the thermodynamic potential (Gibbs free energy) per
unit mass. For constant temperature, this becomes

\begin{equation}
d\Phi = V\,dp = dp/\rho.
\end{equation}

This let's us write

\begin{equation}
\frac{\vec{\nabla}p}{\rho} = \vec{\nabla}\Phi.
\end{equation}

Euler's equation then becomes

\begin{equation}
\vec{\nabla}\Phi = \vec{g}.
\end{equation}

For a constant vector $\vec{g}$ directed along the negative
$z$-axis, we have

\begin{equation}
\vec{g}:=-\vec{\nabla}(gz)
\end{equation}

hence

\begin{equation}
\vec{\nabla}(\Phi + gz) = 0,
\end{equation}

or equivalently

\begin{equation}
\Phi + gz = \mbox{constant}.
\end{equation}

#+begin_remark
Does this make sense? Well, $\Phi + gz = \mbox{constant}$ is known
to be the condition for thermodynamic equilirium of a system in an
external field. Good, recovering well-known results tell us we're
on the right track...or, we've been on the wrong track for such a
long time that we can't tell. At any rate, we're consistent, and
that's good.
#+end_remark

*** Consequence of Hydrostatic Condition: Mechanical Equilibrium Criteria

Particularly useful for me, when considering a fluid like the
atmosphere, which is in mechanical equilibrium in a gravitational
field, the pressure in it can be a function only of the
altitude/"height" $z$ (otherwise, if the pressure were different at
different points with the same altitude, motion would follow).

It follows then that the density

\begin{equation}
\rho = \frac{-1}{g}\frac{dp}{dz}
\end{equation}

is also a function of $z$ only. The pressure and density determine
the temperature, which is therefore again a function of $z$
only. So in mechanical equilibrium in a gravitational field,
the pressure, density, and temperature distributions depend only on
the altitude.

Conversely, if, say, the temperature is different at different
points with the same altitude, then mechanical equilibrium is
impossible. (Thus this fact is useful in contrapositive form, too.)

*** For a large mass of self-gravitating Fluid

When we have a large mass of fluid, say a star, whose separate
parts are held together by gravitational attraction. Let $\phi$
be the Newtonian gravitational potential of the field due to the
fluid. It satisfies the differential equation

\begin{equation}
\nabla^{2}\phi = 4\pi G\rho
\end{equation}

where $G$ is the Newtonian gravitational constant. The
gravitational acceleration is $-\vec{\nabla}\phi$, and the force on
a mass $\rho$ is $-\rho\vec{\nabla}\phi$. The condition of
equilibrium is therefore

\begin{equation}
\vec{\nabla}p = -\rho\vec{\nabla}\phi.
\end{equation}

Dividing both sides by $\rho$ then taking the divergence of both
sides gives us

\begin{equation}
\nabla\cdot\left(\frac{1}{\rho}\vec{\nabla}p\right) = -4\pi G\rho.
\end{equation}

This seems like a great deal more difficult. But we did not assume
thermodynamic equilibrium, and in exchange we have a condition for
mechanical equilibrium.

If we further assume the body is not rotating, then it will enjoy a
spherical symmetry when in equilibrium, and the density & pressure
distributions will be spherically symmetric. We have in spherical
coordinates our condition become

\begin{equation}
\frac{1}{r^{2}}\frac{d}{dr}\left(\frac{r^{2}}{\rho}\frac{dp}{dr}\right) = -4\pi G\rho.
\end{equation}

Again, this fails to hold for a rotating body (like the Earth).

** On the "Absence of Convection" Condition

We've concluded from our discussion of hydrostatics that a fluid
can be in [[mechanical-equilibrium][mechanical equilibrium]] (i.e., exhibit no macroscopic motion)
without being in thermodynamic equilibrium. The hydrostatic
equation can be satisfied even if the temperature is not constant
throughout the fluid.

The question arises concerning the stability of such an
equilibrium. Unsurprisingly, the equilibrium is stable if
a condition is fulfilled. Otherwise, the equilibrium is /unstable/,
and this leads to the appearance in the fluid of currents which
tend to mix the fluid in such a way as to equalize the
temperature. This motion is called {{{define(Convection)}}}.

The condition for "mechanical equilibrium being stable" is "absence
of convection".

** Bernoulli's Equation

*** Steady Flows

#+begin_definition
By {{{define(Steady Flow)}}}, we mean one in which the velocity is
constant in time at any point occupied in the fluid. I.e.,
$\vec{v}$ is a function of the coordinates only, so that $\partial_{t}\vec{v}=0$.
#+end_definition

In a steady flow, the isentropic Euler equation becomes

\begin{equation}
\frac{1}{2}\vec{\nabla}(v^{2}) - \vec{v}\times(\vec{\nabla}\times\vec{v}) = -\vec{\nabla}w.
\end{equation}

*** Streamlines

Streamlines are lines such that the tangent to a streamline at any
point gives the direction of the velocity of that point. They are
determined by the system of differential equations

\begin{equation}
\frac{dx}{v_{x}} = \frac{dy}{v_{y}} = \frac{dz}{v_{z}}.
\end{equation}

In steady flow, the streamlines do not vary with time, and coincide
with the paths of the fluid particles.

*BUT* for non-steady flows, this coincidence no longer occurs: the
tangents to the streamlines give the directions of the velocities
of fluid particles at various points in space at a given instant,
where the tangents to the paths give the directions of the
velocities of given fluid particles at various times.

*Question:* for non-steady flows, are streamlines still a valuable
concept?

*** Bernoulli's Equation Derivation

Taking the equation for steady flows, then forming the scalar
product with the unit vector tangent to the streamline at each
point (call this unit vector $\vec{\ell}$). The projection of the
gradient on any direction is the derivative in that direction (duh,
the directional derivative). So

\begin{equation}
\vec{\ell}\cdot(\vec{\nabla}w) = \partial w/\partial\ell.
\end{equation}

The vector $\vec{v}\times(\vec{\nabla}\times\vec{v})$ is orthogonal
to $\vec{v}$, hence its dot product with $\vec{\ell}$ vanishes.

Thus we get the simplified equation

\begin{equation}
\frac{\partial}{\partial\ell}\left(\frac{v^{2}}{2} + w\right) = 0.
\end{equation}

It follows that $w + v^{2}/2$ is constant along the streamline, i.e.,

\begin{equation}
\frac{1}{2}v^{2} + w = \mbox{constant}.
\end{equation}

This is precisely {{{define(Bernoulli's Equation)}}}.

In general, the constant $w + v^{2}/2$ takes different values for
different streamlines.

*** In a Gravitational Field

So, if our fluid flows in a gravitational field, the acceleration
$\vec{g}$ due to gravity must be added to the right-hand side of
the isentropic Euler equations for steady flows:

\begin{equation}
\frac{1}{2}\vec{\nabla}(v^{2}) - \vec{v}\times(\vec{\nabla}\times\vec{v}) = -\vec{\nabla}w + \vec{g}.
\end{equation}

Let us take the direction of gravity as the $z$-axis, with $z$
increasing upwards. This choice let's us relate the cosine of the
angle between $\vec{g}$ and $\vec{\ell}$ to be equal to the derivative
$-dz/d\ell$, so the projection of $\vec{g}$ on $\vec{\ell}$ is $-gdz/d\ell$.

Then we have our projected equation become

\begin{equation}
\frac{\partial}{\partial\ell}\left(\frac{v^{2}}{2} + w + gz\right) = 0.
\end{equation}

Hence Bernoulli's equation states that along a streamline we have

\begin{equation}
\left(\frac{v^{2}}{2} + w\right) = \mbox{constant}.
\end{equation}

** Energy Flux

*** Energy per unit volume

For our fluid, the energy per unit volume of fluid is
$\rho v^{2}/2 + \rho\varepsilon$ the sum of its kinetic energy and
internal energy, where $\varepsilon$ is internel energy per unit mass.

The change in this energy is given by its partial derivative with
respect to time.

*** Conservation Equation

#+begin_theorem
Assuming an adiabatic fluid, the conservation of energy implies

\begin{equation}
\partial_{t}(\rho v^{2}/2 + \rho\varepsilon) = -\nabla\cdot[\rho\vec{v}(v^{2}/2 + w)].
\end{equation}
#+end_theorem

This follows by computing $\partial_{t}(\rho v^{2}/2 + \rho\varepsilon)$,
the change in energy with respect to time. The first and second
terms are rather involved, and delegated to "lemmas" below. But the
lemmas then give us

\begin{equation}
\partial_{t}\left(\frac{\rho v^{2}}{2} + \rho\varepsilon\right)
= -\left(\frac{v^{2}}{2} + w\right)\vec{\nabla}\cdot(\rho\vec{v})
  -\rho\vec{v}\cdot\vec{\nabla}(w + v^{2}/2)
\end{equation}

The right-hand side can be rewritten to give the final result.

**** Change of Kinetic Energy with respect to Time

To compute this quantity, we begin by considering the kinetic energy term

\begin{equation}
\partial_{t}(\rho v^{2}/2) =
\frac{v^{2}}{2}\frac{\partial\rho}{\partial t} +
\rho\vec{v}\cdot\frac{\partial\vec{v}}{\partial t}
\end{equation}

Now we use the [[*Continuity Equation][continuity equation]] and equation of motion

\begin{equation}
\partial_{t}(\rho v^{2}/2) =
\frac{-v^{2}}{2}\nabla\cdot(\rho\vec{v}) - \vec{v}\cdot(\vec{\nabla}p)
- \rho\vec{v}\cdot\bigl((\vec{v}\cdot\vec{\nabla})\vec{v}\bigr).
\end{equation}

In the last term, we replace

\begin{equation}
\vec{v}\cdot\bigl((\vec{v}\cdot\vec{\nabla})\vec{v}\bigr) = \frac{1}{2}\vec{v}\cdot(\vec{\nabla}(v^{2}))
\end{equation}

and in the middle term we (use the thermodynamic relation
$dw = T\,ds + (1/\rho)dp$ to) replace

\begin{equation}
\vec{\nabla}p = \rho\vec{\nabla}w - \rho T\vec{\nabla}s
\end{equation}

thus obtaining

\begin{equation}
\partial_{t}(\rho v^{2}/2) =
\frac{-v^{2}}{2}\nabla\cdot(\rho\vec{v})
- \rho\vec{v}\cdot\vec{\nabla}(w + v^{2}/2)
+ \rhoT\vec{v}\cdot(\vec{\nabla}s).
\end{equation}

**** Change of Internal Energy with respect to Time

Now we compute $\partial_{t}(\rho\varepsilon)$, we use the
thermodynamic relation

\begin{equation}
d\varepsilon = T\,ds - p\,dV = T\,ds + (p/\rho^{2})d\rho.
\end{equation}

Since $\varepsilon + p/\rho = \varepsilon + pV$ is the heat
function $w$ per unit mass, we find

\begin{equation}
d(\rho\varepsilon) = \varepsilon\,d\rho + \rho\,d\varepsilon
= w\,d\rho + \rho T\,ds.
\end{equation}

Thus (using the general adiabatic equation of motion)

\begin{equation}
\partial_{t}(\rho\varepsilon) = w\partial_{t}\rho + \rho T\partial_{t}s
= -w\vec{\nabla}\cdot(\rho\vec{v}) - \rho T\vec{v}\cdot(\vec{\nabla}s).
\end{equation}

*** Meaning of the Conservation Equation

We have an abstract equation we assert is correct through a long
string of equations. Believe me? Well, let's see what it
/means/. We need to integrate it over some volume $V$:

\begin{equation}
\partial_{t}\int\left(\frac{\rho v^{2}}{2} + \rho\varepsilon)dV
= -\int\vec{\nabla}\cdot\left[\rho\vec{v}\left(\frac{v^{2}}{2}+w\right)\right] dV
\end{equation}

We convert the integral on the right to a surface integral

\begin{equation}
\partial_{t}\int\left(\frac{\rho v^{2}}{2} + \rho\varepsilon)dV
= -\oint\left[\rho\vec{v}\left(\frac{v^{2}}{2}+w\right)\right]\cdot d\vec{f}.
\end{equation}

- The LHS is the rate of change of the energy of the fluid in some volume.
- The RHS is the amount of energy flowing out of this volume in
  unit time.
- We may call $\rho\vec{v}(w + v^{2}/2)$ the {{{define(Energy Flux Density)}}}.
  Its magnitude is the amount of energy passing in unit time
  through unit area perpendicular to the direction of the
  velocity. Nifty.

#+begin_remark
The expression $\rho\vec{v}(w + v^{2}/2)$ shows any unit mass of
fluid carries with it during its motion an amount of energy $w+v^{2}/2$.
The fact that the heat function $w$ appears here, and not the
internal energy $\varepsilon$, has physical significance. Putting
$w=\varepsilon + p/\rho$, we can write the flux of energy through a
closed surface in the form

\begin{equation}
-\oint\rho\vec{v}\left(\frac{v^{2}}{2}+\varepsilon\right)\cdot d\vec{f}
-\oint p\vec{v}\cdot d\vec{f}
\end{equation}

The first term is the energy (kinetic and internal) transported
through the surface in unit time by the mass of fluid. The second
term is the work done by pressure forces on the fluid within the
surface.
#+end_remark

** Momentum Flux

*** Derivation of Momentum Flux Density Tensor

The momentum of unit volume is $\rho\vec{v}$. What is its rate of
change with respect to time $\partial_{t}(\rho\vec{v})$? We will
switch to index notation for ease of computation.

We can use the product rule to find

\begin{equation}
\frac{\partial}{\partial t}(\rho v_{i})
= \rho\frac{\partial v_{i}}{\partial t} + \frac{\partial\rho}{\partial t}v_{i}
\end{equation}

We can use the [[*Continuity Equation][continuity equation]] in the form of

\begin{equation}
\partial_{t}\rho = -\sum_{k}\frac{\partial(\rho v_{k})}{\partial x_{k}}
\end{equation}

and Euler's equations in the form of

\begin{equation}
\partial_{t}v_{i} = -\frac{1}{\rho}\frac{\partial p}{\partial x_{i}} - \sum_{k}v_{k}\frac{\partial v_{i}}{\partial x_{k}} 
\end{equation}

to obtain

\begin{equation}
\partial_{t}(\rho v_{i})
 = \rho\left(-\frac{1}{\rho}\frac{\partial p}{\partial x_{i}} - \sum_{k}v_{k}\frac{\partial v_{i}}{\partial x_{k}}\right)
 + \left(-\sum_{k}\frac{\partial(\rho v_{k})}{\partial x_{k}}\right) v_{i}
\end{equation}

which simplifies to

\begin{equation}
\partial_{t}(\rho v_{i})
 = -\frac{\partial p}{\partial x_{i}} - \sum_{k}\frac{\partial}{\partial x_{k}}(\rho v_{i}v_{k}).
\end{equation}

The first term on the right hand side can be rewritten using index
gymnastics as

\begin{equation}
\frac{\partial p}{\partial x_{i}} = \sum_{k}\delta_{ik}\frac{\partial p}{\partial x_{k}}.
\end{equation}

Then we have

\begin{equation}
\partial_{t}(\rho v_{i}) = -\sum_{k}\frac{\partial\Pi_{ik}}{\partial x_{k}}
\end{equation}

where the tensor $\Pi_{ik}$ is defined as

\begin{equation}
\Pi_{ik} = p\delta_{ik} + \rho v_{i}v_{k}.
\end{equation}

Since $\Pi_{ik}$ is the sum of two symmetric tensors, it is thus a
symmetric tensor.

**** Momentum Flux Density Tensor

We define the tensor $\Pi_{ik}$ as the {{{define(Momentum Flux Density Tensor)]}}:

\begin{equation}
\Pi_{ik} = p\delta_{ik} + \rho v_{i}v_{k}.
\end{equation}

*** Its interpretation

We grasp the meaning of the momentum flux density tensor by looking
at its integral over some volume

\begin{equation}
\partial_{t}\int \rho v_{i}\,dV =
-\int\sum_{k}\frac{\partial\Pi_{ik}}{\partial x_{k}}\,dV.
\end{equation}

We can apply Green's theorem to the right hand side, obtaining

\begin{equation}
\partial_{t}\int \rho v_{i}\,dV =
-\sum_{k}\oint\Pi_{ik}\,d f_{k}.
\end{equation}

- The left-hand side is the rate of change of the $i$-th component of
  momentum contained in the volume (i.e., the domain of integration).
- The RHS is thus the amount of momentum flowing out through the
  bounding surface in unit time.

So $\Pi_{ik}df^{k}$ is the $i$-th component of momentum flowing
through the surface element $df$. If we write $df_{k}$ in the form
of $n_{k}df$, where $df$ is the area of the surface element and
$\vec{n}$ is a unit vector along the outward normal, we find that
$\Pi_{ik}n^{k}$ is the flux of the $i$-th component of momentum
through unit surface area. Note that

\begin{equation}
\Pi_{ik}n^{k} = p n_{i} + \rho v_{i}v_{k}n^{k}.
\end{equation}

or in vector form

\begin{equation}
\Pi\vec{n} = p\vec{n} + \rho\vec{v}(\vec{v}\cdot\vec{n}).
\end{equation}

** Conservation of Circulation

#+NAME: velocity-circulation
#+begin_definition
The integral

\begin{equation}
\Gamma = \oint \vec{v}\cdot d\vec{\ell}
\end{equation}

along some closed contour is called the {{{define(Velocity Circulation)}}}
around that contour.
#+end_definition



** Potential Flow

** Incompressible Fluids

** Drag force in potential flow past a body

** Gravity waves

** Internal waves in an incompressible fluid

** Waves in a rotating fluid

* References

- George Batchelor,
  {{{book-title(An Introduction to Fluid Dynamics)}}}.
  Cambridge University Press, 2000.
- Laurent Schoeffel, "Lectures on Fluid Dynamics".
  Eprint [[https://arxiv.org/abs/1407.3162][arXiv:1407.3162]].

** Recommendations/Lookup

- [ CFD Python: 12 steps to Navier-Stokes :: Lorena A. Barba Group ]
