#+TITLE: Fluid Dynamics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-13T20:08:49-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Sunday December 13, 2020 at  8:08PM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Overview
:PROPERTIES:
:CUSTOM_ID: h-0892a9ce-f478-4e0e-a808-ae12b3d265aa
:END:

The Reynolds number measures how unimportant viscosity is, by taking the
ratio of non-viscous forces to viscosity. For the atmosphere, around
100km altitude and below, the Reynolds number is usually huge, so
viscosity is unimportant. What's more important is the turbulence
([[https://www.cgd.ucar.edu/staff/islas/teaching/2_Equations.pdf][source]]; ch 8 "The Planetary Boundary Layer" of John Holton's {{{book-title(Introduction to Dynamic Meteorology)}}}).

Liquids are (usually) incompressible fluids.

Gases are (usually) compressible fluids.

See also [[file:fluid-mechanics/index.org][further topics]] on fluids.

I have collected some notes in a [[https://op-om.blogspot.com/][separate blog]], though I haven't written
anything lately.

* Euler Fluid
:PROPERTIES:
:CUSTOM_ID: h-66191b67-1bb9-416b-8bf3-025542461f97
:END:

For inviscuous fluid, we use Euler's equations for the equations of
motion. This is really a sort of nonlocal Poisson equation.

- Peter Constantin,\\
  "The Euler equations and nonlocal conservative Riccati equations".\\
  /International Mathematics Research Notices/ *2000* no.9 (2000)
  pp.455--465 Pages 455–465,
  {{{doi(10.1155/S1073792800000258)}}}
  [[http://web.math.princeton.edu/~const/ricF.pdf][Eprint]]
- Peter Constantin,\\
  "On the Euler Equations of Incompressible Fluids".\\
  /Bulletin of the AMS/ *44* no.4 (2007) pp.603--621
  [[https://www.ams.org/journals/bull/2007-44-04/S0273-0979-07-01184-6/S0273-0979-07-01184-6.pdf][PDF]] and [[http://web.math.princeton.edu/~const/eule.pdf][Eprint]]
- P. Constantin,\\
  "Euler equations, Navier-Stokes equations and turbulence".\\
  [[https://web.math.princeton.edu/~const/cim.pdf][PDF]]
- C. Bardos, E. Titi,\\
  "Euler equations of incompressible ideal fluids".\\
  [[https://users.mccme.ru/ansobol/otarie/slides/Russ-Math-Surveys-Euler-Bardos.pdf][PDF]]

* References
:PROPERTIES:
:CUSTOM_ID: h-4651770a-1851-4f2e-b22c-141ee36d584e
:END:

- Stephen Childress,\\
  "An Introduction to Theoretical Fluid Dynamics".\\
  Lecture notes, [[https://www.math.nyu.edu/~childres/fluidsbook.pdf][pdf]], 177 pages.
- Alexandre Chorin, Jerrold Marsden,\\
  {{{book-title(A Mathematical Introduction to Fluid Mechanics)}}}.\\
  Third ed., Springer, 1993.
- Landau and Lifshitz,\\
  {{{book-title(Fluid Mechanics)}}}.\\
  Second ed., Butterworth-Heinemann, 1987.
  This is my primary reference.
- Simon J.A. Malham,\\
  "Introductory fluid mechanics".\\
  Lecture notes [[http://www.macs.hw.ac.uk/~simonm/fluidsnotes.pdf][pdf]], 2014, 74 pages.

** Recommendations/Lookup
:PROPERTIES:
:CUSTOM_ID: h-45f73710-501c-4f3c-aeb1-93208f7edadf
:END:

- George Batchelor,\\
  {{{book-title(An Introduction to Fluid Dynamics)}}}.\\
  Cambridge University Press, 2000.
  - Remark: this seems to be the basis of several modern texts on
    fluids, like Malham's lecture notes or Childress's book; but this
    may be because there are only finitely many ways to present the
    material.
- Laurent Schoeffel,\\
  "Lectures on Fluid Dynamics".\\
  Eprint [[https://arxiv.org/abs/1407.3162][arXiv:1407.3162]].
- /CFD Python: 12 steps to Navier-Stokes/ Lorena A. Barba Group
- Tai-Peng Tsai,\\
  {{{book-title(Lectures on Navier-Stokes Equations)}}}.\\
  AMS Publishers.
