#+TITLE: Meta-Physics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-22T21:15:57-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Tuesday December 22, 2020 at  9:15PM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Not What you think

This isn't about "New Age" hippy nonsense. By "Metaphysics", I mean
literally "about physics". As in, the conventions adopted to reason
about physics. For example, in presenting "experimental facts" in the
form of axioms, with the understanding their truth is provisional.

I present such things because I'm a mathematician writing a
/Zettelkasten/, and I cannot afford the luxury of space: an experiment's
results must be conveyed in a quarter of a slip of paper (roughly A6 in
size). When citing my /Zettelkasten/ I summarize it as a particular
subclass of propositions.

** Constructive Results

When introducing, e.g., temperature, it's a new undefined term. We
measure it using a thermometer. Which just begs the question: what's a
thermometer? I tend to think providing an idealized construction from
what we have previously established works best.

** Experimental Facts

Some examples of experimental facts taken for granted:

- The universe is described using 3 spatial dimensions and 1 temporal
  dimension.
- (Newton-Laplace Principle of Determinacy.) A physical system's
  evolution is uniquely determined by its initial position and velocity.

Other experimental facts are really just worked examples. The
[[https://en.wikipedia.org/wiki/Cavendish_experiment][Cavendish experiment]], for example, constitutes a particular
[[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.8.7115&rep=rep1&type=pdf][mathematical register]] similar to what a mathematician
would call an "example". (Indeed, almost of physics amounts to a litany
of examples.)

* References

- Atish Bagchi and Charles Wells,
  "Varieties of Mathematical Prose".
  Manuscript dated 1998, [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.8.7115&rep=rep1&type=pdf][PDF]].
