#+TITLE: Meta-Physics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2020-12-22T21:15:57-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
# Created Tuesday December 22, 2020 at  9:15PM
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

* Not What you think
:PROPERTIES:
:CUSTOM_ID: h-13ff4071-eac4-4c43-9ac0-8b03303e6f7c
:END:

This isn't about "New Age" hippy nonsense. By "Metaphysics", I mean
literally "about physics". As in, the conventions adopted to reason
about physics. For example, in presenting "experimental facts" in the
form of axioms, with the understanding their truth is provisional.

I present such things because I'm a mathematician writing a
/Zettelkasten/, and I cannot afford the luxury of space: an experiment's
results must be conveyed in a quarter of a slip of paper (roughly A6 in
size). When citing my /Zettelkasten/ I summarize it as a particular
subclass of propositions.

** Constructive Results
:PROPERTIES:
:CUSTOM_ID: h-e3bde7ba-8b07-4d31-bb23-807910c1b080
:END:

When introducing, e.g., temperature, it's a new undefined term. We
measure it using a thermometer. Which just begs the question: what's a
thermometer? I tend to think providing an idealized construction from
what we have previously established works best.

** Experimental Facts
:PROPERTIES:
:CUSTOM_ID: h-71531992-2a2e-4536-94bc-a9b8b8235ff6
:END:

Some examples of experimental facts taken for granted:

- The universe is described using 3 spatial dimensions and 1 temporal
  dimension.
- (Newton-Laplace Principle of Determinacy.) A physical system's
  evolution is uniquely determined by its initial position and velocity.

Other experimental facts are really just worked examples. Experiments
(like the [[https://en.wikipedia.org/wiki/Cavendish_experiment][Cavendish experiment]], for example) constitutes a particular
[[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.8.7115&rep=rep1&type=pdf][mathematical register]] similar to what a mathematician
would call an "example". (Indeed, almost of physics amounts to a litany
of examples.)

* Examples in Physics
:PROPERTIES:
:CUSTOM_ID: h-c4798587-9008-4c71-8147-718363036b61
:END:

Unlike mathematics, "examples" in physics are not an instructive detour
but the constituents of the subject. Their importance is more akin to
that of theorems in mathematics. Picking good examples requires choosing
different physical situations, not different numeric values for the same
situation.

** Methods for Solving Physics
:PROPERTIES:
:CUSTOM_ID: h-0280afcd-d10f-4d6f-ba80-eadca1f5187c
:END:

Briefly, I've read a number of different ways to solve physics problems.
Back in the 1980s, there was a fascination with AI experts studying how
human experts solve problems. It turns out that Freedman and Young's
ISEE method is the basic approach that experts perform mostly
subconsciously:

1. *Identify the relevant concepts.* Also identify the target variable
   you're solving for. Write down the known and unknown quantities and
   their values. You should be able to answer the question, "What is
   being asked of me?"
2. *Setup.* Write down the relevant equations from physical laws (like
   $F=ma$). Do not solve or substitute numeric values. Pick a coordinate
   system (if relevant). Draw diagrams (if relevant).
3. *Execute.* "Do the math". As far as possible, do everything
   symbolically, only substitute in numeric values at the last step.
4. *Evaluate.* How do we know our answer is correct? This could involve
   taking limits of the symbolic answer (e.g., when friction goes to
   zero, or when it goes to infinity). Can we recover /previous/ results
   taking some appropriate limit? Perhaps we could do order-of-magnitude
   estimates. Also dimensional analysis is useful.

Sometimes the "Identify" and "Setup" steps are contracted into one
"Identify and setup". When one gains expertise, the "identify" step
becomes "automatic".

* References
:PROPERTIES:
:CUSTOM_ID: h-b10f11f4-db59-4585-abc4-1ea4a5feb224
:END:

- Atish Bagchi and Charles Wells,
  "Varieties of Mathematical Prose".
  Manuscript dated 1998, [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.8.7115&rep=rep1&type=pdf][PDF]].
