#+TITLE: Multiphysics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-04-03T14:37:30-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Saturday April  3, 2021 at  2:37PM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-7f76b086-440b-4a4e-954c-f81b46cfafe7
:END:

Multiphysics studies several computer models of physical phenomena,
coupled to each other. Apparently it is a contraction of "Multi-scale
physics". For our interests, the atmosphere coupled to ocean dynamics,
factoring in thermodynamic heat transfer. More generally, we have
{{{dfn(Constituent)}}} systems which are coupled together; the code is
organized to reflect this, using a {{{dfn(Coupler)}}} pattern (a
[[https://en.wikipedia.org/wiki/Mediator_pattern][Mediator]] with delusions of grandeur). The only person who has defined
terms to describe multiphysics appears to be J. Walter Larson in his
article "Ten organising principles for coupling in multiphysics and
multiscale models".

#+begin_remark
COMSOL seems to be a proprietary company with some kind of software,
claiming to be the "alpha and omega" on multiphysics. I never heard of
the term before stumbling across them by accident.
#+end_remark

* References
:PROPERTIES:
:CUSTOM_ID: h-4c9a5e0f-1e17-415c-9c47-360b484928a5
:END:

- DWM Rouson, H. Adalsteinsson, and J. Xia,
  "Design patterns for multiphysics modeling in Fortran 2003 and C++".
  /ACM Transactions on Mathematical Software/ *37*, 1(2010)
  {{{doi(10.1145/1644001.1644004)}}}.
- Damian Rouson, Jim Xia, Xiaofeng Xu,
  {{{book-title(Scientific Software Design: The Object-Oriented Way)}}}.
  Cambridge University Press, 2011.
- J. Walter Larson,\\
  "Ten organising principles for coupling in multiphysics and multiscale models".\\
  /ANZIAM/ *48* (2009) [[https://journal.austms.org.au/ojs/index.php/ANZIAMJ/article/view/138][Eprint]]
  
** In Climate Science
:PROPERTIES:
:CUSTOM_ID: h-6f08bf4a-8ba3-48ee-a293-63c9d13e0c58
:END:

A review of multiphysics, as applied to meteorology and climate science,
may be found in:

- R.  Klein,  S.  Vater,  E.  Paeschke,  and  D.  Ruprecht,
  "Multiplescales  methods  in meteorology".
  In: Steinrück H. (eds) {{{book-title(Asymptotic Methods in Fluid Mechanics: Survey and Recent Advances)}}}. CISM Courses and Lectures, vol 523.
  Springer Verlag, 2011, pp.127--196,
  {{{doi(10.1007/978-3-7091-0408-8_5)}}}
