#+TITLE: Multiphysics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-04-03T14:37:30-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Saturday April  3, 2021 at  2:37PM

* Overview

Multiphysics studies several computer models of physical phenomena,
coupled to each other. Apparently it is a contraction of "Multi-scale
physics". For our interests, the atmosphere coupled to ocean dynamics,
factoring in thermodynamic heat transfer.

#+begin_remark
COMSOL seems to be a proprietary company with some kind of software,
claiming to be the "alpha and omega" on multiphysics. I never heard of
the term before stumbling across them by accident.
#+end_remark

* In Climate Science

A review of multiphysics, as applied to meteorology and climate science,
may be found in:

- R.  Klein,  S.  Vater,  E.  Paeschke,  and  D.  Ruprecht,
  "Multiplescales  methods  in meteorology".
  In: Steinrück H. (eds) {{{book-title(Asymptotic Methods in Fluid Mechanics: Survey and Recent Advances)}}}. CISM Courses and Lectures, vol 523.
  Springer Verlag, 2011, pp.127--196,
  {{{doi(10.1007/978-3-7091-0408-8_5)}}}

* References

- DWM Rouson, H. Adalsteinsson, and J. Xia,
  "Design patterns for multiphysicsmodeling in Fortran 2003 and C++".
  /ACM Transactions on Mathematical Software/ *37*, 1(2010)
  {{{doi(10.1145/1644001.1644004)}}}.
- Damian Rouson, Jim Xia, Xiaofeng Xu,
  {{{book-title(Scientific Software Design: The Object-Oriented Way)}}}.
  Cambridge University Press, 2011.
