#+TITLE: Multiphysics
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-04-03T14:37:30-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Saturday April  3, 2021 at  2:37PM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-7f76b086-440b-4a4e-954c-f81b46cfafe7
:END:

Multiphysics studies several computer models of physical phenomena,
coupled to each other. Apparently it is a contraction of "Multi-scale
physics". For our interests, the atmosphere coupled to ocean dynamics,
factoring in thermodynamic heat transfer. More generally, we have
{{{dfn(Constituent)}}} systems which are coupled together; the code is
organized to reflect this, using a {{{dfn(Coupler)}}} pattern (a
[[https://en.wikipedia.org/wiki/Mediator_pattern][Mediator]] with delusions of grandeur). The only person who has defined
terms to describe multiphysics appears to be J. Walter Larson in his
article "Ten organising principles for coupling in multiphysics and
multiscale models".

#+begin_remark
COMSOL seems to be a proprietary company with some kind of software,
claiming to be the "alpha and omega" on multiphysics. I never heard of
the term before stumbling across them by accident.
#+end_remark

** A Grocery List of Definitions
:PROPERTIES:
:CUSTOM_ID: h-10e654a5-ef08-4497-a99e-ca9955be3aa9
:END:

#+begin_definition
A {{{dfn(Constituent)}}} $\mathcal{C}$ is characterized by a "model"
$\mathcal{M}$ which solves its equations of motion on its domain
$\Gamma$ to calculate its {{{dfn(State)}}} $\mathcal{U}$.

The state is updated using the current model's state /and/ a set of {{{dfn(Input Variables)}}}
$\mathcal{V}$. The {{{dfn(Output Variables)}}} $\mathcal{W}$ are computed from $\mathcal{U}$

The input and output variables $\mathcal{V}$ and $\mathcal{W}$ are the
only data connections of a constituent system to the "outside world",
and are defined on the {{{dfn(Boundary Domain)}}} $\partial\Gamma$ (or
some subset of it).
#+end_definition

For example, the Earth's atmosphere has $\Gamma$ be the region between
the surface of the Earth and the "top of the atmosphere". So usually
it's the difference between two closed balls
$\Gamma=B^{3}_{\text{atm}}\setminus B^{3}_{\text{earth}}$. The standard
mesh for numerically computing finite differences is a
$64\times128\times26$ grid; this could be taken as the domain for a
numerical approximation to the Earth's atmosphere.

#+begin_definition
Two constituents $\mathcal{C}_{i}$ and $\mathcal{C}_{j}$ are
{{{dfn(Coupled)}}} if

1. Have some common intersection of their domains:
   $\Gamma_{i}\cap\Gamma_{j}\neq\emptyset$, and
2. Outputs from one can serve as inputs to the other,
   in at least one of the following senses:
   1. One constituent's outputs overlap the other's inputs:
      $\mathcal{W}_{j}\cap\mathcal{V}_{i}\neq\emptyset$, and/or
      $\mathcal{V}_{j}\cap\mathcal{W}_{i}\neq\emptyset$; or
   2. The inputs $\mathcal{V}_{i}$ can be computed from the other's
      outputs $\mathcal{W}_{j}$ (or $\mathcal{V}_{j}$ can be obtained
      from $\mathcal{W}_{i}$).
#+end_definition

We then describe a multiphysics system as a finite collection of
constituents $\mathcal{C}_{i}$ (where $i=1,\dots,N$), which are usually
coupled together somehow.

The difficulty stems from time-evolution. For explicit finite difference
schemes, it's straightforward...usually. But for implicit finite
difference schemes, it's a nightmare of sharing "the current guess of
the next iterative state's values".

* References
:PROPERTIES:
:CUSTOM_ID: h-4c9a5e0f-1e17-415c-9c47-360b484928a5
:END:

- DWM Rouson, H. Adalsteinsson, and J. Xia,
  "Design patterns for multiphysics modeling in Fortran 2003 and C++".
  /ACM Transactions on Mathematical Software/ *37*, 1(2010)
  {{{doi(10.1145/1644001.1644004)}}}.
- Damian Rouson, Jim Xia, Xiaofeng Xu,
  {{{book-title(Scientific Software Design: The Object-Oriented Way)}}}.
  Cambridge University Press, 2011.
- J. Walter Larson,\\
  "Ten organising principles for coupling in multiphysics and multiscale models".\\
  /ANZIAM/ *48* (2009) [[https://journal.austms.org.au/ojs/index.php/ANZIAMJ/article/view/138][Eprint]]
- Gang Lu, Efthimios Kaxiras,\\
  "Overview of Multiscale Simulations of Materials".\\
  [[https://boulderschool.yale.edu/sites/default/files/files/lu05.pdf][PDF]], 33 pages.
- David Keyes and many friends,\\
  "Multiphysics simulations: Challenges and opportunities".\\
  /Internat. J. of High Performance Comp. App./ *27*, no.1 (2013) pp.4-83, [[https://journals.sagepub.com/doi/pdf/10.1177/1094342012468181][PDF]]

  
** In Climate Science
:PROPERTIES:
:CUSTOM_ID: h-6f08bf4a-8ba3-48ee-a293-63c9d13e0c58
:END:

A review of multiphysics, as applied to meteorology and climate science,
may be found in:

- R.  Klein,  S.  Vater,  E.  Paeschke,  and  D.  Ruprecht,
  "Multiplescales  methods  in meteorology".
  In: Steinrück H. (eds) {{{book-title(Asymptotic Methods in Fluid Mechanics: Survey and Recent Advances)}}}. CISM Courses and Lectures, vol 523.
  Springer Verlag, 2011, pp.127--196,
  {{{doi(10.1007/978-3-7091-0408-8_5)}}}
