#+TITLE: Rarita-Schwinger Fields
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2023-03-15T09:28:26-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
# Created Wednesday March 15, 2023 at  9:28AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-e522a8c7-ccdb-4ff3-8e3d-c9358edddefe
:END:

Rarita-Schwinger field describes a spin-$3/2$ field.


* Velo-Zwanziger Problem
:PROPERTIES:
:CUSTOM_ID: h-19de5aef-a3be-467d-93b1-6db947645960
:END:

The "obvious" action for fields which

1. have spin greater than 1
2. are in a massive irrep of the Lorentz group
3. have minimal coupling to electromagnetism

tend not to have hyperbolic equations of motion (i.e., violate the
familiar causality relations of general relativity). This is the
Velo-Zwanziger problem.

Usually the solution is either to take a massless field, or have
non-minimal coupling to electromagnetism.

* References
:PROPERTIES:
:CUSTOM_ID: h-e8e76a2c-9e38-495c-8659-061b73acd1ba
:END:

- Massimo Porrati, Rakibur Rahman,\\
  "Causal Propagation of a Charged Spin 3/2 Field in an External Electromagnetic Background".\\
  {{{arXiv(0906.1432)}}}, 10 pages.
- Thomas-Paul Hack, Mathias Makedonski,\\
  "A No-Go Theorem for the Consistent Quantization of the Massive
  Gravitino on Robertson-Walker Spacetimes and Arbitrary Spin 3/2 Fields
  on General Curved Spacetimes".\\
  {{{arXiv(1106.6327v2)}}}, 32 pages (the v3 is substantially abridged
  to 8 pages).