#+TITLE: Thermometer Constructions
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-08-13T07:24:21-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday August 13, 2022 at  7:24AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-9ae8a91f-451c-48f3-9a27-6093358bb527
:END:

We will construct a thermometer, or give several different
constructions.

*CAUTION:* these are purely "intellectual" and abstract. These are *NOT*
intended to be instructions for constructing an /actual/ thermometer.

* Greiner's Dilute Gas Thermometer
:PROPERTIES:
:CUSTOM_ID: h-c50bfc67-a08d-4ad2-a57a-d9b9f83abb05
:END:

Consider a glass container, which intuitively looks like a
[[https://en.wikipedia.org/wiki/Volumetric_flask][volumetric flask]]: a large reservoir with a thin glass boundary, and a
long thin neck with a thick glass boundary. We place some dilute gas
inside the flask, then "cap" it off with a "blob" of mercury.
(*This is very dangerous, please do not try this at home.*)

This summarizes the construction found in
{{{book-title(Thermodynamics and Statistical Mechanics)}}}
by Walter Greiner, Horst Stöcker, and Ludwig Neise. (See page 10.)

** Calibration
:PROPERTIES:
:CUSTOM_ID: h-220688bd-64dc-4a35-a3ff-f6ae4bde8497
:END:

The mercury acts as a "pointer". We calibrate this thermometer with the
following steps:

1. measure ice's temperature (as 0 degrees) and place a "tick" on the
   neck of the flask where the pointer rests;
2. measure boiling water's temperature (as 100 degrees) and place a "tick" on the
   neck of the flask where the pointer rests; and finally,
3. divide the distance between these markings into equal parts according
   to the temperature scale used.

** Physics Underlying This Thermometer
:PROPERTIES:
:CUSTOM_ID: h-2406c286-9116-4a3a-aa75-e1bc7f1350d0
:END:

Why does this work? Well, for a dilute gas, it turns out to be
approximated by ideal-gas behaviour very well. In particular, we would
have

\begin{equation}
pV = nRT
\end{equation}

If we make the neck thin enough, and the reservoir large enough, then
pressure $p$ would be approximately constant. We then have

\begin{equation}
\frac{V_{1}}{T_{1}} = \frac{V_{2}}{T_{2}}
\end{equation}

for volume $V_{j}$ and temperature $T_{j}$ for the system in two
states $j=1,2$.

The pointer (blob of mercury) then tracks the volume of the gas, which
is directly proportional to the temperature of the environment (or
whatever the thermometer is in contact with).