#+TITLE: Van der Waals Equation for Hydrogen Sulfide
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-08-28T08:34:54-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Sunday August 28, 2022 at  8:34AM

* Problem
:PROPERTIES:
:CUSTOM_ID: h-f2d80a02-b561-47fa-b5a2-7789a3ed2522
:END:

In the ideal-gas Law, the number of moles per volume $n/V$ is equal to $p/RT$.
But for the van der Waals equation, solving for $n/V$ in terms of
pressure $p$ and temperature $T$ is hard.

(a) Show the van der Waals equation can be written as
\begin{equation}
\frac{n}{V} = \left(\frac{p + a n^{2}/V^{2}}{RT}\right)\left(1 - \frac{bn}{V}\right)
\end{equation}

(b) The van der Waals parameter for Hydrogen Sulfide gas (H_{2} S) are
$a = 0.448~\mathrm{J}\cdot\mathrm{m}^{3}/\mathrm{mol}^{2}$ and
$b = 4.29\times10^{-5}\mathrm{m}^{3}/\mathrm{mol}$.
Determine the number of moles per volume H_{2} S gas at $127^{\circ}~\mathrm{C}$
and an absolute pressure of $9.80\times 10^{5}~\mathrm{Pa}$ as follows:

1. Calculate as a first approximation $n/V = p/RT$
2. Plug this approximation into the right-hand side of the Equation from
   part (a) to get an improved approximation for $n/V$.
3. Repeat step 2 with "the current approximation" used in the right-hand
   side and "the next approximation" being equal to the result. Iterate
   until the approximation is stable to three significant figures.

(c) Compare results from (b) to the result $p/RT$ obtained using the
ideal-gas Law. Which is bigger? Why?

* Solution
:PROPERTIES:
:CUSTOM_ID: h-28c27f25-eecf-45e9-9841-a0f85215cafc
:END:

**Identify:** We need to use the van der Waals equation and the
ideal-gas laws.

**Set up:** We recall the ideal gas Law readily enough:

\begin{equation}
pV = nRT.
\end{equation}

The van der Waals equation modifies the left-hand side to take into
account finite volume occupied by the gas $nb$ and the surface tension
affecting pressure $a n^{2}/V^{2}$. We recall it to be:

\begin{equation}
\left(p + a\frac{n^{2}}{V^{2}}\right)(V - nb) = nRT.
\end{equation}

We are given

\begin{equation}
a = 0.448~\mathrm{J}\cdot\mathrm{m}^{3}/\mathrm{mol}^{2}
\end{equation}

and

\begin{equation}
b = 4.29\times10^{-5}\mathrm{m}^{3}/\mathrm{mol}.
\end{equation}

We work at tempterature $T = 127^{\circ}~\mathrm{C}$ (which must be
converted to Kelvin) and pressure $p = 9.80\times 10^{5}~\mathrm{Pa}$.

**Set up:** (a) This is just algebra, divide through by $V$ and
rearrange terms gives the result.

(b) We can write code to compute this

#+begin_src emacs-lisp :exports both
(let* ((temperature (+ 273.15 127)) ; kelvin
       (pressure 9.8e5) ;; pascal
       (a 0.448)
       (b 4.29e-5)
       (gas-constant 8.31446261815324)
       (rhs (lambda (guess)
              (* (/ (+ pressure (* a guess guess))
                    gas-constant temperature)
                 (- 1
                    (* b guess)))))
       (initial-guess (/ pressure gas-constant temperature)))
  (list
   :initial-guess initial-guess
   :iter-1 (funcall rhs initial-guess)
   :iter-2 (funcall rhs (funcall rhs initial-guess))))
#+end_src

We see it is stable to 3 digits after 2 iterations.

(c) We see that this van der Waals approach boils down to

\begin{equation}
\left(\frac{p}{RT} + \frac{\Delta p}{RT}\right)\left(1 -
\frac{bn}{V}\right).
\end{equation}

The $bn/V\sim 10^{-2}$ so the right factor $1 - bn/V$ is very nearly 1.
The left factor is on the order of 100, so an initial guess for $n/V$
would be on the order of 100. Since $a\sim 10^{-1/2}$, we see that
$\Delta p\sim 10^{3/2}$ or larger.

Hence the problem boils down to comparing $(10 + \pi)(1 - 10^{-2})$ to
10 (the order of ideal-gas answer), which is not "immediately obvious" (to me, at least). But doing the
computation, we find $(10 + \pi)(1 - 10^{-2})\approx 13$ which is bigger
than the ideal-gas's order-of-magnitude.

**Evaluate:**
We see the order-of-magnitude makes sense, since $T\sim400~\mathrm{K}$
and $p\sim 10^{6}~\mathrm{Pa}$ gives us $n/V\sim 10^{6}/3325\approx 300$
moles per meter cube. This should be slightly greater than the answer we
obtained because we rounded up for pressure, down for temperature.

We can also observe that $bn/V\ll 1$, so we end up with a quadratic
equation
\begin{equation}
\frac{n}{V} = \frac{p + an^{2}/V^{2}}{RT}.
\end{equation}
This has its solution be:
\begin{equation}
(n/V)_{\pm} = \frac{RT \pm\sqrt{R^{2}T^{2}-4ap}}{2a}.
\end{equation}
We find the two values numerically are:
\begin{equation}
(n/V)_{+} = 7119.14
\end{equation}
and
\begin{equation}
(n/V)_{-} = 307.27.
\end{equation}
These give us upper-bounds on what we expect the solution should be.
It also gives us a sense of the correction contribution of the $bn/V$
term: small (about 5 moles per cubic meter) but noticeable.