#+TITLE: Navier-Stokes Equations
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-05-05T08:36:05-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Wednesday May  5, 2021 at  8:36AM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-7c2a3764-a09a-45c4-b8fb-05f1efe0fcc7
:END:

When we model fluid flow with viscosity (friction among the fluid
parcels), we end up with the Navier-Stokes equation. It's notoriously
difficult, and if anyone can find a suitable solution to it...they'll
win a million dollars.

* References
:PROPERTIES:
:CUSTOM_ID: h-6be39fe7-fb43-42a6-a667-fa40ca04b0e4
:END:

- O.A. Ladyzhenskaya,
  {{{book-title(The Mathematical Theory of Viscous Incompressible Flow)}}}.
  Published 1963. NB: Ladyzhenskaya is an amazing mathematician, she
  first proved the finite difference method works for numerically
  computing Navier-Stokes.
- Roger Temam,
  {{{book-title(Navier-Stokes Equations: Theory and Numerical Analysis)}}}.
  AMS Press, 2001.

** Recommended
:PROPERTIES:
:CUSTOM_ID: h-990f17f2-ddb7-4435-8954-fe2126e68a6c
:END:

The following have been recommended to me (from Tai-Peng Tsai's
{{{book-title(Lectures on Navier-Stokes Equations)}}}), though I have
yet to look at further:

- Gregory Seregin,
  {{{book-title(Lecture Notes On Regularity Theory For The Navier-Stokes Equations)}}}.
  World Scientific, 2014.
- Peter Constantin and Ciprian Foias,
  {{{book-title(Navier-Stokes equations)}}}.
  U. Chicago Press, 1988
- Pierre-Louis Lions,
  {{{book-title(Mathematical topics in fluid mechanics. Vol. 1, Incompressible models)}}}.
  Oxford Press, 1996.
- Hermann Sohr,
  {{{book-title(The  Navier-Stokes  equations:  An  elementary  functional  analytic  approach)}}}.
  Birkhauser, 2001.
- Pierre Gilles Lemarie-Rieusset,
  {{{book-title(Recent developments in the Navier-Stokes problem)}}}.
  Chapman & Hall, 2002.
- Pierre Gilles Lemarie-Rieusset,
  {{{book-title(The Navier-Stokes problem in the 21st century)}}}.
  CRC Press, 2011.
- Hajer Bahouri, Jean-Yves Chemin, and Raphael Danchin,
  {{{book-title(Fourier analysis and nonlinear partial differential equations)}}}.
  Springer, 2011.
- James C. Robinson, Jose L. Rodrigo, and Witold Sadowski,
  {{{book-title(The three-dimensional Navier-Stokes equations)}}}.
  Cambridge University Press, 2016.

** Steady State Solutions
:PROPERTIES:
:CUSTOM_ID: h-87823b9b-5a59-4903-bed2-a77cc4e6f7e8
:END:

- Giovanni Galdi,
  {{{book-title(An Introduction to the Mathematical Theory of the Navier-Stokes Equations: Steady-State Problems)}}}.
  Springer, 2nd ed., 2011.