#+TITLE: Example Definitions Finite Groups - Mizar
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-02-19T19:09:20-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/stylesheet.css" />
# Created Saturday February 19, 2022 at  7:09PM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-3514a396-c340-41d5-97f5-7fe965d4519c
:END:

This is a collection of definitions I intend to formalize in Mizar. The
hard part of the formalizations is the proof of existence and uniqueness
(or other correctness conditions).

* Extra-special groups
:PROPERTIES:
:CUSTOM_ID: h-2f274d71-e96e-4479-8d58-cfc921adb1df
:END:

Rotman's /Introduction to the Theory of Groups/, 4th ed, defines on page
124: 

#+begin_definition
Let $G$ be a finite $p$ -group. We call it {{{dfn(Extra-special)}}}
if $Z(G)$ is cyclic and $\Phi(G)=Z(G)=G'$.
#+end_definition

This defines an attribute (hinted by being of the form "We call it ~<hairy>~
if..."). Its formalization is straightforward.

#+begin_src mizar
definition
  let p be prime Nat;
  let IT be finite p-group Group;
  attr IT is extra-special means
  (center IT is cyclic) & (Phi(IT) = center IT) &
  (center IT = IT`);
end;
#+end_src

* G Has Characteristic p
:PROPERTIES:
:CUSTOM_ID: h-2e5a9e76-d90b-4603-ac16-2df78d4fc0a8
:END:

These definitions are taken from {{{arXiv(1906.07216)}}}.

#+begin_definition
Let $p$ be a prime number, $G$ be a finite group whose order is
divisible by $p$. A {{{dfn($p$-local subgroup)}}} is one that looks like
$N_{H}(P)$ where $P$ is a nontrivial $p$-subgroup of $G$.
#+end_definition

My intuition is that this definition introduces an attribute "$p$-local"
for subgroups.

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group such that p divides card G;
  let IT be Subgroup of G;
  attr IT is p-local means
  :Def:
  ex P being non trivial p-group Subgroup of G
  st the multMagma of IT = Normalizer P;
end;
#+end_src

Since subgroup equality is defined only for strict subgroups, we cannot
say ~IT = Normalizer P~ without making ~IT~ a strict Subgroup of G. (The
normalizer of a subgroup is defined to be a strict subgroup.) For this
reason, we needed to check ~the multMagma of IT = Normalizer P~.

#+begin_definition
Let $p$ be a prime number, $G$ be a finite group, $L\leq G$ be a subgroup.
We say $L$ {{{dfn(has Characteristic $p$)}}} if
$C_{G}(O_{p}(L))\leq O_{p}(L)$.
#+end_definition

This introduces a new predicate, ~has_characteristic p~ for a subgroup.

#+begin_src mizar
definition
  let p be prime Nat;
  let G be Group;
  let L be Subgroup of G;
  pred L has_characteristic p means
  :Def:
  Centralizer (p-core L) is Subgroup of (p-core L);
end;
#+end_src

#+begin_definition
Let $p$ be a prime number, $G$ be a finite group.
We say $G$ {{{dfn(has local Characteristic $p$)}}} if
if for all $p$-local subgroups $L$ of $G$ has characteristic $p$.
#+end_definition

(A special case when $p = 2$, we just say that $G$ has even
Characteristic.)

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group;
  pred G has_local_characteristic p means
  :Def:
  for L being Subgroup of G st L is p-local holds L has_characteristic p;
end;
#+end_src

From page ix of [[https://users.math.msu.edu/users/meierfra/Preprints/CGP/Structure/structure.pdf][The Local Structure Theorem For Finite Groups With A Large p-Subgroup]]:

#+begin_definition
A finite group $G$ has {{{dfn(characteristic $p$)}}} if $C_{G}(O_{p}(G))\leq O_{p}(G)$.
#+end_definition

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group;
  pred G has_characteristic p means
  :Def:
  Centralizer (p-core G) is Subgroup of (p-core G);
end;
#+end_src

* Parabolic Subgroup
:PROPERTIES:
:CUSTOM_ID: h-03074538-22a6-4bac-869b-a27c2bd4004c
:END:

#+begin_definition
Let $G$ be a finite group.
Any subgroup of $G$ containing a Sylow p-subgroup of $G$ is a
{{{dfn(parabolic subgroup)}}} of $G$.
#+end_definition

This defines an attribute "parabolic" for "Subgroup of $G$". We need to
use the Mizar predicate [[http://mizar.org/version/current/html/group_10.html#R3][~is_Sylow_p-subgroup_of_prime~]] to do the heavy lifting:

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group;
  let IT be Subgroup of G;
  attr IT is parabolic means
  :Def:
  ex P being Subgroup of G st P is_Sylow_p-subgroup_of_prime p &
  P is Subgroup of IT;
end;
#+end_src

#+begin_definition
Let $p$ be a prime number, $G$ be a finite group.
We say $G$ has {{{dfn(parabolic characteristic $p$)}}} if
every $p$-local parabolic subgroup of $G$ has characteristic $p$.
#+end_definition

This defines a predicate (whenever a gadget "has ~<property>~", it
defines a predicate).

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group;
  pred G has_parabolic_characteristic p means
  :Def:
  for H being parabolic Subgroup of G st H is p-local
  holds H has_characteristic p;
end;
#+end_src
* Finite Group Theory
:PROPERTIES:
:CUSTOM_ID: h-5ae83f58-ed1c-4543-8e5d-a49c61ba6701
:END:

** Sections of a Group
:PROPERTIES:
:CUSTOM_ID: h-86c68c5f-b76f-407c-aab0-aa4aecc6ceb9
:END:

Kurzweill and Stellmacher's /Theory of Finite Groups/ \S 1.3 concludes
with a brief definition in passing:

#+begin_definition
Let $G$ be a group, $N\trianglelefteq H\leq G$. We call the quotient
$H/N$ a {{{dfn(Section)}}} of $G$.
#+end_definition

In particular, $N$ is a normal subgroup of $H$ (viz., $N$ is not
necessarily a normal subgroup of $G$).

This appears to define a new mode (as hinted by "~<bork>~ of $G$").
*However* not all groups have a section (the quaternions famously do
not).

Consequently, we need to define this as a predicate.

#+begin_src mizar
definition
  let K,G be Group;
  pred K is_section_of G means :Def:
  ex H being Subgroup of G st
  ex N being normal Subgroup of H st
  K = H./.N;
end;
#+end_src

Note: we may need to change the denominator to ~(H,N)`*`~ which will
"cast" ~N~ as a normal subgroup of ~H~. 

We also have a related notion "$G$ is involved in $K$" means $G$ is
isomorphic to a section of $K$. This is a transitive relation.

* Exponent of Group
:PROPERTIES:
:CUSTOM_ID: h-71ef82c3-d433-4eba-98a8-bac942140338
:END:

#+begin_definition
Let $G$ be a group. Its {{{dfn(Exponent)}}} is the least natural number
$n\in\mathbb{N}$ such that every $g\in G$ satisfies $g^{n}=1_{G}$. If
there is an element of order 0 in the group, then the exponent of $G$ is
defined to be 0.
#+end_definition

#+begin_src mizar
definition
  let G be Group;
  func exponent G -> Nat means
  :Def:
  it = 0 if ex g being Element of G st g is being_of_order_0
  otherwise it > 0 &
            for g being Element of G
            holds g |^ it = 1_G &
                  (for n being Nat st g |^ n = 1_G holds it <= n);
  
  existence
  proof
    thus (ex g being Element of G st g is being_of_order_0) implies
    (ex k being Nat st k = 0);
    thus (for g being Element of G holds not g is being_of_order_0) implies
    (ex k being Nat st
     for g being Element of G
     holds g |^ k = 1_G & (for n being Nat st g |^ n = 1_G holds k <= n));
  end;

  uniqueness
  proof
    defpred P[Element of Nat] means $1 > 0 &
    for g being Element of G
    holds g |^ ($1) = 1_G & (for n being Nat st g |^ n = 1_G holds ($1) <= n);

    let k1,k2 be Nat;

    thus (ex g being Element of G st g is being_of_order_0) & k1 = 0 & k2 = 0
    implies k1 = k2;
    
    thus (for g being Element of G holds not g is being_of_order_0) & P[k1] & P[k2]
    implies k1 = k2;
  end;

  consistency;
end;
#+end_src

* Elementary Abelian Group
:PROPERTIES:
:CUSTOM_ID: h-bea1584a-3260-4505-8938-578af0e8d5db
:END:

Aschbacher's {{{book-title(Finite Group Theory)}}} nicely defines an
elementary Abelian group right before \S1.13:

#+begin_definition
Let $p$ be a prime number, we define an {{{dfn(Elementary Abelian $p$ -Group)}}}
to be an Abelian $p$ -Group of exponent $p$.
#+end_definition

Luckily, ~groupp_1~ defines [[http://mizar.org/version/current/html/groupp_1.html#V3][~p-commutative-group~]] and which does a lot of
heavy lifting for us.

#+begin_src mizar
definition
  let p be prime Nat;
  let IT be finite Group;
  attr IT is p-elementary_Abelian means
  :Def:
  IT is p-commutative-group & exponent IT = p;
end;

:: Kurzweil & Stellmacher, _Theory of Finite Groups_, Thm 5.2.6
theorem
  for G being p-elementary_Abelian Group
  holds Phi(G) is trivial;

:: Kurzweil & Stellmacher, _Theory of Finite Groups_, Thm 5.2.7 (a)
theorem
  for P being p-group Group
  holds P./.Phi(P) is p-elementary_Abelian Group;
#+end_src

We will also want to define the $p$ rank of a finite group. This would
be the largest [[http://mizar.org/version/current/html/groupp_1.html#K1][~expon~]] of the ~p-elementary_Abelian~ subgroups of ~G~.

#+begin_definition
Let $G$ be a group, $p$ be a prime. The {{{dfn($p$ -rank)}}} of $G$ is
the maximum rank of all elementary Abelian $p$ -subgroups of $G$.
#+end_definition

This is only really well-defined if $G$ is a finite group whose order is
divisible by $p$, or if there exists an element whose order is divisible
by $p$. Since we only really care about the $p$ -rank for *finite*
groups, we can restrict our definition to finite groups.

#+begin_src mizar
definition
  let p be prime Nat;
  let G be finite Group;
  func p-rank G means
  :Def:
  it > 0 & for E being Subgroup of G
           st E is p-elementary_Abelian
           holds expon(E,p) <= it &
                 (for n being Nat
                  st n > 0 & expon(E,p) <= n
                  holds it <= n)
  if p divides card G
  otherwise it = 0;

  existence
  proof
    defpred P[Nat] means
    ($1) > 0 & for E being Subgroup of G
               st E is p-elementary_Abelian
               holds expon(E,p) <= ($1) &
                     (for n being Nat st n > 0 & expon(E,p) <= n
                      holds ($1) <= n);
    thus p divides card G implies ex k being Nat st P[k];
    thus not p divides card G implies ex k being Nat st k=0;
  end;

  uniqueness
  proof
    defpred P[Nat] means
    ($1) > 0 & for E being Subgroup of G
               st E is p-elementary_Abelian
               holds expon(E,p) <= ($1) &
                     (for n being Nat st n > 0 & expon(E,p) <= n
                      holds ($1) <= n);
    let k1,k2 be Nat;
    thus p divides card G & P[k1] & P[k2] holds k1 = k2;
    thus not (p divides card G) & (k1 = 0) & (k2 = 0) implies k1 = k2;
  end;

  consistency;
end;

notation
  let p be prime Nat, G be finite Group;
  synonym p-depth G for p-rank G;
end;
#+end_src

** Depth of Group
:PROPERTIES:
:CUSTOM_ID: h-577c3222-c227-4f29-a1ce-778af705a4b5
:END:

The depth of a finite group is the largest $p$ -rank of the group for
any prime $p$.

#+begin_src mizar
definition
  let G be finite Group;
  func depth G -> Nat means
  for p being prime Nat
  holds p-rank G <= it & (for n being Nat
                          st p-rank G <= n
                          holds it <= n);

  existence
  proof
    thus ex k being Nat st
         for p being prime Nat
         holds p-rank G <= k &
               (for n being Nat st p-rank G <= n holds k <= n);
  end;

  uniqueness
  proof
    defpred P[Nat] means for p being prime Nat
    holds p-rank G <= ($1) & (for n being Nat
                              st p-rank G <= n
                              holds ($1) <= n);
    thus for k1,k2 being Nat st P[k1] & P[k2] holds k1=k2;
  end;
end;

theorem
  for G being trivial Group
  for p being prime Nat
  holds p-rank G = 0;
#+end_src

** Thin and Quasithin groups
:PROPERTIES:
:CUSTOM_ID: h-8f7b98d9-997c-4089-8641-56911841c828
:END:

We can now define thin and quasithin groups. They are defined using the
maximum $p$ -rank (over all odd prime $p$) for 2-local subgroups of $G$.

#+begin_src mizar
definition
  let IT be finite Group;
  attr IT is thin means
  :Def:
  for p being odd prime Nat
  holds 2-local_p-rank IT <= 1;

  attr IT is quasithin means
  :Def:
  for p being odd prime Nat
  holds 2-local_p-rank IT <= 2;

  attr IT is strongly_quasithin means
  :Def:
  for p being odd prime Nat
  holds p-rank IT <= 2;
end;

theorem the trivial Group is thin;
theorem the trivial Group is quasithin;

registration
  cluster thin finite Group
  existence
  proof
    take the trivial Group;
    hence thesis;
  end;
  
  cluster quasithin finite Group
  existence
  proof
    take the trivial Group;
    hence thesis;
  end;
end;

registration
  cluster thin -> quasithin finite Group;
  coherence
  proof
    thus for G being finite Group st G is thin holds G is quasithin;
  end;
end;
#+end_src
