#+TITLE: Field Theory - Rosetta Stone
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2025-12-29T08:49:34-08:00>
#+LANGUAGE: en
#+OPTIONS: H:nil toc:nil num:nil
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/stylesheet.css" />
# Created Monday December 29, 2025 at  8:49AM

Again, following Dummit and Foote's /Abstract Algebra/, chapters 13
and 14 (since that's the first half of Caltech's Math 5C course).

* Ch. 13 Field Theory
:PROPERTIES:
:CUSTOM_ID: h-8376fbfe-9da7-4597-8d1a-0db5f790df10
:END:

** \sect13.1 Basic Theory of Field Extensions
:PROPERTIES:
:CUSTOM_ID: h-c96e6267-4b90-4bd5-b21b-85bcddc00971
:END:

- *Definition.* The {{{dfn(Characteristic)}}} of a field $F$, denoted
  $\operatorname{ch}(F)$, is defined to be the smallest positive
  integer $p$ such that $p\cdot1_{F}=0$ if such a $p$ exists and is
  defined to be 0 otherwise. ([[https://mizar.uwb.edu.pl/version/current/html/ring_3.html#K3][~ring_3:def 5~]])
- *Proposition 1.* The characteristic of a field is either 0 or a
  prime $p$. If $\operatorname{ch}(F)=p$ then for any $\alpha\in F$ we
  have $p\cdot\alpha=0$.
- *Examples.*
  1. The fields $\mathbb{Q}$ and $\mathbb{R}$ both have characteristic 0.
  2. The finite field $\mathbb{F}_{p}$ has characteristic $p$
- *Implicit Definition.* Let $F$ be a field. A {{{dfn(Subfield)}}} of
  $F$ is a subring which is a field.
  ([[https://mizar.uwb.edu.pl/version/current/html/ec_pf_1.html#M1][~ec_pf_1:def 1~]])
- *Definition.* The {{{dfn(Prime Subfield)}}} of a field $F$ ([[https://mizar.uwb.edu.pl/version/current/html/ring_3.html#K7][~ring_3:def 10~]]) is the
  subfield of $F$ generated by the multiplicative identity $1_{F}$ of
  $F$. It is isomorphic to either $\mathbb{Q}$ (if
  $\operatorname{ch}(F)=0$ --- [[https://mizar.uwb.edu.pl/version/current/html/ring_3.html#T103][~ring_3:103~]])
  or $\mathbb{F}_{p}$ (if $\operatorname{ch}(F)=p$ --- [[https://mizar.uwb.edu.pl/version/current/html/ring_3.html#T111][~ring_3:111~]]).
- *Definition.* If $K$ Is a field containing the subfield $F$, then
  $K$ is said to be an {{{dfn(extension field)}}} of $F$, denoted
  $K/F$.
  - This is defined as a type in [[https://mizar.uwb.edu.pl/version/current/html/field_4.html#NM4][~field_4~]]
  - The "meat" of the definition is an attribute ([[https://mizar.uwb.edu.pl/version/current/html/field_4.html#V1][~field_4:def 1~]])
  - *Note:* We can really speak of ring extensions analogously, and
    this is formalized in ~field_4~ a bit
- *Implicit definition.* If $K/F$ is a field extension, then $K$ is a
  vector space over $F$. ([[https://mizar.uwb.edu.pl/version/current/html/field_4.html#K2][~field_4:def 6~]])
- *Definition.* The {{{dfn(Degree)}}} of a field extension $K/F$,
  denoted $[K:F]$, is the dimension of $K$ as a vector space over $F$
  --- so $[K:F]:=\dim_{F}K$. ([[https://mizar.uwb.edu.pl/version/current/html/field_4.html#K3][~field_4:def 7~]])
  - *Note:* Mizar's convention is to treat $[K:F]=-1$ when $\dim_{F}K$
    is not finite. This is idiomatic in Mizar handling of [[https://mizar.uwb.edu.pl/version/current/html/int_1.html#V2][~dim-like~]] things.
- *Proposition 2.* Let $\varphi\colon F\to F'$ be a morphism of
  fields. Then $\varphi$ is either identically 0 or injective, so that
  the image of $\varphi$ is either 0 or isomorphic to $F$.
  (This is a registration in [[https://mizar.uwb.edu.pl/version/current/html/ring_2.html#CC2][~ring_2~]])
- *Implicit Definition.* Let $F$ be a field, let $p(x)\in F[x]$,
  let $K/F$ be a field extension, let $c\in K$. Then we can treat
  $p\in K[x]$ and evaluate $p(c)$ --- this is ~Ext_eval(p,c)~
  ([[https://mizar.uwb.edu.pl/version/current/html/algnum_1.html#K1][~algnum_1:def 1~]])
- *Implicit Definition.* Let $F$ be a field and $p(x)\in F[x]$, let
  $K/F$ be a field extension of $F$. We say $p$ {{{dfn(has roots in)}}}
  (or "has roots in") $K$ if there exists an $\alpha\in K$ such
  that $p(\alpha)=0$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_4.html#R2][~field_4:def 3~]])
- *Theorem 3.* Let $F$ be a field, let $p(x)\in F[x]$ be an irreducible
  polynomial. Then there exists a field $K$ containing a subfield
  isomorphic to $F$ in which $p(x)$ has a root.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_4.html#T31][~field_4:31~]])

  Identifying $F$ with
  this isomorphic copy shows there exists an extension of $F$ in which
  $p(x)$ has a root.
- *Theorem 4.* Let $p(x)\in F[x]$ be an irreducible polynomial of
  degree $n$ over the field $F$. Let $K$ be the field $F[x]/(p(x))$.
  Let $\theta=x\pmod{p(x)}\in K$. Then the elements 1, $\theta$,
  \dots, $\theta^{n-1}$ are a basis for $K$ as a vector space over
  $F$, so the degree of the extension is $n$ --- that is, $[K:F]=n$.
  - This set $\{1,\theta,\dots,\theta^{n-1}\}$ is defined in Mizar as
    ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#K7][~field_6:def 8~]])

  - That this is a basis of the vector space is proved in
    [[https://mizar.uwb.edu.pl/version/current/html/field_6.html#T65][~field_6:65~]]
- *Definition.* Let $K$ be an extension of the field $F$. Let
  $\alpha,\beta,\dots\in K$ be a collection of elements of $K$. The
  smallest subfield of $K$ containing both $F$ and the elements
  $\alpha,\beta,\dots$ --- denoted as $F(\alpha,\beta,\dots)$ --- is
  called the field {{{dfn(generated by)}}} $\alpha,\beta,\dots$ over $F$.

  This is usually called the field {{{dfn(adjoined with)}}} $\alpha,\beta,\dots$
  ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#K5][~field_6:def 6~]])
- *Definition.* If the field $K$ is generated by a single element
  $\alpha$ over $F$ --- that is, $K = F(\alpha)$ --- then we say $K$
  is a {{{dfn(Simple)}}} extension of $F$ ([[https://mizar.uwb.edu.pl/version/current/html/field_14.html#V2][~field_14:def 7~]])
  and the element $\alpha$ is
  said to be a {{{dfn(Primitive Element)}}} of the extension ([[https://mizar.uwb.edu.pl/version/current/html/field_14.html#V3][~field_14:def 8~]]).
- *Theorem 6.* Let $F$ be a field and let $p(x)\in F[x]$ be an
  irreducible polynomial. Suppose $K$ is an extension field of $F$
  containing a root $\alpha$ of $p(x)$ --- so $p(\alpha)=0$. Let
  $F(\alpha)$ denote the subfield of $K$ generated by $F$ over
  $\alpha$. Then $F(\alpha)\cong F[x]/(p(x))$.
  - This particular theorem seems to be missing in Mizar, but follows
    from [[https://mizar.uwb.edu.pl/version/current/html/field_6.html#T59][~field_6:59~]]
- *Corollary 7.* Suppose in Theorem 6 that $p(x)$ is of degree
  $n$. Then
  $F(\alpha)=\{a_{0}+a_{1}\alpha+\dots+a_{n-1}\alpha^{n-1}\mid a_{i}\in F\}\subset K$.
  {{{missing()}}}
- *Theorem 8.* Let $\varphi\colon F\to F'$ be an isomorphism of
  fields. Let $p(x)\in F[x]$ be an irreducible polynomial, let
  $p'(x)\in F'[x]$ be the irreducible polynomial obtained by applying
  the map $\varphi$ to the coefficients of $p(x)$. Let $\alpha$ be a
  root of $p(x)$ in some field extension of $F$, let $\beta$ be a root
  of $p'(x)$ in some extension of $F'$. Then there is an isomorphism
  $\sigma\colon F(\alpha)\to F'(\beta)$ sending $\alpha$ to $\beta$
  and extending $\varphi$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_8.html#T55][~field_8:55~]], and $\sigma$ in Mizar is ~Phi~)

** \sect13.2 Algebraic Extensions
:PROPERTIES:
:CUSTOM_ID: h-5464593f-4596-4f0b-9533-5f9f09105f91
:END:

- *Definition.* Let $F$ be a field, let $K$ be an extension field of
  $F$. The element $\alpha\in K$ is said to be {{{dfn(Algebraic)}}}
  over $F$ if $\alpha$ is the root of some nonzero polynomial $f(x)\in
  F[x]$. ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#V2][~field_6:def 7~]])

  If $\alpha$ is not algebraic over $F$, then $\alpha$ is said to be
  {{{dfn(Transcendental)}}} over $F$. (Synonym in [[https://mizar.uwb.edu.pl/version/current/html/field_6.html#NV3][~field_6~]])

  The extension $K/F$ is said to be {{{dfn(Algebraic)}}} if every
  element of $K$ is algebraic over $F$ ([[https://mizar.uwb.edu.pl/version/current/html/field_7.html#V2][~field_7:def 11~]]).
- *Proposition 9.* Let $\alpha$ be algebraic over $F$. Then there is a
  unique monic irreducible polynomial $m_{\alpha,F}(x)\in F[x]$ which
  has $\alpha$ as a root. (Proved in the definition of the minimal polynomial.)

  A polynomial $f(x)\in F[x]$ has $\alpha$ as
  a root if and only if $m_{\alpha,F}(x)$ divides $f(x)$ in $F[x]$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#T53][~field_6:53~]])
- *Corollary 10.* If $L/F$ is a field extension and $\alpha$ is
  algebraic over $F$ and $L$, then $m_{\alpha,L}(x)$ divides
  $m_{\alpha,F}(x)$ in $L[x]$. {{{missing()}}}
- *Definition.* The polynomial $m_{\alpha,F}(x)$ --- or just
  $m_{\alpha}(x)$ --- in Proposition 9 is called the {{{dfn(Minimal Polynomial)}}}
  for $\alpha$ over $F$.
  ([[https://mizar.uwb.edu.pl/version/current/html/algnum_1.html#K4][~algnum_1:def 9~]] and in ~field_6~ abbreviated to [[https://mizar.uwb.edu.pl/version/current/html/field_6.html#NK9][~MinPoly~]])

  The {{{dfn(degree)}}} of $\alpha$ is equal to the degree of the
  minimal polynomial $m_{\alpha}(x)$.
  ([[https://mizar.uwb.edu.pl/version/current/html/algnum_1.html#K5][~algnum_1:def 10~]])
- *Proposition 11.* Let $\alpha$ be algebraic over the field $F$ and
  let $F(\alpha)$ be the field generated by $\alpha$ over $F$. Then
  $F(\alpha)\cong F[x]/(m_{\alpha}(x))$
  ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#T59][~field_6:59~]])
  so that $[F(\alpha):F]=\deg(m_{\alpha}(x))$.
- *Proposition 12.* The element $\alpha$ is algebraic over $F$ if and
  only if the simple extension $F(\alpha)/F$ is finite ([[https://mizar.uwb.edu.pl/version/current/html/field_6.html#T68][~field_6:68~]]).

  More precisely,
  1. if $\alpha$ is an element of an extension of degree
     $n$ over $F$, then $\alpha$ satisfies a polynomial of degree at most
     $n$ over $F$; and
  2. if $\alpha$ satisfies a polynomial of degree $n$ over $F$, then
     the degree of $F(\alpha)$ over $F$ is at most $n$.
- *Corollary 13.* If the extension $K/F$ is finite, then it is
  algebraic. ([[https://mizar.uwb.edu.pl/version/current/html/field_7.html#T37][~field_7:37~]] and also this is registered in [[https://mizar.uwb.edu.pl/version/current/html/field_7.html#CC5][~field_7~]])
- *Theorem 14.* Let $F\subset K\subset L$ be fields. Then
  $[L:F]=[L:K][K:F]$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_7.html#T30][~field_7:30~]])
- *Corollary 15.* Suppose $L/F$ is a finite extension, let $K$ be any
  subfield of $L$ containing $F$ (so $F\subset K\subset L$). Then
  $[K:F]$ divides $[L:F]$. {{{missing()}}}
- *Definition.* An extension $K/F$ is {{{dfn(Finitely Generated)}}} if
  there are elements $\alpha_{1}$, \dots, $\alpha_{n}$ in $K$ such
  that $K=F(\alpha_{1},\dots,\alpha_{n})$.
- *Lemma 16.* $F(\alpha,\beta)=(F(\alpha))(\beta)$ --- that is to say,
  the field generated over $F$ by $\alpha$ and $\beta$ is the field
  generated by $\beta$ over $F(\alpha)$. {{{missing()}}}
- *Theorem 17.* The extension $K/F$ is finite if and only if $K$ is
  generated by a finite number of algebraic elements over $F$. {{{missing()}}}
- *Corollary 18.* Suppose $\alpha$ and $\beta$ are algebraic over
  $F$. Then $\alpha\pm\beta$, $\alpha\beta$, $\alpha/\beta$ (for
  $\beta\neq0$) are all algebraic. {{{missing()}}}
- *Corollary 19.* Let $L/F$ be an arbitrary field extension. Then the
  collection of elements of $L$ that are algebraic over $F$ form a
  subfield $K$ of $L$. {{{missing()}}}
- *Theorem 20.* If $K$ is algebraic over $F$, and if $L$ is algebraic
  over $K$, then $L$ is algebraic over $F$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_7.html#T39][~field_7:39~]])
- *Definition.* Let $K_{1}$ and $K_{2}$ be two subfields of $K$. Then
  the {{{dfn(Composite Field)}}} of $K_{1}$ and $K_{2}$, denoted
  $K_{1}K_{2}$, is the smallest subfield of $K$ containing both
  $K_{1}$ and $K_{2}$. {{{missing()}}}
- *Implicit proposition.* The composite $K_{1}K_{2}$ is the
  intersection of all subfields of $K$ containing both $K_{1}$ and $K_{2}$. {{{missing()}}}
- *Proposition 21.* Let $K_{1}$ and $K_{2}$ be two finite extensions
  of a field $F$ contained in $K$. Then
  $[K_{1}K_{2}:F]\leq[K_{1}:F][K_{2}:F]$ {{{missing()}}}
- *Corollary 22.* Suppose $[K_{1}:F]=n$ and $[K_{2}:F]=m$ in
  Proposition 21 where $m$ and $n$ are coprime $\gcd(m,n)=1$. Then
  $[K_{1}K_{2}:F]=[K_{1}:F][K_{2}:F]=mn$. {{{missing()}}}

** \sect13.3 Classical Straightedge and Compass Constructions
:PROPERTIES:
:CUSTOM_ID: h-f5b73a1c-09b4-4cce-80b7-f164bd8bcc52
:END:

I'm skipping this section. If you're interested, I can revisit this.

** \sect13.4 Splitting Fields and Algebraic Closures
:PROPERTIES:
:CUSTOM_ID: h-e88f42c9-c1cb-466a-a816-d5dc11549b38
:END:

- *Definition.* The extension $K$ of $F$ is called a {{{dfn(Splitting Field)}}} ([[https://mizar.uwb.edu.pl/version/current/html/field_8.html#M1][~field_8:def 1~]])
  for the polynomial $f(x)\in F[x]$ if $f(x)$ factors completely into
  linear factors (or {{{dfn(Splits Completely)}}} [[https://mizar.uwb.edu.pl/version/current/html/field_4.html#R3][~field_4: def 5~]]) in $K[x]$ and
  $f(x)$ does not factor completely into linear factors over any
  proper subfield of $K$ containing $F$.
- *Theorem 25.* For any field $F$, if $f(x)\in F[x]$ then there exists
  an extension $K$ of $F$ which is a splitting field for $f(x)$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_8.html#T31][~field_8:31~]])
  - NOTE: Dummit and Foote errs here! We need $f(x)$ to be a
    nonconstant polynomial.
- *Definition.* If $K$ is an algebraic extension of $F$ which is the
  splitting field over $F$ for a collection of polynomials $f(x)\in F[x]$
  then $K$ is called a {{{dfn(Normal)}}} extension of $F$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_13.html#V2][~field_13:def 5~]])
- *Proposition 26.* A splitting field of a polynomial of degree $n$
  over $F$ is of degree at most $n!$ over $F$. {{{missing()}}}
- *Definition.* A generator of the  cyclic group of all n-th roots of
  unity is called a {{{dfn(Primitive)}}} n-th root of unity. These are
  typically denoted $\zeta_{n}$.
  - Roots of unity are defined in [[https://mizar.uwb.edu.pl/version/current/html/uniroots.html#K2][~uniroots:def 2~]]
- *Definition.* The field $\mathbb{Q}(\zeta_{n})$ is called the
  {{{dfn(Cyclotomic Field of n-th roots of unity)}}}.
  ([[https://mizar.uwb.edu.pl/version/current/html/uniroots.html#K5][~uniroots:def 5~]])
- *Theorem 27.* Let $\varphi\colon F\to F'$ be an isomorphism of
  fields. Let $f(x)\in F[x]$ be a polynomial, let $f'(x)\in F'[x]$ be
  a polynomial obtained by applying $\varphi$ to the coefficients of
  $f(x)$. Let $E$ be a splitting field for $f(x)$ over $F$, let $E'$
  be a splitting field for $f'(x)$ over $F'$. Then the isomorphism
  $\varphi$ extends to an isomorphism $\sigma\colon E\to E'$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_8.html#T57][~field_8:57~]])
- *Corollary 28* (Uniqueness of splitting fields). Any two splitting
  fields for a polynomial $f(x)\in F[x]$ over a field $F$ are
  isomorphic.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_8.html#T58][~field_8:58~]])
- *Definition.* The field $\overline{F}$ is called an {{{dfn(Algebraic Closure)}}}
  of $F$ if $\overline{F}$ is algebraic over $F$ and if every
  polynomial $f(x)\in F[x]$ splits completely over $\overline{F}$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_12.html#M3][~field_12:def 11~]])
- *Definition.* A field $K$ is said to be {{{dfn(Algebraically Closed)}}}
  if every polynomial with coefficients in $K$ has a root over $K$.
  ([[https://mizar.uwb.edu.pl/version/current/html/polynom5.html#V2][~polynom5:def 9~]])
- *Proposition 29.* Let $\overline{F}$ be the algebraic closure of
  $F$. Then $\overline{F}$ is algebraically closed. (This is part of
  the definition of algebraic closure in Mizar.)
- *Proposition 30.* For any field $F$ there exists an algebraically
  closed field $K$ containing $F$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_12.html#T29][~field_12:29~]])
- *Proposition 31.* Let $K$ be an algebraically closed field, let $F$
  be a subfield of $K$. Then the collection of elements $\overline{F}$
  of $K$ which are algebraic over $F$ is an algebraic closure of $F$.

  An algebraic closure of $F$ is unique up to isomorphism.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_12.html#T63][~field_12:63~]])
- *Theorem.* The field $\mathbb{C}$ is algebraically closed.
  (This is [[https://mizar.uwb.edu.pl/version/current/html/polynom5.html#FC6][registered in ~polynom5~]] and is [[https://mizar.uwb.edu.pl/version/current/html/polynom5.html#T74][~polynom5:74~]])
- *Corollary 32.* The field $\mathbb{C}$ contains an algebraic closure
  for any of its subfields. In particular, $\overline{\mathbb{Q}}$
  (the algebraic closure of $\mathbb{Q}$ in $\mathbb{C}$) is an
  algebraic closure of $\mathbb{Q}$.
  {{{missing()}}}

** \sect13.5 Separable and Inseparable Extensions
:PROPERTIES:
:CUSTOM_ID: h-f6703d97-5312-485e-ba61-5304eba506db
:END:

- *Definition.* A polynomial over $F$ is called {{{dfn(Separable)}}}
  if it has no multiple roots (i.e., all its roots are distinct).
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#V1][~field_15:def 3~]])
  Otherwise, it is called {{{dfn(Inseparable)}}}
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#NV2][~field_15~]])
- *Definition.* The {{{dfn(Derivative)}}} of the polynomial
  $f(x)=a_{n}x^{n}+a_{n-1}x^{n-1}+\dots+a_{1}x+a_{0}$ is the
  polynomial
  $D_{x}f(x)=na_{n}x^{n-1}+(n-1)a_{n-1}x^{n-2}+\dots+2a_{2}x+a_{1}$.
  ([[https://mizar.uwb.edu.pl/version/current/html/ringder1.html#K9][~ringder1:def 8~]] and also aliased in [[https://mizar.uwb.edu.pl/version/current/html/field_14.html#NK6][~field_14~]])
- *Proposition 33.* A polynomial $f(x)$ has a multiple root $\alpha$
  if and only if $\alpha$ is also a root of $D_{x}f(x)$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#T70][~field_15:70~]])
- *Corollary 34.* Every irreducible polynomial over a field of
  characteristic 0 is separable. (Registered fact in [[https://mizar.uwb.edu.pl/version/current/html/field_15.html#CC3][~field_15~]])

  A polynomial over such a field is separable if and only if it is the
  product of distinct irreducible polynomials. {{{missing()}}}
- *Proposition 35.* Let $F$ be a field of characteristic $p$. Then for
  any $a,b\in F$ we have $(a+b)^{p}=a^{p}+b^{p}$ and $(ab)^{p}=a^{p}b^{p}$
- *Definition.* The map in Proposition 35 is called the
  {{{dfn(Frobenius Endomorphism)}}} of $F$
  ([[https://mizar.uwb.edu.pl/version/current/html/field_16.html#K5][~field_16:def 6~]])
- *Corollary 36.* Suppose $F$ isa finite field of characteristic
  $p$. Then every element of $F$ is a $p^{th}$ power in $F$
  (notationally: $F=F^{p}$)
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#T93][~field_15:93~]] and [[https://mizar.uwb.edu.pl/version/current/html/field_16.html#T25][~field_16:25~]])
- *Proposition 37.* Every irreducible polynomial over a finite field
  is separable. {{{missing()}}}

  A polynomial in $F[x]$ is separable if and only if it is the product
  of distinct irreducible polynomials in $F[x]$.
- *Definition.* A field $K$ of characteristic $p$ is called
  {{{dfn(Perfect)}}} if every element of $K$ is a p-th power in $K$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#V2][~field_15:def 4~]])
- *Proposition 38.* Let $p(x)$ be an irreducible polynomial over a
  field $F$ of characteristic $p$. Then there exists a unique integer
  $k\geq0$ and a unique irreducible separable polynomial
  $p_{sep}(x)\in F[x]$ such that $p(x)=p_{sep}(x^{p^{k}})$. {{{missing()}}}
- *Definition.* Let $p(x)$ be an irreducible polynomial over a field
  of characteristic $p$. The degree of $p_{sep}(x)$ in the previous
  proposition is called the {{{dfn(Separable Degree)}}} of $p(x)$,
  denoted $\deg_{s}p(x)$. {{{missing()}}}

  The integer $p^{k}$ in the last proposition is called the
  {{{dfn(Inseparable Degree)}}} of $p(x)$, denoted $\deg_{i}p$. {{{missing()}}}
- *Definition.* The field $K$ is said to be {{{dfn(Separable)}}} over
  $F$ if every element of $K$ is the root of a separable polynomial
  over $F$.
  ([[https://mizar.uwb.edu.pl/version/current/html/field_15.html#T93][~field_15:def 5~]])

** \sect13.6 Cyclotomic Polynomials and Extensions
:PROPERTIES:
:CUSTOM_ID: h-eafd3cf5-1227-448a-83cb-6083ec8711a5
:END:

- *Definition.* Let $\mu_{n}$ denote the {{{dfn(Group of n-th Roots of Unity)}}}
  over $\mathbb{Q}$
  ([[https://mizar.uwb.edu.pl/version/current/html/uniroots.html#K3][~uniroots:def 3~]])


* Ch. 14 Galois Theory
:PROPERTIES:
:CUSTOM_ID: h-dd46e7b1-85b0-4dd2-89b0-175263e60ad3
:END:

This is actively being formalized by Christoph Schwarzweller and
friends. So I am deferring transcribing anything until their work is
done. 