#+TITLE: Lie Theory in Mizar
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2022-02-17T09:11:39-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/stylesheet.css" />
# Created Thursday February 17, 2022 at  9:11AM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-0ff3dfee-375a-43d1-b8e5-fe1160a3383e
:END:

This is just a placeholder for my thinking about formalizing Lie
algebras and Lie groups in Mizar. On the whole, it seems following
Bourbaki's books may be the best outline/strategy.

* Relevant Definitions
:PROPERTIES:
:CUSTOM_ID: h-42b94e81-8319-49c1-ab2d-d8852a381f56
:END:

** Existing in Mizar
:PROPERTIES:
:CUSTOM_ID: h-8e62fe3a-da15-47d4-93a1-9f70d1331b65
:END:

Mizar's library is /huge/, here's what I could find at a glance that's
relevant.

- [[http://mizar.org/version/current/html/polynom3.html][~polynom3~]] defines:
  - [[http://mizar.org/version/current/html/polynom3.html#NM1][~Polynomial of L~]] as ~AlgSequence of L~
- In [[http://mizar.org/version/current/html/polyalg1.html][~polyalg1~]], we have the following definitions
  - [[http://mizar.org/version/current/html/polyalg1.html#L1][~AlgebraStr over F~]] (which is both a "ring" (~doubleLoopStr~) and a
    ~ModuleStr~ over F)
  - [[http://mizar.org/version/current/html/polyalg1.html#NM1][~Algebra of L~]]
  - [[http://mizar.org/version/current/html/polyalg1.html#M1][~Subalgebra~]]
- In [[http://mizar.org/version/current/html/vectsp_1.html][~vectsp_1~]]:
  - [[http://mizar.org/version/current/html/vectsp_1.html#NM3][~Ring~]]
  - [[http://mizar.org/version/current/html/vectsp_1.html#NM4][~Skew-Field~]]
  - [[http://mizar.org/version/current/html/vectsp_1.html#NM5][~Field~]]
  - [[http://mizar.org/version/current/html/vectsp_1.html#L1][~ModuleStr~]]
  - [[http://mizar.org/version/current/html/vectsp_1.html#NM9][~VectSp~]]
- In [[http://mizar.org/version/current/html/vectsp_2.html][~vectsp_2~]]:
  - [[http://mizar.org/version/current/html/vectsp_2.html#L1][~RightModStr~]]
  - [[http://mizar.org/version/current/html/vectsp_2.html#NM5][~LeftMod~]]
  - [[http://mizar.org/version/current/html/vectsp_2.html#L2][~BiModStr~]]
- In [[http://mizar.org/version/current/html/ideal_1.html][~ideal_1~]]:
  - [[http://mizar.org/version/current/html/ideal_1.html#V2][~left-ideal~]]
  - [[http://mizar.org/version/current/html/ideal_1.html#V3][~right-ideal~]]
- [[http://mizar.org/version/current/html/zmodlat1.html][~zmodlat1~]] for lattices
- In [[http://mizar.org/version/current/html/mfold_0.html][~mfold_0~]], [[http://mizar.org/version/current/html/mfold_1.html][~mfold_1~]], and [[http://mizar.org/version/current/html/mfold_2.html][~mfold_2~]] --- topological manifolds have
  been formalized as [[http://mizar.org/version/current/html/mfold_0.html#NM1][~topological_manifold~]] being a non-empty Hausdorff,
  second countable, locally Euclidean topological space.
- [[http://mizar.org/version/current/html/topgrp_1.html][~topgrp_1~]] defines the notion of a [[http://mizar.org/version/current/html/topgrp_1.html#NM5][~TopologicalGroup~]] by first
  defining ~TopGroup~ (a topological space whose underlying set is
  equipped with a group structure) then defines the properties
  specifying the group structure must be continuous (~UnContinuous~
  asserts the inverse operator is continuous, ~BinContinuous~ asserts
  the binary operator is continuous).
  
** Not in Mizar
:PROPERTIES:
:CUSTOM_ID: h-7abad33c-acb5-49ce-8243-945872dce09c
:END:

*** Differentiable Manifolds
:PROPERTIES:
:CUSTOM_ID: h-301cfce8-d249-4697-ab45-f1ba73dd82d9
:END:

It's kinda debatable whether this is needed, because topological groups
are also Lie groups ([[https://en.wikipedia.org/wiki/Hilbert%27s_fifth_problem][Hilbert's fifth problem]]) thanks to a theorem by
Andrew Gleason, Deane Montgomery, and Leo Zippin.

Most books define a Lie group as a real analytic manifold equipped with
a smooth group structure (a few weaken this to just(!) a $C^{\infty}$
manifold). 

*** Lie Algebras
:PROPERTIES:
:CUSTOM_ID: h-9cb82a62-a811-4a83-ada1-ab7fc5aaf75b
:END:

#+begin_definition
A vector space $L$ over a field $F$ with an operation $L\times L\to L$,
denoted $(x,y)\to[x, y]$ called the bracket (or commutator) of $x$ and $y$,
is called a {{{dfn(Lie Algbra)}}} over $F$ if

1. The bracket is bilinear
2. $[x,x]=0$ for all $x\in L$
3. $[x, [y,z]] + [y, [z,x]] + [z, [x,y]] = 0$ for all $x,y,z\in L$.
#+end_definition

This is the definition given by Humphreys' /Introduction to Lie Algebras and Representation Theory/
(pg 1, third ed.). It is more narrow than the one Bourbaki gives in
/Lie Groups and Lie Algebras/ I.1\sect2 Definition 1:

#+begin_definition
An algebra $\mathfrak{g}$ over a commutative unital [associative] ring
$K$ is called a {{{dfn(Lie Algebra)}}} over $K$ if its multiplication
(denoted by $(x,y)\mapsto[x,y]$) satisfies:

1. $[x,x]=0$
2. $[x, [y,z]] + [y, [z,x]] + [z, [x,y]] = 0$

for all $x,y,z\in\mathfrak{g}$.
#+end_definition

Bourbaki asserts that the Lie bracket is a bilinear alternating map, but
it is not adequately justified. "Bilinear" yes, but "alternating"? No,
not in general: only if the characteristic of $K$ is not 2.

#+begin_remark
Mizar's notion of an algebra is *almost* good: they demand an algebra be
unital, but this is not true in general for Lie algebras. Further, since
~multMagma~ is a distant ancestor of ~AlgebraStr~, this means that an
infixed ~*~ is provided for multiplication...which we don't
want. Consequently, it seems that we should define a ~struct LieAlgebraStr~
which extends ~ModuleStr~.
#+end_remark

#+begin_src mizar
:: C.f., LOPBAN_8:5 and LOPBAN_8:6, FUNCT_5:def 1 and FUNCT_5:def 3
:: and RINGCAT1:def 1
definition
  let K be 1-sorted;
  let L,M,N be ModuleStr over K
  let IT be Function of [:L,M:],N;
  attr IT is bilinear means
  for l being Element of L holds (curry IT).l is linear &
  for m being Element of M holds (curry' IT).m is linear
end;

registration
  let K be 1-sorted;
  let M be ModuleStr over K;
  cluster bilinear for BinOp of M;
  existence
  proof
    take IT = the addF of M;
  end;
end;

definition
  let K be 1-sorted;
  struct (ModuleStr over K) LieAlgebraStr over K
  (# carrier -> set,
     addF -> BinOp of the carrier,
  bracket -> bilinear BinOp of the carrier,
    ZeroF -> Element of the carrier,
    lmult -> Function of [:the carrier of K,the carrier:], the carrier #);
end;

definition
  let K be 1-sorted;
  let L be LieAlgebraStr over K;
  let x,y be Element of L;
  func [. x, y .] -> Element of L equals
  (the bracket of L).(x, y);
  coherence
  proof
    thus (the bracket of L).(x, y) is Element of L;
  end;
end;

:: RING_3:def 5 defines Char for a Ring
theorem
  for K being Ring st Char K <> 2
  for L being LieAlgebraStr over K
  for x,y being Element of L
  holds [. x,y .] = -1 * [. y,x .];
#+end_src

* References
:PROPERTIES:
:CUSTOM_ID: h-d95aeb61-2705-477a-bff1-5af409e21561
:END:

- Oliver Nash,\\
  "Formalising Lie algebras".\\
  {{{arXiv(2112.04570)}}}, 12 pages.
  + Discusses formalizing Lie algebras in Lean.
- Meinolf Geck,\\
  "On the construction of semisimple Lie algebras and Chevalley groups".\\
  {{{arXiv(1602.04583)}}}, 14 pages.
- Jean-Pierre Serre,\\
  /Complex semisimple Lie algebras/.\\
  Springer, 1987.
- Jim Humphreys,\\
  [[https://mathoverflow.net/q/136880/22457][Definition of "finite group of Lie type"?]]\\
  Thread on Math.Overflow