#+TITLE: Modules in Mizar
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2023-08-08T10:18:32-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/stylesheet.css" />
# Created Tuesday August  8, 2023 at 10:18AM

* Introduction
:PROPERTIES:
:CUSTOM_ID: h-4773abd6-b0bc-496b-9967-5ed5ca96df47
:END:

Let me review all the linear algebra over rings necessary for some Lie
algebra stuff (e.g., the universal envelopping algebra for a Lie algebra).
This will require:

- [ ] Direct Sum of a family of modules
- [ ] Tensor Product for two modules
- [ ] Tensor Product for a family of modules
- [ ] Tensor Algebra generated by an algebra

** Tensor Product of Two Modules
:PROPERTIES:
:CUSTOM_ID: h-77c197aa-5dc2-43ec-a310-fb215550a166
:END:

The difficulty which first presents itself for thinking about the tensor
product for two modules, well, the tensor product is an Abelian
group. We need to prove $M_{1}\otimes M_{2}$ is a module (left/right/bi,
according to the situation). Then we need to register this as a fact, or
redefine the tensor product (ugh).

I also would have to prove $M_{1}\otimes(M_{2}\otimes M_{3}) = (M_{1}\otimes M_{2})\otimes M_{3}$
which then establishes $M_{1}\otimes M_{2}\otimes M_{3}$ is unambiguous.
This requires some care with the exact definition of the tensor product,
because some definitions make this an isomorphism rather than an exact
equality. 

** Tensor Algebra
:PROPERTIES:
:CUSTOM_ID: h-5b908863-245a-4845-819c-99a5d095ad61
:END:

I think we need $R$ to be a commutative associative ring with unit, and $M$ to
be a unitary module over $R$. This is because $T^{0}(M)=R$ must be an
module over $R$, which forces us to insist on $R$ being associative.

A unitary module $M$ over $R$ means:
- For left $R$-modules, for all $m\in M$ we have $m\mapsto 1\cdot m$ be
  the identity automorphism of $M$
- For right $R$-modules, for all $m\in M$ we have $m\mapsto m\cdot 1$ be
  the identity automorphism of $M$
- For bimodules, both of these are the identity automorphism

This obviously requires $R$ being a unital ring.

Why do we need $R$ to be commutative? Well, if we consider
$m_{1}\otimes m_{2}\in M\otimes M$ and $r,s\in R$, then:

\begin{align*}
rs(m_{1}\otimes m_{2})
&=r(m_{1}\otimes(sm_{2}))\\
&=(rm_{1})\otimes(sm_{2})\\
&=s((rm_{1})\otimes m_{2})\\
&=sr(m_{1}\otimes m_{2})
\end{align*}

...which will end up imposing commutativity on the ring, since we just proved
$rs(m_{1}\otimes m_{2})=sr(m_{1}\otimes m_{2})$. So it's unusual to
find tensor products of modules over noncommutative rings, but we could
do it; and for the tensor algebra, it's just extra baggage we have to
eventually jettison.

* Map of Articles
:PROPERTIES:
:CUSTOM_ID: h-0df2c6f1-8881-4bfd-97c7-9012e23f93e3
:END:

- In [[http://mizar.org/version/current/html/vectsp_2.html][~vectsp_2~]] we have a few notion of modules formalized:
  - [[http://mizar.org/version/current/html/vectsp_2.html#NM5][~LeftMod of R~]]
  - [[http://mizar.org/version/current/html/vectsp_2.html#NM6][~RightMod of R~]]
  - [[http://mizar.org/version/current/html/vectsp_2.html#NM7][~BiMod of R1,R2~]] is a left R1-module and right R2-module
- In [[http://mizar.org/version/current/html/vectsp12.html][~vectsp12~]]
  - [[http://mizar.org/version/current/html/vectsp12.html#M1][~VectorSpace-Sequence of K~]] is needed for the product of a family of
    vector spaces, it's possibly infinite, and possibly empty.
  - [[http://mizar.org/version/current/html/vectsp12.html#K7][~product~]] of a ~VectorSpace-Sequence of K~ yields a non-empty strict
    ~ModuleStr over K~. It's then registered to yield a vector space.