#+TITLE: Categorification
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-21T12:12:22-07:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Sunday March 21, 2021 at 12:12PM

* Examples
:PROPERTIES:
:CUSTOM_ID: h-f2bc58bc-0cd9-4ff4-a0ae-6c503a870c27
:END:

** Stacks as Categorified Sheaves
:PROPERTIES:
:CUSTOM_ID: h-325c10eb-0adc-4cc7-a447-b7400b0465ce
:END:

An $n$-stack is an $(n+1)$-sheaf.

If $\cat{C}$ is an $n$-site, then we could define
{{{define($n$-Sheaves)}}} on $\cat{C}$ as 2-sheaves taking values in
$(n-1)$-categories. (C.f., [[https://ncatlab.org/nlab/show/n-localic+2-topos#grothendieck_toposes][nLab]] entry on $n$-localic 2-topos,
specifically Grothendieck $n$-toposes; and
[[https://ncatlab.org/nlab/show/n-localic+2-topos#sites_and_sheaves][n-localic 2-topos]] entry's discussion of n-sheaves.)

We could also consider [[https://ncatlab.org/nlab/show/%28n%2C1%29-sheaf][$(n,1)$-sheafs]] as higher versions.

** Differential Calculus Categorifies as Goodwillie Calculus
:PROPERTIES:
:CUSTOM_ID: h-d33913bd-706c-4ec4-aa9b-3e92ead6f949
:END:

The $(\infty,1)$-categorification of differential calculus is the
Goodwillie calculus.

** Categorifying Lie Algebras
:PROPERTIES:
:CUSTOM_ID: h-cc9bae83-1051-4940-a1f6-ea2b7da67401
:END:

Basically, replace the vector spaces underlying Lie algebras with chain
complexes.

- Dmitry Roytenberg,
  "On weak Lie 2-algebras".
  {{{arXiv(0712.3461)}}}
- Alissa S. Crans,
  "Lie 2-Algebras".
  {{{arXiv(math/0409602)}}}, 119 pages.
- John C. Baez, Alissa S. Crans,
  "Higher-Dimensional Algebra VI: Lie 2-Algebras".
  {{{arXiv(math/0307263)}}}, 50 pages.
- Chengming Bai, Yunhe Sheng, Chenchang Zhu,
  "Lie 2-bialgebras".
  {{{arXiv(1109.1344)}}}, 22 pages.
- Malte Dehling,
  "On weak Lie 3-algebras".
  {{{arXiv(1710.11104)}}}, 39 pages.
- https://golem.ph.utexas.edu/category/2007/02/infinitely_categorified_calcul.html

** Number Theory
:PROPERTIES:
:CUSTOM_ID: h-ff682019-b62c-434b-97d3-1d5811fdb673
:END:

- Mobius inversion
  https://golem.ph.utexas.edu/category/2011/05/mbius_inversion_for_categories.html
