#+TITLE: Large Categories
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-13T14:03:32-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday March 13, 2021 at  2:03PM

* Overview

The basic problem is, when defining a category, we have some
"collection" of objects and some "collection" of morphisms. But there
are two natural notions of "collection" among set theorists: sets and
proper classes.

#+begin_definition
A category is called {{{define(Large)}}} if it consists of a proper
class of objects and a proper class of morphisms.
#+end_definition

#+begin_definition
A category is called {{{define(Locally Small)}}} if it consists of a
proper class of objects, and for any two objects $X$ and $Y$ the hom-set
$\hom(X,Y)$ is a proper set.
#+end_definition

* Small Categories

#+begin_definition
A category is called {{{define(Small)}}} if it consists of a proper set
of objects and, for any two objects $X$ and $Y$, the hom-set $\hom(X,Y)$
is a proper set.
#+end_definition

* References

- Paul Blain Levy, \\
  "Formulating Categorical Concepts using Classes". \\
  [[https://arxiv.org/abs/1801.08528][arXiv:1801.08528]], 21 pages
- Mike Shulman, \\
  "Set theory for category theory". \\
  [[https://arxiv.org/abs/0810.1279][arXiv:0810.1279]]
- Jiri Adamek, Horst Herrlich, and George Strecker,\\
  {{{book-title(Abstract and Concrete Categories: The Joy of Cats)}}}.
  Eprint: [[http://katmat.math.uni-bremen.de/acc/acc.pdf][PDF]], 524 pages, part 0, chapter 2.