#+TITLE: Large Categories
#+AUTHOR: Alex Nelson
#+EMAIL: pqnelson@gmail.com
#+DATE: <2021-03-13T14:03:32-08:00>
#+LANGUAGE: en
#+OPTIONS: H:5
#+HTML_DOCTYPE: html5
#+INCLUDE: ../../org-macros.org
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ../../index.html
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/stylesheet.css" />
# Created Saturday March 13, 2021 at  2:03PM

* Overview
:PROPERTIES:
:CUSTOM_ID: h-80495c4f-0d0c-43ff-9723-9176b698257b
:END:

The basic problem is, when defining a category, we have some
"collection" of objects and some "collection" of morphisms. But there
are two natural notions of "collection" among set theorists: sets and
proper classes.

#+ATTR_HTML: :id defn-large-cat
#+begin_definition
A category is called {{{define([Strictly] Large)}}} if it consists of a proper
class of objects and a proper class of morphisms.
#+end_definition

#+ATTR_HTML: :id defn-locally-small-cat
#+begin_definition
A category is called {{{define(Locally Small)}}} if it consists of a
proper class of objects, and for any two objects $X$ and $Y$ the hom-set
$\hom(X,Y)$ is a proper set.
#+end_definition

** Foundation Dependence
:PROPERTIES:
:CUSTOM_ID: h-2a20f984-0c10-49e3-9786-7e16910d291e
:END:

The real crux of the problem is that, determining if a category is small
or large will depend on your axioms of set theory. This is why
[[file:../set-theory.org::#h-cd10efca-0ee5-4666-b0de-f24ba41391ac][Tarski--Grothendieck set theory]] was developed, to "iterate" the NBG
construction endlessly.

If we work with Morse--Kelley set theory, then we have some problems:

- The category of functors between two strictly large categories would
  have a collection of classes for its objects, which is beyond MK.

See Andreas Blass's [[https://mathoverflow.net/a/275062][answer]] to this question on Mathoverflow.


  
* Small Categories
:PROPERTIES:
:CUSTOM_ID: h-d684cdda-5e5f-486a-b231-5f7d6bead7b9
:END:

#+ATTR_HTML: :id defn-small-cat
#+begin_definition
A category is called {{{define(Small)}}} if it consists of a proper set
of objects and, for any two objects $X$ and $Y$, the hom-set $\hom(X,Y)$
is a proper set.
#+end_definition



* References
:PROPERTIES:
:CUSTOM_ID: h-f6c57835-07c8-47bf-9c80-ddc95467f03c
:END:

- Paul Blain Levy, \\
  "Formulating Categorical Concepts using Classes". \\
  [[https://arxiv.org/abs/1801.08528][arXiv:1801.08528]], 21 pages
- Mike Shulman, \\
  "Set theory for category theory". \\
  [[https://arxiv.org/abs/0810.1279][arXiv:0810.1279]]
- Jiri Adamek, Horst Herrlich, and George Strecker,\\
  {{{book-title(Abstract and Concrete Categories: The Joy of Cats)}}}.
  Eprint: [[http://katmat.math.uni-bremen.de/acc/acc.pdf][PDF]], 524 pages, part 0, chapter 2.
